Repository powerhome/playbook, pull requests merged in 2019-10, with the labels that each got.

#317 v2.9.1
  Gemfile.lock
  lib/playbook/version.rb
  package.json
Labels: create-2019.9, rails, ruby

#310 Add value and type options to button
  app/pb_kits/playbook/pb_button/_button.html.erb
  app/pb_kits/playbook/pb_button/_button.jsx
  app/pb_kits/playbook/pb_button/button.rb
  app/pb_kits/playbook/pb_button/docs/_button_default.jsx
  app/pb_kits/playbook/pb_button/docs/_button_default_dark.jsx
  app/pb_kits/playbook/pb_button/docs/_button_options.html.erb
  app/pb_kits/playbook/pb_button/docs/_button_options.jsx
  app/pb_kits/playbook/pb_button/docs/example.yml
  app/pb_kits/playbook/pb_button/docs/index.js
Labels: create-2019.9

#322 Migrate card kit
  app/pb_kits/playbook/pb_card/_card.html.erb
  app/pb_kits/playbook/pb_card/card.rb
  app/pb_kits/playbook/pb_card/card_body.rb
  app/pb_kits/playbook/pb_card/child_kits/_card_body.html.erb
  app/pb_kits/playbook/props.rb
  app/pb_kits/playbook/props/enum.rb
  spec/pb_kits/playbook/kits/caption_spec.rb
  spec/pb_kits/playbook/kits/card_body_spec.rb
  spec/pb_kits/playbook/kits/card_spec.rb
  spec/pb_kits/playbook/kits/checkbox_spec.rb
  spec/pb_kits/playbook/props_spec.rb
  spec/support/playbook/rspec.rb
Labels: Brave & Bold

#325 Modernize badge kit
  app/pb_kits/playbook/pb_badge/_badge.html.erb
  app/pb_kits/playbook/pb_badge/badge.rb
  app/pb_kits/playbook/pb_badge/docs/_badge_colors.html.erb
  spec/pb_kits/playbook/kits/badge_spec.rb
Labels: Brave & Bold

#330 Yarn security fixes
  package.json
  yarn.lock
Labels: security 🚔

#328 modernize playbook distribution bar kit
  app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.html.erb
  app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.jsx
  app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.scss
  app/pb_kits/playbook/pb_distribution_bar/distribution_bar.rb
  app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_default.html.erb
  app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_default.jsx
  app/pb_kits/playbook/props.rb
  app/pb_kits/playbook/props/number_array.rb
  spec/pb_kits/playbook/kits/distribution_bar_spec.rb
  spec/pb_kits/playbook/props/number_array_spec.rb
Labels: Brave & Bold

#333 Modernize Hashtag
  app/pb_kits/playbook/pb_hashtag/_hashtag.html.erb
  app/pb_kits/playbook/pb_hashtag/hashtag.rb
  spec/pb_kits/playbook/kits/hashtag_spec.rb
Labels: Brave & Bold

#339 Modernize Home Address Street Playbook Kit
  app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb
  app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
  app/pb_kits/playbook/props.rb
  app/pb_kits/playbook/props/number.rb
  spec/pb_kits/playbook/kits/home_address_street_spec.rb
  spec/pb_kits/playbook/props/number_spec.rb
Labels: Brave & Bold

#336 Modernize Input
  app/pb_kits/playbook/pb_input/_input.html.erb
  app/pb_kits/playbook/pb_input/_input.jsx
  app/pb_kits/playbook/pb_input/_input.scss
  app/pb_kits/playbook/pb_input/input.rb
  config/data/menu.yml
  spec/pb_kits/playbook/kits/input_spec.rb
Labels: Brave & Bold

#357 Modernize the Online Status Playbook kit
  app/pb_kits/playbook/pb_online_status/_online_status.html.erb
  app/pb_kits/playbook/pb_online_status/online_status.rb
  spec/pb_kits/playbook/kits/online_status_spec.rb
Labels: Brave & Bold

#358 Modernize Pill Kit
  app/pb_kits/playbook/pb_pill/_pill.html.erb
  app/pb_kits/playbook/pb_pill/pill.rb
  spec/pb_kits/playbook/kits/pill_spec.rb
Labels: Brave & Bold

#360 Fix bug where variant was passed an empty string
  app/pb_kits/playbook/pb_label_pill/label_pill.rb
Labels: Brave & Bold

#356 Bab/modernize bar graph kit
  app/pb_kits/playbook/pb_bar_graph/_bar_graph.html.erb
  app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  app/pb_kits/playbook/props.rb
  app/pb_kits/playbook/props/array.rb
  app/pb_kits/playbook/props/number_array.rb
  spec/pb_kits/playbook/kits/bar_graph_spec.rb
  spec/pb_kits/playbook/props/array_spec.rb
Labels: Brave & Bold

#361 Bab/modernize loading inline kit
  app/pb_kits/playbook/pb_loading_inline/_loading_inline.html.erb
  app/pb_kits/playbook/pb_loading_inline/loading_inline.rb
  spec/pb_kits/playbook/kits/loading_inline_spec.rb
Labels: Brave & Bold

#363 Modernize Title Playbook Kit
  app/helpers/playbook/pb_doc_helper.rb
  app/pb_kits/playbook/pb_title/_title.html.erb
  app/pb_kits/playbook/pb_title/title.rb
  app/views/playbook/pages/kit_show.html.slim
  app/views/playbook/pages/kits.html.slim
  app/views/playbook/pages/tokens.html.slim
  app/views/playbook/pages/tokens/_pb_doc_spacing.html.slim
  app/views/playbook/pages/utilities.html.slim
  app/views/playbook/pages/utilities/_pb_doc_color.html.slim
  spec/pb_kits/playbook/kits/title_spec.rb
Labels: Brave & Bold

#367 Create Optional House Style and Second Address Line for Home Address Street Playbook kit
  app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb
  app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb
  app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.html.erb
  app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Labels: Brave & Bold

#364 Modernize ProgressSimple Playbook kit
  app/pb_kits/playbook/pb_progress_simple/_progress_simple.html.erb
  app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss
  app/pb_kits/playbook/pb_progress_simple/progress_simple.rb
  app/pb_kits/playbook/props.rb
  app/pb_kits/playbook/props/percentage.rb
  lib/playbook.rb
  spec/pb_kits/playbook/kits/progress_simple_spec.rb
  spec/pb_kits/playbook/props/percentage_spec.rb
  spec/spec_helper.rb
Labels: Brave & Bold

#372 Modernize the Person Playbook Kit
  app/pb_kits/playbook/pb_person/_person.html.erb
  app/pb_kits/playbook/pb_person/person.rb
  spec/pb_kits/playbook/kits/person_spec.rb
Labels: Brave & Bold

#371 Modernize table kit
  app/pb_kits/playbook/pb_table/_table.html.erb
  app/pb_kits/playbook/pb_table/_table.jsx
  app/pb_kits/playbook/pb_table/docs/_table_container.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_container.jsx
  app/pb_kits/playbook/pb_table/docs/_table_container_dark.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_container_dark.jsx
  app/pb_kits/playbook/pb_table/docs/_table_dark.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_dark.jsx
  app/pb_kits/playbook/pb_table/docs/_table_disable_hover.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_disable_hover.jsx
  app/pb_kits/playbook/pb_table/docs/_table_lg.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_lg.jsx
  app/pb_kits/playbook/pb_table/docs/_table_md.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_md.jsx
  app/pb_kits/playbook/pb_table/docs/_table_multiline.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_multiline.jsx
  app/pb_kits/playbook/pb_table/docs/_table_single_line.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_single_line.jsx
  app/pb_kits/playbook/pb_table/docs/_table_sm.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_sm.jsx
  app/pb_kits/playbook/pb_table/table.rb
  app/pb_kits/playbook/props/base.rb
  spec/pb_kits/playbook/kits/table_spec.rb
Labels: Brave & Bold

#374 Modernize contact kit
  app/pb_kits/playbook/pb_contact/_contact.html.erb
  app/pb_kits/playbook/pb_contact/contact.rb
  spec/pb_kits/playbook/kits/contact_spec.rb
Labels: Brave & Bold

#375 Modernize Body Playbook kit
  app/pb_kits/playbook/pb_body/_body.html.erb
  app/pb_kits/playbook/pb_body/body.rb
  app/pb_kits/playbook/pb_person/_person.html.erb
  app/pb_kits/playbook/props.rb
  spec/pb_kits/playbook/kits/body_spec.rb
Labels: Brave & Bold

#378 Modernized icon_circle kit
  app/pb_kits/playbook/pb_icon_circle/_icon_circle.html.erb
  app/pb_kits/playbook/pb_icon_circle/icon_circle.rb
  spec/pb_kits/playbook/kits/icon_circle_spec.rb
Labels: Brave & Bold

#382 Bab/modernize fixed conf toast kit
  app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.html.erb
  app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb
  spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
Labels: Brave & Bold

#383 Modernize toggle kit
  app/pb_kits/playbook/pb_toggle/_toggle.html.erb
  app/pb_kits/playbook/pb_toggle/toggle.rb
  spec/pb_kits/playbook/kits/toggle_spec.rb
Labels: Brave & Bold

#380 Bab/modernize source kit
  app/pb_kits/playbook/pb_source/_source.html.erb
  app/pb_kits/playbook/pb_source/source.rb
  spec/pb_kits/playbook/kits/source_spec.rb
Labels: Brave & Bold

#381 Modernize Image pbkit
  app/pb_kits/playbook/pb_image/_image.html.erb
  app/pb_kits/playbook/pb_image/image.rb
  spec/pb_kits/playbook/kits/image_spec.rb
Labels: Brave & Bold

#379 Modernize Icon Value pbkit
  app/pb_kits/playbook/pb_icon_value/_icon_value.html.erb
  app/pb_kits/playbook/pb_icon_value/icon_value.rb
  spec/pb_kits/playbook/kits/icon_value_spec.rb
Labels: Brave & Bold

#385 Modernize TitleCount Playbook kit
  app/pb_kits/playbook/pb_title_count/_title_count.html.erb
  app/pb_kits/playbook/pb_title_count/docs/_title_count_default.html.erb
  app/pb_kits/playbook/pb_title_count/title_count.rb
  app/pb_kits/playbook/props.rb
  app/pb_kits/playbook/props/numeric.rb
  app/pb_kits/playbook/props/percentage.rb
  spec/pb_kits/playbook/kits/title_count_spec.rb
  spec/pb_kits/playbook/props/number_spec.rb
  spec/pb_kits/playbook/props/numeric_spec.rb
Labels: Brave & Bold

#386 Modernize Stat Value Playbook Kit
  app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.html.erb
  app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.html.erb
  app/pb_kits/playbook/pb_stat_value/_stat_value.html.erb
  app/pb_kits/playbook/pb_stat_value/docs/_stat_value_unit.html.erb
  app/pb_kits/playbook/pb_stat_value/stat_value.rb
  spec/pb_kits/playbook/kits/stat_value_spec.rb
Labels: Brave & Bold

#384 Modernize Icon Playbook Kit
  app/pb_kits/playbook/pb_icon/_icon.html.erb
  app/pb_kits/playbook/pb_icon/icon.rb
  spec/pb_kits/playbook/kits/icon_spec.rb
  spec/support/playbook/rspec.rb
Labels: Brave & Bold

#388 Modernize Label Pill kit
  app/pb_kits/playbook/pb_label_pill/_label_pill.html.erb
  app/pb_kits/playbook/pb_label_pill/label_pill.rb
  spec/pb_kits/playbook/kits/label_pill_spec.rb
Labels: Brave & Bold

#393 Modernize line graph kit
  app/pb_kits/playbook/pb_bar_graph/_bar_graph.html.erb
  app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.html.erb
  app/pb_kits/playbook/pb_line_graph/_line_graph.html.erb
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.html.erb
  app/pb_kits/playbook/pb_line_graph/line_graph.rb
  spec/pb_kits/playbook/kits/bar_graph_spec.rb
  spec/pb_kits/playbook/kits/line_graph_spec.rb
Labels: Brave & Bold

#394 Modernize Avatar Kit
  app/pb_kits/playbook/pb_avatar/_avatar.html.erb
  app/pb_kits/playbook/pb_avatar/avatar.rb
  spec/pb_kits/playbook/kits/avatar_spec.rb
Labels: Brave & Bold

#392 Modernize title-detail kit
  app/pb_kits/playbook/pb_title_detail/_title_detail.html.erb
  app/pb_kits/playbook/pb_title_detail/title_detail.rb
  spec/pb_kits/playbook/kits/title_detail_spec.rb
Labels: Brave & Bold

#391 Modernize label value kit
  app/pb_kits/playbook/pb_label_value/_label_value.html.erb
  app/pb_kits/playbook/pb_label_value/label_value.rb
  spec/pb_kits/playbook/kits/label_value_spec.rb
Labels: Brave & Bold

#406 Add node 10.17.0 and npm 6.11.3 to engines
  package.json
Labels: javascript
