Repository powerhome/playbook, pull requests merged in 2019-12, with the labels that each got.

#466 Create React version of Playbook Kit for IconCircle
  app/pb_kits/playbook/pb_icon_circle/_icon_circle.jsx
  app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_color.jsx
  app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_default.jsx
  app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_size.jsx
  app/pb_kits/playbook/pb_icon_circle/docs/example.yml
  app/pb_kits/playbook/pb_icon_circle/docs/index.js
Labels: Thunderbolts

#473 Add jsx support for Date kit
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/pb_date/_date.jsx
  app/pb_kits/playbook/pb_date/docs/_date_default.jsx
  app/pb_kits/playbook/pb_kit/dateTime.js
Labels: Thunderbolts

#499 Display wrong contacts correctly
  CHANGELOG.md
  app/pb_kits/playbook/pb_contact/contact.rb
  app/pb_kits/playbook/pb_person_contact/_person_contact.html.erb
  app/pb_kits/playbook/pb_person_contact/_person_contact.scss
  app/pb_kits/playbook/pb_person_contact/docs/_person_contact_with_wrong_numbers.html.erb
  app/pb_kits/playbook/pb_person_contact/docs/example.yml
  app/pb_kits/playbook/pb_person_contact/person_contact.rb
  spec/pb_kits/playbook/kits/contact_spec.rb
Labels: Brave & Bold

#506 Add textarea kit to form kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb
  app/pb_kits/playbook/pb_form/form_builder.rb
  app/pb_kits/playbook/pb_form/form_builder/form_field_builder.rb
  app/pb_kits/playbook/pb_text_input/_text_input.html.erb
  app/pb_kits/playbook/pb_text_input/_text_input.scss
Labels: birds of prey

#537 Add className support to React version of icon circle kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_icon_circle/_icon_circle.jsx
Labels: bug
