Repository powerhome/playbook, pull requests merged in 2020-02, with the labels that each got.

#587 Fix Form kit data prop merge
  CHANGELOG.md
  app/pb_kits/playbook/pb_form/form/form_with_form.rb
  app/pb_kits/playbook/pb_form/form/simple_form_form.rb
Labels: bug

#559 Create date range stacked kit
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/packs/kits/pb_date_range_stacked.js
  app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.html.erb
  app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.jsx
  app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.scss
  app/pb_kits/playbook/pb_date_range_stacked/date_range_stacked.rb
  app/pb_kits/playbook/pb_date_range_stacked/docs/_date_range_stacked_dark.html.erb
  app/pb_kits/playbook/pb_date_range_stacked/docs/_date_range_stacked_dark.jsx
  app/pb_kits/playbook/pb_date_range_stacked/docs/_date_range_stacked_default.html.erb
  app/pb_kits/playbook/pb_date_range_stacked/docs/_date_range_stacked_default.jsx
  app/pb_kits/playbook/pb_date_range_stacked/docs/example.yml
  app/pb_kits/playbook/pb_date_range_stacked/docs/index.js
  spec/pb_kits/playbook/kits/date_range_stacked_spec.rb
Labels: New Kit, rails, react

#623 Doc framework
  app/helpers/playbook/pb_doc_helper.rb
  app/pb_kits/playbook/config/_kit_ui.html.erb
  app/pb_kits/playbook/config/_kit_ui.html.slim
  app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
  app/pb_kits/playbook/packs/site_styles/docs/_markdown.scss
  app/pb_kits/playbook/pb_section_separator/docs/_description.md
  app/pb_kits/playbook/pb_section_separator/docs/_footer.md
  app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.md
  app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_background.md
  app/views/playbook/pages/kit_show.html.slim
Labels: enhancement
