Repository powerhome/playbook, pull requests merged in 2020-12, with the labels that each got.

#1223 [NUXE-305] - Link kit and sample pages
  playbook/app/controllers/playbook/pages_controller.rb
  playbook/app/helpers/playbook/pb_doc_helper.rb
  playbook/app/helpers/playbook/pb_sample_helper.rb
  playbook/app/pb_kits/playbook/config/_kit_example.html.erb
  playbook/app/pb_kits/playbook/config/_kit_ui.html.erb
  playbook/app/pb_kits/playbook/packs/full-page-samples.js
  playbook/app/pb_kits/playbook/packs/main.scss
  playbook/app/pb_kits/playbook/packs/popover_docs.js
  playbook/app/pb_kits/playbook/packs/site_styles/_kits_show.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_samples_show.scss
  playbook/app/views/layouts/playbook/kits.html.erb
  playbook/app/views/layouts/playbook/samples.html.erb
  playbook/app/views/playbook/pages/all_kit_examples.html.erb
  playbook/app/views/playbook/pages/kit_show.html.erb
  playbook/app/views/playbook/pages/kits.html.erb
  playbook/app/views/playbook/samples/sample_show.html.erb
  playbook/app/views/playbook/samples/trending_repositories/index.html.erb
  playbook/config/routes.rb
Labels: improvement, milano

#1240 Table Reorganization, and change default alignment to top
  playbook/app/pb_kits/playbook/pb_table/_table.scss
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.jsx
  playbook/app/pb_kits/playbook/pb_table/styles/_alignment.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mixins.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_side_highlight.scss
Labels: enhancement, milano

#1244 Allow getOption[Label|Value] props in Typeahead
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Option.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.md
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Labels: enhancement, milano

#1241 [NUXE-210] - Update release script (v2)
  playbook/lib/tasks/new_release.rake
Labels: enhancement, milano

#1237 [NUXE-278] SAMPLE PAGE - Crowdsourced Posts (Reddit home page)
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/views/playbook/samples/crowdsourced_posts/index.html.erb
  playbook/app/views/playbook/samples/crowdsourced_posts/index.jsx
Labels: improvement, milano

#1235 [NUXE-331] Kit search
  playbook/app/controllers/playbook/pages_controller.rb
  playbook/app/controllers/playbook/samples_controller.rb
  playbook/app/helpers/playbook/pb_doc_helper.rb
  playbook/app/pb_kits/playbook/docs_components/DarkModeToggle.jsx
  playbook/app/pb_kits/playbook/docs_components/KitSearch.jsx
  playbook/app/pb_kits/playbook/docs_components/SnippetToggle.jsx
  playbook/app/pb_kits/playbook/docs_components/index.js
  playbook/app/pb_kits/playbook/packs/landing-page.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss
  playbook/app/pb_kits/playbook/pb_nav/_horizontal_nav.scss
  playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss
  playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss
  playbook/app/pb_kits/playbook/pb_nav/docs/_subtle_horizontal_nav.html.erb
  playbook/app/pb_kits/playbook/pb_nav/docs/_subtle_horizontal_nav.jsx
  playbook/app/pb_kits/playbook/pb_nav/docs/example.yml
  playbook/app/pb_kits/playbook/pb_nav/docs/index.js
  playbook/app/pb_kits/playbook/react_rails_kits.js
  playbook/app/views/layouts/playbook/_nav.html.erb
  playbook/app/views/layouts/playbook/application.html.erb
  playbook/app/views/playbook/pages/home.html.erb
Labels: enhancement, milano

#1249 Update gitignore
  .gitignore
Labels: enhancement

#1229 Move Playbook::Props to lib
  playbook/lib/playbook.rb
  playbook/lib/playbook/props.rb
  playbook/lib/playbook/props/array.rb
  playbook/lib/playbook/props/base.rb
  playbook/lib/playbook/props/boolean.rb
  playbook/lib/playbook/props/date.rb
  playbook/lib/playbook/props/enum.rb
  playbook/lib/playbook/props/hash.rb
  playbook/lib/playbook/props/hash_array.rb
  playbook/lib/playbook/props/number.rb
  playbook/lib/playbook/props/number_array.rb
  playbook/lib/playbook/props/numeric.rb
  playbook/lib/playbook/props/percentage.rb
  playbook/lib/playbook/props/proc.rb
  playbook/lib/playbook/props/string.rb
  playbook/spec/playbook/props/array_spec.rb
  playbook/spec/playbook/props/base_spec.rb
  playbook/spec/playbook/props/boolean_spec.rb
  playbook/spec/playbook/props/date_spec.rb
  playbook/spec/playbook/props/enum_spec.rb
  playbook/spec/playbook/props/hash_array_spec.rb
  playbook/spec/playbook/props/hash_spec.rb
  playbook/spec/playbook/props/number_array_spec.rb
  playbook/spec/playbook/props/number_spec.rb
  playbook/spec/playbook/props/numeric_spec.rb
  playbook/spec/playbook/props/percentage_spec.rb
  playbook/spec/playbook/props_spec.rb
  playbook/spec/spec_helper.rb
Labels: enhancement, milano

#1260 Improve navigation overflow for mobile
  playbook/app/pb_kits/playbook/packs/site_styles/_scaffold.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss
Labels: improvement, milano

#1258 Tooltip Rails kit: Tooltip arrow is not centered
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_white.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_with_icon_circle.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/example.yml
Labels: bug, milano

#1265 [NUXE-324] KIT DEV - Add target blank to Nav Item #1212
  playbook/app/pb_kits/playbook/pb_nav/_item.jsx
  playbook/app/pb_kits/playbook/pb_nav/docs/_new_tab.html.erb
  playbook/app/pb_kits/playbook/pb_nav/docs/_new_tab.jsx
  playbook/app/pb_kits/playbook/pb_nav/docs/example.yml
  playbook/app/pb_kits/playbook/pb_nav/docs/index.js
  playbook/app/pb_kits/playbook/pb_nav/item.rb
Labels: enhancement, milano

#1266 Add deprecation back
  playbook/lib/playbook/props/base.rb
Labels: enhancement, milano

#1267 Updated sample page design layout to support categories
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/site_styles/_kits_show.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_samples_index.scss
  playbook/app/views/playbook/pages/kit_show.html.erb
  playbook/app/views/playbook/samples/samples_index.html.erb
Labels: improvement, milano

#1259 Update DatePicker docs for best DateTime obj practices
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_anti_patterns.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_disabled.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_flatpickr_methods.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_flatpickr_methods.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_format.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_min_max.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_description.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js
Labels: enhancement, milano, not ready

#1238 Simplify dark mode
  playbook/app/controllers/playbook/application_controller.rb
  playbook/app/controllers/playbook/pages_controller.rb
  playbook/app/controllers/playbook/samples_controller.rb
  playbook/app/helpers/playbook/application_helper.rb
  playbook/app/helpers/playbook/layout_helper.rb
  playbook/app/helpers/playbook/pb_doc_helper.rb
  playbook/app/helpers/playbook/pb_kit_helper.rb
  playbook/app/helpers/playbook/pb_sample_helper.rb
  playbook/lib/playbook.rb
  playbook/lib/playbook/engine.rb
Labels: enhancement, milano

#1256 Improve consistency of the react filter kit sort icon to match rails
  playbook/app/pb_kits/playbook/pb_filter/Filter/SortMenu.jsx
Labels: improvement, milano

#1247 Remove unused methods from Playbook api
  playbook/lib/playbook.rb
Labels: enhancement, milano

#1269 [NUXE-48] - changelog page
  playbook/CHANGELOG.md
  playbook/app/controllers/playbook/pages_controller.rb
  playbook/app/pb_kits/playbook/packs/main.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_changelog.scss
  playbook/app/views/layouts/playbook/_footer.html.erb
  playbook/app/views/playbook/pages/changelog.html.erb
  playbook/config/routes.rb
Labels: improvement, milano

#1246 [NUXE-43] Dashboard Cards
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/pb_kits/playbook/packs/samples/card_dashboard/styles.scss
  playbook/app/pb_kits/playbook/packs/samples/index.scss
  playbook/app/views/layouts/playbook/samples.html.erb
  playbook/app/views/playbook/samples/card_dashboards/index.html.erb
  playbook/app/views/playbook/samples/card_dashboards/index.jsx
Labels: enhancement, milano

#1253 Forward refs within Text Input, Radio, & Select React kits
  playbook/app/pb_kits/playbook/pb_radio/_radio.jsx
  playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default.jsx
  playbook/app/pb_kits/playbook/pb_radio/docs/index.js
  playbook/app/pb_kits/playbook/pb_radio/radio.test.js
  playbook/app/pb_kits/playbook/pb_select/_select.jsx
  playbook/app/pb_kits/playbook/pb_select/select.test.js
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_description.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_custom.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_default.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error.jsx
  playbook/app/pb_kits/playbook/pb_text_input/text_input.test.js
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.jsx
Labels: enhancement, milano

#1273 Fix for homepage toggle page shake
  playbook/app/pb_kits/playbook/packs/site_styles/_landing-page.scss
Labels: improvement, milano

#1274 Fix snoggle margin, homepage hero background color
  playbook/app/pb_kits/playbook/packs/site_styles/_landing-page.scss
  playbook/app/views/playbook/pages/home.html.erb
Labels: improvement, milano

#1275 [NUXE-304] - rich text output preview
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_preview.html.erb
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_preview.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
Labels: improvement, milano

#1278 Fixes kit generator error
  playbook/lib/playbook/engine.rb
Labels: bug
