Repository powerhome/playbook, pull requests merged in 2020-11, with the labels that each got.

#1184 Revert 1150 feature/timestamp kit
  CHANGELOG.md
  Gemfile.lock
  app/pb_kits/playbook/pb_timestamp/_timestamp.html.erb
  app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  app/pb_kits/playbook/pb_timestamp/_timestamp.scss
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/example.yml
  app/pb_kits/playbook/pb_timestamp/docs/index.js
  app/pb_kits/playbook/pb_timestamp/timestamp.rb
  lib/playbook/version.rb
  package.json
  spec/pb_kits/playbook/kits/time_spec.rb
  spec/pb_kits/playbook/kits/time_stacked_spec.rb
  spec/pb_kits/playbook/kits/timestamp_spec.rb
Labels: milano

#1196 Move readme inside playbook folder
  playbook/README.md
Labels: bug

#1192 Use Docker images under our control
  playbook/Dockerfile
Labels: improvement, milano

#1186 Fix Padding on Background Kit
  playbook/app/pb_kits/playbook/pb_background/docs/_background_white.jsx
  playbook/app/views/playbook/samples/collection_detail/index.html.erb
Labels: improvement

#1198 [NUXE-27] Create index page for samples
  playbook/app/assets/images/sample_screenshot.svg
  playbook/app/controllers/playbook/pages_controller.rb
  playbook/app/controllers/playbook/samples_controller.rb
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/main.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_samples_index.scss
  playbook/app/views/layouts/playbook/_nav.html.erb
  playbook/app/views/layouts/playbook/_sidebar.html.erb
  playbook/app/views/playbook/samples/sample_show.html.erb
  playbook/app/views/playbook/samples/samples_index.html.erb
  playbook/config/routes.rb
  playbook/lib/generators/sample/USAGE
  playbook/lib/generators/sample/sample_generator.rb
Labels: enhancement

#1185 [NUXE-223] KIT DEV - Background Kit Output Improvements
  playbook/app/pb_kits/playbook/pb_background/_background.html.erb
  playbook/app/pb_kits/playbook/pb_background/_background.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_dark.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_gradient.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_image.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_light.jsx
Labels: improvement, milano

#1179 [NUXE-185] Selectable List kit
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
  playbook/app/pb_kits/playbook/pb_list/_list.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_item.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.scss
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list_item.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/docs/_selectable_list_checkbox.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/docs/_selectable_list_checkbox.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/docs/_selectable_list_radio.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/docs/_selectable_list_radio.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/docs/example.yml
  playbook/app/pb_kits/playbook/pb_selectable_list/docs/index.js
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.rb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
  playbook/spec/pb_kits/playbook/kits/selectable_list_item_spec.rb
  playbook/spec/pb_kits/playbook/kits/selectable_list_spec.rb
Labels: enhancement, milano, new kit

#1178 [NUXE-76] KIT DOCS - Build image example for selectable cards
  playbook/app/pb_kits/playbook/pb_image/docs/_rounded_image.html.erb
  playbook/app/pb_kits/playbook/pb_image/docs/_rounded_image.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_image.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_image.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_image.md
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/example.yml
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/index.js
Labels: improvement, milano

#1209 Progress pills dark doc examples
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_status.jsx
Labels: bug, milano, ready

#1202 [NUXE-272] Fixed background kit Rails image bug
  playbook/app/pb_kits/playbook/pb_background/_background.html.erb
  playbook/app/views/playbook/pages/home.html.erb
Labels: bug, milano, ready

#1201 [NUXE-234] Added React getting started
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/pb_kits/playbook/packs/site_styles/_getting_started.scss
  playbook/app/views/layouts/playbook/_nav.html.erb
  playbook/app/views/layouts/playbook/_sidebar.html.erb
  playbook/app/views/playbook/guides/getting_started/_rails_getting_started.md
  playbook/app/views/playbook/guides/getting_started/_react_getting_started.md
  playbook/app/views/playbook/pages/getting_started.html.slim
  playbook/app/views/playbook/samples/analytics_dashboard/index.html.erb
  playbook/app/views/playbook/samples/analytics_dashboard/index.jsx
  playbook/app/views/playbook/samples/conference_statistics/index.html.erb
  playbook/app/views/playbook/samples/conference_statistics/index.jsx
  playbook/app/views/playbook/samples/crm_client_list/index.html.erb
  playbook/app/views/playbook/samples/crm_client_list/index.jsx
  playbook/app/views/playbook/samples/news_magazine/index.html.erb
  playbook/app/views/playbook/samples/news_magazine/index.jsx
  playbook/app/views/playbook/samples/samples_index.html.erb
Labels: improvement, milano, ready

#1215 [NUXE-260] SAMPLE PAGE - Image aspect ratio on News View
  playbook/app/views/playbook/samples/news_magazine/index.html.erb
  playbook/app/views/playbook/samples/news_magazine/index.jsx
Labels: bug, milano

#1207 [NUXE-259] SAMPLE PAGE - GitHub Trending
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/views/playbook/samples/trending_repositories/index.html.erb
  playbook/app/views/playbook/samples/trending_repositories/index.jsx
Labels: improvement, milano

#1213 [NUXE-52] Create Visual Guidelines page
  playbook/app/controllers/playbook/pages_controller.rb
  playbook/app/pb_kits/playbook/packs/main.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_visual_guidelines.scss
  playbook/app/pb_kits/playbook/packs/site_styles/docs/_color_utilities.scss
  playbook/app/pb_kits/playbook/packs/site_styles/docs/_spacing_tokens.scss
  playbook/app/views/layouts/playbook/_nav.html.erb
  playbook/app/views/layouts/playbook/_sidebar.html.erb
  playbook/app/views/playbook/pages/fullscreen.html.slim
  playbook/app/views/playbook/pages/getting_started.html.slim
  playbook/app/views/playbook/pages/getting_started_partials/_rails_getting_started.md
  playbook/app/views/playbook/pages/getting_started_partials/_react_getting_started.md
  playbook/app/views/playbook/pages/grid.html.slim
  playbook/app/views/playbook/pages/home.html.slim
  playbook/app/views/playbook/pages/principals/_getting_started.html.md
  playbook/app/views/playbook/pages/principles.html.slim
  playbook/app/views/playbook/pages/visual_guidelines.html.erb
  playbook/app/views/playbook/pages/visual_guidelines_partials/_colors.html.slim
  playbook/app/views/playbook/pages/visual_guidelines_partials/_pb_doc_color.html.slim
  playbook/app/views/playbook/pages/visual_guidelines_partials/_pb_doc_spacing.html.slim
  playbook/app/views/playbook/pages/visual_guidelines_partials/_spacing.html.slim
  playbook/config/routes.rb
Labels: improvement, milano

#1211 JavaScript React Kit Testing
  README.md
  playbook/Makefile
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
  playbook/app/pb_kits/playbook/utilities/test-utils.js
  playbook/bin/test
  playbook/config/webpack/test.js
  playbook/jest.config.js
  playbook/lib/generators/kit/kit_generator.rb
  playbook/lib/generators/kit/templates/kit_jsx_test.erb.tt
  playbook/package.json
  playbook/yarn.lock
Labels: enhancement

#1189 [NUXE-212] KIT DEV- Form Group Kit
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.jsx
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_button.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_button.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_date_picker.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_date_picker.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_default.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_default.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_selectable_card.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_selectable_card_icon.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_selectable_card_icon.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/example.yml
  playbook/app/pb_kits/playbook/pb_form_group/docs/index.js
  playbook/app/pb_kits/playbook/pb_form_group/form_group.rb
  playbook/spec/pb_kits/playbook/kits/form_group_spec.rb
Labels: enhancement, milano, needs alpha testing, new kit

#1022 [NUXE-269] KIT DEV - IconStatValue kit
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.scss
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_color.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_color.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_default.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_default.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_sizes.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_sizes.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_vertical.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_vertical.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/index.js
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.rb
  playbook/spec/pb_kits/playbook/kits/icon_stat_value_spec.rb
Labels: milano, needs alpha testing, new kit

#1214 [NUXE-47] Create samples categories
  playbook/app/assets/images/full_page_samples.svg
  playbook/app/controllers/playbook/samples_controller.rb
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/pb_kits/playbook/packs/site_styles/_samples_index.scss
  playbook/app/views/layouts/playbook/samples.html.erb
  playbook/app/views/playbook/samples/crm_client_list/index.jsx
  playbook/app/views/playbook/samples/samples_index.html.erb
  playbook/lib/generators/sample/USAGE
  playbook/lib/generators/sample/sample_generator.rb
  playbook/lib/generators/sample/templates/sample_rails_index.erb.tt
  playbook/lib/generators/sample/templates/sample_react_index.erb.tt
Labels: improvement, milano

#1208 [NUXE-227] Add alignment properties to tables
  playbook/app/pb_kits/playbook/pb_table/_table.scss
  playbook/app/pb_kits/playbook/pb_table/docs/_description.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
Labels: enhancement, milano

#1206 [NUXE-226] Update Time Stacked Kit in Playbook Web
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.scss
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_caption.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_caption.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_default.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_default.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/example.yml
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/index.js
  playbook/app/pb_kits/playbook/pb_time_stacked/time_stacked.rb
  playbook/app/pb_kits/playbook/utilities/globalProps.js
  playbook/spec/pb_kits/playbook/kits/time_stacked_spec.rb
  playbook/webpack.config.js
Labels: deprecated, milano
