Repository powerhome/playbook, pull requests merged in 2020-01, with the labels that each got.

#536 Pb Card: Swap implementation of highlight position values.
  CHANGELOG.md
  app/pb_kits/playbook/pb_card/_card.jsx
  app/pb_kits/playbook/pb_card/_card.scss
Labels: bug

#546 Fixed radio bug in docs
  CHANGELOG.md
  app/pb_kits/playbook/pb_radio/_radio.jsx
  app/pb_kits/playbook/pb_radio/docs/_radio_custom.html.erb
  app/pb_kits/playbook/pb_radio/docs/_radio_custom.jsx
  app/pb_kits/playbook/pb_radio/docs/_radio_dark.jsx
  app/pb_kits/playbook/pb_radio/docs/_radio_default.jsx
Labels: bug

#548 Select bug fix
  CHANGELOG.md
  app/pb_kits/playbook/pb_select/_select.scss
Labels: bug

#549 Create Legend Kit (Complete)
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/kits/pb_legend.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/packs/kits.js
  app/pb_kits/playbook/pb_legend/_legend.html.erb
  app/pb_kits/playbook/pb_legend/_legend.jsx
  app/pb_kits/playbook/pb_legend/_legend.scss
  app/pb_kits/playbook/pb_legend/docs/_legend_dark.html.erb
  app/pb_kits/playbook/pb_legend/docs/_legend_dark.jsx
  app/pb_kits/playbook/pb_legend/docs/_legend_dark_prefix.html.erb
  app/pb_kits/playbook/pb_legend/docs/_legend_dark_prefix.jsx
  app/pb_kits/playbook/pb_legend/docs/_legend_default.html.erb
  app/pb_kits/playbook/pb_legend/docs/_legend_default.jsx
  app/pb_kits/playbook/pb_legend/docs/_legend_prefix.html.erb
  app/pb_kits/playbook/pb_legend/docs/_legend_prefix.jsx
  app/pb_kits/playbook/pb_legend/docs/example.yml
  app/pb_kits/playbook/pb_legend/docs/index.js
  app/pb_kits/playbook/pb_legend/legend.rb
  config/data/menu.yml
  spec/pb_kits/playbook/kits/legend_spec.rb
Labels: New Kit, rails, react

#556 Add error state to Select kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_select/_select.html.erb
  app/pb_kits/playbook/pb_select/_select.jsx
  app/pb_kits/playbook/pb_select/_select.scss
  app/pb_kits/playbook/pb_select/docs/_select_dark_error.html.erb
  app/pb_kits/playbook/pb_select/docs/_select_dark_error.jsx
  app/pb_kits/playbook/pb_select/docs/_select_error.html.erb
  app/pb_kits/playbook/pb_select/docs/_select_error.jsx
  app/pb_kits/playbook/pb_select/docs/example.yml
  app/pb_kits/playbook/pb_select/docs/index.js
  app/pb_kits/playbook/pb_select/select.rb
  spec/pb_kits/playbook/kits/select_spec.rb
Labels: enhancement, rails, react

#558 Add error state to Radio kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_radio/_radio.jsx
  app/pb_kits/playbook/pb_radio/_radio.scss
  app/pb_kits/playbook/pb_radio/docs/_radio_dark_error.html.erb
  app/pb_kits/playbook/pb_radio/docs/_radio_dark_error.jsx
  app/pb_kits/playbook/pb_radio/docs/_radio_error.html.erb
  app/pb_kits/playbook/pb_radio/docs/_radio_error.jsx
  app/pb_kits/playbook/pb_radio/docs/example.yml
  app/pb_kits/playbook/pb_radio/docs/index.js
  app/pb_kits/playbook/pb_radio/radio.rb
  spec/pb_kits/playbook/kits/radio_spec.rb
Labels: enhancement, rails, react

#557 Add home_url prop to home_address_street kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb
  app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx
  app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb
  app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.jsx
  app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.html.erb
  app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.jsx
  app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
  spec/pb_kits/playbook/kits/home_address_street_spec.rb
Labels: bug

#547 Typeahead kit
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_enhanced_element/element_observer.js
  app/pb_kits/playbook/pb_enhanced_element/index.js
  app/pb_kits/playbook/pb_list/_item.html.erb
  app/pb_kits/playbook/pb_list/_list.html.erb
  app/pb_kits/playbook/pb_list/item.rb
  app/pb_kits/playbook/pb_list/list.rb
  app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
  app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
  app/pb_kits/playbook/pb_typeahead/docs/example.yml
  app/pb_kits/playbook/pb_typeahead/index.js
  app/pb_kits/playbook/pb_typeahead/typeahead.rb
  config/data/menu.yml
  spec/pb_kits/playbook/pb_typeahead/typeahead_spec.rb
Labels: birds of prey

#565 [BOLT-49] Modernize and improve the Currency kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_currency/_currency.html.erb
  app/pb_kits/playbook/pb_currency/_currency.jsx
  app/pb_kits/playbook/pb_currency/_currency.scss
  app/pb_kits/playbook/pb_currency/currency.rb
  app/pb_kits/playbook/pb_currency/docs/_currency_default.jsx
  app/pb_kits/playbook/pb_currency/docs/_currency_large.html.erb
  app/pb_kits/playbook/pb_currency/docs/_currency_large.jsx
  app/pb_kits/playbook/pb_currency/docs/_currency_small.html.erb
  spec/changelog_spec.rb
  spec/pb_kits/playbook/pb_currency/currency_spec.rb
Labels: Thunderbolts

#566 [BOLT-49] Modernize and improve the Currency kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_currency/_currency.html.erb
  app/pb_kits/playbook/pb_currency/_currency.jsx
  app/pb_kits/playbook/pb_currency/_currency.scss
  app/pb_kits/playbook/pb_currency/currency.rb
  app/pb_kits/playbook/pb_currency/docs/_currency_default.jsx
  app/pb_kits/playbook/pb_currency/docs/_currency_large.html.erb
  app/pb_kits/playbook/pb_currency/docs/_currency_large.jsx
  app/pb_kits/playbook/pb_currency/docs/_currency_small.html.erb
  spec/changelog_spec.rb
  spec/pb_kits/playbook/pb_currency/currency_spec.rb
Labels: Thunderbolts
