Repository powerhome/playbook, pull requests merged in 2020-10, with the labels that each got.

#1135 Fixing Flash on Popover Initial Page Load
  app/pb_kits/playbook/pb_popover/_popover.scss
  app/pb_kits/playbook/pb_popover/index.js
Labels: bug, milano

#1136 Changelog Generator 2.0
  .github/PULL_REQUEST_TEMPLATE.md
  .github_changelog_generator
  HISTORY.md
  lib/tasks/changelog.rake
Labels: improvement

#1126 Make updates to the inline date range kit
  app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.html.erb
  app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.jsx
  app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.scss
  app/pb_kits/playbook/pb_date_range_inline/date_range_inline.rb
  app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default.html.erb
  app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default.jsx
  app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
  spec/pb_kits/playbook/kits/date_range_inline_spec.rb
Labels: enhancement, milano

#1123 Updated Table Documentation with Examples of How to Use Buttons
  app/pb_kits/playbook/pb_table/docs/_table_action_middle.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_action_middle.jsx
  app/pb_kits/playbook/pb_table/docs/_table_action_middle.md
  app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.jsx
  app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.md
  app/pb_kits/playbook/pb_table/docs/_table_one_action.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_one_action.jsx
  app/pb_kits/playbook/pb_table/docs/_table_one_action.md
  app/pb_kits/playbook/pb_table/docs/_table_two_actions.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_two_actions.jsx
  app/pb_kits/playbook/pb_table/docs/_table_two_actions.md
  app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.html.erb
  app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.jsx
  app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.md
  app/pb_kits/playbook/pb_table/docs/example.yml
  app/pb_kits/playbook/pb_table/docs/index.js
Labels: improvement, milano

#1128 Update Progress Step
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
  app/pb_kits/playbook/pb_progress_step/_progress_step.scss
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.html.erb
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_description.md
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.jsx
  app/pb_kits/playbook/pb_progress_step/progress_step.rb
  app/pb_kits/playbook/pb_progress_step/progress_step_item.rb
  spec/pb_kits/playbook/kits/progress_step_item_spec.rb
  spec/pb_kits/playbook/kits/progress_step_spec.rb
Labels: enhancement, milano

#1125 [NUXE-155] Date Picker Patch 3
  app/pb_kits/playbook/pb_date_picker/_date_picker.html.erb
  app/pb_kits/playbook/pb_date_picker/_date_picker.jsx
  app/pb_kits/playbook/pb_date_picker/date_picker.rb
  app/pb_kits/playbook/pb_date_picker/date_picker_helper.js
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.md
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_dark.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_dark.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.md
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_format.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_format.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_input.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_input.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_input.md
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.jsx
  app/pb_kits/playbook/pb_date_picker/docs/example.yml
  app/pb_kits/playbook/pb_date_picker/docs/index.js
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form_validate.html.erb
  app/pb_kits/playbook/pb_form/form_builder/date_picker_field.rb
  spec/pb_kits/playbook/kits/date_picker_spec.rb
Labels: bug, milano

#1104 Typeahead with Pills (Rails)
  app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
  app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
  app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  app/pb_kits/playbook/pb_typeahead/components/MultiValue.jsx
  app/pb_kits/playbook/pb_typeahead/components/Option.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_context_dark.html.erb
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.html.erb
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.md
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.html.erb
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.md
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_summary.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_users.html.erb
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_users.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_users.md
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_summary.jsx
  app/pb_kits/playbook/pb_typeahead/docs/example.yml
  app/pb_kits/playbook/pb_typeahead/typeahead.rb
  app/pb_kits/playbook/react_rails_kits.js
  spec/pb_kits/playbook/pb_typeahead/typeahead_spec.rb
Labels: enhancement, milano

#1129 [NUXE-55] Updated styles to button toolbar kit
  app/pb_kits/playbook/pb_button/_button_mixins.scss
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.jsx
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar_dark.scss
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar_mixins.scss
  app/pb_kits/playbook/pb_button_toolbar/button_toolbar.rb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_default.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_default.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_secondary.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_secondary.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical_secondary.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical_secondary.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/example.yml
  app/pb_kits/playbook/pb_button_toolbar/docs/index.js
  spec/pb_kits/playbook/kits/button_toolbar_spec.rb
Labels: enhancement, milano

#1112 [CMPN-18] Allow all HTML options on input in PbToggle Rails kit.
  app/pb_kits/playbook/pb_toggle/docs/_toggle_options.html.erb
  app/pb_kits/playbook/pb_toggle/docs/example.yml
  app/pb_kits/playbook/pb_toggle/toggle.rb
  spec/pb_kits/playbook/kits/toggle_spec.rb
Labels: enhancement, improvement, milano

#1113 [CMPN-22] Allow all HTML options on input in PbSelectableIcon, PbSelectableCard and PbSelectableCardIcon Rails kits
  app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
  app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_options.html.erb
  app/pb_kits/playbook/pb_selectable_card/docs/example.yml
  app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
  app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_options.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/docs/example.yml
  app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.rb
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.html.erb
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_options.html.erb
  app/pb_kits/playbook/pb_selectable_icon/docs/example.yml
  app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
  spec/pb_kits/playbook/kits/selectable_card_icon_spec.rb
  spec/pb_kits/playbook/kits/selectable_card_spec.rb
  spec/pb_kits/playbook/kits/selectable_icon_spec.rb
Labels: enhancement, milano

#1146 [NUXE-158] Section separator dark mode (WIP)
  app/pb_kits/playbook/pb_section_separator/_section_separator.jsx
  app/pb_kits/playbook/pb_section_separator/_section_separator.scss
  app/pb_kits/playbook/pb_section_separator/_section_separator_mixin.scss
  app/pb_kits/playbook/pb_section_separator/docs/_section_separator_line.jsx
  app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.jsx
  app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_background.jsx
  app/pb_kits/playbook/pb_section_separator/docs/_section_separator_vertical.jsx
  app/pb_kits/playbook/pb_section_separator/section_separator.rb
  spec/pb_kits/playbook/kits/section_seperator_spec.rb
Labels: enhancement, milano

#1151 Fixes Typeahead (Rails) setting wrong image attribute in examples
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
Labels: bug, milano

#1153 Pill Kit double line fix
  app/pb_kits/playbook/pb_pill/_pill.scss
Labels: bug, milano

#1152 Nav Kit Update
  app/pb_kits/playbook/pb_nav/_item.html.erb
  app/pb_kits/playbook/pb_nav/_item.jsx
  app/pb_kits/playbook/pb_nav/_nav.jsx
  app/pb_kits/playbook/pb_nav/_vertical_nav.scss
  app/pb_kits/playbook/pb_nav/docs/_borderless_nav.html.erb
  app/pb_kits/playbook/pb_nav/docs/_borderless_nav.jsx
  app/pb_kits/playbook/pb_nav/docs/_with_img_nav.html.erb
  app/pb_kits/playbook/pb_nav/docs/_with_img_nav.jsx
  app/pb_kits/playbook/pb_nav/docs/_with_img_nav.md
  app/pb_kits/playbook/pb_nav/docs/example.yml
  app/pb_kits/playbook/pb_nav/docs/index.js
  app/pb_kits/playbook/pb_nav/item.rb
  app/pb_kits/playbook/pb_nav/nav.rb
  spec/pb_kits/playbook/kits/nav_item_spec.rb
Labels: enhancement, milano

#1100 [NUX-639] - Caption Kits to support block / Time Kit style updates
  app/pb_kits/playbook/pb_body/body.rb
  app/pb_kits/playbook/pb_caption/_caption.html.erb
  app/pb_kits/playbook/pb_caption/docs/_caption_block.html.erb
  app/pb_kits/playbook/pb_caption/docs/_caption_block.jsx
  app/pb_kits/playbook/pb_caption/docs/example.yml
  app/pb_kits/playbook/pb_caption/docs/index.js
  app/pb_kits/playbook/pb_time/_time.html.erb
  app/pb_kits/playbook/pb_time/_time.jsx
  app/pb_kits/playbook/pb_time/_time.scss
  app/pb_kits/playbook/pb_time/docs/_time_align.jsx
  app/pb_kits/playbook/pb_time/docs/_time_default.html.erb
  app/pb_kits/playbook/pb_time/docs/_time_default.jsx
  app/pb_kits/playbook/pb_time/docs/_time_sizes.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timestamp.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timezone.jsx
  spec/pb_kits/playbook/kits/caption_spec.rb
Labels: enhancement, milano

#1155 Downgrade react-select lib
  package.json
  yarn.lock
Labels: bug

#1154 Highcharts React null value bug fix
  app/pb_kits/playbook/pb_circle_chart/_circle_chart.jsx
  app/pb_kits/playbook/pb_gauge/_gauge.jsx
Labels: bug, milano

#1108 [NUX-638] - Date Kit Refactor/Design
  app/pb_kits/playbook/pb_date/_date.html.erb
  app/pb_kits/playbook/pb_date/_date.jsx
  app/pb_kits/playbook/pb_date/_date.scss
  app/pb_kits/playbook/pb_date/date.rb
  app/pb_kits/playbook/pb_date/docs/_date_alignment.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_alignment.jsx
  app/pb_kits/playbook/pb_date/docs/_date_default.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_default.jsx
  app/pb_kits/playbook/pb_date/docs/_date_variants.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_variants.jsx
  app/pb_kits/playbook/pb_date/docs/example.yml
  app/pb_kits/playbook/pb_date/docs/index.js
  lib/playbook/version.rb
  spec/pb_kits/playbook/kits/date_spec.rb
Labels: enhancement, milano, rails, react

#1110 Create Background kit
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/react-examples.js
  app/pb_kits/playbook/pb_background/_background.html.erb
  app/pb_kits/playbook/pb_background/_background.jsx
  app/pb_kits/playbook/pb_background/_background.scss
  app/pb_kits/playbook/pb_background/background.rb
  app/pb_kits/playbook/pb_background/docs/_background_dark.html.erb
  app/pb_kits/playbook/pb_background/docs/_background_dark.jsx
  app/pb_kits/playbook/pb_background/docs/_background_gradient.html.erb
  app/pb_kits/playbook/pb_background/docs/_background_gradient.jsx
  app/pb_kits/playbook/pb_background/docs/_background_image.html.erb
  app/pb_kits/playbook/pb_background/docs/_background_image.jsx
  app/pb_kits/playbook/pb_background/docs/_background_light.html.erb
  app/pb_kits/playbook/pb_background/docs/_background_light.jsx
  app/pb_kits/playbook/pb_background/docs/_background_white.html.erb
  app/pb_kits/playbook/pb_background/docs/_background_white.jsx
  app/pb_kits/playbook/pb_background/docs/_description.md
  app/pb_kits/playbook/pb_background/docs/example.yml
  app/pb_kits/playbook/pb_background/docs/index.js
  spec/pb_kits/playbook/kits/background_spec.rb
Labels: milano, needs alpha testing, new kit

#1161 [BOP-726] Add safe navigator to address home's without addresses
  app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Labels: bug

#1158 Add solid example of Typeahead (default) Rails kit to Form kit
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
Labels: enhancement

#1166 Adding Google Analytics
  app/views/layouts/playbook/_ga.html.erb
  app/views/layouts/playbook/application.html.erb
Labels: improvement, milano

#1165 [NUXE-23] - Fix tooltip with CSS
  app/pb_kits/playbook/pb_tooltip/_tooltip.scss
  app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default.html.erb
  app/pb_kits/playbook/pb_tooltip/docs/_tooltip_white.html.erb
  app/pb_kits/playbook/pb_tooltip/tooltip.rb
Labels: bug, rails

#1131 [NUXE-156] Refactor date picker form helper to use text field helper
  app/pb_kits/playbook/pb_date_picker/_date_picker.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form_validate.html.erb
  app/pb_kits/playbook/pb_form/form_builder/date_picker_field.rb
  app/pb_kits/playbook/pb_progress_step/progress_step.rb
Labels: bug

#1071 [NUX-640] - New Date Time Kit
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/react-examples.js
  app/pb_kits/playbook/pb_date/date.rb
  app/pb_kits/playbook/pb_date_time/_date_time.html.erb
  app/pb_kits/playbook/pb_date_time/_date_time.jsx
  app/pb_kits/playbook/pb_date_time/_date_time.scss
  app/pb_kits/playbook/pb_date_time/date_time.rb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_align.html.erb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_align.jsx
  app/pb_kits/playbook/pb_date_time/docs/_date_time_default.html.erb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx
  app/pb_kits/playbook/pb_date_time/docs/_date_time_size.html.erb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_size.jsx
  app/pb_kits/playbook/pb_date_time/docs/_description.md
  app/pb_kits/playbook/pb_date_time/docs/example.yml
  app/pb_kits/playbook/pb_date_time/docs/index.js
  app/pb_kits/playbook/pb_flex/_flex.jsx
  app/pb_kits/playbook/pb_flex/_flex.scss
  app/pb_kits/playbook/pb_flex/flex.rb
  spec/pb_kits/playbook/kits/date_time_spec.rb
  spec/pb_kits/playbook/kits/flex_spec.rb
  spec/pb_kits/playbook/kits/time_spec.rb
Labels: enhancement, milano, new kit, rails, react

#1150 Timestamp Kit Formatted Date Additions
  app/pb_kits/playbook/pb_timestamp/_timestamp.html.erb
  app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  app/pb_kits/playbook/pb_timestamp/_timestamp.scss
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/example.yml
  app/pb_kits/playbook/pb_timestamp/docs/index.js
  app/pb_kits/playbook/pb_timestamp/timestamp.rb
  spec/pb_kits/playbook/kits/timestamp_spec.rb
  yarn.lock
Labels: enhancement, milano

#1172 Fix Bad SHA in react-select Version
  yarn.lock
Labels: bug, milano

#1175 Adds an Icon Prop to the Progress Step Item Kit
  app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
  app/pb_kits/playbook/pb_progress_step/_progress_step.scss
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.html.erb
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_custom_icon.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker_click_events.jsx
  app/pb_kits/playbook/pb_progress_step/docs/example.yml
  app/pb_kits/playbook/pb_progress_step/docs/index.js
  app/pb_kits/playbook/pb_progress_step/progress_step.rb
  app/pb_kits/playbook/pb_progress_step/progress_step_item.rb
Labels: enhancement, milano

#1173 [NUXE-50] Add landing page and getting started to docs
  app/assets/images/clark.jpg
  app/assets/images/giant.jpg
  app/assets/images/github-brands.svg
  app/assets/images/landing-background.svg
  app/assets/images/landing-image.svg
  app/assets/images/pb-logo.svg
  app/assets/images/pb-white-logo.svg
  app/controllers/playbook/pages_controller.rb
  app/pb_kits/playbook/packs/docs_components/SnippetToggle.jsx
  app/pb_kits/playbook/packs/landing-page.js
  app/pb_kits/playbook/packs/main.scss
  app/pb_kits/playbook/packs/site_styles/_getting_started.scss
  app/pb_kits/playbook/packs/site_styles/_landing-page.scss
  app/pb_kits/playbook/packs/site_styles/_site-style.scss
  app/views/layouts/playbook/_footer.html.erb
  app/views/layouts/playbook/_nav.html.erb
  app/views/layouts/playbook/_sidebar.html.erb
  app/views/layouts/playbook/application.html.erb
  app/views/layouts/playbook/kits.html.erb
  app/views/playbook/guides/getting_started/_rails_getting_started.md
  app/views/playbook/guides/getting_started/_react_getting_started.md
  app/views/playbook/pages/code_snippets/user_erb.txt
  app/views/playbook/pages/code_snippets/user_jsx.txt
  app/views/playbook/pages/getting_started.html.slim
  app/views/playbook/pages/home.html.erb
  app/views/playbook/pages/home.html.slim
  config/routes.rb
Labels: enhancement, milano

#1180 Revert "Timestamp Kit Formatted Date Additions"
  app/pb_kits/playbook/pb_timestamp/_timestamp.html.erb
  app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  app/pb_kits/playbook/pb_timestamp/_timestamp.scss
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.html.erb
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.jsx
  app/pb_kits/playbook/pb_timestamp/docs/example.yml
  app/pb_kits/playbook/pb_timestamp/docs/index.js
  app/pb_kits/playbook/pb_timestamp/timestamp.rb
  spec/pb_kits/playbook/kits/timestamp_spec.rb
  yarn.lock
Labels: milano
