Repository powerhome/playbook, pull requests merged in 2020-08, with the labels that each got.

#948 ★ Dark Mode Update Badge, Button, Circle Icon Button, Card, Checkbox and Body Kits
  CHANGELOG.md
  Makefile
  app/pb_kits/playbook/pb_badge/_badge.jsx
  app/pb_kits/playbook/pb_badge/_badge.scss
  app/pb_kits/playbook/pb_body/_body.jsx
  app/pb_kits/playbook/pb_body/_body.scss
  app/pb_kits/playbook/pb_body/body.rb
  app/pb_kits/playbook/pb_button/_button.jsx
  app/pb_kits/playbook/pb_button/_button.scss
  app/pb_kits/playbook/pb_button/button.rb
  app/pb_kits/playbook/pb_card/_card.jsx
  app/pb_kits/playbook/pb_card/_card.scss
  app/pb_kits/playbook/pb_card/card.rb
  app/pb_kits/playbook/pb_card/docs/_card_dark.html.erb
  app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
  app/pb_kits/playbook/pb_checkbox/checkbox.rb
  app/pb_kits/playbook/utilities/globalProps.js
  spec/pb_kits/playbook/kits/body_spec.rb
  spec/pb_kits/playbook/kits/checkbox_spec.rb
Labels: milano

#908 Generate button toolbar kit
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.html.erb
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.jsx
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
  app/pb_kits/playbook/pb_button_toolbar/button_toolbar.rb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_default.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_default.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_secondary.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_secondary.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical_secondary.html.erb
  app/pb_kits/playbook/pb_button_toolbar/docs/_button_toolbar_vertical_secondary.jsx
  app/pb_kits/playbook/pb_button_toolbar/docs/_description.md
  app/pb_kits/playbook/pb_button_toolbar/docs/example.yml
  app/pb_kits/playbook/pb_button_toolbar/docs/index.js
  spec/pb_kits/playbook/kits/button_toolbar_spec.rb
Labels: milano

#955 Updated Selectable Icon dark mode
  CHANGELOG.md
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.jsx
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.scss
  app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
  spec/pb_kits/playbook/kits/selectable_icon_spec.rb
Labels: milano

#972 Add Title Detail Dark Mode
  CHANGELOG.md
  app/pb_kits/playbook/pb_title_detail/_title_detail.html.erb
  app/pb_kits/playbook/pb_title_detail/_title_detail.jsx
  app/pb_kits/playbook/pb_title_detail/_title_detail.scss
  app/pb_kits/playbook/pb_title_detail/docs/_title_detail_dark.html.erb
  app/pb_kits/playbook/pb_title_detail/docs/_title_detail_dark.jsx
  app/pb_kits/playbook/pb_title_detail/docs/example.yml
  app/pb_kits/playbook/pb_title_detail/docs/index.js
  spec/pb_kits/playbook/kits/title_detail_spec.rb
Labels: enhancement, milano

#954 Update progress step
  CHANGELOG.md
  app/pb_kits/playbook/pb_progress_step/_progress_step.scss
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_child.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_child.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
  app/pb_kits/playbook/pb_progress_step/docs/example.yml
  app/pb_kits/playbook/pb_progress_step/docs/index.js
  app/pb_kits/playbook/pb_progress_step/progress_step.rb
  spec/pb_kits/playbook/kits/progress_step_spec.rb
Labels: enhancement, milano

#959 Automated changelog
  .github_changelog_generator
  Gemfile.lock
  HISTORY.md
  playbook_ui.gemspec
Labels: enhancement, ready

#963 NUX-1286 - Global Props for Dark on typeahead
  app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
  app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_context_dark.html.erb
  app/pb_kits/playbook/pb_typeahead/typeahead.rb
Labels: enhancement, ready

#964 NUX-1286 - Refactor dark props for text input
  app/pb_kits/playbook/pb_text_input/_text_input.html.erb
  app/pb_kits/playbook/pb_text_input/_text_input.jsx
  app/pb_kits/playbook/pb_text_input/_text_input.scss
  app/pb_kits/playbook/pb_text_input/docs/_text_input_disabled.html.erb
  app/pb_kits/playbook/pb_text_input/docs/_text_input_disabled.jsx
  app/pb_kits/playbook/pb_text_input/docs/example.yml
  app/pb_kits/playbook/pb_text_input/docs/index.js
  app/pb_kits/playbook/pb_text_input/text_input.rb
  spec/pb_kits/playbook/kits/text_input_spec.rb
Labels: enhancement

#966 NUX-1286 - Update dark props for Textarea kit
  app/pb_kits/playbook/pb_textarea/_textarea.jsx
  app/pb_kits/playbook/pb_textarea/_textarea.scss
  app/pb_kits/playbook/pb_textarea/docs/_textarea_dark.jsx
  app/pb_kits/playbook/pb_textarea/docs/_textarea_dark_error.jsx
  app/pb_kits/playbook/pb_textarea/textarea.rb
  spec/pb_kits/playbook/kits/textarea_spec.rb
Labels: enhancement

#983 Update card header kit so that it passes product colors
  app/pb_kits/playbook/pb_card/_card.jsx
  app/pb_kits/playbook/pb_card/_card.scss
  app/pb_kits/playbook/pb_card/_card_mixin.scss
  app/pb_kits/playbook/pb_card/card_header.rb
  app/pb_kits/playbook/pb_card/docs/_card_header.html.erb
  app/pb_kits/playbook/pb_card/docs/_card_header.jsx
  app/pb_kits/playbook/pb_card/docs/_card_header.md
  spec/pb_kits/playbook/kits/card_header_spec.rb
Labels: enhancement, ready

#953 Add checkbox to form helper
  app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
  app/pb_kits/playbook/pb_checkbox/checkbox.rb
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb
  app/pb_kits/playbook/pb_form/docs/_form_simple_form_validate.html.erb
  app/pb_kits/playbook/pb_form/form_builder.rb
  app/pb_kits/playbook/pb_form/form_builder/checkbox_field.rb
  spec/pb_kits/playbook/kits/checkbox_spec.rb
Labels: enhancement, milano

#991 Create online status dark mode
  app/pb_kits/playbook/pb_online_status/_online_status.html.erb
  app/pb_kits/playbook/pb_online_status/_online_status.jsx
  app/pb_kits/playbook/pb_online_status/_online_status_mixins.scss
  app/pb_kits/playbook/pb_online_status/docs/_online_status_dark.html.erb
  app/pb_kits/playbook/pb_online_status/docs/_online_status_dark.jsx
  app/pb_kits/playbook/pb_online_status/docs/example.yml
  app/pb_kits/playbook/pb_online_status/docs/index.js
  spec/pb_kits/playbook/kits/online_status_spec.rb
Labels: enhancement, milano

#992 Create Pill dark mode
  app/pb_kits/playbook/pb_pill/_pill.html.erb
  app/pb_kits/playbook/pb_pill/_pill.jsx
  app/pb_kits/playbook/pb_pill/_pill.scss
  app/pb_kits/playbook/pb_pill/docs/_pill_dark.html.erb
  app/pb_kits/playbook/pb_pill/docs/_pill_dark.jsx
  app/pb_kits/playbook/pb_pill/docs/example.yml
  app/pb_kits/playbook/pb_pill/docs/index.js
  spec/pb_kits/playbook/kits/pill_spec.rb
Labels: enhancement, milano

#987 Add dark mode to Multiple Users
  app/pb_kits/playbook/pb_multiple_users/_multiple_users.html.erb
  app/pb_kits/playbook/pb_multiple_users/_multiple_users.jsx
  app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
  app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_dark.html.erb
  app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_dark.jsx
  app/pb_kits/playbook/pb_multiple_users/docs/example.yml
  app/pb_kits/playbook/pb_multiple_users/docs/index.js
  spec/pb_kits/playbook/kits/multiple_users_spec.rb
Labels: enhancement, milano

#981 Add dark mode to Fixed Confirmation Toast
  app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.html.erb
  app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_dark.html.erb
  app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_dark.jsx
  app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_dark.html.erb
  app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_dark.jsx
  app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml
  app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js
  spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
Labels: enhancement, ready

#1005 Add spacing docs
  app/views/playbook/pages/tokens/_pb_doc_spacing.html.slim
Labels: enhancement, milano, ready

#984 Add User Badge dark mode
  app/pb_kits/playbook/pb_user_badge/_user_badge.html.erb
  app/pb_kits/playbook/pb_user_badge/_user_badge.jsx
  app/pb_kits/playbook/pb_user_badge/docs/_user_badge_dark.html.erb
  app/pb_kits/playbook/pb_user_badge/docs/_user_badge_dark.jsx
  app/pb_kits/playbook/pb_user_badge/docs/_user_badge_size_dark.html.erb
  app/pb_kits/playbook/pb_user_badge/docs/_user_badge_size_dark.jsx
  app/pb_kits/playbook/pb_user_badge/docs/example.yml
  app/pb_kits/playbook/pb_user_badge/docs/index.js
  spec/pb_kits/playbook/kits/user_badge_spec.rb
Labels: enhancement, ready

#1011 Grouping Badge, Hashtag, and Pill kits
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/pb_badge/docs/_description.md
Labels: enhancement, milano

#1007 Refactor Progress Step & added Tracker variant
  app/pb_kits/playbook/pb_progress_step/_progress_step.html.erb
  app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
  app/pb_kits/playbook/pb_progress_step/_progress_step.scss
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.html.erb
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_description.md
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_dark.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/example.yml
  app/pb_kits/playbook/pb_progress_step/docs/index.js
  app/pb_kits/playbook/pb_progress_step/progress_step.rb
  app/pb_kits/playbook/pb_progress_step/progress_step_item.rb
  spec/pb_kits/playbook/kits/progress_step_item_spec.rb
  spec/pb_kits/playbook/kits/progress_step_spec.rb
Labels: enhancement, milano

#989 Add props to Nav
  app/pb_kits/playbook/pb_nav/_item.html.erb
  app/pb_kits/playbook/pb_nav/_item.jsx
  app/pb_kits/playbook/pb_nav/_nav.html.erb
  app/pb_kits/playbook/pb_nav/_nav.jsx
  app/pb_kits/playbook/pb_nav/docs/example.yml
Labels: enhancement, ready

#986 Table dark mode
  app/pb_kits/playbook/pb_table/_table.html.erb
  app/pb_kits/playbook/pb_table/_table.jsx
  app/pb_kits/playbook/pb_table/_table_row.html.erb
  app/pb_kits/playbook/pb_table/_table_row.jsx
  app/pb_kits/playbook/pb_table/table.rb
  spec/pb_kits/playbook/kits/table_spec.rb
Labels: enhancement, ready

#988 Multiple users stacked dark mode
  app/pb_kits/playbook/pb_badge/_badge.jsx
  app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.html.erb
  app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.jsx
  app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.scss
  app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_dark.html.erb
  app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_dark.jsx
  app/pb_kits/playbook/pb_multiple_users_stacked/docs/example.yml
  app/pb_kits/playbook/pb_multiple_users_stacked/docs/index.js
  spec/pb_kits/playbook/kits/multiple_users_stacked_spec.rb
Labels: enhancement, milano

#1014 Link variant for Title 4 and Caption xs
  app/pb_kits/playbook/pb_caption/_caption.jsx
  app/pb_kits/playbook/pb_caption/_caption.scss
  app/pb_kits/playbook/pb_caption/caption.rb
  app/pb_kits/playbook/pb_caption/docs/_caption_variants.html.erb
  app/pb_kits/playbook/pb_caption/docs/_caption_variants.jsx
  app/pb_kits/playbook/pb_caption/docs/_caption_variants.md
  app/pb_kits/playbook/pb_caption/docs/example.yml
  app/pb_kits/playbook/pb_caption/docs/index.js
  app/pb_kits/playbook/pb_title/_title.jsx
  app/pb_kits/playbook/pb_title/_title.scss
  app/pb_kits/playbook/pb_title/docs/_title_variants.html.erb
  app/pb_kits/playbook/pb_title/docs/_title_variants.jsx
  app/pb_kits/playbook/pb_title/docs/_title_variants.md
  app/pb_kits/playbook/pb_title/docs/example.yml
  app/pb_kits/playbook/pb_title/docs/index.js
  spec/pb_kits/playbook/kits/caption_spec.rb
Labels: enhancement, milano

#1008 [NUX-1351] - Update react timezone implementation and examples
  app/pb_kits/playbook/pb_time/_time.jsx
  app/pb_kits/playbook/pb_time/docs/_time_dark.jsx
  app/pb_kits/playbook/pb_time/docs/_time_default.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timestamp.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timezone.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timezone.md
  app/pb_kits/playbook/pb_time/docs/example.yml
  app/pb_kits/playbook/pb_time/docs/index.js
Labels: enhancement, milano

#1034 [NUX-1370] - Date Kit Timezone Props
  app/pb_kits/playbook/pb_date/date.rb
  app/pb_kits/playbook/pb_date/docs/_date_default.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_timezone.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_timezone.md
  app/pb_kits/playbook/pb_date/docs/_description.md
  app/pb_kits/playbook/pb_date/docs/example.yml
  spec/pb_kits/playbook/kits/date_spec.rb
Labels: bug, milano, rails

#1038 [NUX-1347] - Reduce input css specificity
  app/pb_kits/playbook/pb_text_input/_text_input.scss
Labels: bug, milano

#1042 [NUX-1351] - Update react timezone implementation and examples
  app/pb_kits/playbook/pb_time/_time.jsx
  app/pb_kits/playbook/pb_time/docs/_time_dark.jsx
  app/pb_kits/playbook/pb_time/docs/_time_default.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timestamp.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timezone.jsx
  app/pb_kits/playbook/pb_time/docs/_time_timezone.md
  app/pb_kits/playbook/pb_time/docs/example.yml
  app/pb_kits/playbook/pb_time/docs/index.js
Labels: enhancement, milano

#1044 Disable hovers for mobile
  app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
  app/pb_kits/playbook/pb_button/_button_mixins.scss
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
  app/pb_kits/playbook/pb_card/_card_mixin.scss
  app/pb_kits/playbook/pb_checkbox/_checkbox.scss
  app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  app/pb_kits/playbook/pb_icon/docs/_icon_default_dark.html.erb
  app/pb_kits/playbook/pb_icon/docs/_icon_default_dark.jsx
  app/pb_kits/playbook/pb_nav/_horizontal_nav.scss
  app/pb_kits/playbook/pb_nav/_vertical_nav.scss
  app/pb_kits/playbook/pb_radio/_radio.scss
  app/pb_kits/playbook/pb_select/_select.scss
  app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.scss
  app/pb_kits/playbook/pb_table/styles/_hover.scss
  app/pb_kits/playbook/pb_table/styles/_mobile.scss
  app/pb_kits/playbook/pb_table/styles/_table-dark.scss
  app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: bug, milano
