Repository powerhome/playbook, pull requests merged in 2020-05, with the labels that each got.

#796 Update filter kit
  app/pb_kits/playbook/pb_filter/Filter/CurrentFilters.jsx
  app/pb_kits/playbook/pb_filter/Filter/FilterBackground.jsx
  app/pb_kits/playbook/pb_filter/Filter/FilterDouble.jsx
  app/pb_kits/playbook/pb_filter/Filter/FilterSingle.jsx
  app/pb_kits/playbook/pb_filter/Filter/FiltersPopover.jsx
  app/pb_kits/playbook/pb_filter/Filter/ResultsCount.jsx
  app/pb_kits/playbook/pb_filter/Filter/SortMenu.jsx
  app/pb_kits/playbook/pb_filter/Filter/index.jsx
  app/pb_kits/playbook/pb_filter/_filter.jsx
  app/pb_kits/playbook/pb_filter/_filter.scss
  app/pb_kits/playbook/pb_filter/docs/_filter_default.html.erb
  app/pb_kits/playbook/pb_filter/docs/_filter_default.jsx
  app/pb_kits/playbook/pb_filter/docs/_filter_no_background.html.erb
  app/pb_kits/playbook/pb_filter/docs/_filter_no_background.jsx
  app/pb_kits/playbook/pb_filter/docs/_filter_only.html.erb
  app/pb_kits/playbook/pb_filter/docs/_filter_only.jsx
  app/pb_kits/playbook/pb_filter/docs/_filter_single.html.erb
  app/pb_kits/playbook/pb_filter/docs/_filter_single.jsx
  app/pb_kits/playbook/pb_filter/docs/_sort_only.html.erb
  app/pb_kits/playbook/pb_filter/docs/_sort_only.jsx
  app/pb_kits/playbook/pb_filter/templates/_default.html.erb
  app/pb_kits/playbook/pb_popover/_popover.jsx
Labels: milano

#788 Add react online status kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_online_status/_online_status.jsx
  app/pb_kits/playbook/pb_online_status/docs/_online_status_default.jsx
  app/pb_kits/playbook/pb_online_status/docs/example.yml
  app/pb_kits/playbook/pb_online_status/docs/index.js
Labels: milano, ready

#795 Fix stat change so it allows numbers over 100
  CHANGELOG.md
  app/pb_kits/playbook/pb_stat_change/docs/_stat_change_default.html.erb
  app/pb_kits/playbook/pb_stat_change/docs/_stat_change_default.jsx
  app/pb_kits/playbook/pb_stat_change/stat_change.rb
  spec/pb_kits/playbook/kits/stat_change_spec.rb
Labels: milano, ready

#799 Person contact fix
  CHANGELOG.md
  app/pb_kits/playbook/pb_contact/_contact.jsx
  app/pb_kits/playbook/pb_contact/contact.rb
  app/pb_kits/playbook/pb_contact/docs/_contact_default.html.erb
  app/pb_kits/playbook/pb_contact/docs/_contact_default.jsx
  app/pb_kits/playbook/pb_contact/docs/_contact_with_detail.html.erb
  app/pb_kits/playbook/pb_contact/docs/_contact_with_detail.jsx
  spec/pb_kits/playbook/kits/contact_spec.rb
  yarn.lock
Labels: milano, ready

#776 Progress Step Kit
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/packs/kits/pb_progress_step.js
  app/pb_kits/playbook/pb_progress_step/_progress_step.html.erb
  app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
  app/pb_kits/playbook/pb_progress_step/_progress_step.scss
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.html.erb
  app/pb_kits/playbook/pb_progress_step/_progress_step_item.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_description.md
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_dark.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_dark.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.html.erb
  app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.jsx
  app/pb_kits/playbook/pb_progress_step/docs/example.yml
  app/pb_kits/playbook/pb_progress_step/docs/index.js
  app/pb_kits/playbook/pb_progress_step/progress_step.rb
  app/pb_kits/playbook/pb_progress_step/progress_step_item.rb
  spec/pb_kits/playbook/kits/progress_step_item_spec.rb
  spec/pb_kits/playbook/kits/progress_step_spec.rb
Labels: milano, ready

#800 Fix button loading
  CHANGELOG.md
  app/pb_kits/playbook/pb_button/_button.jsx
Labels: ready

#801 Updated react version of layout kit to use sub-components
  CHANGELOG.md
  app/pb_kits/playbook/pb_layout/_body.jsx
  app/pb_kits/playbook/pb_layout/_layout.jsx
  app/pb_kits/playbook/pb_layout/_sidebar.jsx
  app/pb_kits/playbook/pb_layout/docs/_layout_colors.jsx
  app/pb_kits/playbook/pb_layout/docs/_layout_default.jsx
  app/pb_kits/playbook/pb_layout/docs/_layout_sizes.jsx
  app/pb_kits/playbook/pb_layout/docs/_layout_sizes_dark.jsx
  app/pb_kits/playbook/pb_layout/docs/_layout_transparent.jsx
  app/pb_kits/playbook/pb_layout/docs/example.yml
  app/pb_kits/playbook/pb_layout/docs/index.js
Labels: milano, ready

#786 Add react timestamp kit
  CHANGELOG.md
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  app/pb_kits/playbook/pb_timestamp/docs/example.yml
  app/pb_kits/playbook/pb_timestamp/docs/index.js
Labels: milano, ready

#794 Setup Default Correctly in DateYearStacked React implementation
  CHANGELOG.md
  app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.jsx
Labels: milano, ready

#783 Create TitleDetail React component
  CHANGELOG.md
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/pb_title_detail/_title_detail.jsx
  app/pb_kits/playbook/pb_title_detail/docs/_title_detail_default.jsx
  app/pb_kits/playbook/pb_title_detail/docs/example.yml
  app/pb_kits/playbook/pb_title_detail/docs/index.js
Labels: milano, ready

#750 Tooltip V2
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/pb_popover/docs/_popover_with_button.html.erb
  app/pb_kits/playbook/pb_popover/docs/example.yml
  app/pb_kits/playbook/pb_popover/docs/index.js
  app/pb_kits/playbook/pb_tooltip/_tooltip.html.erb
  app/pb_kits/playbook/pb_tooltip/_tooltip.scss
  app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default.html.erb
  app/pb_kits/playbook/pb_tooltip/docs/_tooltip_white.html.erb
  app/pb_kits/playbook/pb_tooltip/docs/example.yml
  app/pb_kits/playbook/pb_tooltip/index.js
  app/pb_kits/playbook/pb_tooltip/tooltip.rb
  app/pb_kits/playbook/tokens/_colors.scss
  app/pb_kits/playbook/vendor.js
  spec/pb_kits/playbook/kits/tooltip_spec.rb
Labels: milano, ready

#812 Aria data id fixes for text input
  CHANGELOG.md
  app/pb_kits/playbook/pb_text_input/_text_input.html.erb
  app/pb_kits/playbook/pb_text_input/_text_input.jsx
  app/pb_kits/playbook/pb_text_input/docs/_text_input_default.html.erb
  app/pb_kits/playbook/pb_text_input/docs/_text_input_default.jsx
  app/pb_kits/playbook/pb_text_input/text_input.rb
Labels: milano

#813 Label pill react
  CHANGELOG.md
  app/pb_kits/playbook/pb_label_pill/_label_pill.html.erb
  app/pb_kits/playbook/pb_label_pill/_label_pill.jsx
  app/pb_kits/playbook/pb_label_pill/docs/_label_pill_default.jsx
  app/pb_kits/playbook/pb_label_pill/docs/example.yml
  app/pb_kits/playbook/pb_label_pill/docs/index.js
  app/pb_kits/playbook/pb_label_pill/label_pill.rb
  spec/pb_kits/playbook/kits/label_pill_spec.rb
Labels: milano

#818 Added legend prop to bar and line graphs
  CHANGELOG.md
  app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.html.erb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.jsx
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend.html.erb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend.jsx
  app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  app/pb_kits/playbook/pb_bar_graph/docs/index.js
  app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.html.erb
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.jsx
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend.html.erb
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend.jsx
  app/pb_kits/playbook/pb_line_graph/docs/example.yml
  app/pb_kits/playbook/pb_line_graph/docs/index.js
  app/pb_kits/playbook/pb_line_graph/line_graph.rb
  app/pb_kits/playbook/plugins/pb_chart.js
Labels: milano

#819 Added height prop to Bar Graph Kit and Line Graph Kit
  CHANGELOG.md
  app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.html.erb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.jsx
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_height.html.erb
  app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_height.jsx
  app/pb_kits/playbook/pb_bar_graph/docs/_description.md
  app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  app/pb_kits/playbook/pb_bar_graph/docs/index.js
  app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  app/pb_kits/playbook/pb_line_graph/docs/_description.md
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.html.erb
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.jsx
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.html.erb
  app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.jsx
  app/pb_kits/playbook/pb_line_graph/docs/example.yml
  app/pb_kits/playbook/pb_line_graph/docs/index.js
  app/pb_kits/playbook/pb_line_graph/line_graph.rb
  app/pb_kits/playbook/plugins/pb_chart.js
Labels: milano

#820 Fix currency kit performance (Rails)
  CHANGELOG.md
  app/pb_kits/playbook/pb_currency/_currency.html.erb
  app/pb_kits/playbook/pb_currency/currency.rb
Labels: milano

#822 Star rating react and fix hide_rating feature
  CHANGELOG.md
  app/pb_kits/playbook/pb_star_rating/_star_rating.html.erb
  app/pb_kits/playbook/pb_star_rating/_star_rating.jsx
  app/pb_kits/playbook/pb_star_rating/docs/_star_rating_default.jsx
  app/pb_kits/playbook/pb_star_rating/docs/_star_rating_hide.jsx
  app/pb_kits/playbook/pb_star_rating/docs/example.yml
  app/pb_kits/playbook/pb_star_rating/docs/index.js
  app/pb_kits/playbook/pb_star_rating/star_rating.rb
  spec/pb_kits/playbook/kits/star_rating_spec.rb
Labels: milano

#782 Selectable card icon
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.jsx
  app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.scss
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_checkmark.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_checkmark.jsx
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_dark.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_dark.jsx
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_default.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_default.jsx
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_single_select.html.erb
  app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_single_select.jsx
  app/pb_kits/playbook/pb_selectable_card_icon/docs/example.yml
  app/pb_kits/playbook/pb_selectable_card_icon/docs/index.js
  app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.rb
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.html.erb
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.jsx
  app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.scss
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_dark.html.erb
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_dark.jsx
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_default.html.erb
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_default.jsx
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_single_select.html.erb
  app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_single_select.jsx
  app/pb_kits/playbook/pb_selectable_icon/docs/example.yml
  app/pb_kits/playbook/pb_selectable_icon/docs/index.js
  app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
  app/pb_kits/playbook/tokens/_colors.scss
  spec/pb_kits/playbook/kits/selectable_card_icon_spec.rb
  spec/pb_kits/playbook/kits/selectable_icon_spec.rb
Labels: milano

#810 Source kit for React
  CHANGELOG.md
  app/pb_kits/playbook/pb_source/_source.jsx
  app/pb_kits/playbook/pb_source/docs/_source_default.html.erb
  app/pb_kits/playbook/pb_source/docs/_source_default.jsx
  app/pb_kits/playbook/pb_source/docs/_source_noicon.jsx
  app/pb_kits/playbook/pb_source/docs/_source_types.jsx
  app/pb_kits/playbook/pb_source/docs/example.yml
  app/pb_kits/playbook/pb_source/docs/index.js
Labels: milano

#823 Added link & new window props to circle icon button
  CHANGELOG.md
  app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.html.erb
  app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.jsx
  app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb
  app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.html.erb
  app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.jsx
  app/pb_kits/playbook/pb_circle_icon_button/docs/example.yml
  app/pb_kits/playbook/pb_circle_icon_button/docs/index.js
  spec/pb_kits/playbook/kits/circle_icon_button_spec.rb
Labels: milano
