Repository powerhome/playbook, pull requests merged in 2020-04, with the labels that each got.

#691 Add onclick handler to icon
  CHANGELOG.md
  app/pb_kits/playbook/pb_icon/_icon.jsx
Labels: wip

#694 Add onClick prop to kits in need
  CHANGELOG.md
  app/pb_kits/playbook/pb_button/docs/_button_options.jsx
  app/pb_kits/playbook/pb_button/docs/example.yml
  app/pb_kits/playbook/pb_checkbox/docs/_checkbox_custom.jsx
  app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.jsx
  app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_click.jsx
  app/pb_kits/playbook/pb_circle_icon_button/docs/example.yml
  app/pb_kits/playbook/pb_circle_icon_button/docs/index.js
  app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.jsx
  app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.jsx
  app/pb_kits/playbook/pb_radio/docs/_radio_custom.jsx
Labels: wip

#680 Time Range Inline kit
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_kit/dateTime.js
  app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.html.erb
  app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.jsx
  app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
  app/pb_kits/playbook/pb_time_range_inline/docs/_time_range_inline_dark.html.erb
  app/pb_kits/playbook/pb_time_range_inline/docs/_time_range_inline_dark.jsx
  app/pb_kits/playbook/pb_time_range_inline/docs/_time_range_inline_default.html.erb
  app/pb_kits/playbook/pb_time_range_inline/docs/_time_range_inline_default.jsx
  app/pb_kits/playbook/pb_time_range_inline/docs/example.yml
  app/pb_kits/playbook/pb_time_range_inline/docs/index.js
  app/pb_kits/playbook/pb_time_range_inline/time_range_inline.rb
  spec/pb_kits/playbook/kits/time_range_inline_spec.rb
Labels: New Kit

#724 [GOG-146] Add ephemeral-storage quota
  config/deploy/templates/deployment.yaml.erb
Labels: guardians

#667 Logistic Kit
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_kit/dateTime.js
  app/pb_kits/playbook/pb_logistic/_logistic.html.erb
  app/pb_kits/playbook/pb_logistic/_logistic.jsx
  app/pb_kits/playbook/pb_logistic/_logistic.scss
  app/pb_kits/playbook/pb_logistic/docs/_logistic_dark.html.erb
  app/pb_kits/playbook/pb_logistic/docs/_logistic_dark.jsx
  app/pb_kits/playbook/pb_logistic/docs/_logistic_default.html.erb
  app/pb_kits/playbook/pb_logistic/docs/_logistic_default.jsx
  app/pb_kits/playbook/pb_logistic/docs/example.yml
  app/pb_kits/playbook/pb_logistic/docs/index.js
  app/pb_kits/playbook/pb_logistic/logistic.rb
  spec/pb_kits/playbook/kits/logistic_spec.rb
Labels: New Kit

#705 Weekday Stacked Kit
  CHANGELOG.md
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_kit/dateTime.js
  app/pb_kits/playbook/pb_kit/pb_date_time.rb
  app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.html.erb
  app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.jsx
  app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.scss
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_compact.html.erb
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_compact.jsx
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_dark.html.erb
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_dark.jsx
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_day_only.html.erb
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_day_only.jsx
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_default.html.erb
  app/pb_kits/playbook/pb_weekday_stacked/docs/_weekday_stacked_default.jsx
  app/pb_kits/playbook/pb_weekday_stacked/docs/example.yml
  app/pb_kits/playbook/pb_weekday_stacked/docs/index.js
  app/pb_kits/playbook/pb_weekday_stacked/weekday_stacked.rb
  spec/pb_kits/playbook/kits/weekday_stacked_spec.rb
Labels: New Kit

#730 File upload kit + doc tabs cleanup
  CHANGELOG.md
  app/controllers/playbook/pages_controller.rb
  app/helpers/playbook/pb_doc_helper.rb
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_file_upload/_file_upload.jsx
  app/pb_kits/playbook/pb_file_upload/_file_upload.scss
  app/pb_kits/playbook/pb_file_upload/docs/_description.md
  app/pb_kits/playbook/pb_file_upload/docs/_file_upload_accept.jsx
  app/pb_kits/playbook/pb_file_upload/docs/_file_upload_default.jsx
  app/pb_kits/playbook/pb_file_upload/docs/example.yml
  app/pb_kits/playbook/pb_file_upload/docs/index.js
  app/pb_kits/playbook/pb_file_upload/file_upload.rb
  app/pb_kits/playbook/pb_label_pill/docs/_label_pill_default.jsx
  app/pb_kits/playbook/pb_label_pill/docs/example.yml
  app/pb_kits/playbook/pb_label_pill/docs/index.js
  app/pb_kits/playbook/pb_online_status/docs/_online_status_default.jsx
  app/pb_kits/playbook/pb_online_status/docs/example.yml
  app/pb_kits/playbook/pb_online_status/docs/index.js
  app/pb_kits/playbook/pb_source/docs/_source_default.jsx
  app/pb_kits/playbook/pb_source/docs/example.yml
  app/pb_kits/playbook/pb_source/docs/index.js
  app/pb_kits/playbook/pb_star_rating/docs/_star_rating_default.jsx
  app/pb_kits/playbook/pb_star_rating/docs/example.yml
  app/pb_kits/playbook/pb_star_rating/docs/index.js
  app/pb_kits/playbook/pb_time/docs/_time_default.jsx
  app/pb_kits/playbook/pb_time/docs/example.yml
  app/pb_kits/playbook/pb_time/docs/index.js
  app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  app/pb_kits/playbook/pb_timestamp/docs/example.yml
  app/pb_kits/playbook/pb_timestamp/docs/index.js
  app/pb_kits/playbook/pb_title_detail/docs/_title_detail_default.jsx
  app/pb_kits/playbook/pb_title_detail/docs/example.yml
  app/pb_kits/playbook/pb_title_detail/docs/index.js
  package.json
  yarn.lock
Labels: New Kit

#749 Limit webpacker CPU & memory on local dev
  CHANGELOG.md
  config/webpack/loaders/erb.js
  docker-compose.yml
  package.json
  yarn.lock
Labels: development

#762 [GOG-162] Pass the correct environment configs
  bin/deploy
  config/deploy/production/values.yaml
  config/deploy/prs/values.yaml
  config/deploy/staging/values.yaml
Labels: milano
