Repository powerhome/playbook, pull requests merged in 2020-09, with the labels that each got.

#1048 Attempting to fix scrollbars on Windows
  app/pb_kits/playbook/pb_filter/_filter.scss
Labels: milano

#1039 Updated Styling for Toggle
  app/pb_kits/playbook/pb_toggle/_toggle.scss
  app/pb_kits/playbook/pb_toggle/docs/_toggle_size.html.erb
  app/pb_kits/playbook/pb_toggle/docs/_toggle_size.jsx
  app/pb_kits/playbook/pb_toggle/docs/example.yml
  app/pb_kits/playbook/pb_toggle/docs/index.js
  app/pb_kits/playbook/pb_toggle/toggle.rb
  spec/pb_kits/playbook/kits/toggle_spec.rb
Labels: breaking, enhancement, milano

#1055 [NUX-640] - Add Date Time kit, update supporting kits
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/data/menu.yml
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_date/_date.jsx
  app/pb_kits/playbook/pb_date/docs/_date_default_react.jsx
  app/pb_kits/playbook/pb_date/docs/_date_timezone_react.jsx
  app/pb_kits/playbook/pb_date/docs/example.yml
  app/pb_kits/playbook/pb_date/docs/index.js
  app/pb_kits/playbook/pb_date_time/_date_time.html.erb
  app/pb_kits/playbook/pb_date_time/_date_time.jsx
  app/pb_kits/playbook/pb_date_time/_date_time.scss
  app/pb_kits/playbook/pb_date_time/date_time.rb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_align.html.erb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_align.jsx
  app/pb_kits/playbook/pb_date_time/docs/_date_time_default.html.erb
  app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx
  app/pb_kits/playbook/pb_date_time/docs/_description.md
  app/pb_kits/playbook/pb_date_time/docs/example.yml
  app/pb_kits/playbook/pb_date_time/docs/index.js
  app/pb_kits/playbook/pb_time/_time.html.erb
  app/pb_kits/playbook/pb_time/_time.jsx
  app/pb_kits/playbook/pb_time/docs/_time_default.html.erb
  app/pb_kits/playbook/pb_time/docs/_time_default.jsx
  app/pb_kits/playbook/pb_time/time.rb
  spec/pb_kits/playbook/kits/date_time_spec.rb
  spec/pb_kits/playbook/kits/time_spec.rb
Labels: milano

#1043 Button & Circle Icon Button Cleanup
  app/pb_kits/playbook/pb_button/_button.jsx
  app/pb_kits/playbook/pb_button/_button_mixins.scss
  app/pb_kits/playbook/pb_button/docs/_button_default.jsx
  app/pb_kits/playbook/pb_button/docs/_button_default_dark.jsx
  app/pb_kits/playbook/pb_button/docs/_button_link.jsx
  app/pb_kits/playbook/pb_button/docs/_button_loading.jsx
  app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.html.erb
Labels: enhancement, milano

#1068 reverting again
  app/pb_kits/playbook/pb_date/_date.html.erb
  app/pb_kits/playbook/pb_date/_date.jsx
  app/pb_kits/playbook/pb_date/_date.scss
  app/pb_kits/playbook/pb_date/date.rb
  app/pb_kits/playbook/pb_date/docs/_date_alignment.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_alignment.jsx
  app/pb_kits/playbook/pb_date/docs/_date_default.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_default.jsx
  app/pb_kits/playbook/pb_date/docs/_date_default_react.jsx
  app/pb_kits/playbook/pb_date/docs/_date_default_react.md
  app/pb_kits/playbook/pb_date/docs/_date_timezone.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_timezone.md
  app/pb_kits/playbook/pb_date/docs/_date_variants.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_variants.jsx
  app/pb_kits/playbook/pb_date/docs/_description.md
  app/pb_kits/playbook/pb_date/docs/example.yml
  app/pb_kits/playbook/pb_date/docs/index.js
  spec/pb_kits/playbook/kits/date_spec.rb
Labels: enhancement, milano

#1083 Popover Sass Patch
  app/pb_kits/playbook/pb_date_picker/_date_picker.scss
Labels: milano

#1082 Renovate/npm highcharts vulnerability
  package.json
  yarn.lock
Labels: improvement

#1054 Typeahead w/ Pills (React)
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
  app/pb_kits/playbook/pb_text_input/_text_input.scss
  app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  app/pb_kits/playbook/pb_typeahead/components/Control.jsx
  app/pb_kits/playbook/pb_typeahead/components/IndicatorsContainer.jsx
  app/pb_kits/playbook/pb_typeahead/components/MenuList.jsx
  app/pb_kits/playbook/pb_typeahead/components/MultiValue.jsx
  app/pb_kits/playbook/pb_typeahead/components/Option.jsx
  app/pb_kits/playbook/pb_typeahead/components/Placeholder.jsx
  app/pb_kits/playbook/pb_typeahead/components/ValueContainer.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_summary.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_users.jsx
  app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_summary.jsx
  app/pb_kits/playbook/pb_typeahead/docs/example.yml
  app/pb_kits/playbook/pb_typeahead/docs/index.js
  package.json
  yarn.lock
Labels: enhancement

#1080 Add timezone prop to date, expand docs
  app/pb_kits/playbook/pb_date/date.rb
  app/pb_kits/playbook/pb_date/docs/_date_default.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_timezone.html.erb
  app/pb_kits/playbook/pb_date/docs/_date_timezone.md
  app/pb_kits/playbook/pb_date/docs/_description.md
  app/pb_kits/playbook/pb_date/docs/example.yml
  spec/pb_kits/playbook/kits/date_spec.rb
Labels: breaking, enhancement, wip

#1086 Date Picker Second Patch
  app/pb_kits/playbook/pb_date_picker/_date_picker.jsx
  app/pb_kits/playbook/pb_date_picker/date_picker.rb
  app/pb_kits/playbook/pb_date_picker/date_picker_helper.js
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.html.erb
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.md
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_read_only.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_read_only.md
  app/pb_kits/playbook/pb_date_picker/docs/example.yml
  app/pb_kits/playbook/pb_date_picker/docs/index.js
  app/pb_kits/playbook/pb_date_picker/sass_partials/_calendar_input_icon.scss
  spec/pb_kits/playbook/kits/date_picker_spec.rb
Labels: milano

#1095 Bug Fix - Swap show_timezone to be false by default
  app/pb_kits/playbook/pb_time/docs/_time_dark.html.erb
  app/pb_kits/playbook/pb_time/docs/_time_default.html.erb
  app/pb_kits/playbook/pb_time/docs/_time_timestamp.html.erb
  app/pb_kits/playbook/pb_time/docs/_time_timezone.html.erb
  app/pb_kits/playbook/pb_time/time.rb
Labels: bug, rails

#1088 Make it
  Makefile
Labels: enhancement, ready

#1106 React Circle Chart
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/examples.js
  app/pb_kits/playbook/pb_circle_chart/_circle_chart.html.erb
  app/pb_kits/playbook/pb_circle_chart/_circle_chart.jsx
  app/pb_kits/playbook/pb_circle_chart/_circle_chart.scss
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_block.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_colors.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_default.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_inner_sizes.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_live_data.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_rounded.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_with_labels.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_with_legend_kit.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_with_title.jsx
  app/pb_kits/playbook/pb_circle_chart/docs/example.yml
  app/pb_kits/playbook/pb_circle_chart/docs/index.js
  app/pb_kits/playbook/plugins/pb_chart.js
Labels: enhancement, milano, new kit, ready

#1099 [CMPN-17] Add input options to Radio Kit
  app/pb_kits/playbook/pb_radio/_radio.html.erb
  app/pb_kits/playbook/pb_radio/docs/_radio_options.html.erb
  app/pb_kits/playbook/pb_radio/docs/example.yml
  app/pb_kits/playbook/pb_radio/radio.rb
  spec/pb_kits/playbook/kits/radio_spec.rb
Labels: enhancement, milano, ready

#1096 [NUXE-66] - Added Date Picker React onChange Prop
  app/pb_kits/playbook/pb_date_picker/_date_picker.jsx
  app/pb_kits/playbook/pb_date_picker/date_picker_helper.js
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_on_change.jsx
  app/pb_kits/playbook/pb_date_picker/docs/_date_picker_on_change.md
  app/pb_kits/playbook/pb_date_picker/docs/example.yml
  app/pb_kits/playbook/pb_date_picker/docs/index.js
  app/pb_kits/playbook/pb_select/_select.scss
Labels: enhancement, ready

#1094 Fix for incorrect order of classNames fixes #1058
  app/pb_kits/playbook/pb_avatar/_avatar.jsx
  app/pb_kits/playbook/pb_badge/_badge.jsx
  app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  app/pb_kits/playbook/pb_button/_button.jsx
  app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.jsx
  app/pb_kits/playbook/pb_caption/_caption.jsx
  app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
  app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.jsx
  app/pb_kits/playbook/pb_contact/_contact.jsx
  app/pb_kits/playbook/pb_currency/_currency.jsx
  app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.jsx
  app/pb_kits/playbook/pb_date_picker/_date_picker.jsx
  app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.jsx
  app/pb_kits/playbook/pb_date_stacked/_date_stacked.jsx
  app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.jsx
  app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.jsx
  app/pb_kits/playbook/pb_flex/_flex.jsx
  app/pb_kits/playbook/pb_flex/_flex_item.jsx
  app/pb_kits/playbook/pb_form_pill/_form_pill.jsx
  app/pb_kits/playbook/pb_gauge/_gauge.jsx
  app/pb_kits/playbook/pb_highlight/_highlight.jsx
  app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx
  app/pb_kits/playbook/pb_icon/_icon.jsx
  app/pb_kits/playbook/pb_icon_value/_icon_value.jsx
  app/pb_kits/playbook/pb_image/_image.jsx
  app/pb_kits/playbook/pb_label_pill/_label_pill.jsx
  app/pb_kits/playbook/pb_layout/_layout.jsx
  app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  app/pb_kits/playbook/pb_list/_list.jsx
  app/pb_kits/playbook/pb_list/_list_item.jsx
  app/pb_kits/playbook/pb_logistic/_logistic.jsx
  app/pb_kits/playbook/pb_message/_message.jsx
  app/pb_kits/playbook/pb_multiple_users/_multiple_users.jsx
  app/pb_kits/playbook/pb_nav/_nav.jsx
  app/pb_kits/playbook/pb_person/_person.jsx
  app/pb_kits/playbook/pb_person_contact/_person_contact.jsx
  app/pb_kits/playbook/pb_popover/_popover.jsx
  app/pb_kits/playbook/pb_progress_simple/_progress_simple.jsx
  app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
  app/pb_kits/playbook/pb_section_separator/_section_separator.jsx
  app/pb_kits/playbook/pb_stat_change/_stat_change.jsx
  app/pb_kits/playbook/pb_stat_value/_stat_value.jsx
  app/pb_kits/playbook/pb_table/_table.jsx
  app/pb_kits/playbook/pb_text_input/_text_input.jsx
  app/pb_kits/playbook/pb_textarea/_textarea.jsx
  app/pb_kits/playbook/pb_time/_time.jsx
  app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.jsx
  app/pb_kits/playbook/pb_time_stacked/_time_stacked.jsx
  app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  app/pb_kits/playbook/pb_title/_title.jsx
  app/pb_kits/playbook/pb_title_count/_title_count.jsx
  app/pb_kits/playbook/pb_title_detail/_title_detail.jsx
  app/pb_kits/playbook/pb_toggle/_toggle.jsx
  app/pb_kits/playbook/pb_user_badge/_user_badge.jsx
  lib/generators/kit/templates/kit_jsx.erb.tt
Labels: bug, milano, ready

#1092 Display numeric zero in StatsValue Kit
  app/pb_kits/playbook/pb_stat_value/_stat_value.jsx
  app/pb_kits/playbook/pb_stat_value/docs/_stat_value_default.jsx
Labels: bug, ready

#1091 [NUX-639] - Add tests for deprecated sizes and time outputs
  app/pb_kits/playbook/pb_time/docs/_time_timezone.html.erb
  spec/pb_kits/playbook/kits/time_spec.rb
Labels: improvement, ready

#1087 [CMPN-16] Allow all HTML options on input in PbCheckbox Rails kit
  app/pb_kits/playbook/pb_checkbox/checkbox.rb
  app/pb_kits/playbook/pb_checkbox/docs/_checkbox_options.html.erb
  app/pb_kits/playbook/pb_checkbox/docs/example.yml
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  spec/pb_kits/playbook/kits/checkbox_spec.rb
Labels: enhancement, improvement, ready

#1064 Updated Styling for Toggle
  app/pb_kits/playbook/pb_toggle/_toggle.jsx
  app/pb_kits/playbook/pb_toggle/_toggle.scss
  app/pb_kits/playbook/pb_toggle/docs/_toggle_size.html.erb
  app/pb_kits/playbook/pb_toggle/docs/_toggle_size.jsx
  app/pb_kits/playbook/pb_toggle/docs/example.yml
  app/pb_kits/playbook/pb_toggle/docs/index.js
  app/pb_kits/playbook/pb_toggle/toggle.rb
  spec/pb_kits/playbook/kits/toggle_spec.rb
Labels: enhancement, milano, ready

#1107 [NUXE-144] - Added user value handling to checkbox form helper
  README.md
  app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  app/pb_kits/playbook/pb_form/form_builder/checkbox_field.rb
  app/pb_kits/playbook/pb_toggle/toggle.rb
Labels: enhancement, milano

#834 Playbook Distribution Release
  .eslintignore
  .gitignore
  .lintstagedrc
  CHANGELOG.md
  Gemfile.lock
  app/controllers/playbook/application_controller.rb
  app/pb_kits/playbook/_playbook.scss
  app/pb_kits/playbook/index.js
  app/pb_kits/playbook/packs/application.js
  app/pb_kits/playbook/packs/rails-examples.js
  app/pb_kits/playbook/packs/react-examples.js
  app/pb_kits/playbook/packs/site.js
  app/pb_kits/playbook/packs/site_styles/_scaffold.scss
  app/pb_kits/playbook/pb_bar_graph/_bar_graph.html.erb
  app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.html.erb
  app/pb_kits/playbook/pb_distribution_bar/distribution_bar.rb
  app/pb_kits/playbook/pb_line_graph/_line_graph.html.erb
  app/pb_kits/playbook/pb_line_graph/line_graph.rb
  app/pb_kits/playbook/pb_person_contact/_person_contact.jsx
  app/pb_kits/playbook/pb_person_contact/docs/_person_contact_with_wrong_numbers.jsx
  app/pb_kits/playbook/pb_title_detail/_title_detail.jsx
  app/pb_kits/playbook/react_rails_kits.js
  app/pb_kits/playbook/tokens/_colors.scss
  app/pb_kits/playbook/tokens/_typography.scss
  app/pb_kits/playbook/tokens/index.scss
  app/pb_kits/playbook/vendor.js
  app/views/layouts/playbook/application.html.erb
  app/views/layouts/playbook/fullscreen.html.slim
  app/views/layouts/playbook/grid.html.slim
  app/views/layouts/playbook/samples.html.erb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  lib/generators/kit/kit_generator.rb
  lib/playbook/engine.rb
  lib/playbook/version.rb
  lib/tasks/pb_release.rake
  package.json
  playbook_ui.gemspec
  spec/pb_kits/playbook/kits/bar_graph_spec.rb
  spec/pb_kits/playbook/kits/line_graph_spec.rb
  webpack.config.js
  yarn.lock
Labels: breaking
