Repository powerhome/playbook, pull requests merged in 2021-12, with the labels that each got.

#1678 added align self and display flex to flex item
  playbook/app/pb_kits/playbook/pb_flex/_flex.jsx
  playbook/app/pb_kits/playbook/pb_flex/_flex.scss
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.jsx
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.scss
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item.html.erb
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item_align_self.html.erb
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item_align_self.jsx
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item_align_self.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item_example.jsx
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_item_example.md
  playbook/app/pb_kits/playbook/pb_flex/docs/example.yml
  playbook/app/pb_kits/playbook/pb_flex/docs/index.js
  playbook/app/pb_kits/playbook/pb_flex/flex.rb
  playbook/app/pb_kits/playbook/pb_flex/flex_item.rb
Labels: enhancement, milano, Needs Review

#1681 Add tests to cover new colors for the background kit
  playbook/app/pb_kits/playbook/pb_background/background.test.js
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: ready, improvement

#1686 Add Global Shadow Props to ALL kits
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/pages/code_snippets/shadow_in_use_jsx.txt
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_shadow.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_shadow.html.erb
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_card/_card.jsx
  playbook/app/pb_kits/playbook/pb_card/_card.scss
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/utilities/_shadow.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.js
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/shadow.rb
  playbook/spec/pb_kits/playbook/kits/card_spec.rb
  playbook/spec/playbook/kit_base_spec.rb
Labels: enhancement, milano

#1693 Added Custom Color Options for Line Graph Kit
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_colors.html.erb
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_colors.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_colors.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_line_graph/docs/index.js
  playbook/app/pb_kits/playbook/pb_line_graph/line_graph.rb
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
  playbook/spec/pb_kits/playbook/kits/line_graph_spec.rb
Labels: enhancement, milano, Needs Review

#1694 Added Custom Color Options for Bar Graph Kit
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_colors.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_colors.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_colors.md
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/index.js
  playbook/spec/pb_kits/playbook/kits/bar_graph_spec.rb
Labels: enhancement, milano, Needs Review

#1692 [GOG-495] Initial portal config
  docs/CHANGELOG.md
  docs/README.md
  docs/upgrade-guide.md
  mkdocs.yml
  portal.yml
Labels: wip, milano, improvement
