Repository powerhome/playbook, pull requests merged in 2021-06, with the labels that each got.

#1510 [LGA-719] Fix invalid date in Date Time docs for Firefox
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx
Labels: bug, milano

#1506 [CHMN-101] Don't allow popover to open when clicking on eyeball in the passphrase kit
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
Labels: bug, milano

#1507 Add the value of a Dialog's portalClassName prop to the React Modal portal DIV class attribute
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default.jsx
Labels: enhancement

#1516 [BOP-979] Enhance message kit to accept timestamp object for hover
  playbook/app/pb_kits/playbook/pb_message/_message.jsx
  playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss
  playbook/app/pb_kits/playbook/pb_message/docs/_message_default.html.erb
  playbook/app/pb_kits/playbook/pb_message/docs/_message_default.jsx
  playbook/app/pb_kits/playbook/pb_message/docs/_message_timestamp.html.erb
  playbook/app/pb_kits/playbook/pb_message/docs/_message_timestamp.jsx
  playbook/app/pb_kits/playbook/pb_message/docs/example.yml
  playbook/app/pb_kits/playbook/pb_message/docs/index.js
  playbook/app/pb_kits/playbook/pb_message/message.html.erb
  playbook/app/pb_kits/playbook/pb_message/message.rb
Labels: enhancement, milano

#1523 Typeahead AsyncCreatable
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_async_createable.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js
Labels: bug

#1524 9.19.0
  playbook/CHANGELOG.md
  playbook/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_async_createable.jsx
  playbook/dist/playbook-doc.js
  playbook/dist/playbook-rails.js
  playbook/dist/playbook-react.js
  playbook/dist/playbook.css
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#1539 [NUX-2012] Move dist cleanup to webpack
  playbook/package.json
  playbook/private/tasks/pb_release.rake
  playbook/webpack.config.js
  yarn.lock
Labels: bug, enhancement

#1540 Change filemanager-webpack-plugin version to 4.0.0
  playbook/package.json
  yarn.lock
Labels: dependencies

#1536 [BOP-1014] Add children to message react kit
  playbook/app/pb_kits/playbook/pb_message/_message.jsx
  playbook/app/pb_kits/playbook/pb_message/docs/_message_default.html.erb
  playbook/app/pb_kits/playbook/pb_message/docs/_message_default.jsx
  playbook/app/pb_kits/playbook/pb_message/message.html.erb
Labels: enhancement, milano

#1521 [BOP-993] Update avatar kit/multi-user kit to support xxs size
  playbook-website/app/javascript/site_styles/docs/_all.scss
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_monogram.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_monogram.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_no_image.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_no_image.jsx
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.jsx
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_description.md
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_size.html.erb
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_size.jsx
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_size.md
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/example.yml
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/index.js
  playbook/app/pb_kits/playbook/pb_multiple_users/multiple_users.html.erb
  playbook/app/pb_kits/playbook/pb_multiple_users/multiple_users.rb
  playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
Labels: enhancement, milano
