Repository powerhome/playbook, pull requests merged in 2021-04, with the labels that each got.

#1405 Accessibility Improvements, Color Fixes, Menu Changes
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_preview.jsx
  playbook/app/pb_kits/playbook/pb_select/_select.scss
  playbook/app/pb_kits/playbook/pb_select/docs/_select_custom_select.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_input.jsx
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
  playbook/app/pb_kits/playbook/pb_textarea/_textarea_mixin.scss
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_character_counter.jsx
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_custom.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  playbook/dist/tokens/colors.scss
Labels: accessibility, improvement, in testing, milano

#1403 [Forms] Drop simple form support
  playbook/Gemfile
  playbook/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_form/docs/_description.md
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_simple_form_validate.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_simple_form_validate.md
  playbook/app/pb_kits/playbook/pb_form/docs/example.yml
  playbook/app/pb_kits/playbook/pb_form/form.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/checkbox_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/collection_select_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/date_picker_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/form_field_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/select_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/typeahead_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_with.rb
  playbook/app/pb_kits/playbook/pb_form/simple_form.html.erb
  playbook/app/pb_kits/playbook/pb_form/simple_form.rb
  playbook/lib/playbook/props/base.rb
  playbook/playbook_ui.gemspec
  playbook/spec/pb_kits/playbook/pb_form/form_spec.rb
Labels: breaking, deprecated, enhancement, in testing, milano

#1406 [NUXE-575] - Form helpers
  playbook/Gemfile.lock
  playbook/app/helpers/playbook/application_helper.rb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/checkbox_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/collection_select_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/date_picker_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/select_field.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/typeahead_field.rb
  playbook/lib/playbook.rb
  playbook/lib/playbook/forms.rb
  playbook/lib/playbook/forms/builder.rb
  playbook/lib/playbook/forms/builder/action_area.rb
  playbook/lib/playbook/forms/builder/checkbox_field.rb
  playbook/lib/playbook/forms/builder/collection_select_field.rb
  playbook/lib/playbook/forms/builder/date_picker_field.rb
  playbook/lib/playbook/forms/builder/form_field_builder.rb
  playbook/lib/playbook/forms/builder/select_field.rb
  playbook/lib/playbook/forms/builder/typeahead_field.rb
  playbook/lib/playbook/pb_forms_helper.rb
  playbook/lib/playbook/pb_kit_helper.rb
  playbook/playbook_ui.gemspec
  playbook/spec/pb_kits/playbook/pb_form/form_spec.rb
  playbook/spec/playbook/pb_forms_helper_spec.rb
  playbook/spec/rails_helper.rb
Labels: enhancement, in testing, milano

#1430 Correcting z-index bleed on avatar
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
Labels: bug, milano

#1433 Fix typahead height
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: bug, milano

#1411 More flexible dependency versions
  playbook/Gemfile.lock
  playbook/config/webpack/loaders/fast-sass-loader.js
  playbook/package.json
  playbook/playbook_ui.gemspec
  playbook/private/tasks/pb_release.rake
  playbook/webpack.config.js
  playbook/yarn.lock
Labels: improvement, in testing

#1423 OKRs
  playbook/app/pb_kits/playbook/pb_highlight/_highlight.jsx
  playbook/app/pb_kits/playbook/pb_highlight/highlight.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_description.md
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_status.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_status.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.rb
  playbook/app/pb_kits/playbook/pb_stat_value/_stat_value.jsx
  playbook/app/pb_kits/playbook/pb_stat_value/stat_value.html.erb
Labels: accessibility, enhancement, milano, needs alpha testing

#1408 [NUXE-560] - Indeterminate example, kit upgrade
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate.jsx
Labels: enhancement

#1387 Add aria-labels to Icon kit
  playbook/app/pb_kits/playbook/pb_icon/_icon.jsx
  playbook/app/pb_kits/playbook/pb_icon/icon.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.jsx
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.html.erb
  playbook/app/pb_kits/playbook/pb_nav/_item.jsx
  playbook/app/pb_kits/playbook/pb_nav/item.html.erb
Labels: accessibility, enhancement, in testing

#1349 [NUXE-372] Passphrase Kit
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.scss
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_common.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_default.html.erb
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_default.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_default.md
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_input_props.html.erb
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_input_props.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_input_props.md
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_meter_settings.html.erb
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_meter_settings.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_meter_settings.md
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_strength_change.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_strength_change.md
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_tips.html.erb
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_tips.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_tips.md
  playbook/app/pb_kits/playbook/pb_passphrase/docs/example.yml
  playbook/app/pb_kits/playbook/pb_passphrase/docs/index.js
  playbook/app/pb_kits/playbook/pb_passphrase/passphrase.html.erb
  playbook/app/pb_kits/playbook/pb_passphrase/passphrase.rb
  playbook/app/pb_kits/playbook/pb_passphrase/passphrase.test.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/passwordStrength.js
  playbook/app/pb_kits/playbook/react_rails_kits.js
  playbook/package.json
  playbook/spec/pb_kits/playbook/kits/passphrase_spec.rb
  playbook/yarn.lock
Labels: in testing, new kit

#1455 Pins react-select to 3.0.8
  playbook/package.json
  playbook/yarn.lock
Labels: bug

#1394 [NUXE-479] - Add margin overrides to select
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.rb
  playbook/app/pb_kits/playbook/pb_select/_select.jsx
  playbook/app/pb_kits/playbook/pb_select/_select.scss
  playbook/app/pb_kits/playbook/pb_select/select.rb
  playbook/spec/pb_kits/playbook/kits/select_spec.rb
Labels: enhancement

#1453 Set a default value for flex items
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.jsx
Labels: bug, ready

#1449 [CHPN-205] Add spec testing to typeahead, fix rubocop errors
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/spec/pb_kits/playbook/kits/typeahead_spec.rb
Labels: enhancement, milano, ready

#1443 Date variant small with icon
  playbook/app/pb_kits/playbook/pb_date/_date.jsx
  playbook/app/pb_kits/playbook/pb_date/date.html.erb
  playbook/app/pb_kits/playbook/pb_date/docs/_date_variants.html.erb
  playbook/app/pb_kits/playbook/pb_date/docs/_date_variants.jsx
Labels: enhancement, milano, ready

#1435 Updated user css file
  playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss
  playbook/app/pb_kits/playbook/pb_nav/docs/_block_nav.html.erb
  playbook/app/pb_kits/playbook/pb_nav/docs/_block_nav.jsx
Labels: enhancement, milano, ready

#1442 [CHMN-64] Playbook - Fixed Confirmation Toast Responsive
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.scss
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.html.erb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb
  playbook/spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
Labels: enhancement, milano, ready

#1386 [NUXE-454] Form Group Full Width Prop
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.jsx
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_full_width.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_full_width.jsx
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_full_width.md
  playbook/app/pb_kits/playbook/pb_form_group/docs/example.yml
  playbook/app/pb_kits/playbook/pb_form_group/docs/index.js
  playbook/app/pb_kits/playbook/pb_form_group/form_group.rb
  playbook/spec/pb_kits/playbook/kits/form_group_spec.rb
Labels: enhancement

#1462 [CHMN-60] HaveIBeenPwned passphrase
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_breached.html.erb
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_breached.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_breached.md
  playbook/app/pb_kits/playbook/pb_passphrase/docs/_passphrase_default.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/docs/example.yml
  playbook/app/pb_kits/playbook/pb_passphrase/docs/index.js
  playbook/app/pb_kits/playbook/pb_passphrase/passphrase.rb
  playbook/app/pb_kits/playbook/pb_passphrase/passphrase.test.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/useHaveIBeenPwned.js
  playbook/app/pb_kits/playbook/pb_passphrase/useZxcvbn.js
Labels: enhancement, ready

#1468 [CHMN-78] Hotfix passphrase strength bar display
  playbook/app/pb_kits/playbook/pb_passphrase/useZxcvbn.js
Labels: bug, milano

#1429 [NUXE-490] - Update Button for A11y (OKR)
  playbook/app/pb_kits/playbook/pb_button/_button.jsx
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_accessibility.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_accessibility.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_link.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_link.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_loading.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_loading.jsx
Labels: enhancement
