Repository powerhome/playbook, pull requests merged in 2021-01, with the labels that each got.

#1297 [NUXE-367] Fix typeahead cursor position (REACT)
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: improvement, ready

#1296 Dashboard cards
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/pb_kits/playbook/packs/samples/card_dashboard/styles.scss
  playbook/app/views/playbook/samples/card_dashboard/index.html.erb
  playbook/app/views/playbook/samples/card_dashboard/index.jsx
Labels: improvement, ready

#1291 [NUXE-315] UX - KIT DEV - Remove extra Margin from selectable cards
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
Labels: bug, ready

#1289 Add mobile search
  playbook/app/pb_kits/playbook/docs_components/KitSearch.jsx
  playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss
  playbook/app/views/layouts/playbook/_nav.html.erb
  playbook/app/views/layouts/playbook/_sidebar.html.erb
  playbook/app/views/layouts/playbook/kits.html.erb
  playbook/app/views/playbook/pages/visual_guidelines.html.erb
Labels: improvement, ready

#1286 Fixes genrator error
  playbook/lib/playbook/engine.rb
Labels: bug, ready

#1277 [NUXE-363] UX - KIT DEV - Add character counter prop to Textarea Kit
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.html.erb
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.jsx
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_character_counter.html.erb
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_character_counter.jsx
  playbook/app/pb_kits/playbook/pb_textarea/docs/example.yml
  playbook/app/pb_kits/playbook/pb_textarea/docs/index.js
  playbook/app/pb_kits/playbook/pb_textarea/textarea.rb
Labels: enhancement, ready

#1276 Jest Code Coverage Action
  .github/actions/badge/action.yml
  .github/actions/badge/coverage-badge.js
  .github/actions/badge/package.json
  .github/actions/badge/yarn.lock
  .github/workflows/coverage.yml
  playbook/jest.config.js
  playbook/package.json
  playbook/yarn.lock
Labels: enhancement, ready

#1304 Table prop passing hotfix
  playbook/app/pb_kits/playbook/pb_table/docs/_table_lg.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_multiline.jsx
Labels: bug

#1239 Remove custom webpacker instance
  playbook/Makefile
  playbook/app/helpers/playbook/application_helper.rb
  playbook/config/webpacker.yml
  playbook/lib/playbook.rb
  playbook/lib/playbook/engine.rb
  playbook/lib/tasks/playbook_tasks.rake
  playbook/spec/dummy/config/webpack
  playbook/spec/dummy/config/webpack/development.js
  playbook/spec/dummy/config/webpack/environment.js
  playbook/spec/dummy/config/webpack/loaders/erb.js
  playbook/spec/dummy/config/webpack/loaders/fast-sass-loader.js
  playbook/spec/dummy/config/webpack/loaders/svg.js
  playbook/spec/dummy/config/webpack/production.js
  playbook/webpack.config.js
Labels: enhancement, milano

#1243 Cleanup playbook configs
  playbook/config.ru
  playbook/config/application.rb
  playbook/config/boot.rb
  playbook/config/cable.yml
  playbook/config/environment.rb
  playbook/config/environments/development.rb
  playbook/config/environments/production.rb
  playbook/config/environments/test.rb
  playbook/config/initializers/assets.rb
  playbook/config/initializers/content_security_policy.rb
  playbook/config/initializers/cookies_serializer.rb
  playbook/config/initializers/filter_parameter_logging.rb
  playbook/config/initializers/wrap_parameters.rb
  playbook/config/locales/en.yml
  playbook/config/spring.rb
  playbook/lib/playbook.rb
  playbook/lib/playbook/markdown/template_handler.rb
  playbook/spec/dummy/config/environments/development.rb
  playbook/spec/dummy/config/environments/production.rb
  playbook/spec/dummy/config/environments/test.rb
  playbook/spec/dummy/config/initializers/content_security_policy.rb
  playbook/spec/dummy/config/initializers/global_variables.rb
  playbook/spec/dummy/config/initializers/markdown_template.rb
Labels: enhancement, milano

#1303 Allow React Filter kit popover to be closed
  playbook/app/pb_kits/playbook/pb_filter/Filter/FiltersPopover.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_close_popover.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/example.yml
  playbook/app/pb_kits/playbook/pb_filter/docs/index.js
Labels: enhancement

#1309 Add Object-fit: cover to Image Kit
  playbook/app/pb_kits/playbook/pb_image/_image.scss
Labels: improvement, milano

#1306 Create a prop that allows the card kit to use border radius variables
  playbook/app/pb_kits/playbook/pb_card/_card.jsx
  playbook/app/pb_kits/playbook/pb_card/_card.scss
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_border_radius.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_border_radius.jsx
  playbook/app/pb_kits/playbook/pb_card/docs/_card_border_radius.md
  playbook/app/pb_kits/playbook/pb_card/docs/example.yml
  playbook/app/pb_kits/playbook/pb_card/docs/index.js
  playbook/app/pb_kits/playbook/tokens/_border_radius.scss
Labels: enhancement, milano

#1302 [NUXE-376] Add padding to Typeahead Kit when it expands to two lines
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: bug, milano

#1300 [NUXE-308] Set Overflow to be Auto on the Card Kit
  playbook/app/pb_kits/playbook/pb_card/_card.scss
Labels: bug, milano

#1292 [CMPN-351] Checkbox-on-selectable-card
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_input.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_input.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_input.md
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_single_select.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/example.yml
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/index.js
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
  playbook/spec/pb_kits/playbook/kits/selectable_card_spec.rb
Labels: enhancement, milano

#1308 [NUXE-98] Selectable card border bug (using border)
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_block.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_default.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_image.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_single_select.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.scss
Labels: bug, milano

#1298 [NUXE-74] Global Container width utilities
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_card/docs/_card_light.md
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.md
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_collection.html.erb
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_collection.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sm.md
  playbook/app/pb_kits/playbook/utilities/_max_width.scss
  playbook/app/pb_kits/playbook/utilities/_spacing.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.js
  playbook/app/views/playbook/pages/visual_guidelines.html.erb
  playbook/app/views/playbook/pages/visual_guidelines_partials/_max_width.html.slim
  playbook/app/views/playbook/pages/visual_guidelines_partials/_pb_doc_max_width.html.slim
  playbook/lib/playbook/props.rb
Labels: enhancement, milano

#1320 [NUXE-427] Fix select card form group
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_default.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.scss
Labels: bug, milano

#1318 [NUXE-298] Darkmode Typeahead
  playbook/app/pb_kits/playbook/docs_components/KitSearch.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  playbook/app/pb_kits/playbook/pb_typeahead/components/Control.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Option.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_context.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_custom_options.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async_users.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Labels: enhancement, milano

#1325 Fixing some styles for dark mode
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: enhancement, milano

#1326 Revert "Remove custom webpacker instance"
  playbook/Makefile
  playbook/app/helpers/playbook/application_helper.rb
  playbook/config/webpack/development.js
  playbook/config/webpack/environment.js
  playbook/config/webpack/loaders/erb.js
  playbook/config/webpack/loaders/fast-sass-loader.js
  playbook/config/webpack/loaders/svg.js
  playbook/config/webpack/production.js
  playbook/config/webpacker.yml
  playbook/lib/playbook.rb
  playbook/lib/playbook/engine.rb
  playbook/lib/tasks/playbook_tasks.rake
  playbook/spec/dummy/config/webpack
  playbook/webpack.config.js
Labels: bug

#1324 Adds truncation for select kit
  playbook/app/pb_kits/playbook/pb_select/_select.scss
Labels: enhancement, ready

#1317 Music Player sample page
  playbook/app/pb_kits/playbook/data/samples.yml
  playbook/app/pb_kits/playbook/packs/samples.js
  playbook/app/pb_kits/playbook/pb_layout/_layout.scss
  playbook/app/views/playbook/samples/music_app/index.html.erb
  playbook/app/views/playbook/samples/music_app/index.jsx
  playbook/lib/generators/sample/sample_generator.rb
Labels: enhancement, ready

#1271 Add Empty Filter Message to Filter Kit
  playbook/app/pb_kits/playbook/pb_filter/Filter/CurrentFilters.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.jsx
  playbook/app/pb_kits/playbook/pb_filter/templates/_core.html.erb
Labels: enhancement, ready

#1329 Add Table Collapse prop for specific breakpoints
  playbook/app/pb_kits/playbook/pb_table/_table.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_responsive_table.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_responsive_table.jsx
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_desktop_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_tablet_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/table.rb
  playbook/spec/pb_kits/playbook/kits/table_spec.rb
Labels: enhancement, ready

#1330 Prevent Typeahead menu opening on FormPill removal
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MultiValue.jsx
Labels: bug, milano, ready

#1234 Timestamp kit backward compatibility update
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.scss
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_description.md
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_align.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_align.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_align.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/example.yml
  playbook/app/pb_kits/playbook/pb_timestamp/docs/index.js
  playbook/app/pb_kits/playbook/pb_timestamp/timestamp.rb
  playbook/spec/pb_kits/playbook/kits/timestamp_spec.rb
Labels: enhancement, milano, ready

#1322 Add Auto Resizing to Textarea
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.jsx
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_resize.html.erb
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_resize.jsx
  playbook/app/pb_kits/playbook/pb_textarea/index.js
  playbook/app/pb_kits/playbook/pb_textarea/textarea.rb
  playbook/app/pb_kits/playbook/vendor.js
Labels: enhancement, milano, ready
