Repository powerhome/playbook, pull requests merged in 2021-08, with the labels that each got.

#1574 [LGA-824] Fix documentation for getting started with PB
  README.md
Labels: bug, milano

#1571 [BOP-1023] Add inline and inline compact options to the select kit for inline usage
  playbook/app/pb_kits/playbook/pb_select/_select.jsx
  playbook/app/pb_kits/playbook/pb_select/_select.scss
  playbook/app/pb_kits/playbook/pb_select/docs/_select_inline.html.erb
  playbook/app/pb_kits/playbook/pb_select/docs/_select_inline.jsx
  playbook/app/pb_kits/playbook/pb_select/docs/_select_inline_compact.html.erb
  playbook/app/pb_kits/playbook/pb_select/docs/_select_inline_compact.jsx
  playbook/app/pb_kits/playbook/pb_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_select/docs/index.js
  playbook/app/pb_kits/playbook/pb_select/select.html.erb
  playbook/app/pb_kits/playbook/pb_select/select.rb
  playbook/dist/playbook-doc.js
  playbook/dist/playbook.css
  playbook/dist/playbook.js
Labels: enhancement, milano

#1581 Allow to specify verbiage for selected file types
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.jsx
Labels: enhancement
