Repository powerhome/playbook, pull requests merged in 2021-07, with the labels that each got.

#1541 [NUXE-649] - Remove Base64 Fonts
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Black.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-BlackIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Bold.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-BoldIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Extrabld.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-ExtrabldIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Light.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-LightIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Regular.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-RegularIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Semibold.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-SemiboldIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Thin.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-ThinIt.woff2
  playbook-website/app/javascript/site_styles/main.scss
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/tokens/_fonts.scss
  playbook/dist/playbook-doc.js
  playbook/dist/playbook-rails.js
  playbook/dist/playbook-react.js
  playbook/dist/playbook.css
  playbook/dist/tokens/fonts.scss
Labels: Needs Runway, improvement, milano

#1542 [NUXE-640] Restructure Button kit stylings
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/dist/playbook.css
Labels: bug, milano

#1550 Fix getting started page
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/pages/getting_started.html.erb
  playbook-website/app/views/pages/getting_started.html.slim
Labels: bug, milano

#1549 [NUXE-589] Fix Rich Text Editor flex container bug
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
  playbook/dist/playbook.css
Labels: bug, milano

#1554 Fixes the dev-start from Crashing
  playbook/webpack.config.js
Labels: milano

#1553 Fix custom icon [NUXE-837]
  playbook/app/pb_kits/playbook/pb_icon/_icon.jsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.jsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.md
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.jsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.jsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.scss
  playbook/dist/playbook.css
Labels: bug

#1561 Fix popover copypasta
  playbook/app/pb_kits/playbook/pb_popover/_popover.scss
  playbook/dist/playbook.css
Labels: bug, milano
