Repository powerhome/playbook, pull requests merged in 2021-11, with the labels that each got.

#1638 [NUXE-995] Removed Node version pinning
  playbook/package.json
Labels: dependencies, milano

#1639 Add & operator to guard against nil
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Labels: bug, milano

#1650 [PLAY-35] Add Spline example to Bar Graph docs
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_spline.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_spline.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_spline.md
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/index.js
Labels: milano, ready, improvement

#1644 Update Rubocop Dependencies
  .rubocop.yml
  Dockerfile
  playbook-website/.rubocop.yml
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: milano, Needs Review

#1659 [PLAY-1] Screen size docs -Update Slim files to ERB
  playbook-website/app/views/pages/visual_guidelines.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_screen_sizing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_screen_sizing.html.erb
Labels: milano, improvement, Needs Review

#1660 Add Background Colors to the Card Kit
  playbook/app/pb_kits/playbook/pb_card/_card.jsx
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background.jsx
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background.md
  playbook/app/pb_kits/playbook/pb_card/docs/example.yml
  playbook/app/pb_kits/playbook/pb_card/docs/index.js
  playbook/spec/pb_kits/playbook/kits/card_spec.rb
Labels: enhancement, milano, ready

#1653 [PLAY-24] Improve max width global props docs/visual-guidelines
  playbook-website/app/javascript/site_styles/_visual_guidelines.scss
  playbook-website/app/views/pages/code_snippets/width_jsx.txt
  playbook-website/app/views/pages/visual_guidelines.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_max_width.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_max_width.html.slim
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_max_width.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_max_width.html.slim
Labels: milano, improvement, Needs Review

#1645 Remove deprecated props
  playbook/app/pb_kits/playbook/pb_flex/_flex.jsx
  playbook/app/pb_kits/playbook/pb_flex/docs/_description.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_align.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_justify.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_spacing.md
Labels: milano, improvement, Needs Review

#1661 [PLAY-14] Add more colors to the background kit
  playbook/app/pb_kits/playbook/pb_background/_background.jsx
  playbook/app/pb_kits/playbook/pb_background/_background.scss
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_category.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_category.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_category.md
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.md
  playbook/app/pb_kits/playbook/pb_background/docs/_description.md
  playbook/app/pb_kits/playbook/pb_background/docs/example.yml
  playbook/app/pb_kits/playbook/pb_background/docs/index.js
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: enhancement, milano

#1652 [PLAY-25] Improve number spacing global props docs
  playbook-website/app/views/pages/code_snippets/number_spacing_jsx.txt
  playbook-website/app/views/pages/visual_guidelines_partials/_number_spacing.html.slim
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_number_spacing.html.slim
Labels: milano, improvement, Needs Review

#1663 Line height tokens
  playbook-website/app/javascript/site_styles/_visual_guidelines.scss
  playbook-website/app/views/pages/code_snippets/line_height_jxs.txt
  playbook-website/app/views/pages/visual_guidelines.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_line_height.html.erb
Labels: improvement, Needs Review

#1670 Improve number spacing
  playbook-website/app/views/pages/code_snippets/number_spacing_jsx.txt
  playbook-website/app/views/pages/visual_guidelines_partials/_number_spacing.html.slim
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_number_spacing.html.slim
Labels: milano, Needs Review

#1669 remove deprecated props
  playbook/app/pb_kits/playbook/pb_flex/docs/_description.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_align.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_justify.md
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_spacing.md
Labels: milano, Needs Review

#1668 Background kit colors
  playbook/app/pb_kits/playbook/pb_background/_background.jsx
  playbook/app/pb_kits/playbook/pb_background/_background.scss
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_category.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_category.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_category.md
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.md
  playbook/app/pb_kits/playbook/pb_background/docs/_description.md
  playbook/app/pb_kits/playbook/pb_background/docs/example.yml
  playbook/app/pb_kits/playbook/pb_background/docs/index.js
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: milano, Needs Review

#1673 Expand max width props global
  playbook-website/app/views/pages/visual_guidelines_partials/_max_width.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_max_width.html.erb
  playbook/app/pb_kits/playbook/utilities/_max_width.scss
  playbook/lib/playbook/spacing.rb
Labels: milano, improvement, Needs Review
