Repository powerhome/playbook, pull requests merged in 2021-02, with the labels that each got.

#1341 Fix Image kit rounded prop warning
  playbook/app/pb_kits/playbook/pb_image/_image.jsx
Labels: bug

#1331 Create a Masonry Variant for the Layout Kit
  playbook/app/pb_kits/playbook/pb_layout/_item.html.erb
  playbook/app/pb_kits/playbook/pb_layout/_layout.jsx
  playbook/app/pb_kits/playbook/pb_layout/_layout.scss
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_masonry.html.erb
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_masonry.jsx
  playbook/app/pb_kits/playbook/pb_layout/docs/example.yml
  playbook/app/pb_kits/playbook/pb_layout/docs/index.js
  playbook/app/pb_kits/playbook/pb_layout/item.rb
  playbook/app/pb_kits/playbook/pb_layout/layout.rb
  playbook/spec/pb_kits/playbook/kits/layout_spec.rb
Labels: enhancement, milano

#1332 Fix DateTime kit bug, add more examples
  playbook/app/pb_kits/playbook/pb_date_time/_date_time.jsx
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx
Labels: bug, milano

#1342 [CMPN-379] Add Error State to Selectable Card
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_error.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_error.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/example.yml
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/index.js
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
Labels: enhancement, milano

#1343 [NUXE-349] Update gauge examples using overflow in flex item
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.jsx
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.scss
  playbook/app/pb_kits/playbook/pb_flex/flex_item.rb
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.html.erb
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.jsx
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.md
  playbook/app/pb_kits/playbook/pb_gauge/docs/example.yml
  playbook/spec/pb_kits/playbook/kits/flex_item_spec.rb
Labels: enhancement, milano

#1334 Avatar - hide broken image and alt text on failure to load [NUXE-381]
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_no_image.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_no_image.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_no_image.md
  playbook/app/pb_kits/playbook/pb_avatar/docs/example.yml
  playbook/app/pb_kits/playbook/pb_avatar/docs/index.js
  playbook/app/pb_kits/playbook/pb_image/_image.html.erb
  playbook/app/pb_kits/playbook/pb_image/_image.jsx
  playbook/app/pb_kits/playbook/pb_image/docs/_custom_error_image.html.erb
  playbook/app/pb_kits/playbook/pb_image/docs/_custom_error_image.jsx
  playbook/app/pb_kits/playbook/pb_image/docs/example.yml
  playbook/app/pb_kits/playbook/pb_image/docs/index.js
  playbook/app/pb_kits/playbook/pb_image/image.rb
  playbook/spec/pb_kits/playbook/kits/image_spec.rb
Labels: improvement, milano

#1348 Several fixes for kit warnings found on the "all kits" react page.
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.jsx
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_collection_detail.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx
Labels: bug, react

#1353 Unify Star Rating kit spacing
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.html.erb
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.jsx
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.scss
Labels: improvement, milano

#1345 Add `zIndex` as a global prop
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/utilities/_positioning.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.js
  playbook/app/views/playbook/pages/visual_guidelines.html.erb
  playbook/app/views/playbook/pages/visual_guidelines_partials/_pb_doc_positioning.html.slim
  playbook/app/views/playbook/pages/visual_guidelines_partials/_positioning.html.slim
  playbook/lib/playbook/props.rb
Labels: enhancement, milano

#1354 Improved Accessibility by adding focus to Checkbox & Radio Kits
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.jsx
  playbook/app/pb_kits/playbook/pb_radio/_radio.scss
  playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default.html.erb
  playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default.jsx
  playbook/app/pb_kits/playbook/pb_table/styles/_desktop_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_tablet_collapse.scss
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
  playbook/app/pb_kits/playbook/tokens/_positioning.scss
Labels: accessibility, enhancement, milano

#1346 Accessibility Spike
  package.json
  playbook/app/pb_kits/playbook/packs/site.js
  playbook/app/pb_kits/playbook/pb_image/_image.jsx
  playbook/app/pb_kits/playbook/pb_image/docs/_default_image.html.erb
  playbook/app/pb_kits/playbook/pb_image/docs/_default_image.jsx
  playbook/app/pb_kits/playbook/pb_image/docs/_rounded_image.html.erb
  playbook/app/pb_kits/playbook/pb_image/docs/_rounded_image.jsx
  playbook/app/pb_kits/playbook/pb_image/image.rb
  playbook/app/pb_kits/playbook/pb_image/image.test.js
  playbook/app/pb_kits/playbook/utilities/accessibility.js
  playbook/app/pb_kits/playbook/utilities/test-utils.js
  playbook/lib/generators/kit/templates/kit_jsx_test.erb.tt
  playbook/package.json
  playbook/spec/pb_kits/playbook/kits/image_spec.rb
  playbook/yarn.lock
  yarn.lock
Labels: accessibility, enhancement, milano

#1356 fixup dark mode select truncation
  playbook/app/pb_kits/playbook/pb_select/_select.scss
Labels: enhancement, milano

#1357 Added status colors to the distribution bar
  playbook/app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.scss
  playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.html.erb
  playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.jsx
  playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.md
Labels: enhancement

#1337 Remove jQuery from docs site
  playbook/app/pb_kits/playbook/config/_kit_ui.html.erb
  playbook/app/pb_kits/playbook/docs_components/DarkModeToggle.jsx
  playbook/app/pb_kits/playbook/packs/site.js
  playbook/app/views/layouts/playbook/kits.html.erb
  playbook/app/views/layouts/playbook/samples.html.erb
Labels: improvement, milano

#1352 Add data, aria, & name props to RichTextEditor
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_attributes.html.erb
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_attributes.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
  playbook/app/pb_kits/playbook/pb_rich_text_editor/rich_text_editor.html.erb
  playbook/app/pb_kits/playbook/pb_rich_text_editor/rich_text_editor.test.js
Labels: enhancement, milano, not ready

#1351 Update webpack dev server
  playbook/package.json
  playbook/yarn.lock
Labels: enhancement, milano

#1312 Introduce filter view component
  playbook/app/pb_kits/playbook/pb_filter/_filter.html.erb
  playbook/app/pb_kits/playbook/pb_filter/filter.html.erb
  playbook/app/pb_kits/playbook/pb_filter/filter.rb
  playbook/app/pb_kits/playbook/pb_filter/templates/_core.html.erb
  playbook/app/pb_kits/playbook/pb_filter/templates/_default.html.erb
  playbook/spec/pb_kits/playbook/kits/filter_spec.rb
Labels: milano

#1313 Introduce form view component
  playbook/app/pb_kits/playbook/pb_form/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.rb
  playbook/app/pb_kits/playbook/pb_form/form/form_with_form.rb
  playbook/app/pb_kits/playbook/pb_form/form/simple_form_form.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.html.erb
  playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/form_with_form_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/simple_form_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/form_with.rb
  playbook/app/pb_kits/playbook/pb_form/simple_form.html.erb
  playbook/app/pb_kits/playbook/pb_form/simple_form.rb
  playbook/spec/pb_kits/playbook/kits/form_spec.rb
  playbook/spec/pb_kits/playbook/pb_form/form_spec.rb
Labels: milano, not ready

#1359 Date Picker Safari fixes
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_flatpickr_styles.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_header_styles.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss
Labels: improvement, milano

#1358 Add name prop to typeahead with pills options
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Labels: bug, milano

#1314 Clear partials use in kits
  playbook/app/controllers/playbook/application_controller.rb
  playbook/app/helpers/playbook/pb_doc_helper.rb
  playbook/app/pb_kits/playbook/config/_pb_kit_api.html.erb
  playbook/app/pb_kits/playbook/pb_kit/base.rb
  playbook/app/pb_kits/playbook/pb_layout/item.html.erb
  playbook/app/pb_kits/playbook/pb_layout/item.rb
  playbook/app/views/playbook/config/_kit_example.html.erb
  playbook/app/views/playbook/config/_kit_samples_list.html.erb
  playbook/app/views/playbook/config/_kit_ui.html.erb
  playbook/app/views/playbook/config/_pb_kit_api.html.erb
  playbook/app/views/playbook/pages/kit_show.html.erb
  playbook/lib/playbook.rb
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/engine.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/kit_resolver.rb
  playbook/lib/playbook/pb_kit_helper.rb
  playbook/lib/playbook/props.rb
  playbook/lib/playbook/spacing.rb
  playbook/lib/playbook/z_index.rb
  playbook/spec/playbook/kit_base_spec.rb
  playbook/spec/playbook/kit_resolver_spec.rb
  playbook/spec/playbook/props_spec.rb
Labels: improvement, milano

#1362 Decouple docs helpers
  playbook/Gemfile.lock
  playbook/app/controllers/playbook/application_controller.rb
  playbook/app/helpers/playbook/application_helper.rb
  playbook/app/helpers/playbook/pb_doc_helper.rb
  playbook/app/helpers/playbook/pb_sample_helper.rb
  playbook/app/helpers/playbook/redcarpet_helper.rb
  playbook/app/pb_kits/playbook/pb_docs/kit_api.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_api.rb
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
  playbook/app/views/playbook/config/_kit_example.html.erb
  playbook/app/views/playbook/config/_kit_samples_list.html.erb
  playbook/app/views/playbook/config/_kit_ui.html.erb
  playbook/app/views/playbook/pages/all_kit_examples.html.erb
  playbook/app/views/playbook/pages/kit_show.html.erb
  playbook/app/views/playbook/pages/kits.html.erb
  playbook/lib/playbook.rb
  playbook/lib/playbook/markdown.rb
  playbook/lib/playbook/markdown/helper.rb
  playbook/lib/playbook/pb_doc_helper.rb
  playbook/playbook_ui.gemspec
Labels: milano

#1364 Fix tooltip - Center Arrows
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
Labels: bug

#1310 Create Collapse Kit - Refresh
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.scss
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleContent.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/_collapsible_content.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/_collapsible_main.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.rb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.test.js
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_content.rb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.rb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_default.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_default.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/example.yml
  playbook/app/pb_kits/playbook/pb_collapsible/docs/index.js
  playbook/app/pb_kits/playbook/pb_collapsible/index.js
  playbook/app/pb_kits/playbook/vendor.js
  playbook/package.json
  playbook/spec/pb_kits/playbook/kits/collapsible_content_spec.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_main_spec.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_spec.rb
  playbook/yarn.lock
Labels: milano, new kit

#1366 Reintroduce missing kit description markdown
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
Labels: bug

#1365 [CHMN-35] Add yellow as option to progress simple kit
  playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.jsx
  playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_variants.html.erb
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_variants.jsx
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_variants.md
  playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.rb
  playbook/spec/pb_kits/playbook/kits/progress_simple_spec.rb
Labels: enhancement, milano

#1361 Nav Kit - Accessibility Improvements (#1361)
  playbook/app/pb_kits/playbook/pb_nav/_item.jsx
  playbook/app/pb_kits/playbook/pb_nav/_nav.jsx
  playbook/app/pb_kits/playbook/pb_nav/item.html.erb
  playbook/app/pb_kits/playbook/pb_nav/nav.html.erb
Labels: improvement

#1290 Update to Time Stacked to use Time instead of Date
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.jsx
  playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.scss
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_default.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_default.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/time_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/time_stacked.rb
  playbook/app/pb_kits/playbook/pb_time_stacked/time_stacked.test.js
  playbook/spec/pb_kits/playbook/kits/time_stacked_spec.rb
Labels: enhancement

#1367 Update render of Collapsible to view component
  playbook/app/pb_kits/playbook/pb_card/card_header.rb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.rb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_content.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_content.rb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.rb
  playbook/lib/playbook/props/base.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_content_spec.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_main_spec.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_spec.rb
Labels: bug, milano

#1368 Fix form kit view context
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.html.erb
  playbook/app/pb_kits/playbook/pb_form/form.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.html.erb
  playbook/app/pb_kits/playbook/pb_form/form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/form_with.rb
Labels: milano

#1369 Update generators to view component
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.rb
  playbook/lib/generators/kit/kit_generator.rb
  playbook/lib/generators/kit/templates/kit_ruby.erb.tt
  playbook/spec/pb_kits/playbook/kits/collapsible_content_spec.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_main_spec.rb
  playbook/spec/pb_kits/playbook/kits/collapsible_spec.rb
Labels: milano
