Repository powerhome/playbook, pull requests merged in 2021-03, with the labels that each got.

#1371 Add React tests for Button, Button Toolbar, Circle Icon Button
  playbook/app/pb_kits/playbook/pb_button/_button.jsx
  playbook/app/pb_kits/playbook/pb_button/button.test.js
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.jsx
  playbook/app/pb_kits/playbook/pb_button_toolbar/button_toolbar.test.js
  playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.test.js
  playbook/app/pb_kits/playbook/utilities/test-utils.js
Labels: enhancement, milano

#1373 Update renovate config
  playbook/renovate.json
Labels: improvement

#1370 [NUXE-220] Add reset to dist
  playbook/README.md
  playbook/app/pb_kits/playbook/packs/site_styles/_scaffold.scss
  playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss
  playbook/app/pb_kits/playbook/pb_dashboard/commonSettings.js
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.js
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
  playbook/app/pb_kits/playbook/tokens/_border_radius.scss
  playbook/app/pb_kits/playbook/tokens/_colors.scss
  playbook/app/pb_kits/playbook/tokens/_line_height.scss
  playbook/app/pb_kits/playbook/tokens/_opacity.scss
  playbook/app/pb_kits/playbook/tokens/_positioning.scss
  playbook/app/pb_kits/playbook/tokens/_screen_sizes.scss
  playbook/app/pb_kits/playbook/tokens/_shadows.scss
  playbook/app/pb_kits/playbook/tokens/_spacing.scss
  playbook/app/pb_kits/playbook/tokens/_typography.scss
  playbook/app/pb_kits/playbook/tokens/exports/_border_radius.scss
  playbook/app/pb_kits/playbook/tokens/exports/_colors.scss
  playbook/app/pb_kits/playbook/tokens/exports/_line_height.scss
  playbook/app/pb_kits/playbook/tokens/exports/_opacity.scss
  playbook/app/pb_kits/playbook/tokens/exports/_positioning.scss
  playbook/app/pb_kits/playbook/tokens/exports/_screen_sizes.scss
  playbook/app/pb_kits/playbook/tokens/exports/_shadows.scss
  playbook/app/pb_kits/playbook/tokens/exports/_spacing.scss
  playbook/app/pb_kits/playbook/tokens/exports/_typography.scss
  playbook/dist/reset.css
  playbook/lib/tasks/new_release.rake
  playbook/lib/tasks/pb_release.rake
  playbook/package.json
  playbook/playbook_ui.gemspec
  playbook/webpack.config.js
Labels: enhancement, milano

#1380 Fix forms and action area rendering context
  playbook/app/pb_kits/playbook/pb_form/form_builder.rb
  playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.html.erb
  playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.rb
  playbook/app/pb_kits/playbook/pb_form/simple_form.html.erb
  playbook/app/pb_kits/playbook/pb_form/simple_form.rb
Labels: milano

#1382 Security udpate for actionpack, actionview and activesupport
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: security

#1381 Add caption html tag to Caption kit
  playbook/app/pb_kits/playbook/pb_caption/_caption.jsx
  playbook/app/pb_kits/playbook/pb_caption/caption.rb
  playbook/spec/pb_kits/playbook/kits/caption_spec.rb
Labels: accessibility, improvement, milano

#1376 Add tags and aria + data props to Card kit
  playbook/app/pb_kits/playbook/pb_card/_card.jsx
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_tag.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_tag.jsx
  playbook/app/pb_kits/playbook/pb_card/docs/example.yml
  playbook/app/pb_kits/playbook/pb_card/docs/index.js
Labels: accessibility, improvement, milano

#1375 Online Status Accessibility Improvements
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/pb_online_status/_online_status.jsx
  playbook/app/pb_kits/playbook/pb_online_status/online_status.html.erb
Labels: accessibility, improvement, milano

#1254 Dialog Kit React
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_dialog/_close_icon.jsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/_dialog_context.jsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_body.jsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_footer.jsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_header.jsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog.rb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.test.jsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.rb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_compound_components.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_compound_components.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_scrollable.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_scrollable.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_separators.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_separators.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_should_close_on_overlay.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_should_close_on_overlay.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dialog/docs/index.js
  playbook/app/pb_kits/playbook/react_rails_kits.js
  playbook/dist/playbook-rails.css
  playbook/dist/playbook-react.css
  playbook/package.json
  playbook/spec/pb_kits/playbook/kits/dialog_spec.rb
  playbook/yarn.lock
Labels: milano, new kit

#1385 React User Badge bug hotfix
  playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.jsx
Labels: bug, milano

#1372 Add indeterminate checkbox option to kits
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.rb
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.test.js
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_custom.jsx
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate.jsx
  playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml
  playbook/app/pb_kits/playbook/pb_checkbox/docs/index.js
  playbook/spec/pb_kits/playbook/kits/checkbox_spec.rb
Labels: enhancement, milano

#1388 Allow url to be empty so form_with can generate a url based on the model
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_form/form_with.rb
  playbook/spec/pb_kits/playbook/pb_form/form_with_spec.rb
Labels: improvement, milano

#1398 [NUXE-561] - Upgrade max of action pack gem
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: improvement, milano

#1399 github_changelog_generator is a dev dependency
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: dependencies

#1410 Do not build everything on every start up
  playbook/Makefile
Labels: improvement

#1412 Update body light & lighter to a more accessible color
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: accessibility, docs, enhancement, milano
