Repository powerhome/playbook, pull requests merged in 2021-05, with the labels that each got.

#1470 Rails 5.2.4.5
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: milano

#1379 Breadcrumb kit
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/packs/react-examples.js
  playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumb_item.jsx
  playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.jsx
  playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.rb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.rb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.test.js
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_bread_crumbs_default.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_bread_crumbs_default.jsx
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_description.md
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/example.yml
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/index.js
  playbook/dist/reset.css
Labels: new kit

#1479 [CHMN-77] Add close on click "outside" prop to passphrase popover
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.scss
Labels: enhancement

#1378 Update Design for Date Time Stacked
  playbook/app/pb_kits/playbook/pb_date_stacked/_date_stacked.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/date_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_date_stacked/date_stacked.rb
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_bold.html.erb
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_bold.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/index.js
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.jsx
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss
  playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.rb
  playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.test.js
  playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_default.html.erb
  playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_default.jsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog.test.jsx
  playbook/app/pb_kits/playbook/pb_flex/_flex.jsx
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/time_stacked.html.erb
  playbook/spec/pb_kits/playbook/kits/date_stacked_spec.rb
  playbook/spec/pb_kits/playbook/kits/date_time_stacked_spec.rb
Labels: enhancement, ready

#1374 NEW PROPS- Text Input (Add On)
  playbook/.rubocop.yml
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.jsx
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
  playbook/app/pb_kits/playbook/pb_text_input/add_on.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/add_on.rb
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_custom.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_text_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_text_input/text_input.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/text_input.rb
  playbook/lib/playbook/props.rb
  playbook/lib/playbook/props/nested_props.rb
  playbook/spec/pb_kits/playbook/kits/text_input_spec.rb
  playbook/spec/playbook/props/nested_props_spec.rb
Labels: enhancement

#1488 Fixed broken styles in multiple users stacked + pill accessibility, badge alignment, & menu re-organization
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/pb_badge/_badge.scss
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.scss
  playbook/app/pb_kits/playbook/pb_pill/_pill.jsx
  playbook/app/pb_kits/playbook/pb_pill/pill.html.erb
Labels: bug, milano

#1489 [CHMN-98] Add classname to popover on passphrase kit
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
Labels: enhancement, ready

#1490 [NUXE-655] Move error text
  playbook/app/pb_kits/playbook/pb_select/_select.jsx
Labels: bug, ready

#1496 Radio alignment
  .gitignore
  playbook/app/pb_kits/playbook/pb_radio/_radio.jsx
  playbook/app/pb_kits/playbook/pb_radio/_radio.scss
  playbook/app/pb_kits/playbook/pb_radio/docs/_radio_alignment.html.erb
  playbook/app/pb_kits/playbook/pb_radio/docs/_radio_alignment.jsx
  playbook/app/pb_kits/playbook/pb_radio/docs/example.yml
  playbook/app/pb_kits/playbook/pb_radio/docs/index.js
  playbook/app/pb_kits/playbook/pb_radio/radio.rb
  playbook/spec/dummy/app/views/pages/visual_guidelines.html.erb
  playbook/spec/pb_kits/playbook/kits/radio_spec.rb
Labels: enhancement, milano

#1498 [NUXE-673] Fix Timestamp Duplicated Zone
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
Labels: bug, milano
