Repository powerhome/playbook, pull requests merged in 2022-06, with the labels that each got.

#1942 Add Ruby 3.1 & Rails Upgrades for Playbook Website
  .tool-versions
  Dockerfile
  playbook-website/.ruby-version
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/helpers/sample_helper.rb
  playbook-website/bin/rails
  playbook-website/bin/rake
  playbook-website/bin/setup
  playbook-website/bin/spring
  playbook-website/bin/yarn
  playbook-website/config.ru
  playbook-website/config/application.rb
  playbook-website/config/environments/development.rb
  playbook-website/config/environments/production.rb
  playbook-website/config/environments/test.rb
  playbook-website/config/initializers/backtrace_silencers.rb
  playbook-website/config/initializers/new_framework_defaults_6_1.rb
  playbook-website/config/locales/en.yml
  playbook-website/config/puma.rb
  playbook-website/config/spring.rb
  playbook/.rubocop.yml
  playbook/.ruby-version
  playbook/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_form/form.rb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/lib/playbook/props.rb
  playbook/playbook_ui.gemspec
  playbook/private/tasks/pb_release.rake
  playbook/spec/dummy/bin/rails
  playbook/spec/dummy/bin/rake
  playbook/spec/dummy/bin/setup
  playbook/spec/dummy/config/application.rb
  playbook/spec/dummy/config/boot.rb
  playbook/spec/dummy/config/environment.rb
  playbook/spec/dummy/config/environments/development.rb
  playbook/spec/dummy/config/environments/test.rb
  playbook/spec/dummy/config/initializers/new_framework_defaults_7_0.rb
  yarn.lock
Labels: breaking, milano, ready, ruby

#1941 Make Button Kit Compatible with Turbo/Hotwire Features in Rails 7
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: ready, improvement

#1939 [PLAY-170] Convert Border Radius Visual Guideline to React
  playbook-website/app/javascript/components/VisualGuidelines/Examples/BorderRadius.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
Labels: ready, typescript

#1934 [Play-118] Adding All Colors to Background Kit
  playbook/app/pb_kits/playbook/pb_background/_background.scss
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/types/colors.ts
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: enhancement, ready

#1932 [PLAY-192] Convert Select kit to TypeScript
  playbook/app/pb_kits/playbook/pb_body/_body.tsx
  playbook/app/pb_kits/playbook/pb_caption/_caption.tsx
  playbook/app/pb_kits/playbook/pb_select/_select.tsx
Labels: ready, typescript

#1921 [Play-191] Form Pill Kit Typescript Conversion
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_example.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_size.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.jsx
Labels: ready, typescript

#1909 [Play-159] Play Adding Alert To Dialog Kit
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dialog/docs/index.js
Labels: enhancement, ready

#1904 [PLAY-181] Add Success And Error Colors For Dark Mode
  playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss
  playbook/app/pb_kits/playbook/pb_caption/docs/_caption_colors.html.erb
  playbook/app/pb_kits/playbook/pb_caption/docs/_caption_colors.jsx
Labels: ready, improvement

#1900 [Play-182] Update Success And Error Props
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/_body.tsx
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_body/body.rb
  playbook/app/pb_kits/playbook/pb_body/body.test.js
  playbook/app/pb_kits/playbook/pb_body/docs/_body_light.html.erb
  playbook/app/pb_kits/playbook/pb_body/docs/_body_light.jsx
  playbook/app/pb_kits/playbook/pb_body/docs/_description.md
  playbook/app/pb_kits/playbook/pb_body/docs/_footer.md
  playbook/spec/pb_kits/playbook/kits/body_spec.rb
Labels: enhancement, ready

#1899 Updates Visual Guidelines Color Partial to TSX
  playbook-website/app/javascript/components/VisualGuidelines/Colors/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Colors/variables.ts
  playbook-website/app/views/pages/visual_guidelines_partials/_colors.html.slim
Labels: ready, typescript

#1886 [Play-153] Hashtag Kit Convert to TS
  playbook/app/pb_kits/playbook/pb_badge/_badge.tsx
  playbook/app/pb_kits/playbook/pb_hashtag/_hashtag.tsx
Labels: ready, typescript

#1916 [PLAY-169] Create React Spacing Partial
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/PropsValues.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  yarn.lock
Labels: ready, typescript

#1910 Created Visual Guidelines Shadow Partial for React
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Shadows.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
Labels: ready, typescript

#1895 Create React Number Spacing Partial
  playbook-website/app/javascript/components/VisualGuidelines/Examples/NumberSpacing.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
Labels: ready, typescript

#1892 Create React Line Height Partial
  playbook-website/app/javascript/components/VisualGuidelines/Examples/LineHeight.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
Labels: ready, typescript

#1946 [PLAY-58] Swift UI / Setup folder and ReadMe file
  playbook-swift/readME.md
Labels: swiftUI

#1951 Fix Home Address Street
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/pb_home_address_street/city_emphasis.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/city_emphasis.rb
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
  playbook/app/pb_kits/playbook/pb_home_address_street/street_emphasis.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/street_emphasis.rb
  playbook/lib/playbook/props.rb
Labels: bug, ready
