Repository powerhome/playbook, pull requests merged in 2022-10, with the labels that each got.

#2111 [PLAY-347] Filter Kit Dropdown updates
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_close_popover.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_min_width.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_min_width.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_sort.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_sort.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_only.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_only.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_placement.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_placement.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_single.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_single.jsx
Labels: bug, milano, docs

#2108 [PLAY-379]-Fixed Example Doc Border Issue
  playbook-website/app/views/layouts/_nav.html.erb
Labels: bug, docs

#2109 [PLAY-371] Dialog kit docs examples not containing contents
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
Labels: bug, docs

#2110 [PLAY-368] Lists kit docs are broken
  playbook/app/pb_kits/playbook/pb_list/docs/_description.md
Labels: bug, docs

#2112 [PLAY-378] Table kit doc example buttons should be right aligned
  playbook/app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_one_action.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_one_action.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_two_actions.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_two_actions.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.jsx
Labels: bug, milano, docs

#2113 [PLAY-376] Table kit missing space between doc examples
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx
Labels: bug, milano, docs

#2114 [PLAY-389]-Page Title Spacing Bug Fix
  playbook-website/app/views/pages/kit_category_show.html.erb
  playbook-website/app/views/pages/kits.html.erb
Labels: bug, milano, docs

#2115 [PLAY-369] Getting Started markdown code background styling is the wrong color
  playbook-website/app/javascript/site_styles/_getting_started.scss
Labels: bug, milano, docs

#2119 [PLAY-399]-Textarea Doc Bug Fix
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_default.jsx
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error.jsx
Labels: bug, milano, docs

#2092 [PLAY-203] Full-height Variant for Dialog
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_footer.tsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog.test.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_compound_components.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height_placement.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height_placement.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dialog/docs/index.js
Labels: enhancement

#2129 Fix dialog kit border-radius
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Labels: bug, milano

#2120 [PLAY-354] Table Kit (React) doesn’t have responsive js code
  playbook/app/pb_kits/playbook/pb_table/_table.jsx
Labels: bug

#2135 [PLAY-427]-Fixed Issue Where Typeahead Kit Was Returning Null Classes
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
Labels: bug, milano

#2122 [PLAY-394]- Timeline Kit Errors Fix
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_date.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_date.jsx
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_date.md
Labels: bug, milano

#2116 [PLAY-395]-Fixed Hover State on Selectable List Rails Kit
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
  playbook/spec/pb_kits/playbook/kits/selectable_list_item_spec.rb
Labels: bug

#2123 [PLAY-405] Nav Title Spacing Fix
  playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss
Labels: bug, milano

#2117 [PLAY-374]-Filter Kit Style Bleed Fix
  playbook/app/pb_kits/playbook/pb_filter/_filter.scss
Labels: bug, milano

#2128 [PLAY-407]-Home Address Kit Spacing Bug Fix
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx
Labels: bug, milano

#2124 [PLAY-396] Selectable List Radios have extra padding
  playbook/app/pb_kits/playbook/pb_radio/_radio.scss
Labels: bug

#2137 [PLAY-411] Collapsible kit icon size and color
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.rb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_default.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_size.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_size.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_size.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/example.yml
  playbook/app/pb_kits/playbook/pb_collapsible/docs/index.js
Labels: bug, milano

#2150 [PLAY-391] - Legend Kit to Take Custom Colors
  playbook/app/pb_kits/playbook/pb_legend/_legend.jsx
  playbook/app/pb_kits/playbook/pb_legend/_legend.scss
  playbook/app/pb_kits/playbook/pb_legend/docs/_legend_custom_colors.html.erb
  playbook/app/pb_kits/playbook/pb_legend/docs/_legend_custom_colors.jsx
  playbook/app/pb_kits/playbook/pb_legend/docs/_legend_custom_colors.md
  playbook/app/pb_kits/playbook/pb_legend/docs/example.yml
  playbook/app/pb_kits/playbook/pb_legend/docs/index.js
  playbook/app/pb_kits/playbook/pb_legend/legend.html.erb
  playbook/app/pb_kits/playbook/pb_legend/legend.rb
Labels: enhancement, milano

#2133 [PLAY-377] Typeahead kit doesn’t align to Playbook color rules for forms
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: bug

#2134 [PLAY-382] -Filter Doc Popover Close On Click
  playbook/app/pb_kits/playbook/pb_filter/docs/_description.md
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_close_popover.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_max_width.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_sort.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_only.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_placement.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_placement.md
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_single.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/example.yml
  playbook/app/pb_kits/playbook/pb_filter/docs/index.js
Labels: bug, milano, docs

#2151 [Play-390] Tokens for subtle Status and Background Kit colors
  playbook-website/app/javascript/components/VisualGuidelines/Colors/StatusExample.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Colors/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Colors/variables.ts
  playbook-website/app/javascript/components/VisualGuidelines/types.ts
  playbook-website/app/javascript/site_styles/docs/_color_utilities.scss
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status_subtle.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status_subtle.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_status_subtle.md
  playbook/app/pb_kits/playbook/pb_background/docs/example.yml
  playbook/app/pb_kits/playbook/pb_background/docs/index.js
  playbook/app/pb_kits/playbook/tokens/_colors.scss
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: enhancement, milano

#2140 [PLAY-409] Collapsible kit missing hover for button icon
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.scss
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.test.js
Labels: bug, milano

#2136 [PLAY-418]-Filter Kit Doc Spacing
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.jsx
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.jsx
Labels: bug, milano

#2159 Add Subtitle Prop to User Kit
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  playbook/app/pb_kits/playbook/pb_user/docs/_user_block_content_subtitle_rails.html.erb
  playbook/app/pb_kits/playbook/pb_user/docs/_user_block_content_subtitle_rails.md
  playbook/app/pb_kits/playbook/pb_user/docs/_user_block_content_subtitle_react.jsx
  playbook/app/pb_kits/playbook/pb_user/docs/_user_block_content_subtitle_react.md
  playbook/app/pb_kits/playbook/pb_user/docs/_user_subtitle.html.erb
  playbook/app/pb_kits/playbook/pb_user/docs/_user_subtitle.jsx
  playbook/app/pb_kits/playbook/pb_user/docs/example.yml
  playbook/app/pb_kits/playbook/pb_user/docs/index.js
  playbook/app/pb_kits/playbook/pb_user/user.html.erb
  playbook/app/pb_kits/playbook/pb_user/user.rb
  playbook/app/pb_kits/playbook/pb_user/user.test.js
  playbook/spec/pb_kits/playbook/kits/user_spec.rb
Labels: enhancement, milano
