Repository powerhome/playbook, pull requests merged in 2022-05, with the labels that each got.

#1870 Treemap chart
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.js
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.js
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_description.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_colors.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_colors.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_colors.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_default.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_default.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_default.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_drillable.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_drillable.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_drillable.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_grouped_data.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_grouped_data.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_grouped_data.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/index.js
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemap_chart.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemap_chart.rb
  playbook/app/pb_kits/playbook/playbook-doc.js
  playbook/app/pb_kits/playbook/playbook-rails-react-bindings.js
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
  playbook/spec/pb_kits/playbook/kits/treemap_chart_spec.rb
Labels: new kit, ready

#1874 Converting caption to tsx
  playbook/app/pb_kits/playbook/pb_caption/_caption.tsx
Labels: ready, typescript

#1849 [PLAY-142] Visual Guidelines - Switch to React - Examples Template
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Positioning.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/PropsValues.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/javascript/site_styles/visual_guidelines/_border_radius_guidelines.scss
  playbook-website/app/views/pages/visual_guidelines_react.html.erb
Labels: enhancement, milano, ready

#1880 [PLAY-152] Convert Badges Kit To Typescript
  playbook/app/pb_kits/playbook/pb_badge/_badge.tsx
  playbook/app/pb_kits/playbook/pb_badge/docs/_badge_colors.jsx
  playbook/app/pb_kits/playbook/pb_badge/docs/_badge_default.jsx
  playbook/app/pb_kits/playbook/pb_badge/docs/_badge_rounded.jsx
  playbook/app/pb_kits/playbook/pb_badge/docs/index.js
Labels: enhancement, ready, typescript

#1883 Migration to the new registry (Harbor)
  Dockerfile
  Jenkinsfile
  Makefile
  playbook-website/bin/deployer
  playbook-website/config/deploy/templates/deployment.yaml.erb
Labels: milano

#1925 [PLAY-198] Fix Title Bug
  playbook-website/app/views/pages/kit_show.html.erb
Labels: bug, milano

#1922 APP Registry - No explicit imagePullSecrets
  playbook-website/config/deploy/templates/deployment.yaml.erb
Labels: milano

#1926 [Rails 7 fix] Conditionally use render_component method in PbKitHelper
  playbook/lib/playbook/pb_kit_helper.rb
Labels: milano

#1943 Fix Incorrect Type Declaration and Card Kit buildCss for Highlight Class
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/utilities/props.ts
Labels: bug, milano
