Repository powerhome/playbook, pull requests merged in 2022-03, with the labels that each got.

#1801 Add form as a prop for button kit
  playbook/app/pb_kits/playbook/pb_button/_button.jsx
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_accessibility.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_form.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_form.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_button/docs/index.js
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: enhancement, ready

#1778 Addressing deprecation warning in order to avoid using Kernel.open
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
Labels: milano, improvement, needs alpha testing

#1794 Use react-trix lib for RTE kit
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_default.html.erb
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_default.jsx
  playbook/package.json
  yarn.lock
Labels: enhancement, milano, needs alpha testing

#1796 Remove globalProps.js >> globalProps.ts
  playbook/app/pb_kits/playbook/pb_image/docs/_default_image.tsx
  playbook/app/pb_kits/playbook/pb_image/docs/index.js
  playbook/app/pb_kits/playbook/utilities/globalProps.js
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
Labels: needs alpha testing

#1792 Form Group Kit alignment bug fixed
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
Labels: bug, milano, needs alpha testing

#1790 Button's min-height bug fix
  playbook/app/pb_kits/playbook/pb_button/_button.scss
Labels: bug, milano, needs alpha testing

#1793 [YNGJ-574] Background Kit - Set Background Size
  playbook/app/pb_kits/playbook/pb_background/_background.jsx
  playbook/app/pb_kits/playbook/pb_background/background.html.erb
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_background/background.test.js
  playbook/app/pb_kits/playbook/pb_background/docs/_background_size.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_size.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_size.md
  playbook/app/pb_kits/playbook/pb_background/docs/example.yml
  playbook/app/pb_kits/playbook/pb_background/docs/index.js
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: enhancement, milano, ready

#1810 Dialog Kit shows a strange border intermittently
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Labels: bug, ready, priority: low

#1788 [PLAY-119] Background kit custom colors prop
  playbook/app/pb_kits/playbook/pb_background/_background.jsx
  playbook/app/pb_kits/playbook/pb_background/_background.scss
  playbook/app/pb_kits/playbook/pb_background/background.html.erb
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_background/background.test.js
  playbook/app/pb_kits/playbook/pb_background/docs/_background_light.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_description.md
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: enhancement, ready
