Repository powerhome/playbook, pull requests merged in 2022-12, with the labels that each got.

#2182 [PLAY-462] Rails Dialog All Remaining Variants
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.rb
  playbook/app/pb_kits/playbook/pb_dialog/dialogHelper.js
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_compound_components.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height_placement.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height_placement.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height_placement.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_scrollable.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_should_close_on_overlay.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
Labels: enhancement, milano, ready

#2141 Add maxSize to FileUpload
  playbook-website/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_max_size.jsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/example.yml
  playbook/app/pb_kits/playbook/pb_file_upload/docs/index.js
  playbook/app/pb_kits/playbook/pb_file_upload/fileupload.test.js
Labels: enhancement, milano, ready

#2179 [PLAY-486] Date Picker AM/PM Buttons Instead of Toggle
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.test.js
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_time.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/timeSelect.ts
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_time_selection_styles.scss
Labels: enhancement, milano, ready

#2174 [PLAY-414] Change bg color when selectable list item is selected
  playbook-website/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_selectable_list/_item.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.scss
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.rb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
Labels: bug, milano, ready

#2192 [PLAY-460] Website: kit pages in React
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/PbKitReact/index.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/views/pages/kit_show_react.html.erb
  playbook-website/config/routes.rb
Labels: milano, ready, improvement

#2223 [PLAY-530] Nav Kit Wiggle Fix
  playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss
Labels: bug, milano, ready for release

#2217 Updating new kit architecture names
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/KitDocs/index.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/views/pages/kit_show_new.html.erb
  playbook-website/app/views/pages/kit_show_react.html.erb
Labels: milano, ready for release, improvement, docs

#2207 [PLAY-495] Dialog Sticky Header Footer
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_header.tsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.rb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_full_height.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_scrollable.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_scrollable.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_scrollable.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes.jsx
Labels: enhancement, milano, ready for release
