Repository powerhome/playbook, pull requests merged in 2022-07, with the labels that each got.

#1961 Add Matching Decimals Prop to Currency Kit
  playbook/app/pb_kits/playbook/pb_currency/_currency.jsx
  playbook/app/pb_kits/playbook/pb_currency/currency.rb
  playbook/app/pb_kits/playbook/pb_currency/currency.test.js
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_matching_decimals.html.erb
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_matching_decimals.jsx
  playbook/app/pb_kits/playbook/pb_currency/docs/example.yml
  playbook/app/pb_kits/playbook/pb_currency/docs/index.js
  playbook/spec/pb_kits/playbook/pb_currency/currency_spec.rb
Labels: enhancement, milano

#1967 [FINC-1393] Add Precision to Stat Value Kit
  playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_default.md
  playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_precision.html.erb
  playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_precision.md
  playbook/app/pb_kits/playbook/pb_stat_value/docs/example.yml
  playbook/app/pb_kits/playbook/pb_stat_value/stat_value.rb
  playbook/spec/pb_kits/playbook/kits/stat_value_spec.rb
Labels: enhancement, milano

#1970 Revert Back to TS and Fix Props in Radio Kit Input Field
  playbook/app/pb_kits/playbook/pb_radio/_radio.jsx
  playbook/app/pb_kits/playbook/pb_radio/_radio.tsx
Labels: milano

#1966 [PLAY-194] Contact Kit Update: Extension Variant
  playbook/app/pb_kits/playbook/pb_contact/_contact.jsx
  playbook/app/pb_kits/playbook/pb_contact/contact.rb
  playbook/app/pb_kits/playbook/pb_contact/contact.test.js
  playbook/app/pb_kits/playbook/pb_contact/docs/_contact_with_detail.html.erb
  playbook/app/pb_kits/playbook/pb_contact/docs/_contact_with_detail.jsx
  playbook/spec/pb_kits/playbook/kits/contact_spec.rb
Labels: milano

#1973 [PLAY-206] Dialog Kit: Fix Sweet Alert from Original PR
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dialog/docs/index.js
Labels: enhancement, milano

#1972 [PLAY-121] Add Sidenav to the Visual Guidelines Page
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/app/views/layouts/visual_guidelines.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_colors.html.slim
  playbook-website/app/views/pages/visual_guidelines_partials/_cursor.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_display.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_flex_box_props.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_partial_title.html.erb
  playbook/app/pb_kits/playbook/data/menu.yml
Labels: enhancement, milano

#1772 Lightbox Component
  playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_caption/_caption.tsx
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.tsx
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Slide.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Slides.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Thumbnail.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Thumbnails.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/index.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/_lightbox.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/_lightbox_context.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/_lightbox_header.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/_lightbox_header_icon.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/docs/_lightbox_compound_component.jsx
  playbook/app/pb_kits/playbook/pb_lightbox/docs/_lightbox_compound_component.md
  playbook/app/pb_kits/playbook/pb_lightbox/docs/_lightbox_default.jsx
  playbook/app/pb_kits/playbook/pb_lightbox/docs/_lightbox_default.md
  playbook/app/pb_kits/playbook/pb_lightbox/docs/_lightbox_multiple.jsx
  playbook/app/pb_kits/playbook/pb_lightbox/docs/example.yml
  playbook/app/pb_kits/playbook/pb_lightbox/docs/index.js
  playbook/app/pb_kits/playbook/pb_lightbox/hooks/useKbdControls.ts
  playbook/app/pb_kits/playbook/pb_lightbox/hooks/useVisibility.js
  playbook/app/pb_kits/playbook/pb_lightbox/hooks/useWindowSize.ts
  playbook/app/pb_kits/playbook/pb_lightbox/lightbox.scss
  playbook/app/pb_kits/playbook/pb_lightbox/lightbox.test.jsx
  playbook/app/pb_kits/playbook/playbook-doc.js
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/package.json
  yarn.lock
Labels: new kit, milano

#1974 Fix Minor Typo
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_description.md
Labels: milano, docs
