Repository powerhome/playbook, pull requests merged in 2022-09, with the labels that each got.

#2035 [PLAY-171]- Visual Guidelines React: Typography Section
  playbook-website/app/javascript/components/VisualGuidelines/Examples/TYPOGRAPHY_DATA.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Typography.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
Labels: milano, ready, improvement

#2023 [PLAY-277] Home ID in HomeAddressStreet should open in a new tab
  playbook/app/pb_kits/playbook/pb_hashtag/_hashtag.tsx
  playbook/app/pb_kits/playbook/pb_hashtag/docs/_hashtag_link.html.erb
  playbook/app/pb_kits/playbook/pb_hashtag/docs/_hashtag_link.jsx
  playbook/app/pb_kits/playbook/pb_hashtag/docs/_hashtag_link.md
  playbook/app/pb_kits/playbook/pb_hashtag/docs/example.yml
  playbook/app/pb_kits/playbook/pb_hashtag/docs/index.js
  playbook/app/pb_kits/playbook/pb_hashtag/hashtag.html.erb
  playbook/app/pb_kits/playbook/pb_hashtag/hashtag.rb
  playbook/app/pb_kits/playbook/pb_hashtag/hashtag.test.js
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/city_emphasis.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/city_emphasis.rb
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_link.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_link.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_link.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/index.js
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
  playbook/app/pb_kits/playbook/pb_home_address_street/street_emphasis.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/street_emphasis.rb
  playbook/spec/pb_kits/playbook/kits/hashtag_spec.rb
  playbook/spec/pb_kits/playbook/kits/home_address_street_spec.rb
Labels: enhancement, milano

#2030 [PLAY-248] Alert Dialog Cleanup
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_body.jsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_footer.jsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_header.jsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog.test.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
Labels: bug, milano

#2037 [PLAY-233]-Typescript Conversion of Date Time Kit
  playbook/app/pb_kits/playbook/pb_date/_date.tsx
  playbook/app/pb_kits/playbook/pb_date_time/_date_time.tsx
  playbook/app/pb_kits/playbook/pb_date_time/dateTime.test.js
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_align.jsx
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_size.jsx
  playbook/app/pb_kits/playbook/pb_time/_time.tsx
Labels: enhancement, milano, ready

#2043 [PLAY-257] Typescript Conversion: Form Group
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.tsx
  playbook/app/pb_kits/playbook/pb_form_group/form_group.test.js
  playbook/app/pb_kits/playbook/utilities/props.ts
Labels: enhancement, milano, ready

#2044 [PLAY-226] Typescript Conversion: File Upload
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
Labels: enhancement, milano, ready

#2046 [PLAY-231]- TS Conversion of Date Stacked Kit
  playbook/app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_year_stacked/date_year_stacked.test.js
Labels: enhancement, milano, ready

#2060 Add --tag alpha to release script when detected
  playbook/private/tasks/pb_release.rake
Labels: bug, ready

#2048 [PLAY-218]- TS Conversion of Date Range Inline Kit
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.jsx
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.tsx
  playbook/app/pb_kits/playbook/pb_date_range_inline/date_range_inline.test.js
  playbook/app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default.jsx
  playbook/global-jest-setup.js
  playbook/jest.config.js
Labels: enhancement, milano, ready

#2050 Fix Lightbox Jest Tests
  playbook/app/pb_kits/playbook/pb_lightbox/lightbox.test.jsx
Labels: bug, milano, ready

#2052 [Play 300] - Fix Global Responsive Props and Cleanup
  playbook/app/pb_kits/playbook/utilities/_flexbox.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_align_content.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_align_items.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_align_self.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_flex.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_flex_direction.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_flex_grow.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_flex_shrink.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_flex_wrap.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_justify_content.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_justify_self.scss
  playbook/app/pb_kits/playbook/utilities/flexbox_global_props/_order.scss
Labels: enhancement, milano, ready

#2053 [PLAY-299] Datepicker Allow Custom Positions
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.scss
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.rb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.js
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_positions.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_positions.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_positions.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_positions_element.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_positions_element.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss
  playbook/package.json
  playbook/spec/pb_kits/playbook/kits/date_picker_spec.rb
  yarn.lock
Labels: enhancement, milano, ready

#2054 [Play-311] - Add Sidebar For Visual Guidelines React Page
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/packs/react_sidebar.js
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/app/views/pages/visual_guidelines_react.html.erb
Labels: milano, ready, improvement

#2055 [PLAY-317] - Visual Guidelines Improvements
  playbook-website/app/javascript/components/VisualGuidelines/Examples/LineHeight.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Positioning.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/SpacingProps.tsx
  playbook-website/app/javascript/site_styles/_visual_guidelines.scss
Labels: milano, ready, improvement

#2056 Remove typos from Tooltip Kit
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
Labels: enhancement, milano, ready

#2061 [PLAY-322] Enable theming for colors and font family for asset pipeline users
  playbook/app/pb_kits/playbook/tokens/_colors.scss
  playbook/app/pb_kits/playbook/tokens/_typography.scss
Labels: enhancement, milano

#2058 [Play-301]- Timestamp Kit Last Updated Text as Optional Prop
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/timestamp.rb
  playbook/app/pb_kits/playbook/pb_timestamp/timestamp.test.js
Labels: enhancement, milano, ready

#2078 Updated .gitignore
  .gitignore
  playbook-website/.gitignore
  playbook/.gitignore
Labels: improvement

#2064 [PLAY-302] - Button Kit Icon Props + Fixing Examples
  playbook/app/pb_kits/playbook/pb_button/_button.tsx
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_button/button.html.erb
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_block_content.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_block_content.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_block_content.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options.md
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_button/docs/index.js
Labels: enhancement, milano, ready

#2042 [PLAY-259] Typescript Conversion: Home Address Street
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/home_adress_street.test.js
  playbook/app/pb_kits/playbook/utilities/text.ts
Labels: enhancement, milano, typescript

#2066 Add Jest Tests to Badge Kit
  playbook/app/pb_kits/playbook/pb_badge/badge.test.js
Labels: ready, improvement

#2068 [PLAY-312] - Remove Rails Visual Guidelines Code and Replace with React
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/LineHeight.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Positioning.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/site_styles/_visual_guidelines.scss
  playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/app/views/layouts/visual_guidelines.html.erb
  playbook-website/app/views/pages/visual_guidelines.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_border_radius.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_colors.html.slim
  playbook-website/app/views/pages/visual_guidelines_partials/_cursor.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_display.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_display_breakpoints.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_flex_box_props.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_line_height.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_max_width.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_number_spacing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_partial_code_example.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_partial_props.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_partial_title.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_border_radius.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_color.html.slim
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_line_height.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_max_width.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_number_spacing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_positioning.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_screen_sizing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_shadows.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_spacing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_pb_doc_spacing_tokens.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_positioning.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_screen_sizes.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_screen_sizing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_shadows.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_spacing.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_typography.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_typography_headings.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_typography_size.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_typography_spacing.html.erb
  playbook-website/app/views/pages/visual_guidelines_react.html.erb
  playbook-website/config/routes.rb
  playbook/app/pb_kits/playbook/data/menu.yml
Labels: milano, improvement

#2083 [PLAY-332] Bug - Text Input not full-width with addOn prop
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
Labels: bug, milano

#2077 [PLAY-265]- Converted Label Value Kit to TS + Added Jest Test
  playbook/app/pb_kits/playbook/pb_label_value/_label_value.jsx
  playbook/app/pb_kits/playbook/pb_label_value/_label_value.tsx
  playbook/app/pb_kits/playbook/pb_label_value/label_value.test.js
Labels: enhancement, milano, ready, typescript

#2081 PLAY-261-TS Conversion Icon Stat Value Kit + Jest Test
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.tsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.test.js
Labels: enhancement, milano, ready, typescript

#2075 [PLAY-315] - Created Example App for a React Only App Using Playbook
  examples/react-example/.gitignore
  examples/react-example/README.md
  examples/react-example/package.json
  examples/react-example/public/favicon.ico
  examples/react-example/public/index.html
  examples/react-example/public/logo192.png
  examples/react-example/public/logo512.png
  examples/react-example/public/manifest.json
  examples/react-example/public/robots.txt
  examples/react-example/src/App.css
  examples/react-example/src/App.js
  examples/react-example/src/App.test.js
  examples/react-example/src/index.css
  examples/react-example/src/index.js
  examples/react-example/src/logo.svg
  examples/react-example/src/reportWebVitals.js
  examples/react-example/src/setupTests.js
  examples/react-example/yarn.lock
Labels: ready

#2086 [PLAY-343]- Date Pickr SCSS Bug Fix
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_flatpickr_styles.scss
Labels: bug, milano, ready, needs alpha testing

#2082 [PLAY-331] Section Separator Type Bug
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
Labels: bug, milano, ready, typescript

#2070 [PLAY-216] - TS Conversion of Date Stacked kit + Jest Test
  playbook/app/pb_kits/playbook/pb_date_stacked/_date_stacked.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/_date_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_stacked/date_stacked.test.js
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_align.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_bold.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_default.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_not_current_year.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_reverse.jsx
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_sizes.jsx
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
Labels: enhancement, ready, typescript

#2098 [PLAY-344]- Add XXS Spacing Token
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx
  playbook/app/pb_kits/playbook/tokens/_spacing.scss
  playbook/app/pb_kits/playbook/utilities/_spacing.scss
  playbook/lib/playbook/spacing.rb
Labels: enhancement, milano, ready

#2071 [PLAY-219] Typescript Conversion: Date Picker
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/timeSelect.js
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/timeSelect.ts
  playbook/app/pb_kits/playbook/playbook-rails.js
Labels: enhancement, ready, typescript

#2073 [PLAY-217]- Convert Date Range Stacked to TS + Added Jest Test
  playbook/app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_range_stacked/date_range_stacked.test.js
Labels: enhancement, ready, typescript

#2084 [PLAY-230] Typescript Conversion: Dialog
  playbook/app/pb_kits/playbook/pb_dialog/_close_icon.tsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog_context.jsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog_context.tsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_body.tsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_footer.tsx
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_header.tsx
  playbook/package.json
Labels: enhancement, ready

#2088 [PLAY-330]-Lightbox Kit Responsive on Mobile
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Slides.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Thumbnails.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/index.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Header/_lightbox_header.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Header/_lightbox_header_icon.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/_lightbox.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/lightbox.scss
Labels: bug, ready

#2089 [Play-346] Update pb_chart plugin to resize gauge kit on load
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.html.erb
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.jsx
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.md
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.html.erb
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.jsx
  playbook/app/pb_kits/playbook/pb_gauge/docs/example.yml
  playbook/app/pb_kits/playbook/pb_gauge/docs/index.js
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
Labels: bug, milano, needs alpha testing
