Repository powerhome/playbook, pull requests merged in 2022-02, with the labels that each got.

#1724 [Play-82]Bug Popover close on any
  playbook/app/pb_kits/playbook/pb_popover/_popover.jsx
  playbook/app/pb_kits/playbook/pb_popover/docs/_popover_close.html.erb
  playbook/app/pb_kits/playbook/pb_popover/index.js
  playbook/app/pb_kits/playbook/pb_popover/popover.html.erb
Labels: bug, milano, ready

#1774 Fix typo CSS attribute name
  playbook-website/app/views/pages/code_snippets/typography_tokens.txt
Labels: bug

#1768 [PLAY-16] File Upload Kit: Can't upload Pages, Numbers, and Keynote files [#1575]
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.jsx
  playbook/app/pb_kits/playbook/pb_file_upload/fileupload.test.js
Labels: bug, milano

#1752 [PLAY-30] Line Graph Chart: Add Darkmode
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.js
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.jsx
  playbook/app/pb_kits/playbook/pb_gauge/gauge.rb
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/line_graph.rb
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
Labels: enhancement, milano

#1758 [PLAY-111] Size Prop styling needs to be corrected: Avatar
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
  playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
Labels: bug, milano, Needs Review

#1760 [PCA-17] React Rich Text Editor Kit: Field doesn't update with an external value update [#1579]
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.jsx
Labels: bug, milano

#1756 [PLAY-112] Size Prop styling needs to be corrected: Image Kit
  playbook/app/pb_kits/playbook/pb_image/_image.jsx
  playbook/app/pb_kits/playbook/pb_image/_image.scss
  playbook/app/pb_kits/playbook/pb_image/image.rb
  playbook/app/pb_kits/playbook/pb_image/image.test.js
  playbook/spec/pb_kits/playbook/kits/image_spec.rb
Labels: bug, milano

#1722 [PLAY-76]Text Input kit spacing fixed
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
  playbook/app/pb_kits/playbook/pb_text_input/text_input.test.js
  playbook/spec/pb_kits/playbook/kits/text_input_spec.rb
Labels: enhancement, milano, not ready

#1749 [PCA-105] Add size prop to the button kit/fixing bug on previous PR
  playbook/app/pb_kits/playbook/pb_button/_button.jsx
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/button.test.js
  playbook/app/pb_kits/playbook/pb_button/docs/_button_size.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_size.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_size.md
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_button/docs/index.js
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: bug, milano

#1743 [Play-19] background kit add lazy loading to images pt 2
  playbook/app/pb_kits/playbook/pb_background/_background.jsx
  playbook/app/pb_kits/playbook/pb_background/_background.scss
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_image.html.erb
  playbook/app/pb_kits/playbook/pb_background/docs/_background_image.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_image.md
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: enhancement, milano

#1741 [PLAY-91] Add unique key prop to text input
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.jsx
Labels: enhancement, milano

#1750 [PLAY-2] Add flexbox props to all kits
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/pages/code_snippets/cursor_jsx.txt
  playbook-website/app/views/pages/code_snippets/justify_self_jsx.txt
  playbook-website/app/views/pages/visual_guidelines.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_cursor.html.erb
  playbook-website/app/views/pages/visual_guidelines_partials/_flex_box_props.html.erb
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_card/card_body.rb
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_align.jsx
  playbook/app/pb_kits/playbook/pb_flex/flex_item.rb
  playbook/app/pb_kits/playbook/utilities/_align_content.scss
  playbook/app/pb_kits/playbook/utilities/_align_items.scss
  playbook/app/pb_kits/playbook/utilities/_align_self.scss
  playbook/app/pb_kits/playbook/utilities/_flex.scss
  playbook/app/pb_kits/playbook/utilities/_flex_direction.scss
  playbook/app/pb_kits/playbook/utilities/_flex_grow.scss
  playbook/app/pb_kits/playbook/utilities/_flex_shrink.scss
  playbook/app/pb_kits/playbook/utilities/_flex_wrap.scss
  playbook/app/pb_kits/playbook/utilities/_flexbox.scss
  playbook/app/pb_kits/playbook/utilities/_justify_content.scss
  playbook/app/pb_kits/playbook/utilities/_justify_self.scss
  playbook/app/pb_kits/playbook/utilities/_order.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.js
  playbook/lib/playbook/align_content.rb
  playbook/lib/playbook/align_items.rb
  playbook/lib/playbook/align_self.rb
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/flex.rb
  playbook/lib/playbook/flex_direction.rb
  playbook/lib/playbook/flex_grow.rb
  playbook/lib/playbook/flex_shrink.rb
  playbook/lib/playbook/flex_wrap.rb
  playbook/lib/playbook/justify_content.rb
  playbook/lib/playbook/justify_self.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/order.rb
  playbook/spec/pb_kits/playbook/kits/flex_item_spec.rb
  playbook/spec/pb_kits/playbook/kits/flex_spec.rb
  playbook/spec/playbook/kit_base_spec.rb
Labels: enhancement, milano, ready, needs alpha testing

#1797 React Line Graph - line graph height doc example missing a fixed height prop
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.jsx
Labels: bug, milano
