Repository powerhome/playbook, pull requests merged in 2022-11, with the labels that each got.

#2162 [PLAY-445] Walkthrough kit update Joyride version
  playbook/package.json
  yarn.lock
Labels: milano, ready, improvement

#2163 [PLAY-423] Radio kit (React) alignment error
  playbook/app/pb_kits/playbook/pb_radio/_radio.scss
Labels: bug, milano, ready

#2169 [PLAY-385] Added Hover State to Buttons with Link Variant
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.jsx
Labels: enhancement, milano, ready

#2170 [PLAY-463] Added Missing Export for BreadCrumbItem
  playbook/app/pb_kits/playbook/index.js
Labels: bug, milano, ready

#2171 [Play-450] Charts/Graphs kits legend position
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend_position.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend_position.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend_position.md
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/index.js
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_legend_position.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_legend_position.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_legend_position.md
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/index.js
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_position.html.erb
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_position.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_position.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_line_graph/docs/index.js
  playbook/app/pb_kits/playbook/pb_line_graph/line_graph.rb
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
  playbook/spec/pb_kits/playbook/kits/bar_graph_spec.rb
  playbook/spec/pb_kits/playbook/kits/line_graph_spec.rb
Labels: enhancement, milano, ready

#2175 [PLAY-489] Reinstated Flatpickr Default AM/PM Toggle
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.test.js
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_time.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/timeSelect.ts
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_time_selection_styles.scss
Labels: bug, milano, ready

#2183 [PLAY-501] Fix Button Hover Bug
  playbook/app/pb_kits/playbook/pb_button/_button.scss
Labels: bug, milano
