Repository powerhome/playbook, pull requests merged in 2023-01, with the labels that each got.

#2191 [PLAY-236] Rebuild Charts to Use React-Highcharts
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx
  playbook/app/pb_kits/playbook/pb_circle_chart/ChartsTypes.ts
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsColorsHelper.ts
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts
  playbook/app/pb_kits/playbook/pb_dashboard/themeTypes.ts
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.jsx
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.scss
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.tsx
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.html.erb
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.jsx
  playbook/app/pb_kits/playbook/pb_gauge/gauge.html.erb
  playbook/app/pb_kits/playbook/pb_gauge/gauge.rb
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.jsx
  playbook/app/pb_kits/playbook/playbook-rails-react-bindings.js
  playbook/app/pb_kits/playbook/playbook-rails.js
  playbook/app/pb_kits/playbook/plugins/pb_chart.js
  playbook/package.json
  yarn.lock
Labels: milano, ready for release, improvement

#2237 Circlechart Fix for Live Update Variant
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.tsx
Labels: bug

#2230 [PLAY-512] Update React to v17
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_popover/_popover.jsx
  playbook/app/pb_kits/playbook/pb_popover/docs/_popover_close.jsx
  playbook/package.json
  yarn.lock
Labels: milano, ready for release, improvement, needs alpha testing

#2240 Allow deployments to proceed smoothly within quota
  playbook-website/config/deploy/templates/deployment.yaml.erb
Labels: milano

#2226 [PLAY-519] Update Error Color Token
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: enhancement, ready for release

#2189 [PLAY-449] New psuedo border on hover: + Table.scss file cleanup
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_as-cards.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_desktop_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_hover.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_single-line.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_table-card.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_tablet_collapse.scss
Labels: enhancement, milano, ready for release

#2235 [PLAY-520] Popover Kit Updates for Dropdown Doc Example
  playbook/app/pb_kits/playbook/pb_popover/docs/_popover_list.html.erb
  playbook/app/pb_kits/playbook/pb_popover/docs/_popover_list.jsx
Labels: milano, ready for release, improvement

#2241 [PLAY-543] Fixes loader-utils security vulnerability
  playbook/package.json
  yarn.lock
Labels: milano, ready for release, improvement

#2244 Fixed SVG-loader Error in Badge Kit
  playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.jsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/million-dollar.jsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/veteran.jsx
Labels: bug

#2234 [PLAY-525] Convert List Kit to Typescript
  playbook/app/pb_kits/playbook/pb_list/_list.jsx
  playbook/app/pb_kits/playbook/pb_list/_list.tsx
  playbook/app/pb_kits/playbook/pb_list/_list_item.tsx
Labels: enhancement, milano, ready for release, 11.19.0

#2231 [PLAY-79] Provide text highlight example in Typeahead kit
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_highlight.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js
Labels: enhancement, milano, ready for release, 11.19.0

#2229 [PLAY-366] Fixing Collapsible kit content spacing issue
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleContent.tsx
Labels: bug, milano, ready for release, 11.19.0

#2219 [PLAY-336] TS Conversion Popover
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
  playbook/app/pb_kits/playbook/pb_popover/_popover.jsx
  playbook/app/pb_kits/playbook/pb_popover/_popover.tsx
  playbook/app/pb_kits/playbook/pb_popover/index.ts
  playbook/app/pb_kits/playbook/pb_popover/popover.test.js
  playbook/package.json
  yarn.lock
Labels: enhancement, ready for release, 11.19.0

#2236 Make Dev Dependencies Actually Dev Dependencies
  playbook/package.json
  yarn.lock
Labels: milano, ready for release, improvement, 11.19.0

#2247 [PLAY-443] Body kit style <b>, <strong>, and <a>
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.html.erb
  playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.jsx
  playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.md
  playbook/app/pb_kits/playbook/pb_body/docs/example.yml
  playbook/app/pb_kits/playbook/pb_body/docs/index.js
Labels: enhancement, milano, ready for release

#2248 [PLAY-493] dialog kit animation
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog.rb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.test.jsx
  playbook/spec/pb_kits/playbook/kits/dialog_spec.rb
Labels: enhancement, milano, ready for release

#2253 [PLAY-521] Fixing select icon position in error state
  playbook/app/pb_kits/playbook/pb_select/_select.scss
Labels: bug, milano, ready for release

#2258 Play 526 typescript selectable card
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.tsx
  playbook/app/pb_kits/playbook/pb_radio/_radio.tsx
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.tsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_default.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_single_select.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.test.js
Labels: enhancement, milano, ready for release, typescript

#2259 [PLAY-527] Converting Selectable Icon kit to Typescript
  playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.tsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_default.jsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_single_select.jsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.test.js
Labels: enhancement, milano, ready for release

#2256 [PLAY-566] Add Custom Message to FileUpload kit
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_description.md
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_custom_message.jsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/example.yml
  playbook/app/pb_kits/playbook/pb_file_upload/docs/index.js
  playbook/app/pb_kits/playbook/pb_file_upload/fileupload.test.js
Labels: enhancement, milano, ready for release

#2180 [PLAY-490] Removed FA from Dist, Imported into Playbook via Yarn
  .dockerignore
  .gitignore
  .npmrc
  .sops.yaml
  Dockerfile
  Jenkinsfile
  Makefile
  docker-compose.ci.yml
  docker-compose.yml
  playbook-website/app/javascript/packs/application.js
  playbook-website/package.json
  playbook/fonts/fontawesome-min.js
  playbook/fonts/regular-min.js
  playbook/package.json
  playbook/webpack.config.js
  yarn.lock
  yarn.secrets.env
Labels: breaking, milano, improvement
