Repository powerhome/playbook, pull requests merged in 2023-11, with the labels that each got.

#2798 [PBIOS-160] Docs: Button
  playbook/app/pb_kits/playbook/pb_button/docs/_button_circle_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_full_width_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_props_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_size_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2800 [PLAY-1027] 📄 Table kit [sortable] table header docs
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.md
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
Labels: milano, improvement

#2808 [PBIOS-161] Docs: Card
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_border_none_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_border_radius_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_highlight_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_light_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_padding_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_props_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_selected_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_separator_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_shadow_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_styles_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_tag_swift.md
  playbook/app/pb_kits/playbook/pb_card/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2806 [PLAY-945] 🌐 Website V1 - Getting Started Updated Headers 🌐
  playbook-website/app/javascript/components/App.tsx
  playbook-website/app/javascript/images/getting-started.svg
  playbook-website/app/javascript/images/pb_generic_header.jpg
  playbook-website/app/views/layouts/docs.html.erb
Labels: milano, ready for release, improvement

#2831 [PBIOS-164] Docs: Checkbox
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default_swift.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_error_swift.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate_swift.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_props_swift.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2844 [PBIOS-166] Docs: Icon Circle
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_color_props.md
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_color_swift.md
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_defaul_swift.md
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_sizes_swift.md
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2823 [PLAY-1048] RTE kit Tiptap optional toolbar (for Huddle integration)
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_tiptap_styles.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_toolbar_disabled.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_toolbar_disabled.md
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
  playbook/app/pb_kits/playbook/pb_rich_text_editor/rich_text_editor_advanced.test.js
  yarn.lock
Labels: enhancement, milano, ready for release, alpha

#2824 [PLAY-1018] Update kit generator
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_dawg/docs/example.yml
  playbook/lib/generators/kit/kit_generator.rb
  playbook/lib/generators/kit/templates/kit_example_swift.erb.tt
  playbook/lib/generators/kit/templates/kit_example_yml.erb.tt
Labels: milano

#2871 Remove Glob code breaking Nitro's Playbook docs
  playbook/app/pb_kits/playbook/pb_dawg/docs/example.yml
  playbook/lib/playbook/pb_doc_helper.rb
Labels: milano

#2838 [PBIOS-165] Docs: Icon
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_border_swift.md
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default_swift.md
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_flip_swift.md
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_props_swift.md
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_rotate_swift.md
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_sizes_swift.md
  playbook/app/pb_kits/playbook/pb_icon/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2880 Update CHANGELOG.md for 13.11.1
  playbook/CHANGELOG.md
Labels: milano

#2851 [PBIOS-167] Docs: Image
  playbook/app/pb_kits/playbook/pb_image/docs/_image_props_swift.md
  playbook/app/pb_kits/playbook/pb_image/docs/_rounded_image_swift.md
  playbook/app/pb_kits/playbook/pb_image/docs/_size_image_swift.md
  playbook/app/pb_kits/playbook/pb_image/docs/_size_none_image_swift.md
  playbook/app/pb_kits/playbook/pb_image/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2810 [PLAY-1038] Beta React-Router Scaffold/Setup
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/App.tsx
  playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
  playbook-website/app/javascript/components/PbKitFetch/index.tsx
  playbook-website/app/javascript/components/Website/README.md
  playbook-website/app/javascript/components/Website/index.tsx
  playbook-website/app/javascript/components/Website/src/assets/README.md
  playbook-website/app/javascript/components/Website/src/components/DarkModeToggle.jsx
  playbook-website/app/javascript/components/Website/src/components/HeroImage.tsx
  playbook-website/app/javascript/components/Website/src/components/README.md
  playbook-website/app/javascript/components/Website/src/hooks/README.md
  playbook-website/app/javascript/components/Website/src/hooks/loaders.js
  playbook-website/app/javascript/components/Website/src/hooks/useFormatter.ts
  playbook-website/app/javascript/components/Website/src/layouts/Footer.tsx
  playbook-website/app/javascript/components/Website/src/layouts/LayoutRight.tsx
  playbook-website/app/javascript/components/Website/src/layouts/README.md
  playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
  playbook-website/app/javascript/components/Website/src/pages/ComponentShow.tsx
  playbook-website/app/javascript/components/Website/src/pages/README.md
  playbook-website/app/javascript/packs/app.js
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/views/layouts/application_beta.html.erb
  playbook-website/app/views/pages/kit_category_show.html.erb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/app/views/pages/kits.html.erb
  playbook-website/config/routes.rb
  playbook-website/tsconfig.json
Labels: milano, improvement

#2856 [PLAY-821] 🌐 Console error cleanup: site-wide and homepage
  playbook-website/Gemfile.lock
  playbook-website/app/javascript/components/HomepageHero/HeroComponents/SelectPlan.tsx
  playbook-website/app/javascript/components/HomepageHero/Pages/Welcome.tsx
  playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/packs/main_sidebar.js
  playbook-website/app/javascript/packs/samples.js
  playbook-website/app/javascript/packs/visual_guidelines.js
  playbook-website/lib/generators/sample/sample_generator.rb
  playbook/app/pb_kits/playbook/playbook-doc.js
  playbook/lib/generators/kit/kit_generator.rb
Labels: milano, ready for release, improvement, alpha

#2850 [PLAY-1060] Add a dependencies page
  playbook-website/app/views/guides/_dependencies_index.html.erb
  playbook-website/app/views/guides/_docs_index_list.html.erb
  playbook-website/app/views/guides/dependencies.html.md
  playbook-website/app/views/guides/dependencies/first.md
Labels: milano, ready for release, improvement

#2855 [PBIOS-168] Docs: Label Value
  playbook/app/pb_kits/playbook/pb_label_value/docs/_label_value_default_swift.md
  playbook/app/pb_kits/playbook/pb_label_value/docs/_label_value_details_examples_swift.md
  playbook/app/pb_kits/playbook/pb_label_value/docs/_label_value_details_swift.md
  playbook/app/pb_kits/playbook/pb_label_value/docs/_label_value_props_swift.md
  playbook/app/pb_kits/playbook/pb_label_value/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2865 [PBIOS-169] Docs: Message
  playbook/app/pb_kits/playbook/pb_message/docs/_message_default_swift.md
  playbook/app/pb_kits/playbook/pb_message/docs/_message_props_swift.md
  playbook/app/pb_kits/playbook/pb_message/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2826 [PLAY-1056] Tooltip for truncated text (only)
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default_react.jsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_delay.jsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_interaction.jsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_margin.jsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_selectors.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_show_tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_show_tooltip.md
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_show_tooltip_react.jsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_show_tooltip_react.md
  playbook/app/pb_kits/playbook/pb_tooltip/docs/example.yml
  playbook/app/pb_kits/playbook/pb_tooltip/docs/index.js
  playbook/app/pb_kits/playbook/pb_tooltip/index.js
  playbook/app/pb_kits/playbook/pb_tooltip/tooltip.rb
  playbook/app/pb_kits/playbook/pb_tooltip/tooltip.test.jsx
Labels: milano, ready for release, alpha

#2846 [PLAY-1054] Use new sorting style
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_header.rb
Labels: enhancement, milano, ready for release, alpha

#2870 [PLAY-1072] Initial State and External Controls for Collapse in Rails
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_content.rb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_external_controls.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_external_controls.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_external_controls_multiple.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_external_controls_multiple.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/example.yml
  playbook/app/pb_kits/playbook/pb_collapsible/index.js
Labels: enhancement, milano, ready for release

#2872 [PLAY-406] 🐞 Table kit hover style fixes in Darkmode
  playbook/app/pb_kits/playbook/pb_table/styles/_hover.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_table-dark.scss
Labels: bug, milano, ready for release

#2885 [PLAY-1061] ☑️ Linting improvements
  .eslintignore
  .eslintrc.json
  package.json
  yarn.lock
Labels: milano, ready for release, improvement

#2886 [PBIOS-185] Docs: Textarea
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_default_swift.md
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error_swift.md
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_props_swift.md
  playbook/app/pb_kits/playbook/pb_textarea/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2884 [PBIOS-180] Docs: Section Separator
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children_swift.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_dashed_swift.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_line_swift.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_props_swift.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_swift.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_vertical_swift.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2888 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano
