Repository powerhome/playbook, pull requests merged in 2023-02, with the labels that each got.

#2254 [PLAY-497] Paginate/passthrough
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/app/controllers/pages_controller.rb
  playbook/Gemfile.lock
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.scss
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default.html.erb
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default.md
  playbook/app/pb_kits/playbook/pb_pagination/docs/example.yml
  playbook/app/pb_kits/playbook/pb_pagination/pagination.html.erb
  playbook/app/pb_kits/playbook/pb_pagination/pagination.rb
  playbook/lib/playbook/pagination_renderer.rb
  playbook/playbook_ui.gemspec
  playbook/spec/pb_kits/playbook/kits/paginate_spec.rb
Labels: new kit, milano, ready for release

#2285 [PLAY-575] Added Position Fixed to Rails Dialog
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Labels: bug, milano, ready for release

#2289 [PLAY-576] GitHub Actions Alpha
  .github/workflows/github-actions-alpha-version.yml
Labels: ready for release, improvement, alpha

#2283 [PLAY-555] Fixed Body Content disappearing behind Footer for Dialog
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/child_kits/_dialog_footer.tsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
Labels: bug, milano, ready for release

#2282 [PLAY- 567] Fix for Typeahead Event Detail Showing Null
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_without_pills.html.erb
Labels: bug, milano, ready for release

#2293 [Play-528] Typescript Conversion Stat Change
  playbook/app/pb_kits/playbook/pb_stat_change/_stat_change.jsx
  playbook/app/pb_kits/playbook/pb_stat_change/_stat_change.tsx
  playbook/app/pb_kits/playbook/pb_stat_change/stat_change.test.js
Labels: enhancement, milano, ready for release

#2294 [Play-529] Typescript Conversion Stat Value
  playbook/app/pb_kits/playbook/pb_stat_value/_stat_value.tsx
  playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_unit.jsx
  playbook/app/pb_kits/playbook/pb_stat_value/stat_value.test.js
Labels: enhancement, milano, ready for release

#2295 [PLAY-499] Added ClassName prop to Tooltip Kit
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default_react.jsx
  playbook/app/pb_kits/playbook/pb_tooltip/tooltip.test.jsx
Labels: bug, milano, ready for release

#2297 [PLAY-585] Time Stacked Typescript Conversion
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_default.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/docs/index.js
Labels: enhancement, milano, ready for release

#2298 [PLAY-586] Typescript Conversion: TimeStamp
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.tsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.jsx
Labels: enhancement, milano, ready for release

#2300 [PLAY-412] Bar Graph borders don't match theme
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: bug, milano, ready for release

#2308 [PLAY-596] Checkbox Pseudo Styles
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss
Labels: enhancement, milano, ready for release

#2306 [PLAY-588] TS Conversion of Progress Simple + Jest Tests
  playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.tsx
  playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.test.js
Labels: enhancement, milano, ready for release

#2286 [Play-568] typeahead error state
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.test.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ClearIndicator.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Control.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.md
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Labels: enhancement, milano, ready for release

#2304 [PLAY-393]- Fixed Form Group Bug Where content Jumped on Select
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
Labels: bug, milano, ready for release

#2281 [Play-554] button focus state
  playbook/app/pb_kits/playbook/mixins/_accessibility.scss
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_button/_button.tsx
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_accessibility.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_block_content.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_form.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_full_width.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_link.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_link.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_loading.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_loading.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_options.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_size.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_size.jsx
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: enhancement, milano, ready for release

#2273 [PLAY-580] Maplibre Map POC
  playbook-website/app/javascript/site_styles/main.scss
  playbook-website/app/javascript/site_styles/map_styles/_map_default.scss
  playbook-website/config/initializers/content_security_policy.rb
  playbook-website/package.json
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_map/_map.scss
  playbook/app/pb_kits/playbook/pb_map/_map.tsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_default.jsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_default.md
  playbook/app/pb_kits/playbook/pb_map/docs/_map_with_plugin.jsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_with_plugin.md
  playbook/app/pb_kits/playbook/pb_map/docs/example.yml
  playbook/app/pb_kits/playbook/pb_map/docs/index.js
  playbook/app/pb_kits/playbook/pb_map/map.test.jsx
  playbook/app/pb_kits/playbook/playbook-doc.js
  yarn.lock
Labels: new kit, milano, ready for release

#2301 [Play-595] Circle Icon Button pseudo state
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
Labels: enhancement, milano, ready for release

#2318 [PLAY-415] Text Input kit Left-Aligned Add On With No Border padding missing
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.jsx
Labels: bug, milano, ready for release

#2311 [PLAY-589] ♻️ Typescript Conversion: Title Count
  playbook/app/pb_kits/playbook/pb_title_count/_title_count.tsx
  playbook/app/pb_kits/playbook/pb_title_count/title_count.test.js
Labels: enhancement, milano, ready for release

#2315 [PLAY-232] ♻️ Typescript Conversion: Date Time Stacked
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_default.jsx
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx
Labels: enhancement, milano, ready for release

#2314 [Play-597] Radio kit :pseudo styles
  playbook/app/pb_kits/playbook/pb_radio/_radio.scss
  playbook/app/pb_kits/playbook/pb_radio/_radio.tsx
Labels: enhancement, milano, ready for release

#2317 [PLAY-607] Give Sticky Header for Dialog a z-index
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Labels: bug, milano, ready for release

#2305 [Play-594] Adding new Phone Number Input kit
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/data/menu.yml
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_default.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_default.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_initial_country.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_initial_country.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_only_countries.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_only_countries.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_preferred_countries.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_preferred_countries.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.test.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/types.d.ts
  playbook/app/pb_kits/playbook/playbook-doc.js
  playbook/package.json
  playbook/webpack.config.js
  yarn.lock
Labels: new kit, milano, ready for release

#2322 [PLAY-619] Color tokens need default property
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: enhancement, milano, ready for release

#2312 [PLAY-413] Date Picker Hide Input Icon broken
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
Labels: bug, breaking, milano, ready for release

#2325 [PLAY-620] Selectable List kit active background color is wrong
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.scss
Labels: bug, milano, ready for release

#2323 [PLAY-370] Fixing Typeahead off spacing on dropdown
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: bug, milano, ready for release

#2326 [PLAY-633] Converting Message kit to Typescript
  playbook/app/pb_kits/playbook/pb_message/_message.tsx
  playbook/app/pb_kits/playbook/pb_message/message.test.js
Labels: enhancement, milano, ready for release

#2328 [PLAY-610] Converting Loading Inline kit to Typescrit
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.jsx
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.test.js
Labels: enhancement, milano, ready for release

#2331 [PLAY-634] Converting Passphrase kit to Typescript
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.tsx
  playbook/app/pb_kits/playbook/pb_popover/_popover.tsx
Labels: enhancement, milano, ready for release

#2333 [PLAY-639] Phone Number Input Rails
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_default.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
  playbook/app/pb_kits/playbook/playbook-rails-react-bindings.js
Labels: new kit, milano, ready for release

#2329 [PLAY-553] Map Kit Custom Styles
  playbook-website/app/javascript/site_styles/map_styles/_map_default.scss
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_button/_button.tsx
  playbook/app/pb_kits/playbook/pb_map/_map.scss
  playbook/app/pb_kits/playbook/pb_map/_map.tsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_default.jsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_default.md
  playbook/app/pb_kits/playbook/pb_map/docs/_map_with_plugin.jsx
  playbook/app/pb_kits/playbook/pb_map/docs/example.yml
  playbook/app/pb_kits/playbook/pb_map/pbMapTheme.ts
Labels: enhancement, milano, ready for release
