Repository powerhome/playbook, pull requests merged in 2023-03, with the labels that each got.

#2324 [PLAY-618] Adding secondary action to color tokens
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: milano, ready for release, improvement

#2336 [PLAY-637] Changing green token color
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: milano, ready for release, improvement

#2338 [PLAY-635] Converting Person Contact kit to Typescript
  playbook/app/pb_kits/playbook/pb_person_contact/_person_contact.tsx
  playbook/app/pb_kits/playbook/pb_person_contact/person_contact.test.js
Labels: enhancement, milano, ready for release

#2343 [PLAY-650] Working Rails Version of Phone Number
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_initial_country.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_only_countries.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_preferred_countries.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.html.erb
Labels: enhancement, milano, ready for release

#2352 [PLAY-662] Recoded separator to remove z-index issues
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
  playbook/app/pb_kits/playbook/pb_nav/_nav.jsx
  playbook/app/pb_kits/playbook/pb_nav/nav.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator_mixin.scss
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_background.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_background.jsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/example.yml
  playbook/app/pb_kits/playbook/pb_section_separator/docs/index.js
  playbook/app/pb_kits/playbook/pb_section_separator/section_separator.html.erb
Labels: bug, milano, ready for release

#2351 [PLAY-661] MultiLevelSelect in Rails
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.test.jsx
  playbook/app/pb_kits/playbook/playbook-rails-react-bindings.js
Labels: new kit, milano, ready for release

#2345 [PLAY-602] Selectable Cards hover target area update
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.scss
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.scss
Labels: bug, milano, ready for release

#2342 [PLAY-638] Allowing input typing on Date Picker
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.scss
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_allow_input.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_input_styles.scss
Labels: bug, milano, ready for release

#2334 [PLAY-631] Phone Number Input kit button up
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
Labels: milano, ready for release, improvement

#2365 [PLAY-663] MultiLevelSelect returnAllSelected Prop
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_select_helper.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
Labels: enhancement, milano, ready for release

#2348 [PLAY-641] ♻️ Typescript Conversion: Multiple Users Kit
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.tsx
  playbook/app/pb_kits/playbook/pb_multiple_users/multiple_users.test.js
Labels: enhancement, milano, ready for release

#2362 [PLAY-644] Converting Progress Pills kit to TS
  playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.tsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_status.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.test.js
Labels: enhancement, milano, ready for release

#2361 [PLAY-655] Only importing FontAwesome's regular font
  playbook-website/app/javascript/packs/application.js
Labels: milano, ready for release, improvement

#2366 NPM + Ruby Gem Alpha Release
  .github/workflows/github-actions-alpha-version.yml
  playbook/private/tasks/pb_action.rake
Labels: improvement, alpha

#2373 [PLAY-671] Adding classname prop to Typeahead kit
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.test.jsx
Labels: bug, milano, ready for release

#2353 [PLAY-417] Styling treemap back button
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.scss
Labels: bug, milano, ready for release

#2367 [PLAY-645] ♻️ Typescript Conversion: Progress Step Kit
  playbook/app/pb_kits/playbook/pb_progress_step/_progress_step.tsx
  playbook/app/pb_kits/playbook/pb_progress_step/_progress_step_item.tsx
  playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
  playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.jsx
  playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker_click_events.jsx
  playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.jsx
  playbook/app/pb_kits/playbook/pb_progress_step/progress_step.test.js
Labels: enhancement, milano, ready for release

#2371 [PLAY-625] Implementing Phone Number Input kit dark mode
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_default.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_initial_country.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_only_countries.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_preferred_countries.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
Labels: enhancement, milano, ready for release

#2394 Fix For Chart for Release PR
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.scss
Labels: bug, milano, ready for release

#2368 [PLAY- 649] Map Kit Styles
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_map/_map.scss
  playbook/app/pb_kits/playbook/pb_map/_pb_map_button_mixin.scss
  playbook/app/pb_kits/playbook/pb_map/docs/_map_default.jsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_with_plugin.jsx
Labels: milano, ready for release

#2398 [PLAY-689] 🐞 Text Input spacing error without label
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_no_label.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_no_label.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_text_input/docs/index.js
Labels: bug, milano, ready for release, alpha

#2376 [PLAY-643] Converting Nav kit to Typescript
  playbook/app/pb_kits/playbook/pb_nav/_item.tsx
  playbook/app/pb_kits/playbook/pb_nav/_nav.test.js
  playbook/app/pb_kits/playbook/pb_nav/_nav.tsx
  playbook/app/pb_kits/playbook/pb_nav/_nav_item.test.js
Labels: enhancement, milano, ready for release

#2395 [PLAY-623] Menu YML Ready for Alpha
  playbook-website/app/views/pages/all_kit_examples.html.erb
  playbook-website/config/initializers/global_variables.rb
  playbook-website/config/menu.yml
  playbook/lib/generators/kit/kit_generator.rb
  playbook/lib/playbook/pb_doc_helper.rb
  playbook/playbook_ui.gemspec
  playbook/webpack.config.js
Labels: enhancement, ready for release

#2400 [PLAY-682] Add Articles doc to Body kit
  playbook-website/app/javascript/components/VisualGuidelines/Examples/LineHeight.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook/app/pb_kits/playbook/pb_body/docs/_body_articles.html.erb
  playbook/app/pb_kits/playbook/pb_body/docs/_body_articles.jsx
  playbook/app/pb_kits/playbook/pb_body/docs/_body_articles.md
  playbook/app/pb_kits/playbook/pb_body/docs/example.yml
  playbook/app/pb_kits/playbook/pb_body/docs/index.js
Labels: milano, ready for release, improvement

#2402 Adjust Renovate PR Concurrency
  renovate.json
Labels: dependencies

#2410 [PLAY-680] Converting Source kit to Typescript
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_source/_source.tsx
  playbook/app/pb_kits/playbook/pb_source/source.test.js
Labels: enhancement, milano, ready for release

#2404 [PLAY-678] Converting Selectable Card Icon kit to Typescript
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.tsx
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.test.js
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.tsx
Labels: enhancement, milano, ready for release

#2396 [PLAY-475] Creating Fixed Toast auto close functionality
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.tsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_auto_close.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_auto_close.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/index.js
Labels: enhancement, milano, ready for release

#2411 Dependency Updates
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
  playbook/package.json
  yarn.lock
Labels: milano, ready for release, improvement

#2415 [PLAY-514] Custom Tooltip Prop for Circle Chart
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.md
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/index.js
Labels: enhancement, milano, ready for release

#2403 Addresses critical security Active Record RCE bug #86 #87
  examples/playbook-rails-webpack/Gemfile.lock
  examples/playbook-rails/.gitignore
  examples/playbook-rails/Gemfile
  examples/playbook-rails/Gemfile.lock
  examples/playbook-rails/log/development.log
  examples/playbook-rails/tmp/.keep
  examples/playbook-rails/tmp/development_secret.txt
  examples/playbook-rails/tmp/pids/.keep
  examples/playbook-rails/tmp/restart.txt
  examples/playbook-rails/tmp/storage/.keep
  examples/rails-react-example/package.json
  examples/rails-react-example/yarn.lock
  examples/react-example/package.json
  examples/react-example/yarn.lock
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
Labels: dependencies, milano, ready for release
