Repository powerhome/playbook, pull requests merged in 2023-04, with the labels that each got.

#2423 [PLAY-706] Adding xxs to Flex gap, column gap and row gap
  playbook/app/pb_kits/playbook/pb_flex/_flex.scss
  playbook/app/pb_kits/playbook/pb_flex/_flex.tsx
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_gap.html.erb
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_gap.jsx
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_gap.md
  playbook/app/pb_kits/playbook/pb_flex/flex.rb
  playbook/spec/pb_kits/playbook/kits/flex_spec.rb
Labels: enhancement, milano, ready for release

#2421 [PLAY-679] Selectable List to Typescript
  playbook/app/pb_kits/playbook/pb_selectable_list/_item.jsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_item.tsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.tsx
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.test.js
Labels: enhancement, milano, ready for release

#2420 [PLAY-697] Updating Sandpack docs styles
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/javascript/components/KitDocs/index.tsx
  playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
  playbook-website/app/views/pages/kit_show_new.html.erb
Labels: milano, ready for release, improvement, alpha

#2426 [PLAY-686] Adding Position global prop
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Position.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Positioning.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/ZIndex.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/position_jsx.txt
  playbook-website/app/views/pages/code_snippets/position_token.txt
  playbook-website/app/views/pages/code_snippets/positioning_jsx.txt
  playbook-website/app/views/pages/code_snippets/z_index_jsx.txt
  playbook-website/app/views/pages/code_snippets/z_index_token.txt
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_layout/_layout.tsx
  playbook/app/pb_kits/playbook/tokens/_positioning.scss
  playbook/app/pb_kits/playbook/utilities/_positioning.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/position.rb
Labels: milano, ready for release, improvement

#2442 [PLAY-700] Adding Card Header support to striped colors
  playbook/app/pb_kits/playbook/pb_card/_card.scss
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_card/card_header.rb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.jsx
Labels: milano, ready for release, improvement

#2428 [PLAY-681] Change Star Rating Kit from JSX to TSX
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.test.js
Labels: enhancement, milano, ready for release

#2433 [PLAY-676] Updating Global Props Cursor values
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Cursor.tsx
  playbook-website/app/views/pages/code_snippets/cursor_jsx.txt
  playbook/app/pb_kits/playbook/utilities/_cursor.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/cursor.rb
Labels: milano, ready for release, improvement

#2446 [PLAY-729] 🛠️ Update Avatar kit imageAlt default
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.html.erb
  playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
Labels: enhancement, milano, ready for release

#2460 Rails / React Playground and React Render Rails Examples
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/KitDemo/index.tsx
  playbook-website/app/javascript/components/PbKitFetch/index.tsx
  playbook-website/app/javascript/components/PbKitPlayground/index.tsx
  playbook-website/app/javascript/components/PbKitReact/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Cursor.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
  playbook-website/app/views/layouts/fullscreen.html.erb
  playbook-website/app/views/layouts/fullscreen.html.slim
  playbook-website/app/views/layouts/rails_raw.html.erb
  playbook-website/app/views/pages/kit_show_demo.html.erb
  playbook-website/app/views/pages/rails_in_react.html.erb
  playbook-website/app/views/pages/rails_in_react_playground.html.erb
  playbook-website/config/routes.rb
  playbook-website/package.json
Labels: milano, improvement

#2463 [PLAY-400] 🐞 Icon Stat Value kit misalignment
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.tsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.html.erb
Labels: bug, milano, ready for release

#2458 [Play-701] new success sm token
  playbook/app/pb_kits/playbook/pb_badge/_badge.scss
  playbook/app/pb_kits/playbook/pb_badge/_badge.tsx
  playbook/app/pb_kits/playbook/pb_badge/badge.rb
  playbook/app/pb_kits/playbook/pb_badge/badge.test.js
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: enhancement, milano, ready for release

#2457 [PLAY-712] Converting Table kit to Typescript
  playbook/app/pb_kits/playbook/pb_enhanced_element/index.ts
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/_table_row.tsx
  playbook/app/pb_kits/playbook/pb_table/index.ts
Labels: enhancement, milano, ready for release

#2444 [PLAY-713] Convert kit to typescript
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.jsx
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.tsx
  playbook/app/pb_kits/playbook/pb_textarea/index.tsx
  playbook/app/pb_kits/playbook/pb_textarea/textarea.test.js
Labels: enhancement, milano, ready for release

#2456 [PLAY-616] Testing adding proxima nova to Sandpack
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/KitDocs/entryPoint.tsx
  playbook-website/app/javascript/components/KitDocs/index.tsx
  playbook-website/app/views/pages/kit_show_new.html.erb
Labels: milano, ready for release, improvement

#2475 [PLAY-739] Rebuild Getting Started
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/site_styles/_getting_started.scss
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/views/pages/getting_started.html.erb
  playbook-website/app/views/pages/getting_started/html.html.erb
  playbook-website/app/views/pages/getting_started/index.html.erb
  playbook-website/app/views/pages/getting_started/rails.html.erb
  playbook-website/app/views/pages/getting_started/rails_react.erb
  playbook-website/app/views/pages/getting_started/react.html.erb
  playbook-website/app/views/pages/getting_started_partials/_html_css_getting_started.md
  playbook-website/app/views/pages/getting_started_partials/_rails_getting_started.md
  playbook-website/app/views/pages/getting_started_partials/_rails_react_getting_started.md
  playbook-website/app/views/pages/getting_started_partials/_react_getting_started.md
  playbook-website/config/routes.rb
  playbook-website/public/images/getting_started/copy_html.png
Labels: milano, improvement

#2481 [Play-744] 🌐 Improve global props documentation in Rails
  playbook-website/app/javascript/site_styles/_kit_api.scss
  playbook-website/app/javascript/site_styles/main.scss
  playbook/app/pb_kits/playbook/pb_docs/kit_api.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_api.rb
Labels: milano, improvement

#2476 [PLAY-748] Restructure Visual Guidelines Page
  playbook-website/app/javascript/components/KitDocs/index.tsx
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/BorderRadius.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Cursor.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Display.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/javascript/site_styles/_visual_guidelines.scss
  playbook-website/app/views/layouts/_nav.html.erb
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/app/views/pages/visual_guidelines.html.erb
  playbook-website/config/routes.rb
Labels: milano, improvement

#2473 [PLAY-742] Add favicon
  playbook-website/app/views/layouts/application.html.erb
  playbook-website/app/views/layouts/kits.html.erb
  playbook-website/app/views/layouts/samples.html.erb
  playbook-website/app/views/layouts/visual_guidelines.html.erb
  playbook-website/public/images/pb-favicon.png
Labels: enhancement, milano

#2474 [PLAY-745] Implementing React Kit Props
  playbook-website/app/javascript/components/AvailableProps/globalProps.tsx
  playbook-website/app/javascript/components/AvailableProps/globalPropsValues.ts
  playbook-website/app/javascript/components/AvailableProps/index.tsx
  playbook-website/app/javascript/components/AvailableProps/kitProps.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/site_styles/_kits_show.scss
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/webpack/environment.js
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
  yarn.lock
Labels: milano, improvement

#2495 Revert "[PLAY-745] Implementing React Kit Props"
  playbook-website/app/javascript/components/AvailableProps/globalProps.tsx
  playbook-website/app/javascript/components/AvailableProps/globalPropsValues.ts
  playbook-website/app/javascript/components/AvailableProps/index.tsx
  playbook-website/app/javascript/components/AvailableProps/kitProps.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/site_styles/_kits_show.scss
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/webpack/environment.js
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
  yarn.lock
Labels: milano

#2496 Fix for broken datepicker page
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
  playbook/app/pb_kits/playbook/pb_image/docs/_default_image.jsx
Labels: bug, milano

#2488 [PLAY-731] Adding optional vertical borders to Table kit
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_vertical_border.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_vertical_border.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_vertical_border.scss
  playbook/app/pb_kits/playbook/pb_table/table.rb
Labels: milano, ready for release, improvement

#2486 [PLAY-762] Converting Timeline to Typescript
  playbook/app/pb_kits/playbook/pb_date_stacked/_date_stacked.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_item.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.tsx
  playbook/app/pb_kits/playbook/pb_timeline/timeline.test.js
Labels: enhancement, milano, ready for release

#2497 [PLAY-764] Adding styles tags to Body kit
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.html.erb
  playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.jsx
  playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.md
  playbook/app/pb_kits/playbook/pb_body/docs/example.yml
Labels: milano, ready for release, improvement
