Repository powerhome/playbook, pull requests merged in 2023-05, with the labels that each got.

#2465 Markdown repairs & re-enable smart markdown docs in Playbook
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/app/controllers/guides_controller.rb
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/javascript/site_styles/_getting_started.scss
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
  playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/guides/create_kit.html.slim
  playbook-website/app/views/guides/create_kit/_view_objects.html.md
  playbook-website/app/views/guides/design_guidelines.html.md
  playbook-website/app/views/guides/design_guidelines/example_markdown_styling.md
  playbook-website/app/views/guides/design_guidelines/file_naming.md
  playbook-website/app/views/guides/design_guidelines/generator.md
  playbook-website/app/views/guides/design_guidelines/kit_examples.md
  playbook-website/app/views/guides/design_guidelines/kit_rails.md
  playbook-website/app/views/guides/design_guidelines/kit_react.md
  playbook-website/app/views/guides/design_guidelines/layout.md
  playbook-website/app/views/guides/design_guidelines/writing_sass.md
  playbook-website/app/views/guides/use_nitro.html.erb
  playbook-website/app/views/guides/use_nitro.html.slim
  playbook-website/app/views/layouts/_docs_navigation.html.erb
  playbook-website/app/views/layouts/_footer.html.erb
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/app/views/layouts/grid.html.slim
  playbook-website/app/views/pages/changelog.html.erb
  playbook-website/app/views/pages/getting_started/html.html.erb
  playbook-website/app/views/pages/getting_started/rails.html.erb
  playbook-website/app/views/pages/getting_started/rails_react.erb
  playbook-website/app/views/pages/getting_started/react.html.erb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/app/views/pages/kit_show_new.html.erb
  playbook-website/config/application.rb
  playbook-website/config/initializers/markdown_template.rb
  playbook-website/config/routes.rb
  playbook/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
  playbook/lib/playbook/markdown.rb
  playbook/lib/playbook/markdown/helper.rb
  playbook/lib/playbook/markdown/template_handler.rb
  playbook/playbook_ui.gemspec
Labels: milano

#2435 [PLAY-693] Fixing Tooltip kit wrong backgrounds in Rails
  playbook/app/pb_kits/playbook/pb_avatar_action_button/avatar_action_button.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_white.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_with_icon_circle.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/example.yml
Labels: bug, milano, ready for release, alpha

#2445 [PLAY-736] Tiptap Variant For RTE
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_nav/_item.tsx
  playbook/app/pb_kits/playbook/pb_nav/_nav.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/EditorButton.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/EditorTypes.ts
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/Toolbar.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarDropdown.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarHistory.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarNodes.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_tiptap_styles.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_description.md
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_advanced_default.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_advanced_default.md
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
  yarn.lock
Labels: enhancement, milano, ready for release, alpha

#2510 [PLAY-784] Converting Toggle kit to Typescript
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.tsx
  playbook/app/pb_kits/playbook/pb_toggle/toggle.test.js
Labels: enhancement, milano, ready for release

#2508 [PLAY-783] Converting Title Detail kit to Typescript
  playbook/app/pb_kits/playbook/pb_title_detail/_title_detail.jsx
  playbook/app/pb_kits/playbook/pb_title_detail/_title_detail.tsx
  playbook/app/pb_kits/playbook/pb_title_detail/title_detail.test.js
Labels: enhancement, milano, ready for release

#2500 [PLAY-714] Converting Time Range Inline kit to TS
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.jsx
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.tsx
  playbook/app/pb_kits/playbook/pb_time_range_inline/time_range_inline.test.js
Labels: enhancement, milano, ready for release

#2464 [PLAY-673] Loop through all kits
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  playbook/spec/pb_kits/playbook/all_kits_spec.rb
Labels: milano, ready for release

#2487 [PLAY-770] 🌐 Update global props documentation in Rails
  playbook/app/pb_kits/playbook/pb_docs/kit_api.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_api.rb
  playbook/lib/playbook/number_spacing.rb
  playbook/lib/playbook/position.rb
  playbook/lib/playbook/spacing.rb
  playbook/lib/playbook/z_index.rb
Labels: milano, ready for release, improvement

#2511 [PLAY-782] Remove {...props}
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
Labels: milano, ready for release, improvement

#2513 [PLAY-788] Fix React Global Props Table
  playbook-website/app/javascript/components/AvailableProps/globalProps.tsx
  playbook-website/app/javascript/components/AvailableProps/globalPropsValues.ts
  playbook-website/app/javascript/components/AvailableProps/index.tsx
  playbook-website/app/javascript/components/AvailableProps/kitProps.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/site_styles/_kits_show.scss
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/webpack/environment.js
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
Labels: milano, ready for release, improvement

#2529 [NUXE-1381] Tooltip position prop
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
  playbook/app/pb_kits/playbook/pb_tooltip/tooltip.test.jsx
Labels: enhancement, milano, ready for release

#2535 [PLAY-747] 🪙 Add/Update tokens for Card (dark)
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: enhancement, milano, ready for release, alpha

#2524 [PLAY-789] Favicon for other devices
  playbook-website/app/views/layouts/application.html.erb
  playbook-website/app/views/layouts/kits.html.erb
  playbook-website/app/views/layouts/samples.html.erb
  playbook-website/app/views/layouts/visual_guidelines.html.erb
  playbook-website/public/images/pb-favicon-180.png
  playbook-website/public/images/pb-favicon-192.png
  playbook-website/public/images/pb-favicon-512.png
  playbook-website/public/images/pb-favicon.ico
  playbook-website/public/images/pb-favicon.png
  playbook-website/public/images/pb-favicon.svg
  playbook-website/public/site.webmanifest
Labels: milano, ready for release, improvement

#2546 [PLAY-753] Anchors Linking
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/site_styles/_changelog.scss
  playbook-website/app/javascript/site_styles/docs/_all.scss
  playbook-website/app/javascript/site_styles/docs/_links.scss
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/package.json
  yarn.lock
Labels: milano, ready for release, improvement

#2548 [PLAY-728] Fixes for SelectableCard Children overflowing Card
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.tsx
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.html.erb
Labels: bug, milano, ready for release

#2539 [PLAY-699] Making zIndex global prop responsive
  playbook-website/app/javascript/components/VisualGuidelines/Examples/ZIndex.tsx
  playbook-website/app/views/pages/code_snippets/z_index_jsx.txt
  playbook/app/pb_kits/playbook/utilities/_positioning.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/z_index.rb
Labels: milano, ready for release, improvement, alpha

#2534 [PLAY-785] Converting Typeahead kit to Typescript
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ClearIndicator.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Control.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/IndicatorsContainer.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MenuList.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MultiValue.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MultiValue.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Option.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Option.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Placeholder.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ValueContainer.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/index.ts
  playbook/app/pb_kits/playbook/pb_typeahead/types.d.ts
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  yarn.lock
Labels: enhancement, milano, ready for release, alpha

#2556 [PLAY-795] Converting Walkthrough kit to Typescript
  playbook/app/pb_kits/playbook/pb_walkthrough/_walkthrough.jsx
  playbook/app/pb_kits/playbook/pb_walkthrough/_walkthrough.tsx
Labels: enhancement, milano, ready for release

#2551 [PLAY-794] Converting User Badge kit to Typescript
  playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/million-dollar.jsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/million-dollar.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/veteran.jsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/veteran.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/user_badge.test.js
Labels: enhancement, milano, ready for release

#2564 Fixed addeventlistner console error by adding conditional
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
Labels: bug, milano

#2569 [PLAY-813] Fix Renovate Failures
  renovate.json
Labels: milano, improvement

#2560 [PLAY-807] Created extensions prop For advanced RTE
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/MoreExtensionsDropdown.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/Toolbar.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarDropdown.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_more_extensions.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_more_extensions.md
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
  yarn.lock
Labels: enhancement, milano, ready for release, alpha

#2571 [PLAY-816] Convert WeekdayStacked to TS + Jest Tests
  playbook/app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.tsx
  playbook/app/pb_kits/playbook/pb_weekday_stacked/weekday_stacked.test.jsx
Labels: enhancement, milano, ready for release

#2575 [PLAY-834] Fixes for darkmode Styling of TextInput
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
Labels: bug, milano, ready for release

#2559 Title 2 Defaults to Bold
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.md
Labels: enhancement, milano, ready for release, alpha, release 2

#2563 [PLAY-698] responsive Spacing global prop
  playbook-website/app/javascript/components/AvailableProps/globalPropsValues.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/SpacingProps.tsx
  playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
  playbook-website/app/views/pages/code_snippets/spacing_global_props_jsx.txt
  playbook/app/pb_kits/playbook/tokens/_screen_sizes.scss
  playbook/app/pb_kits/playbook/utilities/_spacing.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/spacing.rb
Labels: milano, ready for release, improvement, alpha, release 2

#2550 [PLAY-806] Creating an example Swift kit doc
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/routes.rb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_swift.md
  playbook/app/pb_kits/playbook/pb_avatar/docs/example.yml
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
  playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
  playbook/lib/playbook/pb_doc_helper.rb
Labels: milano, ready for release, improvement, release 2
