Repository powerhome/playbook, pull requests merged in 2023-12, with the labels that each got.

#2876 [PBIOS-170] Docs: Multiple Users
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_default_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_props_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_reverse_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_size_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users/docs/example.yml
Labels: ready for release, improvement, swiftUI

#2882 [PBIOS-172] Docs: Multiple Users Stacked
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_default_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_props_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_small_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_xsmall_swift.md
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/example.yml
Labels: ready for release, improvement, swiftUI

#2887 [PBIOS-182] Docs: Text Input
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on_swift.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_default_swift.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_disabled_swift.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error_swift.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_props_swift.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
Labels: ready for release, improvement, swiftUI

#2892 Safe check for type var
  playbook-website/app/views/pages/kit_show_new.html.erb
Labels: bug, milano

#2934 [PLAY-1087] Scripts for Quicker Release Formatting
  playbook/changelog.rb
  playbook/connect.rb
Labels: milano, ready for release, improvement

#2927 [PBNTR-149] Update Filter Docs for "No Filter Selected"
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.md
Labels: ready for release, improvement

#2924 [PLAY-1081] Adding declaration files
  playbook/package.json
  playbook/tsconfig.json
Labels: enhancement, milano, ready for release, alpha

#2899 [PLAY-1008] Website PS2 - Components - Index Navigation & Cards
  playbook-website/app/javascript/components/Website/src/components/CategoryTitle/index.tsx
  playbook-website/app/javascript/components/Website/src/components/CategoryTitle/styles.scss
  playbook-website/app/javascript/components/Website/src/components/Hero/index.tsx
  playbook-website/app/javascript/components/Website/src/components/Hero/styles.scss
  playbook-website/app/javascript/components/Website/src/components/HeroImage.tsx
  playbook-website/app/javascript/components/Website/src/components/KitCard/index.tsx
  playbook-website/app/javascript/components/Website/src/components/KitCard/styles.scss
  playbook-website/app/javascript/components/Website/src/components/KitGrid/index.tsx
  playbook-website/app/javascript/components/Website/src/components/KitGrid/styles.scss
  playbook-website/app/javascript/components/Website/src/components/PageContainer/index.tsx
  playbook-website/app/javascript/components/Website/src/hooks/loaders.js
  playbook-website/app/javascript/components/Website/src/hooks/loaders.ts
  playbook-website/app/javascript/components/Website/src/layouts/LayoutRight.tsx
  playbook-website/app/javascript/components/Website/src/pages/CategoryShow/index.tsx
  playbook-website/app/javascript/components/Website/src/pages/CategoryShow/styles.scss
  playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
  playbook-website/app/javascript/images/pb-hero-desktop.svg
  playbook-website/app/javascript/images/pb-hero-mobile.svg
  playbook-website/app/javascript/images/pb_generic_header_desktop.jpg
  playbook-website/app/javascript/packs/app.js
  playbook-website/app/javascript/utilities/website_sidebar_helper.ts
  playbook-website/config/menu.yml
Labels: milano, improvement

#2959 13.13.0 Changelog
  playbook/CHANGELOG.md
Labels: milano

#2933 [PBIOS-228] Docs: Contact
  playbook/app/pb_kits/playbook/pb_contact/docs/_contact_default_swift.md
  playbook/app/pb_kits/playbook/pb_contact/docs/_contact_props_swift.md
  playbook/app/pb_kits/playbook/pb_contact/docs/_contact_with_detail_swift.md
  playbook/app/pb_kits/playbook/pb_contact/docs/example.yml
Labels: ready for release, improvement, swiftUI

#2946 [PBIOS-229] Docs: HomeStreetAddress
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default_swift.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis_swift.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_link_swift.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_modified_swift.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_props_swift.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml
Labels: ready for release, improvement, swiftUI

#2935 [PLAY-880] 🐞 Card kit highlight z-index error
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
Labels: bug, milano, ready for release, alpha

#2945 [PLAY-1090] Exporting CSS Tokens
  playbook/app/pb_kits/playbook/index.js
Labels: milano, ready for release, improvement, alpha

#2952 [PLAY-1097] Removing ESLint disable tag from Enhanced Element
  playbook/app/pb_kits/playbook/pb_enhanced_element/element_observer.ts
  playbook/app/pb_kits/playbook/pb_enhanced_element/index.ts
Labels: milano, ready for release, improvement, alpha

#2972 Update CHANGELOG.md 13.14.0
  playbook/CHANGELOG.md
Labels: milano

#2898 [PBIOS-187] Docs: User
  playbook/app/pb_kits/playbook/pb_user/docs/_user_horizontal_swift.md
  playbook/app/pb_kits/playbook/pb_user/docs/_user_props_table.md
  playbook/app/pb_kits/playbook/pb_user/docs/_user_size_swift.md
  playbook/app/pb_kits/playbook/pb_user/docs/_user_text_only_swift.md
  playbook/app/pb_kits/playbook/pb_user/docs/_user_vertical_size_swift.md
  playbook/app/pb_kits/playbook/pb_user/docs/example.yml
Labels: milano, ready for release, improvement, swiftUI

#2953 [PBIOS-227] Docs: Person
  playbook/app/pb_kits/playbook/pb_person/docs/_person_default_swift.md
  playbook/app/pb_kits/playbook/pb_person/docs/_person_props_swift.md
  playbook/app/pb_kits/playbook/pb_person/docs/example.yml
Labels: ready for release, improvement, swiftUI

#2978 Ready Playbook web for Swift!
  playbook-website/app/components/hp_solutions_component.html.erb
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuildesNavItems.ts
  playbook-website/app/javascript/images/hp-swift-solutions.svg
  playbook-website/app/views/guides/_docs_index_list.html.erb
  playbook-website/app/views/guides/getting_started/rails_&_react_setup.md
  playbook-website/app/views/guides/getting_started/swift_setup.md
  playbook-website/app/views/pages/kit_category_show.html.erb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/app/views/pages/kits.html.erb
  playbook-website/app/views/samples/show.html.erb
Labels: milano, improvement
