Repository powerhome/playbook, pull requests merged in 2023-06, with the labels that each got.

#2585 Update CODEOWNERS
  .github/CODEOWNERS
Labels: milano

#2584 Repair incorrect Proxima Nova font settings
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Black-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Black.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Bold-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Bold.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Light-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Light.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Reg-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Reg.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Sbold-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Sbold.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Thin-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Thin.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Xbold-It.woff
  playbook-website/app/javascript/site_styles/fonts/Proxima-Nova-Xbold.woff
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Black.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-BlackIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Bold.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-BoldIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Extrabld.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-ExtrabldIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Light.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-LightIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Regular.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-RegularIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Semibold.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-SemiboldIt.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-Thin.woff2
  playbook-website/app/javascript/site_styles/fonts/ProximaNova-ThinIt.woff2
  playbook-website/app/javascript/site_styles/fonts/_site-fonts.scss
  playbook-website/app/views/layouts/application.html.erb
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/app/views/layouts/visual_guidelines.html.erb
Labels: milano

#2587 Update portal.yml ux-team > playbook-web
  portal.yml
Labels: milano

#2588 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#2591 Fix up change log to look better
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/site_styles/_changelog.scss
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/app/views/pages/changelog.html.erb
  playbook/CHANGELOG.md
Labels: milano

#2579 [PLAY-833] bold option for title 3
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/title.rb
  playbook/app/pb_kits/playbook/pb_title/title.test.js
  playbook/spec/pb_kits/playbook/kits/title_spec.rb
Labels: enhancement, milano, ready for release, alpha, release 2

#2592 [PLAY-839] Unstyled Date and Time Kits
  playbook/app/pb_kits/playbook/pb_date/_date.tsx
  playbook/app/pb_kits/playbook/pb_date/date.html.erb
  playbook/app/pb_kits/playbook/pb_date/date.rb
  playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.html.erb
  playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.jsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.md
  playbook/app/pb_kits/playbook/pb_date/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date/docs/index.js
  playbook/app/pb_kits/playbook/pb_time/_time.tsx
  playbook/app/pb_kits/playbook/pb_time/docs/_time_unstyled.html.erb
  playbook/app/pb_kits/playbook/pb_time/docs/_time_unstyled.jsx
  playbook/app/pb_kits/playbook/pb_time/docs/_time_unstyled.md
  playbook/app/pb_kits/playbook/pb_time/docs/example.yml
  playbook/app/pb_kits/playbook/pb_time/docs/index.js
  playbook/app/pb_kits/playbook/pb_time/time.html.erb
  playbook/app/pb_kits/playbook/pb_time/time.rb
Labels: enhancement, milano, ready for release

#2593 Bump ci-kubed@v6.7.0
  Jenkinsfile
Labels: milano

#2601 Fix for Broken bread_crumb Rails Page on Website
  playbook-website/app/components/playbook/pb_docs/kit_api.html.erb
Labels: bug, milano

#2600 Correct broken swift markdown docs
  playbook-website/app/components/playbook/pb_docs/kit_example.html.erb
  playbook-website/app/components/playbook/pb_docs/kit_example.rb
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/lib/pb_doc_helper.rb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_swift.md
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
Labels: milano

#2583 [PLAY-843] Kit mashup page for handoffs
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/site_styles/_kits_show.scss
  playbook-website/app/views/pages/kit_collection.html.erb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/routes.rb
Labels: milano, ready for release, improvement

#2596 [PLAY-733] Detail Kit
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_detail/_detail.scss
  playbook/app/pb_kits/playbook/pb_detail/_detail.tsx
  playbook/app/pb_kits/playbook/pb_detail/_detail_mixins.scss
  playbook/app/pb_kits/playbook/pb_detail/detail.html.erb
  playbook/app/pb_kits/playbook/pb_detail/detail.rb
  playbook/app/pb_kits/playbook/pb_detail/detail.test.jsx
  playbook/app/pb_kits/playbook/pb_detail/docs/_description.md
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_bold.html.erb
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_bold.jsx
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_bold.md
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_colors.html.erb
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_colors.jsx
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_colors.md
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_default.html.erb
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_default.jsx
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_styled.html.erb
  playbook/app/pb_kits/playbook/pb_detail/docs/_detail_styled.jsx
  playbook/app/pb_kits/playbook/pb_detail/docs/example.yml
  playbook/app/pb_kits/playbook/pb_detail/docs/index.js
  playbook/app/pb_kits/playbook/playbook-doc.js
  playbook/spec/pb_kits/playbook/kits/detail_spec.rb
Labels: new kit, milano, ready for release, alpha

#2578 [PLAY-818] MultiLevelSelect Refactor
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.scss
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_select_helper.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/helper_functions.ts
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.test.jsx
  playbook/package.json
  yarn.lock
Labels: enhancement, milano, ready for release, alpha

#2610 Fixes Alpha Script
  .github/workflows/github-actions-alpha-version.yml
Labels: milano, improvement, alpha

#2611 Correct page name / titleize bug
  playbook-website/app/controllers/guides_controller.rb
Labels: milano

#2612 Fixes for MultiLevelSelect as tested in Nitro
  playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
Labels: bug, milano, alpha

#2617 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#2616 [PLAY-878] Add CSS for Changelog Dates
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/guides/design_guidelines/example_markdown_styling.md
  playbook/CHANGELOG.md
Labels: milano, ready for release, improvement

#2598 [PLAY-822] Bold default for Title 3
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.md
  playbook/app/pb_kits/playbook/pb_title/title.rb
  playbook/app/pb_kits/playbook/pb_title/title.test.js
  playbook/spec/pb_kits/playbook/kits/title_spec.rb
Labels: enhancement, milano, ready for release, alpha

#2609 [PLAY-865] Font weight tokens updates
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
  playbook-website/app/javascript/site_styles/docs/_color_utilities.scss
  playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
  playbook-website/app/javascript/site_styles/visual_guidelines/_line_height_guidelines.scss
  playbook-website/app/javascript/site_styles/visual_guidelines/_spacing_tokens.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_flatpickr_styles.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_month_and_year_styles.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_week_styles.scss
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_trix_styles.scss
Labels: milano, ready for release, improvement

#2590 [PLAY-871] MultiSelect Rails
  playbook-website/Gemfile
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_with_form.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
  playbook/lib/playbook/forms/builder.rb
  playbook/lib/playbook/forms/builder/multi_level_select_field.rb
Labels: enhancement, milano, ready for release, alpha

#2582 [PLAY-824] Phone Number Kit Validation
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_validation.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_validation.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.test.js
  playbook/app/pb_kits/playbook/utilities/object.ts
  playbook/lib/playbook/forms/builder.rb
  playbook/lib/playbook/forms/builder/intl_telephone_field.rb
  playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
  playbook/spec/support/playbook/rspec.rb
Labels: enhancement, react, rails, ready for release, alpha

#2621 [PLAY-889] Fixed Expanded State to Load From TreeData
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.jsx
Labels: bug, milano, ready for release, alpha

#2620 [PLAY-779] Implementing custom icons for Selectable Card Icon kit
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_custom.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_custom.jsx
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_custom.md
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/example.yml
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/index.js
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.rb
  playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
Labels: enhancement, milano, ready for release

#2613 [PLAY-860] Access Phone Number Input Kit's Input Attributes
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_access_input_element.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_access_input_element.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_clear_field.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_clear_field.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js
Labels: enhancement, milano, ready for release, alpha

#2625 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano
