Repository powerhome/playbook, pull requests merged in 2023-09, with the labels that each got.

#2726 Update CHANGELOG.md 13.2.0
  playbook/CHANGELOG.md
Labels: milano

#2699 [PBNTR-77] Table kit sortable columns
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_table_header.scss
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_header.rb
  playbook/spec/pb_kits/playbook/kits/table_header_spec.rb
Labels: new kit, milano, ready for release

#2708 [PLAY-929] Website V1 - Homepage - What's New
  docs/CHANGELOG_ARCHIVE.md
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/helpers/changelog_helper.rb
  playbook-website/app/views/pages/home.html.erb
  playbook/CHANGELOG.md
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/_body.tsx
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_body/body.rb
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/_title_mixin.scss
  playbook/app/pb_kits/playbook/pb_title/title.rb
Labels: milano, ready for release, improvement

#2727 [PLAY-934] Convert Website Sidebar to React
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/packs/main_sidebar.js
  playbook-website/app/javascript/types.d.ts
  playbook-website/app/javascript/utilities/website_sidebar_helper.ts
  playbook-website/app/views/layouts/_sidebar.html.erb
Labels: milano, ready for release, improvement

#2732 [PLAY-975] Unstyled Timestamp Kit
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.tsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_unstyled.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_unstyled.jsx
  playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_unstyled.md
  playbook/app/pb_kits/playbook/pb_timestamp/docs/example.yml
  playbook/app/pb_kits/playbook/pb_timestamp/docs/index.js
  playbook/app/pb_kits/playbook/pb_timestamp/timestamp.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/timestamp.rb
Labels: enhancement, milano, ready for release

#2695 [PLAY-886] Homepage - Solutions and Global Prop Edits + Additions
  playbook-website/app/components/hp_solutions_component.html.erb
  playbook-website/app/components/hp_solutions_component.rb
  playbook-website/app/components/lg_hp_social_proof_component.html.erb
  playbook-website/app/components/md_hp_social_proof_component.html.erb
  playbook-website/app/components/sm_hp_social_proof_component.html.erb
  playbook-website/app/javascript/components/AvailableProps/globalPropsValues.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx
  playbook-website/app/javascript/images/hp-htmlcss-solutions.svg
  playbook-website/app/javascript/images/hp-rails-solutions.svg
  playbook-website/app/javascript/images/hp-react-solutions.svg
  playbook-website/app/javascript/packs/imageComparsionSlider.js
  playbook-website/app/javascript/site_styles/_landing-page-solutions.scss
  playbook-website/app/javascript/site_styles/_landing-page.scss
  playbook-website/app/views/pages/code_snippets/spacing_global_props_jsx.txt
  playbook-website/app/views/pages/home.html.erb
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/tokens/_spacing.scss
  playbook/app/pb_kits/playbook/tokens/_text_align.scss
  playbook/app/pb_kits/playbook/types/sizes.ts
  playbook/app/pb_kits/playbook/utilities/_max_width.scss
  playbook/app/pb_kits/playbook/utilities/_spacing.scss
  playbook/app/pb_kits/playbook/utilities/_text_align.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/spacing.rb
  playbook/lib/playbook/text_align.rb
Labels: milano, ready for release, improvement

#2729 [PLAY-1000] Collapsible Nav in Website Sidebar
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.tsx
Labels: milano, ready for release, improvement

#2725 [PLAY-943] Website V1 - Site Footer
  playbook-website/app/javascript/images/power-subtract-logo.svg
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/views/layouts/_footer.html.erb
  playbook/app/pb_kits/playbook/pb_button/button.html.erb
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_two_actions.jsx
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/hover.rb
Labels: milano, ready for release, improvement

#2735 [PLAY-971] Add Sentry to Playbook
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/config/deploy/production/secrets.yaml
  playbook-website/config/deploy/prs/secrets.yaml
  playbook-website/config/deploy/staging/secrets.yaml
  playbook-website/config/deploy/templates/deployment.yaml.erb
  playbook-website/config/deploy/templates/secret.yaml.erb
  playbook-website/config/initializers/sentry.rb
Labels: milano, improvement

#2741 Update CHANGELOG.md 13.4.0
  playbook/CHANGELOG.md
Labels: milano

#2723 [PBNTR-85] Col and Colgroup table kits
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_background_kit.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_background_kit.jsx
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
Labels: milano, ready for release, improvement

#2734 [PLAY-970] Website - Changelog updates
  docs/CHANGELOG_ARCHIVE.md
  playbook-website/app/javascript/site_styles/docs/_all.scss
  playbook-website/app/javascript/site_styles/docs/_changelog.scss
  playbook-website/app/views/pages/changelog.html.erb
  playbook/CHANGELOG.md
Labels: milano, ready for release, improvement

#2740 [PLAY-937] Text Align Global Prop Docs
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/TextAlign.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/text_align_jsx.txt
Labels: milano, ready for release, improvement

#2747 Performance Fix Rollback
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/pages/changelog.html.erb
  playbook-website/app/views/pages/home.html.erb
Labels: milano

#2748 Update CHANGELOG.md 13.5.0
  playbook/CHANGELOG.md
Labels: milano

#2749 [PLAY-1001] Sidebar Collapsible Nav Optimization
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/MainSidebar/NestedNavItems.tsx
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook/app/pb_kits/playbook/pb_nav/_collapsible_nav.scss
Labels: milano, ready for release, improvement

#2744 [PLAY-823] Global Prop Overflow
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Overflow.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/SpacingProps.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/overflow_jsx.txt
  playbook-website/app/views/pages/code_snippets/overflow_token.txt
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.scss
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.tsx
  playbook/app/pb_kits/playbook/pb_flex/flex_item.rb
  playbook/app/pb_kits/playbook/tokens/_overflow.scss
  playbook/app/pb_kits/playbook/utilities/_overflow.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/overflow.rb
  playbook/spec/pb_kits/playbook/kits/flex_item_spec.rb
Labels: enhancement, milano, ready for release, alpha

#2738 [PBNTR-89] Table Header Improvements
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_header.md
  playbook/app/pb_kits/playbook/pb_table/styles/_table_header.scss
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_header.rb
  playbook/spec/pb_kits/playbook/kits/table_header_spec.rb
Labels: milano, ready for release, improvement

#2742 [PLAY-973] Prevent Conflicts with Ruby's Hash
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.rb
  playbook/app/pb_kits/playbook/pb_dashboard_value/dashboard_value.rb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.rb
  playbook/app/pb_kits/playbook/pb_file_upload/file_upload.rb
  playbook/app/pb_kits/playbook/pb_passphrase/passphrase.rb
  playbook/app/pb_kits/playbook/pb_radio/radio.rb
  playbook/app/pb_kits/playbook/pb_select/select.rb
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
  playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.rb
  playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
  playbook/app/pb_kits/playbook/pb_source/source.rb
  playbook/app/pb_kits/playbook/pb_text_input/text_input.rb
  playbook/app/pb_kits/playbook/pb_toggle/toggle.rb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/props/hash.rb
  playbook/spec/pb_kits/playbook/kits/card_spec.rb
  playbook/spec/pb_kits/playbook/kits/dashboard_value_spec.rb
  playbook/spec/pb_kits/playbook/kits/date_picker_spec.rb
  playbook/spec/pb_kits/playbook/kits/file_upload_spec.rb
  playbook/spec/pb_kits/playbook/kits/source_spec.rb
  playbook/spec/pb_kits/playbook/kits/typeahead_spec.rb
  playbook/spec/playbook/props/hash_spec.rb
  playbook/spec/support/playbook/rspec.rb
Labels: bug, milano, ready for release, alpha

#2739 [PLAY-961] Turn off Rails deprecation warnings
  playbook/app/pb_kits/playbook/pb_body/_body.tsx
  playbook/app/pb_kits/playbook/pb_caption/_caption.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.tsx
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/props/base.rb
Labels: milano, ready for release, alpha

#2733 [PLAY-992] Updating Markdown to support headers and index
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/app/components/lg_hp_social_proof_component.html.erb
  playbook-website/app/components/md_hp_social_proof_component.html.erb
  playbook-website/app/components/sm_hp_social_proof_component.html.erb
  playbook-website/app/controllers/guides_controller.rb
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/javascript/images/pb_generic_header.jpg
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/views/guides/_docs_index_list.html.erb
  playbook-website/app/views/guides/_getting_started_selections.html.erb
  playbook-website/app/views/guides/getting_started.html.md
  playbook-website/app/views/guides/getting_started/HTML_&_CSS.md
  playbook-website/app/views/guides/getting_started/rails_&_react_setup.md
  playbook-website/app/views/guides/getting_started/react_setup.md
  playbook-website/app/views/guides/getting_started/ruby_on_rails_setup.md
  playbook-website/app/views/layouts/_docs_navigation.html.erb
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/config/initializers/global_variables.rb
  playbook-website/lib/markdown_helper.rb
Labels: milano, ready for release, improvement

#2753 Update CHANGELOG.md 13.6.0
  playbook/CHANGELOG.md
Labels: milano

#2750 [PLAY-996] Body and Title Truncate Docs + Prevent Class Name Clash
  playbook/app/pb_kits/playbook/pb_body/docs/_body_truncate.html.erb
  playbook/app/pb_kits/playbook/pb_body/docs/_body_truncate.jsx
  playbook/app/pb_kits/playbook/pb_body/docs/_body_truncate.md
  playbook/app/pb_kits/playbook/pb_body/docs/example.yml
  playbook/app/pb_kits/playbook/pb_body/docs/index.js
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/_title_mixin.scss
  playbook/app/pb_kits/playbook/pb_title/docs/_title_truncate.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_truncate.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_truncate.md
  playbook/app/pb_kits/playbook/pb_title/docs/example.yml
  playbook/app/pb_kits/playbook/pb_title/docs/index.js
  playbook/app/pb_kits/playbook/pb_title/title.rb
Labels: milano, ready for release, improvement

#2751 [PLAY-984] Collapsible kit hides tooltip
  playbook/app/pb_kits/playbook/pb_collapsible/_helper_functions.ts
  playbook/app/pb_kits/playbook/pb_collapsible/index.js
Labels: bug, milano, ready for release, alpha

#2757 testing fix for Nitro tiptap issue
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/EditorButton.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/MoreExtensionsDropdown.tsx
Labels: bug, milano, ready for release, alpha

#2758 Requesting More CPU
  playbook-website/config/deploy/production/values.yaml
  playbook-website/config/deploy/templates/deployment.yaml.erb
  playbook-website/config/deploy/templates/partials/resources.yaml.erb
Labels: milano

#2760 Adding Profiler to Debug Performance
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/app/controllers/application_controller.rb
Labels: milano

#2759 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#2766 [PBNTR-95] Make style improvements
  playbook/app/pb_kits/playbook/pb_nav/_item.tsx
  playbook/app/pb_kits/playbook/pb_nav/_nav_item.test.js
  playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss
  playbook/app/pb_kits/playbook/pb_nav/item.rb
  playbook/app/pb_kits/playbook/pb_table/styles/_table_header.scss
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
  playbook/spec/pb_kits/playbook/kits/nav_item_spec.rb
Labels: milano, ready for release, improvement

#2755 [PLAY-987] Unstyled Currency Kit + Fix Variants and Emphasize False
  playbook/app/pb_kits/playbook/pb_currency/_currency.scss
  playbook/app/pb_kits/playbook/pb_currency/_currency.tsx
  playbook/app/pb_kits/playbook/pb_currency/currency.html.erb
  playbook/app/pb_kits/playbook/pb_currency/currency.rb
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_unstyled.html.erb
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_unstyled.jsx
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_unstyled.md
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_variants.html.erb
  playbook/app/pb_kits/playbook/pb_currency/docs/example.yml
  playbook/app/pb_kits/playbook/pb_currency/docs/index.js
Labels: enhancement, milano, ready for release

#2754 [PLAY-1007] Website Sidebar Consolidation
  playbook-website/app/controllers/guides_controller.rb
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/controllers/samples_controller.rb
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuildesNavItems.ts
  playbook-website/app/javascript/components/MainSidebar/MenuData/SidebarNavItems.ts
  playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/images/pb-logo-mobile.svg
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/javascript/packs/react_sidebar.js
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/javascript/types.d.ts
  playbook-website/app/views/layouts/_mobile_nav.html.erb
  playbook-website/app/views/layouts/_nav.html.erb
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/app/views/layouts/application.html.erb
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/app/views/pages/kit_category_show.html.erb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/app/views/pages/kits.html.erb
  playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss
Labels: enhancement, milano, ready for release

#2765 [PLAY-1011] Added Changelog Previews to Homepage
  playbook-website/app/components/preview_card_component.html.erb
  playbook-website/app/components/preview_card_component.rb
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/changelog_helper.rb
  playbook-website/app/views/pages/home.html.erb
Labels: milano, ready for release

#2768 Upgrade deprecated kube resource API versions
  playbook-website/config/deploy/templates/ingress.yaml.erb
Labels: milano
