Repository powerhome/playbook, pull requests merged in 2023-07, with the labels that each got.

#2626 [PLAY-837] Map Custom Button
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_map/_map.scss
  playbook/app/pb_kits/playbook/pb_map/_map.tsx
  playbook/app/pb_kits/playbook/pb_map/_map_controls.tsx
  playbook/app/pb_kits/playbook/pb_map/_map_custom_button.tsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_with_custom_button.jsx
  playbook/app/pb_kits/playbook/pb_map/docs/_map_with_custom_button.md
  playbook/app/pb_kits/playbook/pb_map/docs/example.yml
  playbook/app/pb_kits/playbook/pb_map/docs/index.js
Labels: enhancement, milano, ready for release, alpha

#2407 [Play-603] Quick Pick with Input and Preset Dropdown
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.scss
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.rb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.test.js
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_rails.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_rails.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_range_limit.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_range_limit.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_range_limit.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_react.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_react.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/quickPick.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_calendar_input_icon.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_quick_pick_styles.scss
  playbook/app/pb_kits/playbook/pb_nav/_item.tsx
  playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss
Labels: enhancement, milano, ready for release, alpha

#2632 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#2602 Use Docker Bake
  .dockerignore
  Dockerfile
  Jenkinsfile
  docker-bake.hcl
Labels: milano, alpha

#2628 [PLAY-863] MultiLevelSelect: expansion improvement and no pills option
  playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.scss
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
Labels: enhancement, milano, ready for release, alpha

#2629 [PLAY-737] 🛠️ Tighter spacing for dataTables
  playbook/app/pb_kits/playbook/pb_table/docs/_table_data_table.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_data_table.md
  playbook/app/pb_kits/playbook/pb_table/styles/_structure.scss
Labels: enhancement, milano, ready for release

#2631 [PLAY-802] Implementing Responsive Title
  playbook/app/pb_kits/playbook/pb_label_value/label_value.test.js
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.md
  playbook/app/pb_kits/playbook/pb_title/docs/example.yml
  playbook/app/pb_kits/playbook/pb_title/docs/index.js
  playbook/app/pb_kits/playbook/pb_title/title.rb
  playbook/app/pb_kits/playbook/pb_title/title.test.js
  playbook/spec/pb_kits/playbook/kits/title_spec.rb
Labels: enhancement, milano, ready for release

#2633 [PLAY-903] Circle Icon with Emojis
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/icon.html.erb
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.tsx
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_color.html.erb
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_default.html.erb
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_emoji.html.erb
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_emoji.jsx
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_emoji.md
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_sizes.html.erb
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_sizes.jsx
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon_circle/docs/index.js
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.html.erb
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.rb
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.test.js
Labels: enhancement, milano, ready for release

#2634 Fix `flexGrow={0}`, `flexShrink={0}`
  playbook/app/pb_kits/playbook/types/base.ts
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/app/pb_kits/playbook/utilities/test/globalProps/flexGrow.test.js
  playbook/app/pb_kits/playbook/utilities/test/globalProps/flexShrink.test.js
Labels: bug, milano, ready for release

#2643 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#2639 [PLAY-906] MultiLevel: Added New selectedIds Prop
  playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
Labels: enhancement, milano, ready for release, alpha

#2640 [PLAY-901] Adding new dashed section separator
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children.jsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_dashed.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_dashed.jsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.jsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/example.yml
  playbook/app/pb_kits/playbook/pb_section_separator/docs/index.js
  playbook/app/pb_kits/playbook/pb_section_separator/section_separator.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/section_separator.rb
  playbook/spec/pb_kits/playbook/kits/section_seperator_spec.rb
Labels: enhancement, milano, ready for release

#2642 [PLAY-909] Implementing Responsive Title
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.md
  playbook/app/pb_kits/playbook/pb_title/docs/example.yml
  playbook/app/pb_kits/playbook/pb_title/docs/index.js
  playbook/app/pb_kits/playbook/pb_title/title.rb
  playbook/app/pb_kits/playbook/pb_title/title.test.js
  playbook/spec/pb_kits/playbook/kits/title_spec.rb
Labels: enhancement, milano, ready for release, alpha

#2644 [PLAY-864] - Global Hover Prop
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_button/docs/_button_hover.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_button/docs/index.js
  playbook/app/pb_kits/playbook/pb_message/docs/_message_default.jsx
  playbook/app/pb_kits/playbook/pb_message/docs/_message_hover.jsx
  playbook/app/pb_kits/playbook/pb_message/docs/example.yml
  playbook/app/pb_kits/playbook/pb_message/docs/index.js
  playbook/app/pb_kits/playbook/tokens/_scale.scss
  playbook/app/pb_kits/playbook/tokens/exports/_scale.scss
  playbook/app/pb_kits/playbook/utilities/_border_radius.scss
  playbook/app/pb_kits/playbook/utilities/_colors.scss
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
Labels: enhancement, milano, ready for release, alpha

#2646 Update CHANGELOG.md for 12.31.0
  playbook/CHANGELOG.md
Labels: milano

#2648 [PLAY-918] DatePicker Disabled Dates Conflict
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
Labels: bug, milano, ready for release, alpha

#2649 [PLAY-920] MultiLevelSelect: Designs for no pills Variant
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.scss
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
Labels: enhancement, milano, ready for release, alpha

#2651 [PLAY-910] Adding children prop to Fixed Confirmation Toast
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.tsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children.html.erb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.html.erb
Labels: enhancement, milano, ready for release

#2656 12.32.0 Changelog
  playbook/CHANGELOG.md
Labels: milano

#2659 [PLAY-912] 🌐 kit_collection: add kit + global props table to Rails page
  playbook-website/app/views/pages/kit_collection.html.erb
Labels: milano, ready for release, improvement

#2655 [PLAY-881] Fixing the map kit button height for Safari
  playbook/app/pb_kits/playbook/pb_map/_map.scss
Labels: bug, milano, ready for release

#2641 [PLAY-884] 🌐 Website V1 - Homepage - Social Proof
  playbook-website/app/components/lg_hp_social_proof_component.erb
  playbook-website/app/components/lg_hp_social_proof_component.rb
  playbook-website/app/components/md_hp_social_proof_component.erb
  playbook-website/app/components/md_hp_social_proof_component.rb
  playbook-website/app/components/sm_hp_social_proof_component.html.erb
  playbook-website/app/components/sm_hp_social_proof_component.rb
  playbook-website/app/javascript/images/hp-social-proof-background.png
  playbook-website/app/javascript/site_styles/_landing-page.scss
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/app/views/pages/home.html.erb
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
  playbook/app/pb_kits/playbook/pb_background/background.html.erb
  playbook/app/pb_kits/playbook/pb_background/background.rb
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.tsx
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.rb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.tsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_color.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_color.jsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.rb
  playbook/app/pb_kits/playbook/tokens/_colors.scss
  playbook/app/pb_kits/playbook/utilities/_border_radius.scss
  playbook/app/pb_kits/playbook/utilities/_line_height.scss
  playbook/app/pb_kits/playbook/utilities/_shadow.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/spec/pb_kits/playbook/kits/background_spec.rb
  playbook/spec/pb_kits/playbook/kits/icon_circle_spec.rb
  playbook/spec/pb_kits/playbook/kits/icon_stat_value_spec.rb
Labels: milano, ready for release, improvement

#2657 [PBNTR-65] Center Align Text for Status Dialogs
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
Labels: enhancement, milano, ready for release

#2650 Refactor Dialog Kit Close on Outside Click
  playbook/app/pb_kits/playbook/pb_dialog/dialogHelper.js
Labels: enhancement, milano, ready for release

#2647 [PLAY-872] Self-Hosted Custom Font Enablement (RAILS and REACT)
  playbook-website/app/components/playbook/pb_docs/kit_example.rb
  playbook-website/app/javascript/scripts/custom-icons.js
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_fa_kit.html.erb
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_fa_kit.jsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_fa_kit.md
  playbook/app/pb_kits/playbook/pb_icon/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon/docs/index.js
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
Labels: enhancement, milano, ready for release, alpha

#2627 [PLAY-814]📦 Remove moment.js
  playbook/app/pb_kits/playbook/pb_date/_date.tsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_alignment.jsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_default.jsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.jsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_variants.jsx
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.tsx
  playbook/app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_stacked/_date_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_time/_date_time.tsx
  playbook/app/pb_kits/playbook/pb_date_time/dateTime.test.js
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.tsx
  playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.test.js
  playbook/app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.tsx
  playbook/app/pb_kits/playbook/pb_kit/dateTime.ts
  playbook/app/pb_kits/playbook/pb_label_value/_label_value.tsx
  playbook/app/pb_kits/playbook/pb_logistic/_logistic.jsx
  playbook/app/pb_kits/playbook/pb_message/_message.tsx
  playbook/app/pb_kits/playbook/pb_time/_time.tsx
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.tsx
  playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx
  playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.tsx
  playbook/app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.tsx
Labels: milano, ready for release, improvement, alpha

#2663 [PLAY-916] 🧬📄 Hover global prop docs
  playbook-website/app/javascript/components/Sidebar/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/hover_jsx.txt
Labels: milano, improvement

#2662 Update CHANGELOG.md for 12.33.0
  playbook/CHANGELOG.md
Labels: milano

#2658 [PLAY-905] Reaction Button Variant for Button Kit
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_button/_button.tsx
  playbook/app/pb_kits/playbook/pb_button/button.html.erb
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction.md
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_button/docs/index.js
  playbook/app/pb_kits/playbook/pb_icon/_icon.scss
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/icon.html.erb
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: enhancement, milano, ready for release, alpha

#2670 Version Bump to 12.34.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#2671 Update CHANGELOG.md for 12.34.0
  playbook/CHANGELOG.md
Labels: milano
