Repository powerhome/playbook, pull requests merged in 2024-06, with the labels that each got.

#3427 [PLAY-1351] Upgrade Highcharts
  playbook/app/pb_kits/playbook/pb_bar_graph/barGraph.test.js
  playbook/app/pb_kits/playbook/pb_circle_chart/circleChart.test.js
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts
  playbook/app/pb_kits/playbook/pb_gauge/gauge.test.js
  playbook/app/pb_kits/playbook/pb_line_graph/lineGraph.test.js
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemapChart.test.js
  playbook/package.json
  yarn.lock
Labels: milano, Product Approved

#3440 [PLAY-1343] fix Tooltip oversize and misalignment issue
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
Labels: bug, alpha, Product Approved

#3445 Revert "[PLAY-1343] fix Tooltip oversize and misalignment issue"
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
Labels: milano

#3437 [PLAY-829] Remove buffer
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.tsx
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.html.erb
Labels: milano, alpha, Product Approved

#3443 [PBNTR-304] accept all Highcharts props in Chart kits
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.md
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom_rails.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom_rails.md
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.tsx
  playbook/app/pb_kits/playbook/pb_gauge/gauge.rb
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.tsx
  playbook/app/pb_kits/playbook/pb_line_graph/line_graph.rb
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemap_chart.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3438 [PLAY-1359] Fix for Icon Rails Kit based on Subdirectory Structure
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
Labels: milano, alpha, Product Approved

#3450 [PBNTR-326] Adding Vertical Align global prop doc
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/VerticalAlign.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/vertical_align_jsx.txt
Labels: milano, improvement, Product Approved, Code Approved

#3457 [PBNTR-335] add border width prop to circle chart
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
Labels: enhancement, milano, Code Approved

#3461 Update CHANGELOG.md 13.28.0
  playbook/CHANGELOG.md
Labels: milano

#3462 Update CHANGELOG.md 13.29.0
  playbook/CHANGELOG.md
Labels: milano

#3460 [PBNTR-330] Horizontal Bar Graph POC in Rails
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_horizontal.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_horizontal.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/index.js
Labels: enhancement, milano, Product Approved, Code Approved

#3463 [PBNTR-329] Draggable v3 (Beta)
  playbook/app/pb_kits/playbook/pb_card/_card.scss
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list.jsx
  playbook/app/pb_kits/playbook/pb_draggable/draggable.test.jsx
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3453 [PLAY-1355] Upgrade phone number lib
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/package.json
  playbook/webpack.config.js
  yarn.lock
Labels: milano, improvement, Product Approved, Code Approved

#3441 [PBNTR-297] Creating Overlay kit
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.scss
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.tsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_multi_directional.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_multi_directional.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
  playbook/app/pb_kits/playbook/pb_overlay/docs/index.js
  playbook/app/pb_kits/playbook/pb_overlay/overlay.test.jsx
  playbook/app/pb_kits/playbook/pb_overlay/subcomponents/_overlay_percentage.tsx
  playbook/app/pb_kits/playbook/pb_overlay/subcomponents/_overlay_token.tsx
  playbook/app/pb_kits/playbook/playbook-doc.js
Labels: new kit, milano, alpha, Product Approved, Code Approved

#3448 [PLAY-1361] Fix kit props in Docs Circle Chart
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
Labels: milano, improvement, Product Approved, Code Approved

#3452 [PBNTR-312] Table_header flex removal
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3459 [PLAY-1330] Fix Kit Generator in Playbook
  playbook-website/app/helpers/application_helper.rb
  playbook-website/config/menu.yml
  playbook/lib/generators/kit/templates/kit_example_react.erb.tt
  playbook/lib/generators/kit/templates/kit_html.erb.tt
  playbook/lib/generators/kit/templates/kit_jsx_test.erb.tt
  playbook/lib/playbook/kit_base.rb
Labels: bug, milano, Product Approved, Code Approved

#3451 [PBHUB-127] Add turbo frame event listener to dialog kit
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3466 [PLAY-1274] Website: Allow Type-Specific Kit Doc Description Markdown
  playbook-website/app/components/playbook/pb_docs/kit_example.rb
Labels: milano, improvement, Product Approved, Code Approved

#3472 [PBNTR-345] Draggable v4 (Beta)
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_draggable/_draggable.scss
  playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx
  playbook/app/pb_kits/playbook/pb_draggable/context/types.ts
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list.md
  playbook/app/pb_kits/playbook/pb_draggable/draggable.test.jsx
  playbook/app/pb_kits/playbook/pb_draggable/subcomponents/DraggableItem.tsx
  playbook/app/pb_kits/playbook/pb_list/_list.tsx
  playbook/app/pb_kits/playbook/pb_list/_list_item.tsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_item.tsx
  playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.tsx
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
Labels: enhancement, milano, Product Approved

#3474 [PBNTR-333] NEW Overlay kit in Rails
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.html.erb
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_multi_directional.html.erb
  playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
  playbook/app/pb_kits/playbook/pb_overlay/overlay.html.erb
  playbook/app/pb_kits/playbook/pb_overlay/overlay.rb
  playbook/spec/pb_kits/playbook/kits/overlay_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3478 [PLAY-1329] allow any icon to be used in Fixed Confirmation Toast
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.tsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_custom_icon.html.erb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_custom_icon.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.test.js
  playbook/spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3479 [PLAY-1397] Support Aliasing for Playbook-icons
  playbook-website/app/javascript/components/Website/src/pages/IconList/index.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default.html.erb
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default.jsx
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/app/pb_kits/playbook/pb_icon/icon_aliases.json
  playbook/app/pb_kits/playbook/pb_icon/types.d.ts
  yarn.lock
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3480 [PBNTR-343] Loading Advanced Table mock data in all pages we need
  playbook-website/app/controllers/pages_controller.rb
Labels: bug, milano, Product Approved, Code Approved

#3481 [PBNTR-331] Adding column sort to Advanced Table kit
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
Labels: enhancement, milano, Product Approved, Code Approved

#3483 [PBNTR-360] Adding Collapsed Prop to Collapsible Nav on Rails
  playbook/app/pb_kits/playbook/pb_collapsible/index.js
  playbook/app/pb_kits/playbook/pb_nav/docs/_collapsible_nav.html.erb
  playbook/app/pb_kits/playbook/pb_nav/docs/_collapsible_nav.jsx
  playbook/app/pb_kits/playbook/pb_nav/docs/_collapsible_nav.md
  playbook/app/pb_kits/playbook/pb_nav/item.html.erb
  playbook/app/pb_kits/playbook/pb_nav/item.rb
  playbook/spec/pb_kits/playbook/kits/nav_item_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3485 [PBNTR-352] Adding error state to the Dropdown kit
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_error.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_error.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
Labels: enhancement, milano, Product Approved, Code Approved

#3486 [PBIOS-442] Date Time Stacked Docs
  playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_default_swift.md
  playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_props_swift.md
  playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/example.yml
Labels: milano, docs, swiftUI, Product Approved

#3495 Fixing up docs
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default.html.erb
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default.jsx
  playbook/app/pb_kits/playbook/pb_icon/types.d.ts
Labels: milano
