Repository powerhome/playbook, pull requests merged in 2024-05, with the labels that each got.

#3378 [PLAY-1296] Update Progress Simple docs to Use Flex
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_flex.html.erb
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_flex.jsx
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_flex.md
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/example.yml
  playbook/app/pb_kits/playbook/pb_progress_simple/docs/index.js
  playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.rb
Labels: milano, Product Approved, Code Approved

#3372 [PBNTR-277] fix Bar Graph axisTitle requirement
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx
Labels: bug, milano, alpha, Product Approved, Code Approved

#3384 Document reset css for Ruby on Rails setup guide
  playbook-website/app/views/guides/getting_started/ruby_on_rails_setup.md
Labels: milano, improvement

#3386 Update milano links
  milano.production.yml
  milano.staging.yml
  milano.yml
Labels: milano

#3387 [PLAY-1307] add Loading Inline custom text option
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_custom.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_custom.jsx
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_default.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_default.jsx
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/example.yml
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/index.js
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.rb
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.test.js
  playbook/spec/pb_kits/playbook/kits/loading_inline_spec.rb
Labels: enhancement, milano, Code Approved

#3388 13.26.0 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3383 [PBNTR-275] Implementing expand/collapse to Rails Advanced Table kit
  playbook-website/app/components/playbook/pb_docs/advanced_table_mock_data.json
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_default.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_description.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
  playbook/app/pb_kits/playbook/playbook-rails.js
Labels: enhancement, Product Approved, Code Approved

#3382 [PBNTR-260] Avatar componentOverlay variant [corner positions]
  playbook/app/pb_kits/playbook/pb_avatar/Utilities/GetPlacementPropsHelper.tsx
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_badge_component_overlay.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_badge_component_overlay.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_circle_icon_component_overlay.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_circle_icon_component_overlay.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/example.yml
  playbook/app/pb_kits/playbook/pb_avatar/docs/index.js
Labels: enhancement, milano, Product Approved, Code Approved

#3379 [PBNTR-262] Dropdown Kit Rails v1
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subcomponent_structure.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subcomponent_structure.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_autocomplete.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_autocomplete_and_custom_display.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_padding.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_label.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.rb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.rb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.rb
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/keyboard_accessibility.js
  playbook/app/pb_kits/playbook/playbook-rails.js
Labels: new kit, milano, Product Approved

#3380 [PLAY-1249] Fix Tooltips wrapping form elements causing misalignment
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
Labels: bug, milano, alpha, Code Approved

#3392 Dropdown to Use Content Tag instead of pb_content_tag
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.html.erb
Labels: enhancement, milano

#3394 13.27.0 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3395 [PBNTR-276] Avatar overlayComponent variant [center positions]
  playbook/app/pb_kits/playbook/pb_avatar/Utilities/GetPlacementPropsHelper.tsx
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
  playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_badge_component_overlay.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_badge_component_overlay.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_badge_component_overlay.md
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_circle_icon_component_overlay.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_circle_icon_component_overlay.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_circle_icon_component_overlay.md
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/example.yml
  playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3389 [PBNTR- 291] Dropdown Rails v2
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subcomponent_structure.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_padding.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_label.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
Labels: enhancement, milano, alpha, Product Approved

#3393 [PLAY-1022] Card kit subtle backgrounds
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background.jsx
  playbook/app/pb_kits/playbook/pb_card/docs/_card_background.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.md
  playbook/app/pb_kits/playbook/pb_card/docs/_card_highlight.md
  playbook/spec/pb_kits/playbook/kits/card_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3385 [PLAY-1292] Update Website Sidebar and Guide Navigation Integration
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuildesNavItems.ts
  playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/views/guides/_docs_index_list.html.erb
  playbook-website/app/views/guides/getting_started/HTML&_CSS.md
  playbook-website/app/views/layouts/_docs_navigation.html.erb
  playbook-website/app/views/layouts/_sidebar.html.erb
  playbook-website/config/initializers/global_variables.rb
Labels: milano, improvement, Product Approved

#3396 [PLAY-1122] fix Multiple Users padding overflow
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
Labels: bug, milano, alpha, Product Approved

#3373 [PLAY-468] Change darkmode button and link color
  playbook-website/app/components/playbook/pb_docs/kit_example.html.erb
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss
  playbook/app/pb_kits/playbook/pb_detail/_detail_mixins.scss
  playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/tokens/_titles.scss
Labels: enhancement, milano, Product Approved, Code Approved

#3400 [PLAY-1250] fix Text Input addon border radius within a form group
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
Labels: bug, milano, alpha

#3402 [PBNTR-300] Dropdown Doc Examples Cleanup
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subcomponent_structure.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subcomponent_structure_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subcomponent_structure_rails.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display_rails.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options_rails.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_padding.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger_rails.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_label.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.rb
Labels: enhancement, milano, Product Approved

#3297 [PBIOS-331] Date Range Inline Docs
  playbook/app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default_swift.md
  playbook/app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_props_swift.md
  playbook/app/pb_kits/playbook/pb_date_range_inline/docs/example.yml
Labels: docs, swiftUI, Product Approved, Code Approved

#3306 [PBIOS-335]Date Stacked Docs
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_bold_swift.md
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_default_swift.md
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_not_current_year_swift.md
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_props_swift.md
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_reversed_swift.md
  playbook/app/pb_kits/playbook/pb_date_stacked/docs/example.yml
Labels: docs, swiftUI, Product Approved, Code Approved

#3314 [PBIOS-338]Date Time Docs
  playbook-website/app/javascript/site_styles/docs/_kits_examples.scss
  playbook-website/app/views/pages/kit_show.html.erb
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_alignment_swift.md
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default_swift.md
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_props_swift.md
  playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_size_swift.md
  playbook/app/pb_kits/playbook/pb_date_time/docs/example.yml
Labels: docs, swiftUI, Product Approved, Code Approved

#3317 [PBIOS-340] Date Year Stacked Docs
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/_date_year_stacked_default_swift.md
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/_date_year_stacked_props_swift.md
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/example.yml
Labels: docs, swiftUI, Product Approved, Code Approved

#3353 [PBIOS-349] Fixed Confirmation Toast Docs
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_close_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_default_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_dismiss_with_timer_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_positions_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_props_swift.md
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml
Labels: docs, Product Approved, Code Approved

#3415 Update CHANGELOG.md for 13.26.0 & 13.27.0
  playbook/CHANGELOG.md
Labels: milano

#3411 [PLAY-1350] Improve Rails App Example
  examples/rails-react-example/.gitignore
  examples/rails-react-example/.npmrc
  examples/rails-react-example/.ruby-version
  examples/rails-react-example/.tool-versions
  examples/rails-react-example/Gemfile
  examples/rails-react-example/Gemfile.lock
  examples/rails-react-example/README.md
  examples/rails-react-example/app/assets/config/manifest.js
  examples/rails-react-example/app/assets/stylesheets/application.scss
  examples/rails-react-example/app/controllers/application_controller.rb
  examples/rails-react-example/app/javascript/components/App.tsx
  examples/rails-react-example/app/javascript/components/HelloWorld.jsx
  examples/rails-react-example/app/javascript/packs/application.ts
  examples/rails-react-example/app/javascript/packs/component_context.js
  examples/rails-react-example/app/types.d.ts
  examples/rails-react-example/app/views/layouts/application.html.erb
  examples/rails-react-example/app/views/pages/index.html.erb
  examples/rails-react-example/config/initializers/assets.rb
  examples/rails-react-example/config/routes.rb
  examples/rails-react-example/config/webpacker.yml
  examples/rails-react-example/package.json
  examples/rails-react-example/yarn.lock
Labels: rails, milano, docs, Product Approved

#3407 [PLAY-1115] fix Text input add-on dark mode border and message color
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
Labels: bug, milano, Product Approved

#3390 Update _button_mixins.scss to remove underline for users not including reset.css
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
Labels: milano, alpha, Product Approved

#3399 [PBNTR-48] Making Phone Number Input kit compatible with pb_form_with
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/lib/playbook/forms/builder.rb
  playbook/lib/playbook/forms/builder/phone_number_field.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3408 [PBNTR-294] Fix for Nitro Style bleed with Pagination kit
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.scss
Labels: bug, milano, alpha, Product Approved

#3410 [PBNTR-306] Collapsible Kit with Custom Collapsible.Main
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleIcon.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_icon.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_icon.rb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_rails.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_rails.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_with_icon.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_with_icon.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_with_icon_rails.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_with_icon_rails.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/example.yml
  playbook/app/pb_kits/playbook/pb_collapsible/docs/index.js
  playbook/app/pb_kits/playbook/pb_collapsible/index.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3405 [PLAY-1342] DRY up the content_tag portion of Rails kits: "simple kits"
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/avatar_action_button.html.erb
  playbook/app/pb_kits/playbook/pb_badge/badge.html.erb
  playbook/app/pb_kits/playbook/pb_button_toolbar/button_toolbar.html.erb
  playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_content.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.html.erb
  playbook/app/pb_kits/playbook/pb_contact/contact.html.erb
  playbook/app/pb_kits/playbook/pb_currency/currency.html.erb
  playbook/app/pb_kits/playbook/pb_dashboard_value/dashboard_value.html.erb
  playbook/app/pb_kits/playbook/pb_date/date.html.erb
  playbook/app/pb_kits/playbook/pb_date_range_inline/date_range_inline.html.erb
  playbook/app/pb_kits/playbook/pb_date_range_stacked/date_range_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_date_stacked/date_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_date_time/date_time.html.erb
  playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_date_year_stacked/date_year_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.html.erb
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.html.erb
  playbook/app/pb_kits/playbook/pb_icon_value/icon_value.html.erb
  playbook/app/pb_kits/playbook/pb_label_pill/label_pill.html.erb
  playbook/app/pb_kits/playbook/pb_label_value/label_value.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.html.erb
  playbook/app/pb_kits/playbook/pb_message/message_mention.html.erb
  playbook/app/pb_kits/playbook/pb_multiple_users/multiple_users.html.erb
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/multiple_users_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_pagination/pagination.html.erb
  playbook/app/pb_kits/playbook/pb_person/person.html.erb
  playbook/app/pb_kits/playbook/pb_person_contact/person_contact.html.erb
  playbook/app/pb_kits/playbook/pb_pill/pill.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/section_separator.html.erb
  playbook/app/pb_kits/playbook/pb_source/source.html.erb
  playbook/app/pb_kits/playbook/pb_stat_change/stat_change.html.erb
  playbook/app/pb_kits/playbook/pb_stat_value/stat_value.html.erb
  playbook/app/pb_kits/playbook/pb_time_range_inline/time_range_inline.html.erb
  playbook/app/pb_kits/playbook/pb_time_stacked/time_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/item.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/timeline.html.erb
  playbook/app/pb_kits/playbook/pb_timestamp/timestamp.html.erb
  playbook/app/pb_kits/playbook/pb_title_count/title_count.html.erb
  playbook/app/pb_kits/playbook/pb_title_detail/title_detail.html.erb
  playbook/app/pb_kits/playbook/pb_weekday_stacked/weekday_stacked.html.erb
  playbook/lib/generators/kit/templates/kit_html.erb.tt
  playbook/lib/playbook/kit_base.rb
Labels: enhancement, milano, alpha, Product Approved

#3414 [PLAY-1178] Fixed Styling when Select Kit is used within a Flex Kit
  playbook/app/pb_kits/playbook/pb_select/_select.scss
Labels: milano, alpha

#3416 [PBNTR-308] Dropdown Custom Option Padding
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_padding.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger_rails.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.rb
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
Labels: enhancement, milano, alpha

#3420 Revert "[PBIOS-340] Date Year Stacked Docs"
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/_date_year_stacked_default_swift.md
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/_date_year_stacked_props_swift.md
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/example.yml
Labels: milano

#3424 [PLAY-1356] Release Notes Generator
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: milano

#3421 [PLAY-1352] Fix React Props Table Collapsible kit
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_collapsible/__snapshots__/collapsible.test.js.snap
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.test.js
Labels: milano, improvement, Product Approved, Code Approved

#3426 [PBNTR-288] Table kit subcomponent alignment + shift
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx
  playbook/app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.tsx
  playbook/app/pb_kits/playbook/pb_line_graph/line_graph.rb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/tokens/_vertical_align.scss
  playbook/app/pb_kits/playbook/utilities/_vertical_align.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/vertical_align.rb
Labels: enhancement, milano, Product Approved

#3431 Play 1209 fix form group date picker border radius react
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
Labels: bug, milano, alpha, Product Approved

#3433 [PBNTR-316] Draggable Kit Beta
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_draggable/_draggable.scss
  playbook/app/pb_kits/playbook/pb_draggable/_draggable.tsx
  playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/docs/index.js
  playbook/app/pb_kits/playbook/pb_draggable/draggable.test.jsx
  playbook/app/pb_kits/playbook/pb_draggable/subcomponents/DraggableContainer.tsx
  playbook/app/pb_kits/playbook/pb_draggable/subcomponents/DraggableItem.tsx
  playbook/app/pb_kits/playbook/playbook-doc.js
Labels: new kit, milano, Product Approved

#3435 [PBNTR-255] Adding outer padding prop
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_outer_padding.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_outer_padding.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_outer_padding.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_outer_padding.scss
  playbook/app/pb_kits/playbook/pb_table/table.rb
  playbook/app/pb_kits/playbook/pb_table/table.test.js
  playbook/spec/pb_kits/playbook/kits/table_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3436 [PLAY-1290] Make New Designer Guidelines Public Facing
  playbook-website/app/controllers/guides_controller.rb
  playbook-website/app/javascript/components/MainSidebar/MenuData/SidebarNavItems.ts
  playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/javascript/site_styles/_design_guidelines.scss
  playbook-website/app/javascript/site_styles/main.scss
  playbook-website/app/views/guides/_design_docs_index_list.html.erb
  playbook-website/app/views/guides/design_guidelines.md
  playbook-website/app/views/guides/design_guidelines/color.md
  playbook-website/app/views/guides/design_guidelines/example_markdown_styling.md
  playbook-website/app/views/guides/design_guidelines/file_naming.md
  playbook-website/app/views/guides/design_guidelines/generator.md
  playbook-website/app/views/guides/design_guidelines/kit_examples.md
  playbook-website/app/views/guides/design_guidelines/kit_rails.md
  playbook-website/app/views/guides/design_guidelines/kit_react.md
  playbook-website/app/views/guides/design_guidelines/layout.md
  playbook-website/app/views/guides/design_guidelines/spacing.md
  playbook-website/app/views/guides/design_guidelines/typography.md
  playbook-website/app/views/guides/design_guidelines/writing_sass.md
  playbook-website/app/views/layouts/_sidebar.html.erb
Labels: milano, improvement, Product Approved
