Repository powerhome/playbook, pull requests merged in 2024-03, with the labels that each got.

#3183 [PBNTR-205] Fixing kit props table for Advanced Table
  playbook-website/app/javascript/components/AvailableProps/index.tsx
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  yarn.lock
Labels: bug, milano, Ready for Release, Product Approved

#3188 [PBNTR-207] Adding div support for Table kit
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_div.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_div.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_table/styles/_content.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_desktop_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_headers.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_hover.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_reset.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_side_highlight.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_single-line.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_sticky_header.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_striped.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_structure.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_table-card.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_table-dark.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_table_header.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_tablet_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_vertical_border.scss
  playbook/app/pb_kits/playbook/pb_table/table.html.erb
  playbook/app/pb_kits/playbook/pb_table/table.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved

#3201 [PLAY-1141] Copy branch to have signed commits
  Dockerfile
  playbook-website/app/components/hp_solutions_component.html.erb
  playbook-website/app/components/lg_hp_social_proof_component.html.erb
  playbook-website/app/controllers/samples_controller.rb
  playbook-website/app/javascript/components/Website/src/pages/IconList/index.tsx
  playbook-website/app/javascript/site_styles/_site-style.scss
  playbook-website/app/views/layouts/_footer.html.erb
  playbook-website/app/views/layouts/_mobile_nav.html.erb
  playbook-website/app/views/layouts/docs.html.erb
  playbook-website/app/views/samples/icons.html.erb
  playbook-website/config/application.rb
  playbook-website/config/routes.rb
  playbook-website/config/webpack/environment.js
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.html.erb
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.jsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.md
  playbook/app/pb_kits/playbook/pb_icon/icon.html.erb
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/spec/pb_kits/playbook/kits/icon_spec.rb
  playbook/tsconfig.json
  yarn.lock
Labels: milano, Ready for Release

#3211 [PBNTR-204] add Turbo to Playbook POC
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/app/javascript/packs/application.js
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, Product Approved

#3218 [PLAY-1186] Fix Bold Nav Icon Color
  playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss
Labels: milano, alpha, Product Approved

#3197 [PLAY-1196] Docs: add Truncate global prop doc
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Truncate.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/overflow_jsx.txt
  playbook-website/app/views/pages/code_snippets/truncate_jsx.txt
Labels: milano, Product Approved

#3202 [PLAY-1237] Fix addon input child
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.jsx
Labels: milano, Product Approved

#3196 Fix colors guidelines layout
  playbook-website/app/javascript/components/VisualGuidelines/Colors/index.tsx
Labels: bug, milano

#3236 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#3237 Version Bump 13.20.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
  yarn.lock
Labels: milano

#3235 [PBIOS-300] Date Doc Update
  playbook/app/pb_kits/playbook/pb_date/docs/_date_alignment_swift.md
  playbook/app/pb_kits/playbook/pb_date/docs/_date_default_swift.md
Labels: docs, Product Approved

#3195 [PBFIG-135] Figma Library Getting Started Markdown - Create figma_setup.md
  playbook-website/app/views/guides/getting_started/figma_setup.md
Labels: milano, improvement

#3239 fix Message kit description typos
  playbook/app/pb_kits/playbook/pb_message/docs/_description.md
Labels: milano, improvement

#3226 [PBIOS-296] update setup guide
  playbook-website/app/views/guides/getting_started/swift_setup.md
Labels: docs, Product Approved

#3199 [PLAY-1241] rebuild Playbook-Icons-react for use in Nitro
  playbook-website/app/javascript/components/Website/src/layouts/Footer.tsx
  playbook-website/app/javascript/components/Website/src/pages/IconList/index.tsx
  playbook-website/app/javascript/packs/app.js
  playbook-website/config/routes.rb
  playbook-website/config/webpack/environment.js
  playbook-website/config/webpacker.yml
  playbook-website/package.json
  yarn.lock
Labels: milano, Product Approved

#3228 [PLAY-1232] Global Props & Examples
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Position.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/SpacingProps.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/javascript/packs/samples.js
  playbook-website/app/javascript/site_styles/visual_guidelines/_border_radius_guidelines.scss
  playbook-website/app/views/pages/code_snippets/global_positioning.txt
  playbook-website/app/views/samples/global_positioning/index.html.erb
  playbook-website/app/views/samples/global_positioning/index.jsx
  playbook-website/config/samples.yml
  playbook/app/pb_kits/playbook/utilities/_positioning.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/bottom.rb
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/left.rb
  playbook/lib/playbook/right.rb
  playbook/lib/playbook/top.rb
  yarn.lock
Labels: milano

#3217 Enable Remote Shell
  Makefile
  playbook-website/bin/cluster_for_review_stack
  playbook-website/bin/remote_exec
Labels: milano

#3256 [PLAY-1265] Add 'svg-inline--fa' class to our icons
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
Labels: milano, Product Approved

#3240 [PBNTR-222] Fixing Advanced Table hover
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
Labels: bug, milano, Product Approved

#3241 [PBNTR-225] Applying Advanced Table feedback provided by Sr. Playbook dev
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/SortIconButton.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/SubRowHeaderRow.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/ToggleIconButton.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableBody.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableHeader.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/ExpansionControlHelpers.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/types.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_collapsible_trail.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_default.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expanded_control.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_inline_row_loading.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_inline_row_loading.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_loading.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_control.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_subrow_headers.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_table_options.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_table_props.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_mock_data.js
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_mock_data_inline_loading.js
  playbook/app/pb_kits/playbook/pb_advanced_table/scss_partials/_chrome_styles.scss
  playbook/app/pb_kits/playbook/types/data.ts
Labels: milano, improvement, alpha, Product Approved

#3203 [PLAY-1174] Fix confirmation toast mobile bug
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.scss
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.tsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.html.erb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.jsx
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_positions.html.erb
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.html.erb
Labels: bug, milano, alpha, Product Approved

#3246 [PLAY-1245] Make border of Breadcrumbs kit transparent
  playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss
Labels: bug, milano, Product Approved

#3254 [PLAY-1257] Ruby 3.3.0 Upgrade
  .tool-versions
  Dockerfile
  examples/playbook-rails-webpack/.ruby-version
  examples/playbook-rails-webpack/Gemfile
  examples/playbook-rails/Gemfile
  examples/rails-react-example/.ruby-version
  examples/rails-react-example/Gemfile
  playbook-website/.ruby-version
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
Labels: milano, improvement, alpha, Product Approved

#3257 [PLAY-1187] Fix Broken Doc Page Layouts
  playbook-website/app/javascript/components/VisualGuidelines/Colors/index.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/BorderRadius.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Cursor.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Display.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/ZIndex.tsx
  playbook/app/pb_kits/playbook/pb_flex/docs/_flex_spacing.html.erb
Labels: milano, improvement, Product Approved

#3258 [PBNTR-220] Advanced Table kit: further improve "expand all" subrows expansion speed
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/ExpansionControlHelpers.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
Labels: enhancement, milano, alpha

#3305 [PBFIG-166] Playbook Designer Guideline #1 Markdown Create color_guidelines.md
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/guides/design_guidelines.md
  playbook-website/app/views/guides/design_guidelines/color_guidelines.md
  playbook-website/app/views/guides/design_guidelines/example_markdown_styling.md
Labels: milano, Product Approved, Code Approved

#3260 [PLAY-1271][PLAY-1270] Enable Online Status & New Colors + Hide Date Range Picker Docs
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_online_status/_online_status.scss
  playbook/app/pb_kits/playbook/pb_online_status/_online_status.tsx
  playbook/app/pb_kits/playbook/pb_online_status/_online_status_mixins.scss
  playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_default.html.erb
  playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_default.jsx
  playbook/app/pb_kits/playbook/pb_online_status/online_status.rb
  playbook/spec/pb_kits/playbook/kits/online_status_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3266 [PLAY-1159] Make rails disable prop for toggle kit
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.scss
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.tsx
  playbook/app/pb_kits/playbook/pb_toggle/docs/_toggle_disabled.html.erb
  playbook/app/pb_kits/playbook/pb_toggle/docs/_toggle_disabled.jsx
  playbook/app/pb_kits/playbook/pb_toggle/docs/example.yml
  playbook/app/pb_kits/playbook/pb_toggle/docs/index.js
  playbook/app/pb_kits/playbook/pb_toggle/toggle.rb
  playbook/app/pb_kits/playbook/pb_toggle/toggle.test.js
  playbook/spec/pb_kits/playbook/kits/toggle_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3269 [PBNTR-224] Letting user reset row expansion in Advanced Table
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expanded_control.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expanded_control.md
  playbook/lib/playbook/kit_base.rb
Labels: milano, improvement, alpha, Product Approved, Code Approved

#3273 [PLAY-1203] Default cancel and close button type to prevent submission
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_compound_components.html.erb
Labels: bug, milano, alpha, Product Approved, Code Approved

#3275 [PBNTR-236] fix FormGroup kit breaking borders between Phone Number Input and Selects
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.jsx
Labels: bug, milano, Product Approved, Code Approved

#3277 [PLAY-1205] Update Multilevel React Doc for clarity on selectedIds
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids_react.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids_react.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
Labels: milano, improvement, docs, Product Approved, Code Approved

#3289 [PBNTR-243] Global Positioning Props to Allow Inset Value
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Position.tsx
  playbook/app/pb_kits/playbook/utilities/_positioning.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/bottom.rb
  playbook/lib/playbook/left.rb
  playbook/lib/playbook/position_props_css.rb
  playbook/lib/playbook/right.rb
  playbook/lib/playbook/top.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3296 [PLAY-1266] Fix Nav Category Page
  playbook-website/app/controllers/pages_controller.rb
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default.html.erb
Labels: milano, Product Approved, Code Approved

#3308 [PBNTR-246] fix UI Samples code view
  playbook-website/app/javascript/site_styles/_samples_show.scss
  playbook-website/app/views/samples/show.html.erb
Labels: bug, milano
