Repository powerhome/playbook, pull requests merged in 2024-07, with the labels that each got.

#3499 13.31.0 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3501 [PLAY-692] Remove duplicate "block" button in RTE on start, not change
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.tsx
Labels: bug, milano, Product Approved, Code Approved

#3500 [PLAY-1291] hide beta versions of kits within Beta Index (with menu.yml)
  playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
Labels: bug, milano, Product Approved, Code Approved

#3497 [PLAY-1367] Use new content tag
  playbook/app/pb_kits/playbook/pb_background/background.html.erb
  playbook/app/pb_kits/playbook/pb_body/body.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.html.erb
  playbook/app/pb_kits/playbook/pb_caption/caption.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_detail/detail.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_body.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb
  playbook/app/pb_kits/playbook/pb_flex/flex.html.erb
  playbook/app/pb_kits/playbook/pb_hashtag/hashtag.html.erb
  playbook/app/pb_kits/playbook/pb_highlight/highlight.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.html.erb
Labels: milano, alpha, Product Approved, Code Approved

#3507 [PBNTR-361] Implementing Dropdown form validation
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
Labels: enhancement, milano, Code Approved

#3488 [PLAY-1391] Add Category to Playbook kit generator
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/application_helper.rb
  playbook-website/config/menu.yml
  playbook-website/config/routes.rb
  playbook/lib/generators/kit/kit_generator.rb
Labels: milano, improvement, Product Approved, Code Approved

#3509 Update CHANGELOG.md for 13.31.0
  playbook/CHANGELOG.md
Labels: milano

#3508 [PLAY-1364] Date Year Stacked Left Align Text Color Bug
  playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/_date_year_stacked_default.jsx
Labels: bug, milano, Code Approved

#3413 Bump ci-kubed v8.2.0 and convert to use remote buildkit cache mounts
  Dockerfile
  Jenkinsfile
Labels: milano, improvement, alpha

#3522 Change Draggable Kit status to Stable
  playbook-website/config/menu.yml
Labels: bug, milano

#3510 [PBNTR-363] Implementing default value for Dropdown kit
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default_value.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default_value.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
Labels: enhancement, milano, Product Approved, Code Approved

#3533 13.32.0 CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#3529 [PBNTR-381] Implementing form resetting and blank selection prop
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_blank_selection.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_blank_selection.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.rb
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
Labels: enhancement, milano, Product Approved, Code Approved

#3491 [PLAY-1262] Playbook Icons Styles
  playbook-website/app/javascript/components/Website/src/pages/IconList/index.tsx
  playbook-website/app/views/samples/icons.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/__snapshots__/collapsible.test.js.snap
  playbook/app/pb_kits/playbook/pb_icon/_icon.scss
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/app/pb_kits/playbook/pb_nav/_nav_item.test.js
Labels: milano, alpha, Product Approved, Code Approved

#3504 [PLAY-1086] Linter implementation: kits T - W
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_body.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_cell.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_head.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_header.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_row.tsx
  playbook/app/pb_kits/playbook/pb_table/table.test.js
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_default.jsx
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.tsx
  playbook/app/pb_kits/playbook/pb_textarea/index.tsx
  playbook/app/pb_kits/playbook/pb_time/_time.tsx
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_item.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.tsx
  playbook/app/pb_kits/playbook/pb_title_detail/_title_detail.tsx
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.tsx
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemapChart.test.js
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ClearIndicator.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Control.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/IndicatorsContainer.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MenuList.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MultiValue.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Option.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Placeholder.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ValueContainer.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_custom_menu_list.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/index.ts
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/million-dollar.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/veteran.tsx
  playbook/app/pb_kits/playbook/pb_walkthrough/_walkthrough.tsx
  playbook/app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.tsx
Labels: milano, improvement, alpha, Product Approved, Code Approved

#3505 [PLAY-882] Form pills: match handoff (primary + default)
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.test.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_example.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_example.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_size.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_size.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.rb
  playbook/spec/pb_kits/playbook/kits/form_pill_spec.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3511 [PLAY-1429] Improve consistency in docs for default variant of Typeahead
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
Labels: bug, milano, Product Approved, Code Approved

#3513 [PLAY-1402] hide beta versions of kits within Kit Categories (with menu.yml)
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/Website/src/components/CategoryTitle/index.tsx
  playbook-website/app/javascript/components/Website/src/hooks/loaders.ts
  playbook-website/app/javascript/components/Website/src/pages/CategoryShow/index.tsx
  playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
  playbook-website/app/javascript/packs/app.js
  playbook-website/test/menu_yml_spec.rb
Labels: milano, improvement, Product Approved, Code Approved

#3514 [PLAY-1416] Add alias map entrypoint for rails
  Dockerfile
  playbook-website/app/views/samples/icons.html.erb
  playbook-website/config/application.rb
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/app/pb_kits/playbook/pb_icon/icon_aliases.json
  yarn.lock
Labels: milano, alpha, Product Approved, Code Approved

#3515 [PLAY-1431] Update Highcharts CustomOptions Formatting Note
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.md
Labels: milano, improvement, Product Approved, Code Approved

#3528 [PLAY-877] RTE Custom Extenion Dropdown Button Bug Fix
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/MoreExtensionsDropdown.tsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarDropdown.tsx
Labels: bug, milano, Product Approved, Code Approved

#3523 [PBNTR-285] Star Rating kit: interactive form variant (Rails)
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.scss
  playbook/app/pb_kits/playbook/pb_star_rating/docs/_star_rating_interactive.html.erb
  playbook/app/pb_kits/playbook/pb_star_rating/docs/example.yml
  playbook/app/pb_kits/playbook/pb_star_rating/index.js
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.html.erb
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.rb
  playbook/app/pb_kits/playbook/playbook-rails.js
  playbook/lib/playbook/forms/builder.rb
  playbook/lib/playbook/forms/builder/star_rating_field.rb
  playbook/spec/pb_kits/playbook/kits/star_rating_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3521 [PBNTR-342] Adding tabbing prop to the Nav kit
  playbook/app/pb_kits/playbook/pb_nav/docs/_tab_nav.html.erb
  playbook/app/pb_kits/playbook/pb_nav/docs/_tab_nav.md
  playbook/app/pb_kits/playbook/pb_nav/docs/example.yml
  playbook/app/pb_kits/playbook/pb_nav/index.js
  playbook/app/pb_kits/playbook/pb_nav/nav.rb
  playbook/app/pb_kits/playbook/playbook-rails.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3534 [PLAY-1405] Create a Doc for Border Radius Global Props
  playbook-website/app/javascript/components/VisualGuidelines/Examples/BorderRadius.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/border_radius_jsx.txt
Labels: milano, improvement, Product Approved, Code Approved

#3543 Revert "[PLAY-1086] Linter implementation: kits T - W"
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_body.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_cell.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_head.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_header.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_row.tsx
  playbook/app/pb_kits/playbook/pb_table/table.test.js
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_default.jsx
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.tsx
  playbook/app/pb_kits/playbook/pb_textarea/index.tsx
  playbook/app/pb_kits/playbook/pb_time/_time.tsx
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_item.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.tsx
  playbook/app/pb_kits/playbook/pb_title_detail/_title_detail.tsx
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.tsx
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemapChart.test.js
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ClearIndicator.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Control.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/IndicatorsContainer.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MenuList.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MultiValue.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Option.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/Placeholder.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/ValueContainer.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_custom_menu_list.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/index.ts
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/million-dollar.tsx
  playbook/app/pb_kits/playbook/pb_user_badge/badges/veteran.tsx
  playbook/app/pb_kits/playbook/pb_walkthrough/_walkthrough.tsx
  playbook/app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.tsx
Labels: milano

#3538 13.33.0 CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#3536 [PBNTR-405] Dropdown Kit in Rails Form Fixes
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
Labels: bug, milano, alpha, Product Approved, Code Approved

#3527 [PLAY-1138] Icon kit: add a color prop
  playbook/app/pb_kits/playbook/pb_icon/_icon.scss
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_color.html.erb
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_color.jsx
  playbook/app/pb_kits/playbook/pb_icon/docs/_icon_color.md
  playbook/app/pb_kits/playbook/pb_icon/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon/docs/index.js
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/app/pb_kits/playbook/pb_icon/icon.test.js
  playbook/spec/pb_kits/playbook/kits/icon_spec.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3526 [PLAY-1436] Dark Mode Fix: Contact and DRI
  playbook/app/pb_kits/playbook/pb_contact/_contact.tsx
  playbook/app/pb_kits/playbook/pb_contact/contact.html.erb
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.tsx
Labels: bug, milano, Product Approved, Code Approved

#3516 [PLAY-1327] Add Variants Specification to Kit Collection View
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/pages/kit_collection.html.erb
  playbook-website/config/routes.rb
  playbook-website/lib/pb_doc_helper.rb
Labels: milano, improvement, Product Approved, Code Approved

#3541 [PLAY-1438] Icons Batch 8
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, Product Approved, Code Approved

#3540 [PLAY-1454] Form pills 2 of 5: add icon prop
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.test.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_icon.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_icon.jsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/example.yml
  playbook/app/pb_kits/playbook/pb_form_pill/docs/index.js
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.rb
  playbook/spec/pb_kits/playbook/kits/form_pill_spec.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3548 [PLAY-1445] Use New Content Tag
  playbook/app/pb_kits/playbook/pb_background/background.html.erb
  playbook/app/pb_kits/playbook/pb_body/body.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.html.erb
  playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.html.erb
  playbook/app/pb_kits/playbook/pb_caption/caption.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_detail/detail.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_body.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb
  playbook/app/pb_kits/playbook/pb_flex/flex.html.erb
  playbook/app/pb_kits/playbook/pb_hashtag/hashtag.html.erb
  playbook/app/pb_kits/playbook/pb_highlight/highlight.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.html.erb
Labels: enhancement, milano, Product Approved, Code Approved

#3550 [PBNTR-356] Implementing Star Rating interactive variant for React
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/docs/_star_rating_hide.jsx
  playbook/app/pb_kits/playbook/pb_star_rating/docs/_star_rating_interactive.jsx
  playbook/app/pb_kits/playbook/pb_star_rating/docs/index.js
  playbook/app/pb_kits/playbook/pb_star_rating/stars/utils.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/subcomponents/_star_rating_display.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/subcomponents/_star_rating_interactive.tsx
Labels: enhancement, milano, Product Approved, Code Approved

#3530 [PLAY-1435] Fix Dark Mode Styles: Collapsible Kit
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.scss
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_rails.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_with_icon.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_custom_main_with_icon_rails.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_icons.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_state.jsx
Labels: bug, milano, Product Approved
