Repository powerhome/playbook, pull requests merged in 2024-12, with the labels that each got.

#3964 Version Bump 14.9.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano, minor

#3962 [PBNTR-736] Adding React Advanced Table Pagination
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination_with_props.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination_with_props.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/advanced_table_pagination_mock_data.json
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.tsx
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3971 [PBIOS-638] Update SWIFT_CHANGELOG.md to Reflect 6.5.1 Release
  playbook/SWIFT_CHANGELOG.md
Labels: milano, docs, swiftUI, minor

#3965 Update CHANGELOG.md 14.9.0
  playbook/CHANGELOG.md
Labels: milano, minor

#3953 [PLAY-1668] Dark Mode Audit - Selectable Card
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.html.erb
Labels: milano, improvement, Code Approved, minor

#3950 [PLAY-1667] Dark Mode Audit - Nav
  playbook/app/pb_kits/playbook/pb_nav/_bold_mixin.scss
  playbook/app/pb_kits/playbook/pb_nav/_collapsible_nav.scss
  playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss
Labels: milano, improvement, Code Approved, minor

#3954 [PLAY-1652] Dark Mode Audit - File Upload Kit
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.scss
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
  playbook/app/pb_kits/playbook/pb_file_upload/file_upload.html.erb
Labels: milano, improvement, Code Approved, minor

#3961 [PLAY-1673] Dark Mode Audit - Caption and Title
  playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title_mixin.scss
  playbook/app/pb_kits/playbook/tokens/_titles.scss
Labels: milano, improvement, Code Approved, minor

#3968 [PLAY-1666] Dark Mode Audit Stat Change
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_stat_change/_stat_change.tsx
  playbook/app/pb_kits/playbook/pb_stat_change/stat_change.html.erb
Labels: milano, improvement, Code Approved, minor

#3973 [PLAY-1635] Bread Crumbs Dark Mode Fix
  playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_bread_crumbs_default.jsx
Labels: milano, improvement, Code Approved, minor

#3974 [PLAY-1740] Fix Sort Function on Rails Advanced Table
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
Labels: bug, milano, Code Approved, minor

#3975 [PLAY-1605] Add underline hover prop
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx
  playbook-website/app/views/pages/code_snippets/hover_jsx.txt
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/app/pb_kits/playbook/utilities/test/globalProps/hover.test.js
  playbook/lib/playbook/hover.rb
  playbook/spec/playbook/global_props/hover_spec.rb
Labels: milano, Code Approved, minor

#3984 [PLAY-1701] Change Playground Key
  playbook-website/app/javascript/components/MainSidebar/MenuData/SidebarNavItems.ts
Labels: bug, milano, minor

#3970 [PBNTR-702] Create a "stickyLeftcolumn" prop for the Table kit - RAILS only
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns.html.erb
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/table.html.erb
  playbook/app/pb_kits/playbook/pb_table/table.rb
  playbook/spec/pb_kits/playbook/kits/table_spec.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3999 Update CHANGELOG.md with design
  playbook/CHANGELOG.md
Labels: milano, minor

#3967 [PBNTR-738] Collapsible Rows for Basic Table
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleContent.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_content.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_content.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_rows.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_rows.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_table.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_table.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_collapsible.scss
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_row.tsx
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3997 [PLAY-1764] Make link live kit
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_link/_link.scss
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#3982 [PLAY-1617] Change Bar Graph Override Example
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom_rails.html.erb
Labels: milano, improvement, Code Approved, minor

#3986 [PLAY-1731] Text Input Masking for React: Currency, Zip Code, Postal Code, SSN
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_text_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_text_input/inputMask.ts
  playbook/app/pb_kits/playbook/pb_text_input/text_input.test.js
Labels: enhancement, milano, alpha, Code Approved, minor

#4014 [PBNTR-694] SkeletonLoading User Component and Filter Component doc examples
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_filter.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_user.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/example.yml
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/index.js
Labels: milano, improvement, Product Approved, Code Approved, minor

#3972 [PLAY-1742] Global Height Fixes
  playbook/app/pb_kits/playbook/pb_drawer/_drawer.tsx
  playbook/app/pb_kits/playbook/pb_layout/_layout.tsx
Labels: milano, alpha, Product Approved, Code Approved, minor

#4030 [PBNTR-739] Adding Collapsible Trail to Rails Advanced Table
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/CollapsibleTrail.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_collapsible_trail_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_collapsible_trail_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_subrow_header.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_subrow_header.rb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor

#3983 [PLAY-1670] Dark Mode Audit - Typeahead
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_highlight.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#4006 [PLAY-1500] Home Address Street: "none" Emphasis Prop
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.md
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
  playbook/app/pb_kits/playbook/pb_home_address_street/none_emphasis.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/none_emphasis.rb
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#4027 [PBNTR-716] Table kit: "Sticky Left Column" variant styling - React and Rails
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/styles/_scroll.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_sticky_columns.scss
  playbook/app/pb_kits/playbook/pb_table/table.html.erb
  playbook/app/pb_kits/playbook/pb_table/table.rb
Labels: milano, improvement, Code Approved, minor

#4007 [PLAY-1623] Icon Integration Docs: Nav Bar and About Page
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
  playbook-website/app/views/guides/getting_started/icons.md
  playbook-website/app/views/guides/getting_started/icons/custom.md
  playbook-website/app/views/guides/getting_started/icons/font_awesome.md
  playbook-website/app/views/guides/getting_started/icons/playbook.md
  playbook-website/app/views/layouts/icons.html.erb
  playbook-website/app/views/pages/icons.html.erb
  playbook-website/app/views/pages/icons_custom.html.erb
  playbook-website/app/views/pages/icons_font_awesome.html.erb
  playbook-website/app/views/pages/icons_playbook.html.erb
  playbook-website/config/initializers/global_variables.rb
  playbook-website/config/routes.rb
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#4013 [PLAY-1539] Playbook Website Redirects - Go to Parent not Home
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/config/routes.rb
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#4021 [PLAY-1708] Skip RC process with 'Inactive RC' label
  .github/workflows/github-actions-release-candidate.yml
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor, Inactive RC

#4015 [PLAY-1678] Dark Mode Audit - Gauge
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.scss
  playbook/app/pb_kits/playbook/pb_gauge/_gauge.tsx
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.jsx
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#4044 [PLAY-1629] Add Status Color to Card Header
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.jsx
  playbook/app/pb_kits/playbook/pb_card/docs/_card_header.md
Labels: milano, improvement, Code Approved, minor

#4004 [PLAY-1703 ] Form Group Error State Alignment
  playbook/app/pb_kits/playbook/pb_form_group/_error_state_mixin.scss
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
Labels: bug, milano, alpha, Product Approved, Code Approved, minor

#4061 Version Bump 14.10.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor

#4063 CHANGELOG.md for 14.10.0
  playbook/CHANGELOG.md
Labels: milano, minor, Inactive RC

#4054 [PLAY-1702] Circle Icon Button Kit: Add Target Prop
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.tsx
  playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.html.erb
  playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.html.erb
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.jsx
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.md
Labels: milano, improvement, Product Approved, Code Approved, minor

#4038 [PBNTR-767] Multi Column Headers for Advanced Table
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableBody.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_multiple.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_multiple.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved, minor
