Repository powerhome/playbook, pull requests merged in 2024-08, with the labels that each got.

#3562 Fix For Icon Color SCSS
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/app/pb_kits/playbook/pb_icon/_icon.scss
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3574 Pulling Fonts from Power-fonts
  playbook-website/app/javascript/site_styles/fonts/PowerCentra-Bold.woff
  playbook-website/app/javascript/site_styles/fonts/PowerCentra-BoldItalic.woff
  playbook-website/app/javascript/site_styles/fonts/PowerCentra-Book.woff
  playbook-website/app/javascript/site_styles/fonts/PowerCentra-BookItalic.woff
  playbook-website/app/javascript/site_styles/fonts/PowerCentra-Light.woff
  playbook-website/app/javascript/site_styles/fonts/_site-fonts.scss
  playbook-website/app/javascript/site_styles/main.scss
Labels: milano, alpha

#3545 [PLAY-1406] Fix zIndex Global Prop Issues in Playbook (and Nitro)
  playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.scss
  playbook/app/pb_kits/playbook/utilities/_positioning.scss
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3553 [Play-1407] Stat Value Kit Inconsistencies
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.tsx
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.rb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.scss
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.tsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/docs/_icon_stat_value_color.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.rb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.test.js
  playbook/spec/pb_kits/playbook/kits/icon_circle_spec.rb
  playbook/spec/pb_kits/playbook/kits/icon_stat_value_spec.rb
Labels: bug, milano, alpha, Product Approved, Code Approved

#3559 [PBNTR-358] Responsive version of AdvancedTable Kit (React)
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableBody.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableHeader.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_responsive.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_responsive.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3561 [PLAY-1424] Document How to Theme within Playbook
  playbook-website/app/views/guides/getting_started/how_to_theme.md
  playbook-website/config/initializers/global_variables.rb
Labels: milano, improvement, Product Approved, Code Approved

#3563 [PLAY-1388] Online Status Kit Props: Size and No Border
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
  playbook/app/pb_kits/playbook/pb_online_status/_online_status.scss
  playbook/app/pb_kits/playbook/pb_online_status/_online_status.tsx
  playbook/app/pb_kits/playbook/pb_online_status/_online_status_mixins.scss
  playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_no_border.html.erb
  playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_no_border.jsx
  playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_size.html.erb
  playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_size.jsx
  playbook/app/pb_kits/playbook/pb_online_status/docs/example.yml
  playbook/app/pb_kits/playbook/pb_online_status/docs/index.js
  playbook/app/pb_kits/playbook/pb_online_status/online_status.rb
  playbook/app/pb_kits/playbook/pb_online_status/online_status.test.js
  playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
  playbook/spec/pb_kits/playbook/kits/online_status_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3566 [PBNTR-371] [3 of 4] Star Rating kit: add styles and animation
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_icon/icon.rb
  playbook/app/pb_kits/playbook/pb_star_rating/_star_rating.scss
  playbook/app/pb_kits/playbook/pb_star_rating/docs/example.yml
  playbook/app/pb_kits/playbook/pb_star_rating/index.js
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.html.erb
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.rb
  playbook/app/pb_kits/playbook/pb_star_rating/stars/utils.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/subcomponents/_star_rating_interactive.tsx
Labels: enhancement, milano, Product Approved, Code Approved

#3575 [PBNTR-332] Rails Typeahead does not accept global props if ismulti=false
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_multi_kit.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Labels: bug, milano, Product Approved, Code Approved

#3580 [Play-1325] Swift Changelog
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/layouts/changelog.html.erb
  playbook-website/app/views/pages/changelog_swift.html.erb
  playbook-website/config/initializers/global_variables.rb
  playbook-website/config/routes.rb
  playbook/SWIFT_CHANGELOG.md
Labels: enhancement, milano, Product Approved, Code Approved

#3581 [PLAY-1466] Updating datepicker doc for rails for formatting issue
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_description.md
Labels: bug, milano, Product Approved, Code Approved

#3582 [PLAY-1467] Horizontal default nav - fix alignment
  playbook/app/pb_kits/playbook/pb_nav/_horizontal_nav.scss
Labels: bug, Product Approved, Code Approved

#3601 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#3587 14.1.0 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3611 [PLAY-1492] Initial RC Github Action
  .github/workflows/github-actions-release-candidate.yml
Labels: milano, improvement

#3598 [PLAY-1475] Bumping "axe-core" dependency from 4.9.1 to 4.10.0
  playbook-website/package.json
  yarn.lock
Labels: dependencies, milano, alpha

#3618 Revert "Testing Dep Update"
  package.json
  yarn.lock
Labels: milano

#3620 Bumping axecore dependency to 4.10.0
  playbook-website/package.json
  yarn.lock
Labels: milano

#3578 [PBNTR-286] RTE Advanced Previewer + output styles (React)
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_previewer_mixin.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_tiptap_styles.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_advanced_preview.jsx
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml
  playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
Labels: milano, improvement, Product Approved, Code Approved

#3551 [PLAY-1387] Add minWidth global prop
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MinWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Overflow.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/min_width_jsx.txt
  playbook/app/entrypoints/playbook.scss
  playbook/app/pb_kits/playbook/pb_filter/filter.rb
  playbook/app/pb_kits/playbook/pb_popover/_popover.tsx
  playbook/app/pb_kits/playbook/tokens/_container.scss
  playbook/app/pb_kits/playbook/utilities/_min_width.scss
  playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/spacing.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3600 [PBNTR-415] Adding Star Rating form controls
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_star_rating/index.js
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.html.erb
  playbook/app/pb_kits/playbook/pb_star_rating/star_rating.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3552 [PBNTR-258] NEW Pagination kit in React
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.scss
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.tsx
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default.jsx
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default_rails.md
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default_react.md
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_page_change.jsx
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_page_change_react.md
  playbook/app/pb_kits/playbook/pb_pagination/docs/data.js
  playbook/app/pb_kits/playbook/pb_pagination/docs/example.yml
  playbook/app/pb_kits/playbook/pb_pagination/docs/index.js
Labels: new kit, milano, alpha, Product Approved, Code Approved

#3596 [PLAY-1411] Badge Notification Error Variant
  playbook/app/pb_kits/playbook/pb_badge/_badge.scss
  playbook/app/pb_kits/playbook/pb_badge/_badge.tsx
  playbook/app/pb_kits/playbook/pb_badge/badge.rb
  playbook/app/pb_kits/playbook/pb_badge/badge.test.js
  playbook/app/pb_kits/playbook/pb_badge/docs/_badge_notification.html.erb
  playbook/app/pb_kits/playbook/pb_badge/docs/_badge_notification.jsx
  playbook/spec/pb_kits/playbook/kits/badge_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved

#3599 [PLAY-1490] Dialog Kit Loading state buttons
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.rb
  playbook/app/pb_kits/playbook/pb_dialog/dialogHelper.js
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.rb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_loading.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_loading.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
Labels: milano, Product Approved

#3602 [PBNTR-441] Bug Fix: Rails Advanced Table Dark Mode
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
Labels: bug, milano, Product Approved, Code Approved

#3607 [PBNTR-416] Form pill 3 of 5: Sizes
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx
  playbook/app/pb_kits/playbook/pb_form_pill/docs/example.yml
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.rb
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3615 Export Highchart Theming Files
  playbook/app/javascript/theme.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3626 [PBNTR-470] Fixing Phone Number Input kit flag misalignment
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
Labels: bug, milano, Product Approved, Code Approved

#3613 [WIP] Upgrade view_component gem
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: milano, improvement, alpha

#3614 [PBNR-455] Gantt Chart Beta Kit
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/entrypoints/playbook.scss
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_gantt_chart/_gantt_chart.scss
  playbook/app/pb_kits/playbook/pb_gantt_chart/_gantt_chart.tsx
  playbook/app/pb_kits/playbook/pb_gantt_chart/docs/_gantt_chart_default.jsx
  playbook/app/pb_kits/playbook/pb_gantt_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_gantt_chart/docs/index.js
  playbook/app/pb_kits/playbook/pb_gantt_chart/gantt_chart.test.jsx
Labels: new kit, milano, alpha, Product Approved, Code Approved

#3560 [PLAY-1447] Add required Icons to kits
  playbook/app/pb_kits/playbook/pb_badge/_badge.tsx
  playbook/app/pb_kits/playbook/pb_button/_button.tsx
  playbook/app/pb_kits/playbook/pb_button/button.html.erb
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_date_time/dateTime.test.js
  playbook/app/pb_kits/playbook/pb_dialog/_close_icon.tsx
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog_header.rb
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/subcomponents/_star_rating_display.tsx
  playbook/app/pb_kits/playbook/pb_star_rating/subcomponents/_star_rating_interactive.tsx
  playbook/app/pb_kits/playbook/pb_time/_time.tsx
  playbook/app/pb_kits/playbook/pb_time/time.html.erb
  playbook/app/pb_kits/playbook/pb_time/time.rb
  playbook/app/pb_kits/playbook/utilities/icons/allicons.tsx
  playbook/app/pb_kits/playbook/utilities/icons/clock.svg
  playbook/app/pb_kits/playbook/utilities/icons/spinner.svg
  playbook/app/pb_kits/playbook/utilities/icons/times.svg
Labels: milano, alpha, Product Approved

#3634 Version Bump 14.2.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3635 [PBIOS-489] Announce 6.1.0 Release
  playbook/SWIFT_CHANGELOG.md
Labels: milano, docs, swiftUI, nitro

#3641 [PLAY-1527] Hosting the right phone number input flags png file
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
Labels: bug, milano, alpha

#3597 [PLAY-1473] Bump "@types/react-highlight-words" from 0.16.4 to 0.16.5
  playbook/package.json
  yarn.lock
Labels: dependencies, milano, javascript, alpha
