Repository powerhome/playbook, pull requests merged in 2024-01, with the labels that each got.

#2985 [PBIOS-231] Reaction Button Variant Docs
  playbook/app/pb_kits/playbook/pb_button/docs/_button_props_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction_swift.md
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
Labels: ready for release, docs

#2983 [PBIOS-181] Select docs
  playbook/app/pb_kits/playbook/pb_select/docs/_select_default_swift.md
  playbook/app/pb_kits/playbook/pb_select/docs/_select_error_swift.md
  playbook/app/pb_kits/playbook/pb_select/docs/_select_props_table.md
  playbook/app/pb_kits/playbook/pb_select/docs/example.yml
Labels: ready for release, docs

#2979 [PBIOS-163] Swift dialog docs
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default_swift.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_props_table.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes_swift.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status_swift.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
Labels: ready for release, docs

#2986 [PLAY-1119] Docs: add `xxl` as Max Width value
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
  playbook-website/app/javascript/site_styles/_visual_guidelines.scss
  playbook-website/app/views/pages/visual_guidelines.html.erb
Labels: bug, milano, ready for release

#2977 [PLAY-1114] Docs: list nav items alphabetically within their categories
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/javascript/components/Website/src/hooks/loaders.ts
  playbook/spec/pb_kits/playbook/kits/timestamp_spec.rb
Labels: milano, ready for release, improvement

#2973 [PLAY-1109] 🐞 Display prop responsive arguments are blocking font color
  playbook/app/pb_kits/playbook/pb_detail/_detail.scss
  playbook/app/pb_kits/playbook/pb_detail/_detail.tsx
  playbook/app/pb_kits/playbook/pb_detail/detail.rb
  playbook/app/pb_kits/playbook/pb_detail/detail.test.jsx
  playbook/spec/pb_kits/playbook/kits/detail_spec.rb
Labels: bug, milano, alpha

#2975 [PLAY-1110] Convert Truncate Prop to Global
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/pb_body/_body.scss
  playbook/app/pb_kits/playbook/pb_body/_body.tsx
  playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss
  playbook/app/pb_kits/playbook/pb_body/body.rb
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/_title_mixin.scss
  playbook/app/pb_kits/playbook/pb_title/title.rb
  playbook/app/pb_kits/playbook/utilities/_truncate.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/app/pb_kits/playbook/utilities/test/globalProps/truncate.test.js
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/truncate.rb
  playbook/spec/playbook/global_props/truncate_spec.rb
Labels: enhancement, milano

#3005 13.15.0 Changelog
  playbook/CHANGELOG.md
Labels: milano

#2980 [PBIOS-173] Swift nav docs
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_horizontal_bold_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_horizontal_default_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_horizontal_subtle_no_highlight_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_horizontal_subtle_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_props_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_vertical_bold_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_vertical_default_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_vertical_subtle_no_highlight_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/_nav_vertical_subtle_swift.md
  playbook/app/pb_kits/playbook/pb_nav/docs/example.yml
Labels: ready for release, docs

#2984 [PBIOS-162] Collapsible Docs
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_colors_swift.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_default_swift.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_props_table.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_sizes_swift.md
  playbook/app/pb_kits/playbook/pb_collapsible/docs/example.yml
Labels: ready for release, docs

#3031 Fixes for Broken Gauge Kit
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts
Labels: bug, milano

#2965 [PLAY-1100] 🌐 Website - Icons index foundation 🌐
  .npmrc
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/Icons/index.tsx
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/views/pages/icons.html.erb
  playbook-website/config/routes.rb
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement

#2990 [PLAY-1120] Lint Date Picker kit
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/quickPick.tsx
Labels: milano, ready for release, improvement, alpha

#3011 [PLAY-1108] Fix Telemetry Links
  milano.production.yml
  milano.staging.yml
Labels: bug, milano, ready for release

#3029 [PLAY-1076] Adding components filter
  playbook-website/app/javascript/components/Website/src/components/KitCard/index.tsx
  playbook-website/app/javascript/components/Website/src/components/KitFilter/RailsSVG.tsx
  playbook-website/app/javascript/components/Website/src/components/KitFilter/ReactSVG.tsx
  playbook-website/app/javascript/components/Website/src/components/KitFilter/SwiftSVG.tsx
  playbook-website/app/javascript/components/Website/src/components/KitFilter/index.tsx
  playbook-website/app/javascript/components/Website/src/components/KitFilter/styles.scss
  playbook-website/app/javascript/components/Website/src/pages/CategoryShow/index.tsx
  playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
Labels: milano, ready for release, improvement

#3037 [PLAY-1131] Select kit: add inline variant with visible chevron
  playbook/app/pb_kits/playbook/pb_select/_select.scss
  playbook/app/pb_kits/playbook/pb_select/_select.tsx
  playbook/app/pb_kits/playbook/pb_select/docs/_select_inline_show_arrow.html.erb
  playbook/app/pb_kits/playbook/pb_select/docs/_select_inline_show_arrow.jsx
  playbook/app/pb_kits/playbook/pb_select/docs/example.yml
  playbook/app/pb_kits/playbook/pb_select/docs/index.js
  playbook/app/pb_kits/playbook/pb_select/select.rb
Labels: milano, ready for release, improvement, alpha

#3071 Updates to PLAY-1141
  playbook-website/app/javascript/components/Icons/index.tsx
  playbook-website/config/webpack/environment.js
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
  yarn.lock
Labels: do not merge

#3030 [PLAY-1136] Bump react-select
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_highlight.jsx
  playbook/package.json
  yarn.lock
Labels: milano, ready for release, alpha

#3046 [PLAY-1084] Linting K-O
  playbook/app/pb_kits/playbook/pb_label_value/_label_value.tsx
  playbook/app/pb_kits/playbook/pb_layout/_layout.tsx
  playbook/app/pb_kits/playbook/pb_layout/layout.test.js
  playbook/app/pb_kits/playbook/pb_legend/_legend.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Slides.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Thumbnail.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Carousel/index.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/Header/_lightbox_header.tsx
  playbook/app/pb_kits/playbook/pb_lightbox/_lightbox.tsx
  playbook/app/pb_kits/playbook/pb_line_graph/_line_graph.tsx
  playbook/app/pb_kits/playbook/pb_list/_list.tsx
  playbook/app/pb_kits/playbook/pb_list/_list_item.tsx
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
  playbook/app/pb_kits/playbook/pb_map/_map.tsx
  playbook/app/pb_kits/playbook/pb_map/_map_controls.tsx
  playbook/app/pb_kits/playbook/pb_map/_map_custom_button.tsx
  playbook/app/pb_kits/playbook/pb_message/_message.tsx
  playbook/app/pb_kits/playbook/pb_message/_message_mention.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.tsx
  playbook/app/pb_kits/playbook/pb_nav/_item.tsx
  playbook/app/pb_kits/playbook/pb_nav/_nav.tsx
Labels: improvement, alpha

#3072 [PLAY-1145] Move Icon Page
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/Website/src/pages/IconList/index.tsx
  playbook-website/app/javascript/packs/app.js
  playbook-website/app/javascript/packs/application.js
  playbook-website/app/views/pages/icons.html.erb
  playbook-website/config/routes.rb
Labels: milano, ready for release, improvement
