Repository powerhome/playbook, pull requests merged in 2024-11, with the labels that each got.

#3864 [PLAY-1571] Add dependencies to getting started page
  playbook-website/app/views/guides/getting_started/dependencies.md
  playbook-website/config/initializers/global_variables.rb
Labels: milano, improvement, Code Approved

#3865 [PLAY-1618] Font Awesome Setup Documentation - Phase 1
  playbook-website/app/views/guides/getting_started/font_awesome.md
  playbook-website/config/initializers/global_variables.rb
Labels: milano, improvement, Product Approved, Code Approved

#3801 [PLAY-1586] Timeline Sub Sub Components
  playbook/app/pb_kits/playbook/pb_timeline/_item.tsx
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.tsx
  playbook/app/pb_kits/playbook/pb_timeline/detail.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/detail.rb
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_children.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_children.jsx
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_children.md
  playbook/app/pb_kits/playbook/pb_timeline/docs/example.yml
  playbook/app/pb_kits/playbook/pb_timeline/docs/index.js
  playbook/app/pb_kits/playbook/pb_timeline/item.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/item.rb
  playbook/app/pb_kits/playbook/pb_timeline/label.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/label.rb
  playbook/app/pb_kits/playbook/pb_timeline/step.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/step.rb
  playbook/app/pb_kits/playbook/pb_timeline/subcomponents/Detail.tsx
  playbook/app/pb_kits/playbook/pb_timeline/subcomponents/Label.tsx
  playbook/app/pb_kits/playbook/pb_timeline/subcomponents/Step.tsx
  playbook/app/pb_kits/playbook/pb_timeline/subcomponents/index.tsx
  playbook/app/pb_kits/playbook/pb_timeline/timeline.test.js
  playbook/spec/pb_kits/playbook/kits/timeline_detail_spec.rb
  playbook/spec/pb_kits/playbook/kits/timeline_label_spec.rb
  playbook/spec/pb_kits/playbook/kits/timeline_step_spec.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved

#3885 [PLAY-1610] Add details to dependencies docs
  playbook-website/app/views/guides/getting_started/dependencies.md
  playbook-website/app/views/guides/getting_started/react_setup.md
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved

#3878 [PLAY-1619] Font Awesome Setup Docs: JS Bundle and Asset Pipeline - Phase 2
  playbook-website/app/views/guides/getting_started/font_awesome.md
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved

#3855 [PLAY-1550] Bump lazysizes from 5.2.2 to 5.3.2
  playbook/package.json
  yarn.lock
Labels: dependencies, milano, Ready for Release, alpha, Product Approved, Code Approved

#3857 [PBNTR-633] Fixing parsing kits props
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
Labels: milano, Ready for Release, improvement, alpha, Product Approved, Code Approved

#3833 [PLAY-1587] Group hover Global Prop
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/GroupHover.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/group_hover_jsx.txt
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/hover.rb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved

#3879 [PLAY-1551] Bump @tiptap/extension-document from 2.1.12 to 2.6.6
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, alpha, Code Approved, Minor

#3889 [PBNTR-666] Custom Cells for Advanced Table First Column
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell.jsx
Labels: enhancement, milano, alpha, Product Approved

#3876 [PBNTR-485] Beta Skeleton Loading Kit- React
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/entrypoints/playbook.scss
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_skeleton_loading/_skeleton_loading.scss
  playbook/app/pb_kits/playbook/pb_skeleton_loading/_skeleton_loading.tsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/_skeleton_loading_mixins.scss
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_border_radius.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_border_radius.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_color.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_color.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_default.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_default.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_layout.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_layout.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/example.yml
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/index.js
  playbook/app/pb_kits/playbook/pb_skeleton_loading/skeleton_loading.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/skeleton_loading.rb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/skeleton_loading.test.jsx
  playbook/spec/pb_kits/playbook/kits/skeleton_loading_spec.rb
Labels: new kit, milano, Ready for Release, Product Approved, Code Approved

#3873 [PLAY-1627] Fix Height Prop for HtmlOptions Support
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx
  playbook/app/pb_kits/playbook/pb_flex/_flex.tsx
  playbook/app/pb_kits/playbook/pb_flex/_flex_item.tsx
  playbook/app/pb_kits/playbook/pb_flex/flex_item.html.erb
  playbook/app/pb_kits/playbook/pb_flex/flex_item.rb
  playbook/app/pb_kits/playbook/pb_popover/_popover.tsx
  playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/kit_base.rb
Labels: bug, milano, alpha, Product Approved, Code Approved, Minor

#3897 Update CHANGELOG.md 14.7.0
  playbook/CHANGELOG.md
Labels: milano

#3863 [PBNTR-692] Draggable in Rails
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/draggable.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/draggable.rb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.rb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_item.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_item.rb
  playbook/app/pb_kits/playbook/pb_draggable/index.js
Labels: new kit, milano, Product Approved, Code Approved, minor

#3904 Fixing Github Action Errors
  .github/workflows/github-actions-release-candidate.yml
Labels: bug, milano, minor

#3906 Small Change to Test RC Process
  playbook/app/pb_kits/playbook/pb_card/docs/_card_light.md
Labels: milano, minor

#3909 Testing RC Action
  playbook/app/pb_kits/playbook/pb_card/docs/_card_light.md
Labels: alpha, minor

#3893 [PBNTR-667] Rails Typeahead Form Integration
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_loading.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/index.ts
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/lib/playbook/forms/builder/typeahead_field.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3903 PLAY-1590 | Timeline Small Variant: Add "Gap" Prop to Timeline Kit
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.tsx
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_gap.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_gap.jsx
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_gap.md
  playbook/app/pb_kits/playbook/pb_timeline/docs/example.yml
  playbook/app/pb_kits/playbook/pb_timeline/docs/index.js
  playbook/app/pb_kits/playbook/pb_timeline/timeline.rb
  playbook/app/pb_kits/playbook/pb_timeline/timeline.test.js
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#3907 [PBNTR-637] Adding defaultDate prop to Date Picker Quick Pick variant
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_default_date.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_default_date.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_default_date.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/quickPick.tsx
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3874 [PLAY-1603] Add color hover docs and fix background hover
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx
  playbook-website/app/views/pages/code_snippets/hover_jsx.txt
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/app/pb_kits/playbook/utilities/test/globalProps/hover.test.js
  playbook/lib/playbook/hover.rb
  playbook/spec/playbook/global_props/hover_spec.rb
Labels: enhancement, milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#3905 [PLAY-1604] Global Hover Visibility Prop
  playbook-website/app/javascript/components/VisualGuidelines/Examples/GroupHover.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx
  playbook-website/app/views/pages/code_snippets/group_hover_jsx.txt
  playbook-website/app/views/pages/code_snippets/hover_jsx.txt
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#3891 [PLAY-1647] Remove react modal from drawer
  playbook/app/pb_kits/playbook/pb_drawer/_drawer.scss
  playbook/app/pb_kits/playbook/pb_drawer/_drawer.tsx
  playbook/app/pb_kits/playbook/pb_drawer/drawer.test.jsx
Labels: milano, Needs Review

#3916 Revert "[PBNTR-667] Rails Typeahead Form Integration"
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_loading.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/index.ts
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/lib/playbook/forms/builder/typeahead_field.rb
Labels: milano, minor

#3919 Version Bump 14.8.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor

#3901 [PBIOS-601] Update playbook-swift changelog
  playbook/SWIFT_CHANGELOG.md
Labels: milano, Code Approved, minor

#3875 [PLAY-1608] Dependency Display: Add flex section for summary display [2 of 2]
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/menu.yml
  playbook/lib/generators/kit/kit_generator.rb
Labels: milano, improvement, Product Approved, Code Approved, minor

#3933 [PBNTR-712] Dropdown Rails to have Position Absolute on Container
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.rb
Labels: bug, milano, minor

#3922 [PLAY-1625] Fix For PhoneNumberInput CSS Conflict
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: milano, alpha, Code Approved, minor

#3890 [PLAY-1663] Timeline Kit: Add a Vertical "With Children " doc example
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_children.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_children.jsx
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#3910 [PLAY-1648] Height Global Props
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Height.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxHeight.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MinHeight.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MinWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/height_jsx.txt
  playbook-website/app/views/pages/code_snippets/max_height_jsx.txt
  playbook-website/app/views/pages/code_snippets/min_height_jsx.txt
  playbook/app/entrypoints/playbook.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_default.html.erb
  playbook/app/pb_kits/playbook/tokens/_height.scss
  playbook/app/pb_kits/playbook/tokens/exports/_height.module.scss
  playbook/app/pb_kits/playbook/utilities/_height.scss
  playbook/app/pb_kits/playbook/utilities/_max_width.scss
  playbook/app/pb_kits/playbook/utilities/_min_width.scss
  playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/height.rb
  playbook/lib/playbook/kit_base.rb
  playbook/lib/playbook/max_height.rb
  playbook/lib/playbook/min_height.rb
Labels: milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3917 [PBNTR-701] Revert "Revert "[PBNTR-667] Rails Typeahead Form Integration""
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_loading.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/index.ts
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/lib/playbook/forms/builder/typeahead_field.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3920 Update CHANGELOG.md 14.8.0
  playbook/CHANGELOG.md
Labels: milano, minor

#3913 [PBNTR-661] Create a "stickyLeftcolumn" prop for the Table kit
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns_react.md
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_table/styles/_all.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_scroll.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_sticky_columns.scss
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3952 [PBNTR-628] Implementing Rails Advanced Table Custom Cell with kits
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.rb
Labels: enhancement, milano, Code Approved, minor

#3958 [PBNTR-713] Fixes for Custom Trigger not Working
  playbook/app/pb_kits/playbook/pb_dropdown/utilities/subComponentHelper.tsx
Labels: bug, milano, alpha, Product Approved, Code Approved, minor

#3949 [PLAY-1630] Add Red "Danger" Button Variant for Delete Actions
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_button/_button.tsx
  playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.jsx
  playbook/app/pb_kits/playbook/pb_button/docs/_button_default.md
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#3944 [PLAY-1649] Roll Out Height Global Props
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
  playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx
  playbook/app/pb_kits/playbook/pb_drawer/_drawer.tsx
  playbook/app/pb_kits/playbook/pb_image/_image.tsx
  playbook/app/pb_kits/playbook/pb_layout/_layout.tsx
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.tsx
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
Labels: milano, Ready for Release, improvement, alpha, Product Approved, Code Approved, minor

#3921 [PLAY-1615] Move negative sign to left of currency sign
  playbook/app/pb_kits/playbook/pb_currency/_currency.tsx
  playbook/app/pb_kits/playbook/pb_currency/currency.html.erb
  playbook/app/pb_kits/playbook/pb_currency/currency.rb
  playbook/app/pb_kits/playbook/pb_currency/currency.test.js
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_negative.html.erb
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_negative.jsx
  playbook/app/pb_kits/playbook/pb_currency/docs/example.yml
  playbook/app/pb_kits/playbook/pb_currency/docs/index.js
  playbook/spec/pb_kits/playbook/pb_currency/currency_spec.rb
Labels: bug, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#3951 [PLAY-1658] Dependency update/upgrade-@tanstack/react-table (8.9.2 -> 8.20.5)
  playbook/package.json
  yarn.lock
Labels: milano, Ready for Release, improvement, alpha, Product Approved, Code Approved, minor

#3926 [PLAY-1598] Bump @floating-ui/react from 0.22.2 to 0.26.23
  playbook/package.json
  yarn.lock
Labels: milano, Ready for Release, improvement, alpha, Product Approved, Code Approved, minor

#3943 [PLAY-1680] Width Global Prop
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/Width.tsx
  playbook-website/app/javascript/components/VisualGuidelines/index.tsx
  playbook-website/app/views/pages/code_snippets/max_width_jsx.txt
  playbook-website/app/views/pages/code_snippets/width_jsx.txt
  playbook/app/entrypoints/playbook.scss
  playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.tsx
  playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.html.erb
  playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.rb
  playbook/app/pb_kits/playbook/utilities/_max_width.scss
  playbook/app/pb_kits/playbook/utilities/_min_width.scss
  playbook/app/pb_kits/playbook/utilities/_width.scss
  playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/spacing.rb
  playbook/spec/pb_kits/playbook/kits/progress_simple_spec.rb
Labels: milano, Ready for Release, improvement, alpha, Product Approved, Code Approved, minor
