Repository powerhome/playbook, pull requests merged in 2024-04, with the labels that each got.

#3318 [PBNTR-242] Hotfix: Remove advanced_table_example_mock_data.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/advanced_table_example_mock_data.rb
Labels: bug, milano

#3326 Remove rails upper version limit in gemspec
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: bug, milano, alpha

#3309 [PBFIG-195] Design Guidelines: Spacing
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/guides/design_guidelines/spacing_guidelines.md
Labels: milano, improvement, docs, Product Approved, Code Approved

#3331 [PLAY-1269] DRY up the content_tag portion of Rails kits: Avatar
  playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb
  playbook/lib/playbook/kit_base.rb
Labels: milano

#3340 [PLAY-1297] Update text styles to prevent inconsistent Tiptap output
  playbook/app/pb_kits/playbook/pb_body/_body.scss
Labels: bug, milano, alpha, Product Approved, Code Approved

#3324 [PLAY-1284] Investigation: Test Typeahead with Consideration for New Prop for MenuList
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/MenuList.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/components/index.tsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_custom_menu_list.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_highlight.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js
Labels: enhancement, milano, alpha

#3332 [PBNTR-254] POC Bar Chart: Can we Show Negative Numbers, a Median line, and Stacked bar data
  playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx
  playbook/app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_negative_numbers.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_negative_numbers.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_stacked.html.erb
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_stacked.jsx
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_stacked.md
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/index.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved

#3344 13.24.0 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3345 13.23.0 CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#3346 Verified Version of Typography Guidelines
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/guides/design_guidelines/typography_guidelines.md
Labels: improvement, docs, Product Approved, Code Approved

#3347 [PLAY-1282] Update badge color for readability
  playbook/app/pb_kits/playbook/tokens/_colors.scss
Labels: enhancement, Product Approved, Code Approved

#3343 [PBNTR-261] New Kit: Dropdown
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/_playbook.scss
  playbook/app/pb_kits/playbook/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/context/index.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/hooks/useDropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/hooks/useHandleOnKeydown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownContainer.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownTrigger.tsx
  playbook/app/pb_kits/playbook/pb_list/_list_item.tsx
  playbook/app/pb_kits/playbook/playbook-doc.js
Labels: new kit, milano, alpha, Product Approved, Code Approved

#3348 [PLAY-998] Background kit remove empty inline styles/attributes
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
Labels: bug, milano, alpha, Product Approved, Code Approved

#3351 Add run.sh
  docs/README.md
  run.sh
Labels: milano, DX

#3355 [PBNTR-268] Dropdown Kit v2
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_default.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/hooks/useHandleOnKeydown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownTrigger.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/utilities/subComponentHelper.tsx
Labels: enhancement, milano, Product Approved, Code Approved

#3356 [PLAY-1126] add px to Max Width global prop values left aligned
  playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
Labels: milano, improvement, Product Approved, Code Approved

#3349 [PBIOS-344] Dialog Docs
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_props_swift.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
Labels: docs, Product Approved, Code Approved

#3361 13.25.0 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: milano

#3362 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano

#3369 [PLAY-1304] fix Kit Collection page when Pagination is present
  playbook-website/app/controllers/pages_controller.rb
Labels: bug, Product Approved, Code Approved

#3366 [PLAY-761] Global padding props don't affect Buttons
  playbook/app/pb_kits/playbook/pb_button/_button.scss
Labels: bug, alpha, Product Approved, Code Approved

#3316 [PBIOS-339] Currency Docs
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_alignment_swift.md
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_props_swift.md
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_size_swift.md
  playbook/app/pb_kits/playbook/pb_currency/docs/example.yml
Labels: docs, swiftUI, Product Approved, Code Approved

#3363 [PLAY-1312] Dialog kit Cancel button hidden on mobile view
  playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Labels: bug, Product Approved, Code Approved

#3342 [PLAY-1263] Install Power fonts
  playbook-website/app/javascript/site_styles/main.scss
  playbook-website/app/views/layouts/_head.html.erb
  playbook-website/package.json
  yarn.lock
Labels: milano, Product Approved, Code Approved

#3370 [PLAY-939] Section Separator Vertical Variant Fixes
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator_mixin.scss
Labels: bug, milano, Product Approved, Code Approved
