Repository powerhome/playbook, pull requests merged in 2025-09, with the labels that each got.

#5104 [PLAY-2402] Playbook Website: Add Missing icons
  playbook-website/app/assets/icons.json
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, minor, Inactive RC

#5123 [PLAY-2395] Playbook Website: Create Text Align, Opacity and Screen Sizes token pages
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Opacity.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/ScreenSizes.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/TextAlign.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/TokensExamplesIndex.tsx
  playbook-website/config/global_props_and_tokens.yml
Labels: milano, improvement, minor, Inactive RC

#5114 [PLAY-2113] Typeahead Kit: Fix Clear All Docs - Rails
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_color.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_color.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_without_pills.html.erb
Labels: milano, improvement, minor, Inactive RC

#5100 [PLAY-2415] Playbook Website: Set up scaffold for React Views
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/javascript/components/Website/index.tsx
  playbook-website/app/javascript/components/Website/src/components/KitCard/index.tsx
  playbook-website/app/javascript/components/Website/src/components/LiveExamples/LiveExampleReact.tsx
  playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/highchartsLoader.tsx
  playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/index.ts
  playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/maplibreLoader.tsx
  playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/tiptapLoader.tsx
  playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/utilities.ts
  playbook-website/app/javascript/components/Website/src/components/PageContainer/index.tsx
  playbook-website/app/javascript/components/Website/src/layouts/LayoutRight.tsx
  playbook-website/app/javascript/components/Website/src/pages/CategoryShow/index.tsx
  playbook-website/app/javascript/components/Website/src/pages/CategoryShow/styles.scss
  playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
  playbook-website/app/javascript/components/Website/src/pages/KitShow/index.tsx
  playbook-website/app/javascript/components/app.tsx
  playbook-website/app/javascript/site_styles/main.scss
  playbook-website/app/javascript/site_styles/website_new.scss
  playbook-website/app/views/layouts/application_beta.html.erb
  playbook-website/config/routes.rb
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, minor, Inactive RC

#5152 [PLAY-2435] Global Props: Create Width, Min Width and Max Width pages
  playbook-website/app/javascript/components/GlobalPropsAndTokens/Data/GlobalPropsCards.ts
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/MaxWidth.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/MinWidth.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Width.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/GlobalPropsExamplesIndex.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/GlobalPropsIndex.tsx
  playbook-website/config/global_props_and_tokens.yml
Labels: milano, improvement, minor, Inactive RC

#5024 [PLAY-1986] Loading Inline kit: Create Solid Variant Based on Design Handoff
  playbook-website/app/assets/icons.json
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_variant.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_variant.jsx
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/example.yml
  playbook/app/pb_kits/playbook/pb_loading_inline/docs/index.js
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.html.erb
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#5166 [PLAY-1980] Card kit: Add Right Side Highlight
  playbook/app/pb_kits/playbook/pb_card/_card.scss
  playbook/app/pb_kits/playbook/pb_card/_card.tsx
  playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss
  playbook/app/pb_kits/playbook/pb_card/docs/_card_highlight.html.erb
  playbook/app/pb_kits/playbook/pb_card/docs/_card_highlight.jsx
Labels: milano, improvement, minor, Inactive RC

#5099 [PLAY-2451] Nav kit - Accessibility
  playbook/app/pb_kits/playbook/pb_nav/_item.tsx
  playbook/app/pb_kits/playbook/pb_nav/item.html.erb
Labels: enhancement, alpha, minor, Inactive RC

#5167 [PLAY-2453] Form Kit: Text Field (i.e., Text Input Kit) Attribute Props - Rails
  playbook/lib/playbook/forms/builder/form_field_builder.rb
  playbook/spec/playbook/pb_forms_helper_spec.rb
Labels: enhancement, milano, alpha, minor

#5170 [PLAY-2420] Advanced Table: First Column Border not rendering in Safari and Chrome
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_vertical_border.jsx
Labels: milano, improvement, alpha, minor, Inactive RC

#5223 [PLAY-2511] Update Playbook Icons
  playbook-website/app/assets/icons.json
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
  playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.rb
  yarn.lock
Labels: milano, improvement, alpha, minor, Inactive RC
