Repository powerhome/playbook, pull requests merged in 2025-08, with the labels that each got.

#4957 Version Bump to 14.24.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: improvement, minor, Inactive RC

#4959 Update CHANGELOG.md for 14.24.0
  playbook/CHANGELOG.md
Labels: milano, improvement, minor, Inactive RC

#4919 [PLAY-2329] Advanced Table: Fix Conflict Between Sticky Header, Pinned Top Row, and verticalBorder in Advanced Table
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_vertical_border.scss
Labels: bug, milano, alpha, minor

#4960 [PLAY-2346] Pagination kit: Sync Pagination's internal state with the external current prop - React
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.test.jsx
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.tsx
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_external_control.jsx
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_external_control_react.md
  playbook/app/pb_kits/playbook/pb_pagination/docs/example.yml
  playbook/app/pb_kits/playbook/pb_pagination/docs/index.js
Labels: enhancement, milano, alpha, minor, Inactive RC

#4991 [PLAY-2373] Update Playbook Icons
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, minor, Inactive RC

#4990 [PLAY-2343] Add @tiptap/react to External Dependencies in vite.config.ts
  playbook/vite.config.ts
Labels: milano, improvement, alpha, minor, Inactive RC

#4992 [PLAY-2374] Remove Fontawesome Free from Playbook
  playbook/package.json
  yarn.lock
Labels: milano, improvement, alpha, minor

#5021 Version Bump to 14.25.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: improvement, minor, Inactive RC

#5006 [PLAY-2116] Date Picker: `cursor` global prop is not working
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/text_input.rb
Labels: bug, milano, alpha, minor

#5045 [PLAY-2379] Date kit: Add Jest Test Coverage - React
  playbook/app/pb_kits/playbook/pb_date/date.test.js
Labels: Ready for Release, improvement, alpha, minor, Inactive RC

#5062 [PLAY-2393] Playbook Website: Create Animation and Vertical Align Token Pages
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Animation.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/bezier.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/ease.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeIn.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInBack.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInCirc.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInCubic.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInExpo.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOut.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutBack.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutCirc.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutCubic.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutExpo.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutQuad.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutQuart.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutQuint.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInOutSine.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInQuad.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInQuart.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInQuint.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeInSine.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOut.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutBack.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutCirc.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutCubic.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutExpo.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutQuad.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutQuart.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutQuint.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/easeOutSine.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/index.ts
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/AnimationImages/linear.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/VerticalAlign.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/TokensExamplesIndex.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/Templates/Subcomponents/ValueCardWithTooltip.tsx
  playbook-website/app/javascript/site_styles/_global_props_and_tokens.scss
  playbook-website/config/global_props_and_tokens.yml
Labels: milano, improvement, minor, Inactive RC
