Repository powerhome/playbook, pull requests merged in 2025-01, with the labels that each got.

#4072 [PBNTR-782] Fixes for Timestamp Spec Failing on Year Change
  playbook/spec/pb_kits/playbook/kits/timestamp_spec.rb
Labels: bug, milano, minor

#4062 [PBNTR-775] Formatting input text mask default value
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/inputMask.ts
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#4029 [PLAY-1700] Bug - Remove Default Padding in Section Separator When Children are Passed
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss
Labels: bug, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#4036 [PLAY-1540] Section Separator: Add Color Option
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_color.html.erb
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_color.jsx
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_color.md
  playbook/app/pb_kits/playbook/pb_section_separator/docs/example.yml
  playbook/app/pb_kits/playbook/pb_section_separator/docs/index.js
  playbook/app/pb_kits/playbook/pb_section_separator/section_separator.rb
  playbook/spec/pb_kits/playbook/kits/section_seperator_spec.rb
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor

#4045 [PLAY-1614] Icon Circle Size Bug Fix
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss
Labels: bug, milano, Ready for Release, Product Approved, Code Approved, minor

#4068 [PBNTR-762] Skeleton Loading Component Build - Rails
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_skeleton_loading/_skeleton_loading.scss
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_description.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_border_radius.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_border_radius_rails.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_border_radius_react.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_color.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_default.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_filter.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_filter.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width_rails.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_height_width_react.md
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_layout.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_user.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/_skeleton_loading_user.jsx
  playbook/app/pb_kits/playbook/pb_skeleton_loading/docs/example.yml
  playbook/app/pb_kits/playbook/pb_skeleton_loading/skeleton_loading.html.erb
  playbook/app/pb_kits/playbook/pb_skeleton_loading/skeleton_loading.rb
  playbook/spec/pb_kits/playbook/kits/skeleton_loading_spec.rb
Labels: enhancement, new kit, milano, Ready for Release, Product Approved, Code Approved, minor

#4071 [PBNTR-777] Double Scroll Bars on "sticky" doc examples
  playbook/app/pb_kits/playbook/pb_table/styles/_scroll.scss
Labels: bug, milano, Ready for Release, Product Approved, Code Approved, minor

#4052 [PBNTR-771] Advanced Table Rails Refactor and Multi Column Headers
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_multiple.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_subrow_header.html.erb
Labels: enhancement, milano, Product Approved, minor

#4037 [PLAY-1660] Upgrade react-dropzone to 14.3.5 and File Upload Kit
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_accept.jsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_custom_description.jsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_max_size.jsx
  playbook/package.json
  yarn.lock
Labels: milano, improvement, alpha, Code Approved, minor, Stale

#4089 [PLAY-1776] Update Kits To Remove Deprecation Warning With Division
  playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.scss
  playbook/app/pb_kits/playbook/pb_badge/_badge.scss
  playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_input_styles.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.scss
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss
  playbook/app/pb_kits/playbook/pb_label_value/_label_value.scss
  playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.scss
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_pill/_pill.scss
  playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
  playbook/app/pb_kits/playbook/pb_select/_select.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.scss
Labels: bug, milano, Code Approved, minor

#4101 [PBNTR-784] Fixing gaps between sticky right columns
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
Labels: bug, milano, Code Approved, minor

#4067 [PLAY-1682] Create Global Gap Prop
  playbook-website/app/javascript/components/AvailableProps/globalPropsValues.ts
  playbook-website/app/javascript/components/VisualGuidelines/Examples/FlexBox.tsx
  playbook/app/entrypoints/playbook.scss
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.tsx
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_gap.html.erb
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_gap.jsx
  playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_gap.md
  playbook/app/pb_kits/playbook/pb_timeline/timeline.rb
  playbook/app/pb_kits/playbook/utilities/_gap.scss
  playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/classnames.rb
  playbook/lib/playbook/spacing.rb
Labels: milano, improvement, alpha, Code Approved, minor

#4104 Revert "[PLAY-1776] Update Kits To Remove Deprecation Warning With Division"
  playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.scss
  playbook/app/pb_kits/playbook/pb_badge/_badge.scss
  playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss
  playbook/app/pb_kits/playbook/pb_button/_button.scss
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_input_styles.scss
  playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss
  playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.scss
  playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss
  playbook/app/pb_kits/playbook/pb_label_value/_label_value.scss
  playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
  playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.scss
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_pill/_pill.scss
  playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss
  playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
  playbook/app/pb_kits/playbook/pb_select/_select.scss
  playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
  playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
  playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
  playbook/app/pb_kits/playbook/pb_toggle/_toggle.scss
Labels: minor

#4105 Version Bump 14.11.1
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor

#4103 Update CHANGELOG.md 14.11.0
  playbook/CHANGELOG.md
Labels: milano, minor

#4087 [PLAY-1801] 'Inactive RC' Label: Skip Later Steps
  .github/workflows/github-actions-release-candidate.yml
Labels: milano, Ready for Release, Product Approved, Code Approved, minor

#4107 [PBNTR-740] Advanced Table - Add Table Props to Rails kit
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_table_props.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_table_props_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_table_props_react.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
Labels: enhancement, milano, Code Approved, minor, Inactive RC

#4123 Scss fixes for Responsive Scroll for Table
  playbook/app/pb_kits/playbook/pb_table/styles/_scroll.scss
Labels: milano, alpha, minor

#4121 Add brakeman as a development dependency in playbook
  playbook/Gemfile.lock
  playbook/playbook_ui.gemspec
Labels: milano, improvement, alpha, minor

#4124 [PBNTR-718] Draggable Kit: Simplified API for SelectableList for Rails
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.rb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.html.erb
  playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
Labels: milano, improvement, alpha, Code Approved, minor

#4132 [PBNTR-719] Draggable Kit: Simplified API for List kit for Rails
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list_rails.md
  playbook/app/pb_kits/playbook/pb_list/item.html.erb
  playbook/app/pb_kits/playbook/pb_list/item.rb
  playbook/app/pb_kits/playbook/pb_list/list.html.erb
  playbook/app/pb_kits/playbook/pb_list/list.rb
Labels: milano, improvement, alpha, Code Approved, minor, Inactive RC

#4138 Update SWIFT_CHANGELOG.md
  playbook/SWIFT_CHANGELOG.md
Labels: milano, minor

#4135 [PBNTR-768] Adding sticky right column and refactoring PBTable enhanced element
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/table.html.erb
  playbook/app/pb_kits/playbook/pb_table/table.rb
  playbook/app/pb_kits/playbook/pb_table/utilities/addDataTitle.ts
  playbook/spec/pb_kits/playbook/kits/table_spec.rb
Labels: enhancement, milano, alpha, Code Approved, minor

#4097 [PLAY-1774] Fix Timeline Label and Step Spacing
  playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
Labels: bug, milano, Needs Review, alpha, minor

#4125 [PLAY-1720] Phone Number Input formatAsYouType Prop
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_format.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_format.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_format.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.test.js
  playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
Labels: enhancement, milano, Ready for Release, alpha, Code Approved, minor

#4106 [PLAY-1750] Convert Kits to Use Pb_content_tag
  playbook/app/pb_kits/playbook/pb_button/button.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.html.erb
  playbook/spec/pb_kits/playbook/kits/dropdown_spec.rb
Labels: enhancement, milano, Ready for Release, alpha, Code Approved, minor

#4130 [PLAY-1798] Enable Dark Mode in Loading Inline Text and Labels
  playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
Labels: enhancement, milano, Ready for Release, Code Approved, minor, Inactive RC

#4133 [PLAY-1797 ] DARK MODE AUDIT - Radio
  playbook/app/pb_kits/playbook/pb_radio/_radio.scss
  playbook/app/pb_kits/playbook/pb_radio/docs/_radio_custom_children.jsx
Labels: enhancement, milano, Ready for Release, Code Approved, minor, Inactive RC

#4136 [PLAY-1832] Fix Doc Typos
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_control.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subtle_variant.md
Labels: bug, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4137 [PLAY]-1715 Fix Website Markdown Code Indention
  playbook-website/app/javascript/site_styles/docs/_markdown.scss
  playbook-website/app/views/guides/getting_started/react_setup.md
Labels: bug, milano, Code Approved, minor, Inactive RC

#4122 [PBNTR-703] Add Expandable/Collapsible Rows to Basic Table Component - RAILS only
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.html.erb
  playbook/app/pb_kits/playbook/pb_collapsible/collapsible.rb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_react.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/styles/_collapsible.scss
  playbook/app/pb_kits/playbook/pb_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_row.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4142 [PBNTR-798] Make Date Picker Work within Turbo Frames
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.rb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_turbo_frames.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_turbo_frames_rails.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4140 [PLAY-1787] Selectable Icon - Dark Mode Audit
  playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.tsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_default.jsx
  playbook/app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_single_select.jsx
Labels: enhancement, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4154 [PLAY-1724] Dark Mode - Map Audit
  playbook-website/app/javascript/site_styles/map_styles/_map_default.scss
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4127 [PLAY-1772] Rails input masking
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask_rails.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_text_input/index.js
  playbook/app/pb_kits/playbook/pb_text_input/text_input.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/text_input.rb
  playbook/spec/pb_kits/playbook/kits/text_input_spec.rb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4152 [PLAY-1792] Typeahead Truncated Text Docs
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_truncated_text.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_truncated_text.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_truncated_text.md
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor, Inactive RC

#4141 [PLAY-1766] Icon button rails
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook.scss
  playbook/app/pb_kits/playbook/pb_icon_button/_icon_button.scss
  playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_default.html.erb
  playbook/app/pb_kits/playbook/pb_icon_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon_button/icon_button.html.erb
  playbook/app/pb_kits/playbook/pb_icon_button/icon_button.rb
  playbook/spec/pb_kits/playbook/kits/icon_button_spec.rb
Labels: new kit, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4139 [PLAY-1796] Dark Audit Multiple Users
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
  playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.tsx
  playbook/app/pb_kits/playbook/pb_multiple_users/multiple_users.html.erb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4028 [PLAY-1744] Drawer Kit Refactor
  playbook/app/pb_kits/playbook/pb_drawer/_drawer.scss
  playbook/app/pb_kits/playbook/pb_drawer/_drawer.tsx
  playbook/app/pb_kits/playbook/pb_drawer/context.ts
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_behavior.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_borders.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_breakpoints.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_default.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_menu.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_menu.md
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_overlay.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/_drawer_sizes.jsx
  playbook/app/pb_kits/playbook/pb_drawer/docs/example.yml
  playbook/app/pb_kits/playbook/pb_drawer/docs/index.js
  playbook/app/pb_kits/playbook/pb_drawer/drawer.test.jsx
  playbook/app/pb_kits/playbook/pb_drawer/hooks/useBreakpoint.tsx
  playbook/app/pb_kits/playbook/pb_drawer/hooks/useDrawerAnimation.tsx
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#4169 Version 14.12.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor, Inactive RC

#4172 [PBIOS-672] Update swift changelog
  playbook/SWIFT_CHANGELOG.md
Labels: milano, minor, Inactive RC

#4151 [PBNTR-743] Advanced Table - Add Responsiveness to Rails kit
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_responsive.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_subrow_header.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_subrow_header.rb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4161 [PBNTR-720] Draggable Kit: Simplified API for Card kit for Rails
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards_rails.md
Labels: milano, improvement, alpha, Code Approved, minor, Inactive RC

#4163 [PBNTR-802] Table kit: Add other collapsible/expandable row doc examples
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_content.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_content_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_content_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_rows_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_rows_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_table_rails.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_nested_table_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/table_row.rb
Labels: milano, improvement, Code Approved, minor, Inactive RC

#4098 [PBNTR-440] Enable Global Props for pb_form_with
  playbook/lib/playbook/pb_forms_global_props_helper.rb
  playbook/lib/playbook/pb_forms_helper.rb
Labels: enhancement, milano, alpha, Code Approved, minor

#4143 [PLAY-1759] Copy Button Kit - React Beta
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/entrypoints/playbook.scss
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_copy_button/_copy_button.scss
  playbook/app/pb_kits/playbook/pb_copy_button/_copy_button.tsx
  playbook/app/pb_kits/playbook/pb_copy_button/copy_button.test.jsx
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_default.jsx
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_from.jsx
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_from.md
  playbook/app/pb_kits/playbook/pb_copy_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_copy_button/docs/index.js
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
Labels: new kit, milano, Code Approved, minor

#4184 [PBNTR-843] Alignment Issue for AdvancedTable with Specific Usecases
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
Labels: bug, milano, alpha, minor

#4171 [PLAY-372] Search Results
  playbook-website/app/javascript/components/KitSearch.tsx
  playbook-website/package.json
Labels: improvement, Code Approved, minor

#4192 Update example app for Tech challenges
  examples/rails-react-example/app/assets/stylesheets/application.scss
  examples/rails-react-example/app/javascript/components/App.tsx
  examples/rails-react-example/app/views/pages/index.html.erb
Labels: improvement, minor

#4180 [PLAY]-1741 Advanced Table Highlight In Rails
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
Labels: enhancement, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4174 [PLAY-1799] Date Dark Mode Audit
  playbook/app/pb_kits/playbook/pb_date/_date.tsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_default.jsx
  playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.jsx
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4190 Fix disabled state for link
  playbook/app/pb_kits/playbook/pb_button/button.rb
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: milano, alpha, Code Approved, minor

#4153 [PLAY-1751] Convert Kits to Use pb_content_tag (File Upload, Filter, Form Group, and Form Pill)
  playbook/app/pb_kits/playbook/pb_file_upload/file_upload.html.erb
  playbook/app/pb_kits/playbook/pb_filter/filter.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/form_group.html.erb
  playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#4185 [PLAY-1788] Avatar - Dark Mode Audit
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_badge_component_overlay.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_circle_icon_component_overlay.jsx
Labels: enhancement, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4194 [PLAY-1501] Enable Lightweight User Names in User Kit
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  playbook/app/pb_kits/playbook/pb_user/docs/_user_light_weight.html.erb
  playbook/app/pb_kits/playbook/pb_user/docs/_user_light_weight.jsx
  playbook/app/pb_kits/playbook/pb_user/docs/_user_light_weight.md
  playbook/app/pb_kits/playbook/pb_user/docs/example.yml
  playbook/app/pb_kits/playbook/pb_user/docs/index.js
  playbook/app/pb_kits/playbook/pb_user/user.html.erb
  playbook/app/pb_kits/playbook/pb_user/user.rb
  playbook/app/pb_kits/playbook/pb_user/user.test.js
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4209 Example repo on Alpha for Free Icons to work
  examples/rails-react-example/Gemfile
  examples/rails-react-example/Gemfile.lock
  examples/rails-react-example/package.json
  examples/rails-react-example/yarn.lock
Labels: improvement, minor, Inactive RC

#4134 [PLAY-1790] Dark Mode Audit Table
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_background_kit.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_background_kit.jsx
  playbook/app/pb_kits/playbook/pb_table/styles/_desktop_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_mobile_collapse.scss
  playbook/app/pb_kits/playbook/pb_table/styles/_tablet_collapse.scss
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC
