Repository powerhome/playbook, pull requests merged in 2025-06, with the labels that each got.

#4645 [PLAY-2211] Draggable Kit: Fixes bug for cross container drag between 2 tables
  playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx
Labels: bug, milano, alpha, minor, Inactive RC

#4678 [PLAY-2196] Advanced Table: Fixes for animation for actions bar
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
Labels: bug, milano, minor, Inactive RC

#4681 [PLAY-2127] Dropdown: closeonSelection prop - React only
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_close_on_select.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_close_on_select.md
  playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownTrigger.tsx
Labels: enhancement, react, milano, alpha, minor, Inactive RC

#4697 Update CHANGELOG.md 14.21.0
  playbook/CHANGELOG.md
Labels: milano, improvement, minor, Inactive RC

#4703 Update CHANGELOG.md with patch
  playbook/CHANGELOG.md
Labels: improvement, patch, Inactive RC

#4705 Advanced Table: Scrollbar none scss fixes
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
Labels: bug, milano, minor, Inactive RC

#4704 [PLAY-1966] Section Separator kit: Add Documentation for Width Requirement
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_description.md
Labels: milano, improvement, minor, Inactive RC

#4698 [PLAY-2167] Advanced Table Horizontal Rows Double when Container True
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
Labels: bug, milano, alpha, minor, Inactive RC

#4689 [PLAY-2214] Checkbox kit: Add Hidden Input Logic Rails
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.rb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_custom.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_custom_rails.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_form.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_form.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_options.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/spec/pb_kits/playbook/kits/checkbox_spec.rb
Labels: enhancement, milano, alpha, minor

#4680 [PLAY-2140] Dependency update/upgrade: rails (7.0.8.1) to 7.1
  examples/playbook-rails-webpack/Gemfile
  examples/playbook-rails/Gemfile
  examples/rails-react-example/Gemfile
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
  playbook-website/config/application.rb
Labels: milano, improvement, alpha, minor

#4746 Fix spelling
  playbook-website/app/views/patterns/custom_user_display/index.html.erb
Labels: improvement, minor, Inactive RC

#4734 [PLAY-2046] Advanced Table: Continue Infinite Scroll - React
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/VirtualizedTableView.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Context/AdvancedTableContext.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableActions.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableBody.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableHeader.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/TableContainerStyles.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_infinite_scroll.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: enhancement, milano, alpha, minor

#4735 [PLAY-2131] Advanced Table Kit: Row Styling prop
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/RegularTableView.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/CellRendererUtils.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_row_styling.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_row_styling.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: enhancement, milano, alpha, minor, Inactive RC

#4736 [PLAY-2227] Playbook Website: Homepage isn't displaying correctly on Chrome
  playbook-website/app/javascript/components/HomepageHero/Pages/SmallScreen.tsx
  playbook-website/app/javascript/components/HomepageHero/index.tsx
Labels: milano, improvement, minor, Inactive RC

#4759 [PLAY-2179] Update playbook icons
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_contact/contact.test.js
  playbook/app/pb_kits/playbook/pb_filter/filter.test.js
  yarn.lock
Labels: milano, improvement, alpha, minor

#4761 [PLAY-2233] Highcharts: Remove Treemap from Playbook
  playbook-website/app/views/guides/getting_started/dependencies.md
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/entrypoints/playbook-rails-react-bindings.js
  playbook/app/entrypoints/playbook.scss
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
  playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.scss
  playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.tsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_description.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_colors.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_colors.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_colors.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_default.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_default.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_default.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_drillable.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_drillable.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_drillable.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_grouped_data.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_grouped_data.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_grouped_data.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.jsx
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/_treemap_chart_tooltip.md
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_treemap_chart/docs/index.js
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemapChart.test.js
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemap_chart.html.erb
  playbook/app/pb_kits/playbook/pb_treemap_chart/treemap_chart.rb
  playbook/spec/pb_kits/playbook/kits/treemap_chart_spec.rb
Labels: deprecated, milano, alpha, minor, Inactive RC

#4754 [PLAY-2255] Testing load time with refactored enhanced element file
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table_action_bar.js
  playbook/app/pb_kits/playbook/pb_advanced_table/flat_advanced_table.js
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_action_bar.html.erb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4766 [PLAY-2112] Table kit: Styling Issue For One Column Table
  playbook/app/pb_kits/playbook/pb_table/styles/_table-card.scss
Labels: enhancement, milano, alpha, minor

#4786 [PLAY-2252] Advanced Table: Add Rails Header Alignment Docs Examples
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
Labels: milano, improvement, minor, Inactive RC

#4791 [PLAY-2207] Typeahead Kit: `preserve_search_input` - Rails
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_preserve_input.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_preserve_input_rails.md
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_preserve_input_react.md
  playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
  playbook/spec/pb_kits/playbook/kits/typeahead_spec.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4805 Revert "Revert "[PLAY-2256] Table kit: sticky_left_column and sticky_right_column depends on id attribute - React Only""
  playbook/app/pb_kits/playbook/pb_table/_table.tsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns_react.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns_react.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns_react.md
Labels: improvement, minor

#4778 [PLAY-2175] Playbook Website: Add Icons to New Icon Page Dynamically
  Dockerfile
  package-lock.json
  playbook-website/app/assets/icons.json
  playbook-website/app/controllers/playbook_icons_controller.rb
  playbook-website/app/javascript/site_styles/_playbook_icons_index.scss
  playbook-website/app/views/pages/playbook_icons.html.erb
  playbook-website/scripts/generate-icon-list.mjs
Labels: milano, improvement, minor, Inactive RC

#4767 [PLAY-2288] Advanced Table: Custom Sort
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/SubRowHeaderRow.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_sort.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_sort.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: enhancement, milano, alpha, minor, Inactive RC
