Repository powerhome/playbook, pull requests merged in 2025-05, with the labels that each got.

#4566 [PLAY-2044] Add "triangle-exclamation" icon to Error State docs - Rails
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_error.html.erb
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_error.html.erb
  playbook/app/pb_kits/playbook/pb_select/docs/_select_error.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error.html.erb
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.html.erb
Labels: milano, improvement, minor, Inactive RC

#4570 [PLAY-1902] Dependency update/upgrade: @types/react-highlight-words
  playbook/package.json
  yarn.lock
Labels: milano, improvement, minor, Inactive RC

#4552 [PLAY-2039] Advanced Table Kit: Selectable Rows - Rails
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_no_subrows_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_no_subrows_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_no_subrows_react.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/flat_advanced_table.js
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_body.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_row.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4572 [PLAY-2037] Select kit: Inline Error Misaligns Arrow
  playbook/app/pb_kits/playbook/pb_select/_select.scss
Labels: bug, milano, alpha, Product Approved, Code Approved, minor, Inactive RC

#4569 [PLAY-2050] Draggable Kit: Line Drop Zones - Rails
  playbook/app/pb_kits/playbook/pb_card/card.html.erb
  playbook/app/pb_kits/playbook/pb_card/card.rb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_line.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_line_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_line_react.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.rb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_item.rb
  playbook/app/pb_kits/playbook/pb_draggable/index.js
Labels: enhancement, milano, minor, Inactive RC

#4582 [PLAY-2150] Table kit: Expandable/Collapsible not behaving correctly when multiple icons are present
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click.jsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_row.tsx
Labels: bug, milano, minor, Inactive RC

#4581 [PLAY-2087] Empty State Kit: Kit Buildout - Rails
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_empty_state/_empty_state.scss
  playbook/app/pb_kits/playbook/pb_empty_state/docs/_empty_state_alignment.html.erb
  playbook/app/pb_kits/playbook/pb_empty_state/docs/_empty_state_default.html.erb
  playbook/app/pb_kits/playbook/pb_empty_state/docs/_empty_state_orientation.html.erb
  playbook/app/pb_kits/playbook/pb_empty_state/docs/_empty_state_size.html.erb
  playbook/app/pb_kits/playbook/pb_empty_state/docs/example.yml
  playbook/app/pb_kits/playbook/pb_empty_state/empty_state.html.erb
  playbook/app/pb_kits/playbook/pb_empty_state/empty_state.rb
  playbook/spec/pb_kits/playbook/kits/empty_state_spec.rb
Labels: enhancement, milano, minor, Inactive RC

#4598 [PLAY-1556] React Prop table not working on Kit Collection pages
  playbook-website/app/views/pages/kit_collection.html.erb
  playbook-website/app/views/pages/kit_variants_collection.html.erb
Labels: milano, improvement, minor, Inactive RC

#4597 [PLAY-2149] Overlay Kit: Dynamic Variant Bug Fix - React
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.scss
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_vertical_dynamic_multi_directional.jsx
  playbook/app/pb_kits/playbook/pb_overlay/subcomponents/_overlay_token.tsx
Labels: bug, milano, alpha, minor, Inactive RC

#4603 [PLAY-1989] Avatar, User, Message Kits: Grayscale Prop
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss
  playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
  playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.rb
  playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_grayscale.html.erb
  playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_grayscale.jsx
  playbook/app/pb_kits/playbook/pb_avatar/docs/example.yml
  playbook/app/pb_kits/playbook/pb_avatar/docs/index.js
  playbook/app/pb_kits/playbook/pb_message/_message.tsx
  playbook/app/pb_kits/playbook/pb_message/docs/_message_grayscale.html.erb
  playbook/app/pb_kits/playbook/pb_message/docs/_message_grayscale.jsx
  playbook/app/pb_kits/playbook/pb_message/docs/example.yml
  playbook/app/pb_kits/playbook/pb_message/docs/index.js
  playbook/app/pb_kits/playbook/pb_message/message.html.erb
  playbook/app/pb_kits/playbook/pb_message/message.rb
  playbook/app/pb_kits/playbook/pb_user/_user.tsx
  playbook/app/pb_kits/playbook/pb_user/docs/_user_grayscale.html.erb
  playbook/app/pb_kits/playbook/pb_user/docs/_user_grayscale.jsx
  playbook/app/pb_kits/playbook/pb_user/docs/example.yml
  playbook/app/pb_kits/playbook/pb_user/docs/index.js
  playbook/app/pb_kits/playbook/pb_user/user.html.erb
  playbook/app/pb_kits/playbook/pb_user/user.rb
  playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
Labels: enhancement, milano, minor, Inactive RC

#4605 [PLAY-1738] Highcharts: Remove Gantt Chart from Playbook
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/entrypoints/playbook.scss
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_gantt_chart/_gantt_chart.scss
  playbook/app/pb_kits/playbook/pb_gantt_chart/_gantt_chart.tsx
  playbook/app/pb_kits/playbook/pb_gantt_chart/docs/_gantt_chart_default.jsx
  playbook/app/pb_kits/playbook/pb_gantt_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_gantt_chart/docs/index.js
  playbook/app/pb_kits/playbook/pb_gantt_chart/gantt_chart.test.jsx
Labels: deprecated, milano, minor, Inactive RC

#4606 Version bump 14.19.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor, Inactive RC

#4607 Update CHANGELOG.md 14.19.0
  playbook/CHANGELOG.md
Labels: milano, improvement, minor, Inactive RC

#4609 [PLAY-2004] Add Semver and Inactive RC to GitHub PR Checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: milano, improvement, minor, Inactive RC

#4613 [PLAY-2093] Playbook Website: upgrade Puma dependency
  playbook-website/Gemfile
  playbook-website/Gemfile.lock
Labels: milano, improvement, alpha, minor, Inactive RC

#4610 [PLAY-2125] Phone Number Input: Fix the Error Styles for Country Search - Rails & React
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
Labels: bug, milano, alpha, minor, Inactive RC

#4614 [PLAY-2067] File Upload Kit: Error State
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.scss
  playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_error.html.erb
  playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_error.jsx
  playbook/app/pb_kits/playbook/pb_file_upload/docs/example.yml
  playbook/app/pb_kits/playbook/pb_file_upload/docs/index.js
  playbook/app/pb_kits/playbook/pb_file_upload/file_upload.html.erb
  playbook/app/pb_kits/playbook/pb_file_upload/file_upload.rb
  playbook/app/pb_kits/playbook/pb_file_upload/fileupload.test.js
  playbook/spec/pb_kits/playbook/kits/file_upload_spec.rb
Labels: enhancement, milano, minor, Inactive RC

#4579 [PLAY-2129] Advanced Table: ColumnVisibility Control
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/RegularTableView.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableActionBar.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/VisibilityTree.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_custom.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_custom.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_multi.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_multi.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/scss_partials/advanced_table_sticky_mixin.scss
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownContainer.tsx
  playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
Labels: enhancement, milano, alpha, minor

#4620 [PLAY-1973] Form Pill kit: Icon and Avatar sizing is off
  playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
Labels: bug, milano, alpha, minor, Inactive RC

#4623 [PLAY-2152] Multi-Level Select: Single variant with selectedIds are rendering value and not label
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_color.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_color.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_default.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_default.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent_default.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent_default.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_error.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_error.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_label.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_label.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_react_hook.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_reset.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_return_all_selected.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids_react.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids_react.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_single.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_single.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_single_children_only.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_single_children_only.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_with_children.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_with_children_with_radios.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_with_form.html.erb
Labels: bug, milano, alpha, minor, Inactive RC

#4626 [PLAY-2182] Form Group Kit: Fix Select and Passphrase Inputs Error Misalignment
  playbook/app/pb_kits/playbook/pb_form_group/_error_state_mixin.scss
Labels: bug, milano, alpha, minor

#4621 [PLAY-2033] Advanced Table: Action bar for Selectable Rows logic - Rails
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_actions_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_actions_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_header_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_header_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_action_bar.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_action_bar.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.rb
Labels: milano, improvement, alpha, minor, Inactive RC

#4637 Revert "[PLAY-2033] Advanced Table: Action bar for Selectable Rows logic - Rails "
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_actions_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_actions_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_header_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_header_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
  playbook/app/pb_kits/playbook/pb_advanced_table/table_action_bar.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_action_bar.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.rb
Labels: milano, minor, Inactive RC

#4634 [PLAY-2139] Update power-fonts to 0.0.1
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, minor, Inactive RC

#4636 [PLAY-2206] Advanced Table: Fix for border when StickyLeftColumn, Sticky Header and ColumnBorderColor used together
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
Labels: bug, milano, alpha, minor, Inactive RC

#4629 [PLAY-2145] All Kits: Fix `html_options style` without Inline Styles Bug - Rails
  playbook/lib/playbook/kit_base.rb
Labels: bug, milano, alpha, minor, Inactive RC

#4639 [PLAY-2171] Advanced Table: Replace Dropdown with Popover for ColumnVisibility + expandByDepth Props
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableActionBar.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.md
Labels: enhancement, milano, alpha, minor, Inactive RC

#4640 Version Bump 14.20.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor, Inactive RC

#4641 Update CHANGELOG.md 14.20.0
  playbook/CHANGELOG.md
Labels: milano, minor, Inactive RC

#4649 Renovate should propose major upgrades
  renovate.json
Labels: improvement, minor, Inactive RC

#4667 [PLAY-2208] Dropdown Kit: Adding Jest and RSpec Tests
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
  playbook/spec/pb_kits/playbook/kits/dropdown_spec.rb
Labels: milano, improvement, minor, Inactive RC

#4673 [PLAY-2161] Dropdown Kit: Display 'no option' with no results in autocomplete - Rails
  playbook/app/pb_kits/playbook/pb_dropdown/index.js
Labels: bug, milano, minor, Inactive RC
