Repository powerhome/playbook, pull requests merged in 2025-10, with the labels that each got.

#5230 [PLAY-2512] Button Kit: Ability to Dynamically Toggle Disabled State in Rails
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled.md
  playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled_helper.html.erb
  playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled_helper.md
  playbook/app/pb_kits/playbook/pb_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_button/index.js
  playbook/spec/pb_kits/playbook/kits/button_spec.rb
Labels: enhancement, alpha, minor

#5258 [PLAY-1995] Dialog kit: Add danger button to the "Delete Status" variants
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
Labels: improvement, minor, Inactive RC

#5260 [PLAY-2397] Tokens: Create Letter Spacing, Shadow and Titles token pages
  playbook-website/app/javascript/components/GlobalPropsAndTokens/Data/TokenCards.ts
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/LetterSpacing.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Shadows.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Titles.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/TokensExamplesIndex.tsx
  playbook-website/config/global_props_and_tokens.yml
Labels: milano, improvement, minor, Inactive RC

#5241 [PLAY-2523] Icon Stat Value: Scss Refactor
  playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.tsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.scss
  playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.tsx
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.html.erb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.rb
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.test.js
  playbook/spec/pb_kits/playbook/kits/icon_stat_value_spec.rb
Labels: enhancement, alpha, minor, Inactive RC

#5248 [PLAY-2525] Typeahead: scss refactor
  playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
Labels: enhancement, milano, Ready for Release, alpha, minor, Inactive RC

#5298 [PLAY-2246] Hover Prop: Updated Visible Hover Prop - React and Rails
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Hover.tsx
  playbook-website/app/javascript/components/VisualGuidelines/Examples/GroupHover.tsx
  playbook-website/app/views/pages/code_snippets/group_hover_jsx.txt
  playbook/app/pb_kits/playbook/pb_card/docs/_card_light.html.erb
  playbook/app/pb_kits/playbook/utilities/_hover.scss
  playbook/app/pb_kits/playbook/utilities/globalProps.ts
  playbook/lib/playbook/hover.rb
  playbook/spec/playbook/global_props/hover_spec.rb
Labels: bug, milano, Ready for Release, minor, Inactive RC

#5310 Fixes for Card doc example
  playbook/app/pb_kits/playbook/pb_card/docs/_card_light.html.erb
Labels: milano, improvement, minor, Inactive RC

#5301 [PLAY-2490] Website: Add images to Cursor global prop page
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Cursor.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/alias.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/allScroll.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/auto.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/cell.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/colResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/contextMenu.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/copy.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/crosshair.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/defaultCursor.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/eResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/ewResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/grab.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/grabbing.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/help.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/index.tsx
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/move.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/nResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/neResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/neswResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/noDrop.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/none.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/notAllowed.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/nsResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/nwResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/nwseResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/pointer.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/progress.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/rowResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/sResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/seResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/swResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/text.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/verticalText.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/wResize.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/wait.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/zoomIn.svg
  playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/CursorImages/zoomOut.svg
  playbook-website/app/javascript/site_styles/_global_props_and_tokens.scss
Labels: milano, Ready for Release, improvement, minor
