Repository powerhome/playbook, pull requests merged in 2025-02, with the labels that each got.

#4227 Revert "[PLAY-1821] Home Address Casing"
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting_rails.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting_react.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/index.js
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Labels: minor, Inactive RC

#4211 [PBNTR-833] Advanced Table: Hide Actions Bar Till Rows are Selected
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/ActionBarAnimationHelper.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
Labels: enhancement, alpha, Product Approved, Code Approved, minor

#4182 [PLAY-1828] Update Vite version
  playbook-website/package.json
  playbook/package.json
  yarn.lock
Labels: improvement, alpha, Code Approved, minor

#4178 [PLAY-1602] Lightbox kit - Nitro Bug
  playbook/app/pb_kits/playbook/pb_lightbox/lightbox.scss
Labels: bug, alpha, Product Approved, Code Approved, minor

#4210 PBNTR-779 | Draggable kit: Add the "cross-container" functionality to RAILS kit
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers_rails.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.rb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_item.rb
  playbook/app/pb_kits/playbook/pb_draggable/index.js
Labels: enhancement, milano, Code Approved, minor, Inactive RC

#4234 [PBNTR-862]Testing Draggable Kit with Table Kit
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_table.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_table.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_container.rb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_item.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/draggable_item.rb
Labels: enhancement, milano, Code Approved, minor, Inactive RC

#4229 [PLAY-1887] Home Address with fix
  playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.html.erb
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.jsx
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting_rails.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting_react.md
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml
  playbook/app/pb_kits/playbook/pb_home_address_street/docs/index.js
  playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Labels: bug, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4221 [PLAY-1478] PB Website - Search Global Props
  playbook-website/app/javascript/components/KitSearch.tsx
  playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts
  playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
Labels: Ready for Release, improvement, Product Approved, Code Approved, minor, Inactive RC

#4201 [PLAY-1866] Mask Use PBenahcnedElement
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask.html.erb
  playbook/app/pb_kits/playbook/pb_text_input/index.js
Labels: bug, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4219 [PLAY-1830] Bump classnames Version
  playbook/package.json
  yarn.lock
Labels: milano, Ready for Release, improvement, alpha, Product Approved, Code Approved, minor, Inactive RC

#4241 [PBNTR-856] Selectable Rows Action Bar Responsive
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
Labels: bug, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4203 [PLAY-1752] Implement pb_content_tag
  playbook/app/pb_kits/playbook/pb_icon/icon.html.erb
  playbook/app/pb_kits/playbook/pb_layout/body.html.erb
  playbook/app/pb_kits/playbook/pb_layout/footer.html.erb
  playbook/app/pb_kits/playbook/pb_layout/header.html.erb
  playbook/app/pb_kits/playbook/pb_layout/item.html.erb
  playbook/app/pb_kits/playbook/pb_layout/layout.html.erb
  playbook/app/pb_kits/playbook/pb_layout/sidebar.html.erb
  playbook/app/pb_kits/playbook/pb_legend/legend.html.erb
  playbook/app/pb_kits/playbook/pb_message/message.html.erb
  playbook/app/pb_kits/playbook/pb_message/message_mention.html.erb
Labels: enhancement, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4248 Version Bump 14.13.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
  yarn.lock
Labels: minor

#4218 [PLAY-1858] Icon Button Sizes
  playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_default.html.erb
  playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_sizes.html.erb
  playbook/app/pb_kits/playbook/pb_icon_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon_button/icon_button.html.erb
  playbook/app/pb_kits/playbook/pb_icon_button/icon_button.rb
  playbook/spec/pb_kits/playbook/kits/icon_button_spec.rb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4240 [PLAY-1888] React Date Picker - initializeOnce - Reinitialization with Other Inputs Bug
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
Labels: bug, milano, alpha, Code Approved, minor

#4249 Update CHANGELOG.md 14.13.0
  playbook/CHANGELOG.md
Labels: milano, minor

#4259 [PBNTR-847] Adding Table Selectable Rows doc example
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/docs/index.js
Labels: milano, improvement, Code Approved, minor, Inactive RC

#4217 [PLAY-1753] Update pb_content_tags
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.html.erb
  playbook/app/pb_kits/playbook/pb_nav/item.html.erb
  playbook/app/pb_kits/playbook/pb_nav/nav.html.erb
  playbook/app/pb_kits/playbook/pb_online_status/online_status.html.erb
  playbook/app/pb_kits/playbook/pb_popover/popover.html.erb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4253 [PBNTR-559] Draggable Kit with Table Kit
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_table.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_table.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_table_react.jsx
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_table_react.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/docs/index.js
  playbook/app/pb_kits/playbook/pb_draggable/subcomponents/DraggableContainer.tsx
  playbook/app/pb_kits/playbook/pb_draggable/subcomponents/DraggableItem.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_body.tsx
  playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_row.tsx
  playbook/app/pb_kits/playbook/pb_table/table_body.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_body.rb
  playbook/app/pb_kits/playbook/pb_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_row.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, minor

#4271 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano, minor, Inactive RC

#4263 [PBNTR-799] Table kit: Collapsible rows with "custom click" for Rails
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible.jsx
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click_react.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/index.ts
  playbook/app/pb_kits/playbook/pb_table/styles/_collapsible.scss
  playbook/app/pb_kits/playbook/pb_table/table_row.html.erb
  playbook/app/pb_kits/playbook/pb_table/table_row.rb
Labels: enhancement, milano, alpha, Code Approved, minor

#4277 [PLAY-1879] Deprecate Action Avatar Button
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/entrypoints/playbook.scss
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.scss
  playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.tsx
  playbook/app/pb_kits/playbook/pb_avatar_action_button/avatar_action_button.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/avatar_action_button.rb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_actions.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_actions.jsx
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_default.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_default.jsx
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_on_click.jsx
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_onclick.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_placement.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_placement.jsx
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/index.js
  playbook/app/pb_kits/playbook/pb_avatar_action_button/pb_avatar_action_button.test.js
  playbook/spec/pb_kits/playbook/kits/avatar_action_button_spec.rb
Labels: deprecated, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4260 [PLAY-1884] Responsive Progress Pill
  playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.scss
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.md
Labels: enhancement, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4269 [PLAY-1900] Progress Pill Full Width
  playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.scss
  playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.tsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_full_width.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_full_width.jsx
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_full_width_rails.md
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_full_width_react.md
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/example.yml
  playbook/app/pb_kits/playbook/pb_progress_pills/docs/index.js
  playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.html.erb
  playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.rb
  playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.test.js
  playbook/spec/pb_kits/playbook/kits/progress_pills_spec.rb
Labels: enhancement, Ready for Release, alpha, Product Approved, Code Approved, minor

#4284 [PBNTR-548] Overlay kit: Multi-directional overlays not behaving correctly - React
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.tsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_vertical_dynamic_multi_directional.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_vertical_dynamic_multi_directional_react.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
  playbook/app/pb_kits/playbook/pb_overlay/docs/index.js
  playbook/app/pb_kits/playbook/pb_overlay/subcomponents/_overlay_token.tsx
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4292 [PBNTR-883] Advanced Table: Multi Column Headers to work with Custom Cells
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_custom_cell.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: bug, milano, alpha, minor, Inactive RC

#4296 [PLAY-1851] checkbox react hook squash
  playbook-website/package.json
  playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.tsx
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.test.js
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_react_hook.jsx
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_react_hook.md
  playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml
  playbook/app/pb_kits/playbook/pb_checkbox/docs/index.js
  yarn.lock
Labels: enhancement, milano, Code Approved, minor, Inactive RC

#4301 Version Bump 14.14.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor, Inactive RC

#4299 [PBNTR-457] Adding Form Time Zone Select field
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/lib/playbook/forms/builder.rb
  playbook/lib/playbook/forms/builder/time_zone_select_field.rb
Labels: enhancement, milano, alpha, Code Approved, minor, Inactive RC

#4297 [PLAY-1875] Playgound Editor Enhancements
  playbook-website/app/javascript/components/PbKitPlayground/index.tsx
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4285 [PLAY-1892] Progress Step Kit:Tooltip Flickering - Rails
  playbook/app/pb_kits/playbook/pb_progress_step/progress_step_item.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/index.js
Labels: bug, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4309 Update CHANGELOG.md 14.14.0
  playbook/CHANGELOG.md
Labels: milano, minor, Inactive RC

#4298 [PLAY-1867] React Icon Button Kit
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-doc.js
  playbook/app/javascript/kits.js
  playbook/app/pb_kits/playbook/pb_icon_button/_icon_button.tsx
  playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_default.jsx
  playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_sizes.jsx
  playbook/app/pb_kits/playbook/pb_icon_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_icon_button/docs/index.js
  playbook/app/pb_kits/playbook/pb_icon_button/icon_button.test.jsx
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4283 [PLAY-1843] Global Props & Tokens Index Page
  playbook-website/app/controllers/guides_controller.rb
  playbook-website/app/views/guides/global_props.html.md
  playbook-website/app/views/guides/global_props/test.md
  playbook-website/app/views/guides/tokens.html.md
  playbook-website/app/views/guides/tokens/test.md
  playbook-website/app/views/layouts/global_props.html.erb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4308 [PLAY-1880] Bump axe-core to 4.10.2
  playbook-website/package.json
  playbook/package.json
  yarn.lock
Labels: milano, improvement, Code Approved, minor, Inactive RC

#4312 [PLAY-1876] Playground - ERB Syntax Highlighting
  playbook-website/app/javascript/components/PbKitPlayground/index.tsx
  playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
Labels: enhancement, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4303 [PBNTR-500] Currency Kit: Handling of `null` values
  playbook/app/pb_kits/playbook/pb_currency/_currency.tsx
  playbook/app/pb_kits/playbook/pb_currency/currency.html.erb
  playbook/app/pb_kits/playbook/pb_currency/currency.rb
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_null_display.html.erb
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_null_display.jsx
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_null_display_rails.md
  playbook/app/pb_kits/playbook/pb_currency/docs/_currency_null_display_react.md
  playbook/app/pb_kits/playbook/pb_currency/docs/example.yml
  playbook/app/pb_kits/playbook/pb_currency/docs/index.js
Labels: enhancement, milano, alpha, Code Approved, minor

#4327 [PBNTR-888] Adding Select Validity Message
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
  playbook/app/pb_kits/playbook/pb_select/index.js
  playbook/app/pb_kits/playbook/pb_select/select.rb
Labels: enhancement, milano, alpha, Code Approved, minor

#4242 [PLAY-1633] Display Title
  playbook/app/pb_kits/playbook/pb_title/_title.scss
  playbook/app/pb_kits/playbook/pb_title/_title.tsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_default.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_default.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_display_size.html.erb
  playbook/app/pb_kits/playbook/pb_title/docs/_title_display_size.jsx
  playbook/app/pb_kits/playbook/pb_title/docs/_title_display_size.md
  playbook/app/pb_kits/playbook/pb_title/docs/example.yml
  playbook/app/pb_kits/playbook/pb_title/docs/index.js
  playbook/app/pb_kits/playbook/pb_title/title.rb
Labels: enhancement, milano, Ready for Release, Product Approved, Code Approved, minor, Inactive RC

#4322 [PLAY-1922] Tooltip Interaction using @floating-ui
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_delay_rails.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_delay_rails.md
  playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_interaction.html.erb
  playbook/app/pb_kits/playbook/pb_tooltip/docs/example.yml
  playbook/app/pb_kits/playbook/pb_tooltip/floating_ui.js
  playbook/app/pb_kits/playbook/pb_tooltip/index.js
  playbook/app/pb_kits/playbook/pb_tooltip/tooltip.rb
  playbook/package.json
  playbook/spec/pb_kits/playbook/kits/tooltip_spec.rb
  yarn.lock
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor

#4336 [PBNTR-877] Adding Rails Overlay Dynamic prop
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_vertical_dynamic_multi_directional.html.erb
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_vertical_dynamic_multi_directional.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
  playbook/app/pb_kits/playbook/pb_overlay/index.js
  playbook/app/pb_kits/playbook/pb_overlay/overlay.html.erb
  playbook/app/pb_kits/playbook/pb_overlay/overlay.rb
Labels: enhancement, milano, Code Approved, minor, Inactive RC
