Repository powerhome/playbook, pull requests merged in 2025-07, with the labels that each got.

#4850 [PLAY-2295] PB Website: Advanced Table as own Menu Item in Sidebar
  playbook-website/app/controllers/pages_controller.rb
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx
  playbook-website/app/javascript/components/MainSidebar/index.tsx
  playbook-website/app/views/pages/kit_show.html.erb
  playbook-website/config/menu.yml
  playbook-website/config/routes.rb
  playbook-website/lib/pb_doc_helper.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
Labels: milano, improvement, alpha, minor, Inactive RC

#4857 [PLAY-2132] Phone Number Input kit: If selecting a country prior to entering a phone number, the "too short" validation appears
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
Labels: enhancement, milano, alpha, minor, Inactive RC

#4821 [PLAY-2257] Draggable Kit: Dragging Between Drag Containers to not Break Page
  playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx
  playbook/app/pb_kits/playbook/pb_draggable/context/types.ts
Labels: bug, milano, alpha, minor

#4884 Version Bump
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: improvement, minor, Inactive RC

#4881 [PLAY-2308] Website Search Bug - after Advanced Table Restructuring
  playbook-website/app/helpers/application_helper.rb
  playbook-website/app/views/pages/playbook_icons.html.erb
Labels: bug, milano, minor, Inactive RC

#4864 Dialog Kit: Remove Dialog kit from react bindings file
  playbook/app/entrypoints/playbook-rails-react-bindings.js
Labels: milano, improvement, alpha, minor, Inactive RC

#4878 [PLAY-2281] Advanced Table: Custom Header - Rails Only
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/table_header.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4892 [PLAY-2264] Highcharts - Line Graph: Update all doc examples with imported styles - React only
  playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend_position.md
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_legend_position.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_description.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_colors.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_colors_rails.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_colors_react.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_nonclickable.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_position.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_position.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_pb_styles.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_pb_styles.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_line_graph/docs/index.js
  playbook/app/pb_kits/playbook/pb_line_graph/lineGraphTheme.ts
Labels: milano, improvement, minor, Inactive RC

#4894 [PLAY-2126] Phone Number Kit: strictMode Prop Accept Numbers and Max Length
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_strict_mode.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_strict_mode.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_strict_mode.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
  playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
Labels: enhancement, milano, minor, Inactive RC

#4895 [PLAY-2243] Checkbox Kit: Custom Indeterminate Main Checkbox Labels - Rails
  playbook/app/pb_kits/playbook/pb_checkbox/checkbox.rb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate.html.erb
  playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate_rails.md
  playbook/app/pb_kits/playbook/pb_checkbox/index.js
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.html.erb
  playbook/spec/pb_kits/playbook/kits/checkbox_spec.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4896 [PLAY-2204] Advanced Table: Support Custom headers with Multi-Header Columns
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header_multi_header.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header_multi_header.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: bug, milano, alpha, minor

#4903 [PLAY-2205] Advanced Table: Selectable Row/Action Bar examples Border Bug Rails and React
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableActionBar.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table_action_bar.js
  playbook/app/pb_kits/playbook/pb_advanced_table/scss_partials/advanced_table_sticky_mixin.scss
  playbook/spec/pb_kits/playbook/pb_advanced_table/advanced_table_spec.rb
Labels: bug, milano, alpha, minor, Inactive RC

#4917 [PLAY-2148] Select Kit: Classnames Spaces Fix - Rails
  playbook/app/pb_kits/playbook/pb_select/select.rb
  playbook/spec/pb_kits/playbook/kits/select_spec.rb
Labels: bug, milano, alpha, minor, Inactive RC

#4918 [PLAY-1985] Pagination Kit: Show Only with Multiple Pages - React
  playbook/app/pb_kits/playbook/pb_pagination/_pagination.tsx
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default_rails.md
  playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default_react.md
Labels: enhancement, milano, alpha, minor

#4936 [PLAY-2166] Patterns: Filter + SectionSeparator + Table inside Card/Flex
  playbook-website/app/controllers/patterns_controller.rb
  playbook-website/app/javascript/entrypoints/patterns.js
  playbook-website/app/views/patterns/table_filter_card/index.html.erb
  playbook-website/app/views/patterns/table_filter_card/index.jsx
  playbook-website/config/patterns.yml
Labels: milano, docs, minor, Inactive RC

#4886 [PLAY-2303] WebpackerReact Config for Playbook kits to come from Playbook
  playbook/app/entrypoints/playbook-rails-react-bindings.js
Labels: milano, improvement, alpha, minor

#4929 [PLAY-2121] Multi Level Select kit: Add Prop to enable expandable fields to be initially render unexpanded - Rails & React
  playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_show_checked_children.html.erb
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_show_checked_children.jsx
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_show_checked_children.md
  playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
  playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4945 [PLAY-2312] Advanced Table: Sort Available on All Columns
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/SortIconButton.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableHeader.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column_for_multi_column.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column_for_multi_column.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: enhancement, milano, alpha, minor, Inactive RC

#4938 [PLAY-1983] Advanced Table kit: Fix Double Border Issue When Table with container: false is Rendered Inside a Card
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/index.js
Labels: milano, alpha, minor
