Repository powerhome/playbook, pull requests merged in 2025-04, with the labels that each got.

#4451 [PLAY-1942] Fullscreen Button - Advanced Table, Multi Level Select, and Drawer Examples
  playbook-website/app/components/playbook/pb_docs/kit_example.html.erb
  playbook-website/app/components/playbook/pb_docs/kit_example.rb
  playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
Labels: milano, improvement, Code Approved, minor, Inactive RC

#4437 [PLAY-1758] Typeahead, Tooltip, User, UserBadge Kits: Convert to use Content Tag
  playbook/app/pb_kits/playbook/pb_tooltip/tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
  playbook/app/pb_kits/playbook/pb_user/user.html.erb
  playbook/app/pb_kits/playbook/pb_user_badge/user_badge.html.erb
  playbook/lib/playbook/kit_base.rb
Labels: enhancement, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4436 [PLAY-1958] Form Group Kit: Fix Error Border Styles
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
Labels: bug, milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4450 [PLAY-1881] Remove lodash from playbook
  playbook-website/app/views/guides/getting_started/dependencies.md
  playbook/package.json
  playbook/vite.config.ts
  yarn.lock
Labels: milano, Ready for Release, alpha, Product Approved, Code Approved, minor, Inactive RC

#4469 [PLAY-319] Remove Font Awesome from Tests
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx
  playbook/app/pb_kits/playbook/pb_collapsible/__snapshots__/collapsible.test.js.snap
  playbook/app/pb_kits/playbook/pb_contact/contact.test.js
  playbook/app/pb_kits/playbook/pb_date_range_inline/date_range_inline.test.js
  playbook/app/pb_kits/playbook/pb_date_range_stacked/date_range_stacked.test.js
  playbook/app/pb_kits/playbook/pb_draggable/draggable.test.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
  playbook/app/pb_kits/playbook/pb_icon/icon.test.js
  playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.test.js
  playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.test.js
  playbook/app/pb_kits/playbook/pb_icon_value/icon_value.test.js
  playbook/app/pb_kits/playbook/pb_label_value/label_value.test.js
  playbook/app/pb_kits/playbook/pb_link/link.test.jsx
  playbook/app/pb_kits/playbook/pb_nav/_nav_item.test.js
  playbook/app/pb_kits/playbook/pb_stat_change/stat_change.test.js
  playbook/jest.setup.js
  playbook/spec/pb_kits/playbook/kits/icon_spec.rb
Labels: milano, improvement, Code Approved, minor, Inactive RC

#4474 [PBNTR-953] Vertical Section Separator Documentation
  playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_vertical.md
Labels: milano, Ready for Release, improvement, Product Approved, Code Approved, minor, Inactive RC

#4477 Update CHANGELOG.md 14.17.0
  playbook/CHANGELOG.md
Labels: milano, improvement, minor, Inactive RC

#4485 Update CHANGELOG.md with image
  playbook/CHANGELOG.md
Labels: milano, improvement, minor, Inactive RC

#4487 Update CHANGELOG.md
  playbook/CHANGELOG.md
Labels: milano, minor, Inactive RC

#4478 [PLAY-1499] - Background Kit: Add Overlay w/ Opacity to Background Image
  playbook/app/pb_kits/playbook/pb_background/_background.scss
  playbook/app/pb_kits/playbook/pb_background/_background.tsx
  playbook/app/pb_kits/playbook/pb_background/background.test.js
  playbook/app/pb_kits/playbook/pb_background/docs/_background_overlay.jsx
  playbook/app/pb_kits/playbook/pb_background/docs/_background_overlay.md
  playbook/app/pb_kits/playbook/pb_background/docs/example.yml
  playbook/app/pb_kits/playbook/pb_background/docs/index.js
Labels: enhancement, milano, Code Approved, minor, Inactive RC

#4486 [PBNTR-925] Table kit: Custom headers - Rails Only
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_header_style_borderless.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_header_style_borderless_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_header_style_floating.html.erb
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_header_style_floating_rails.md
  playbook/app/pb_kits/playbook/pb_table/docs/_table_with_header_style_floating_react.md
  playbook/app/pb_kits/playbook/pb_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_table/table.rb
  playbook/app/pb_kits/playbook/pb_table/table_header.rb
  playbook/spec/pb_kits/playbook/kits/table_spec.rb
Labels: enhancement, milano, alpha, Product Approved, Code Approved, minor

#4501 [PLAY-1906] - Overlay Kit: Add Opacity & Gradient prop - React
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.scss
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.tsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_color.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_color.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_gradient_opacity.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_gradient_opacity.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_layout.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_layout.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
  playbook/app/pb_kits/playbook/pb_overlay/docs/index.js
  playbook/app/pb_kits/playbook/pb_overlay/overlay.test.jsx
Labels: enhancement, milano, alpha, Code Approved, minor, Inactive RC

#4512 [PLAY-2063] From Group: Phone Number Input and Select with Select on the Right
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.html.erb
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.jsx
Labels: enhancement, milano, Ready for Release, Product Approved, minor, Inactive RC

#4502 [PLAY-1967] Bracket Layout - Participant and Completed Games
  playbook/app/pb_kits/playbook/pb_layout/_layout.scss
  playbook/app/pb_kits/playbook/pb_layout/_layout.tsx
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_bracket.jsx
  playbook/app/pb_kits/playbook/pb_layout/docs/_layout_bracket.md
  playbook/app/pb_kits/playbook/pb_layout/subcomponents/_game.tsx
  playbook/app/pb_kits/playbook/pb_layout/subcomponents/_participant.tsx
  playbook/app/pb_kits/playbook/pb_layout/subcomponents/_round.tsx
Labels: enhancement, milano, alpha, Code Approved, minor, Inactive RC

#4515 [PLAY-1889] Add hook and doc example
  playbook/app/javascript/theme.js
  playbook/app/pb_kits/playbook/pb_copy_button/_copy_button.tsx
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook.jsx
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook.md
  playbook/app/pb_kits/playbook/pb_copy_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_copy_button/docs/index.js
  playbook/app/pb_kits/playbook/pb_copy_button/usePBCopy.ts
Labels: enhancement, milano, minor, Inactive RC

#4520 [PLAY-1823] Text Input kit: Mask Prop Sanitized Values - React Only
  playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_sanitize.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_sanitize.md
  playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_text_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_text_input/inputMask.ts
Labels: milano, improvement, alpha, minor, Inactive RC

#4521 [PLAY-2065] Playbook Support - Form Group Support for Credit App - Passphrase with Select Kit
  playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
  playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.jsx
Labels: enhancement, milano, alpha, minor

#4516 [PLAY-1597] Update @tiptap Dependencies to 2.11.7
  playbook-website/package.json
  yarn.lock
Labels: milano, improvement, alpha, minor

#4527 [PLAY-2054] Advanced Table: Expansion Control by Depth
  playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableActions.ts
  playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/ExpansionControlHelpers.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expand_by_depth.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expand_by_depth.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
  playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx
  playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
Labels: enhancement, milano, alpha, minor

#4537 [PLAY-1965] Overlay Kit: Add a "Full Screen" prop - React
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.scss
  playbook/app/pb_kits/playbook/pb_overlay/_overlay.tsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_background.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_background.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_opacity.jsx
  playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_opacity.md
  playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
  playbook/app/pb_kits/playbook/pb_overlay/docs/index.js
Labels: milano, improvement, minor, Inactive RC

#4514 [PLAY-2035] Dialog kit: Add Turbo support
  playbook-website/config/menu.yml
  playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/dialog.rb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_turbo_frames.html.erb
  playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_turbo_frames_rails.md
  playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
  playbook/app/pb_kits/playbook/pb_dialog/index.js
Labels: enhancement, milano, alpha, Product Approved, Code Approved, minor, Inactive RC

#4543 [PLAY-1901] Circle Icon Button kit: Add new 20x20 size
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
  playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.tsx
  playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb
  playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.test.js
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_size.html.erb
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_size.jsx
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_size.md
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/index.js
  playbook/spec/pb_kits/playbook/kits/circle_icon_button_spec.rb
Labels: enhancement, milano, Product Approved, Code Approved, minor, Inactive RC

#4538 [PLAY-2038] Copy Button Kit Go Live and Rails Copy Hook
  playbook-website/config/menu.yml
  playbook/app/entrypoints/playbook-rails.js
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook_rails.html.erb
  playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook_rails.md
  playbook/app/pb_kits/playbook/pb_copy_button/docs/example.yml
  playbook/app/pb_kits/playbook/pb_copy_button/index.js
Labels: enhancement, milano, minor, Inactive RC

#4549 Version Bump 14.18.0
  playbook-website/Gemfile.lock
  playbook/Gemfile.lock
  playbook/lib/playbook/version.rb
  playbook/package.json
Labels: minor, Inactive RC

#4550 Update CHANGELOG.md for 14.18.0
  playbook/CHANGELOG.md
Labels: milano, minor, Inactive RC

#4544 [PLAY-1735] Circle Chart: Add Ability to Use Circle Chart Styles w/o Circle Chart
  playbook/app/javascript/theme.js
  playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
  playbook/app/pb_kits/playbook/pb_circle_chart/circleChart.test.js
  playbook/app/pb_kits/playbook/pb_circle_chart/circleChartTheme.ts
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_block.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_block.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_colors.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_colors.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_default.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_default.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_legend_position.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_legend_position.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_live_data.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_pb_styles.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_pb_styles.md
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_rounded.html.erb
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_rounded.jsx
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/example.yml
  playbook/app/pb_kits/playbook/pb_circle_chart/docs/index.js
  playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_pb_styles.jsx
  playbook/app/pb_kits/playbook/pb_gauge/gaugeTheme.ts
Labels: enhancement, milano, alpha, minor, Inactive RC

#4548 [PLAY-2043] Playbook Website: Add Warning Icon to Error Docs - React
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_error.jsx
  playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_error.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_validation.jsx
  playbook/app/pb_kits/playbook/pb_select/docs/_select_error.jsx
  playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error.jsx
  playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error.jsx
  playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.jsx
Labels: milano, improvement, minor, Inactive RC

#4545 [PLAY-2078] Date Picker: Quick Pick and 3 input pattern
  playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker.rb
  playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_rails.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_range_limit.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_react.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range_pattern.jsx
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range_pattern.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range_pattern_rails.html.erb
  playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range_pattern_rails.md
  playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml
  playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js
  playbook/app/pb_kits/playbook/pb_date_picker/plugins/quickPick.tsx
Labels: enhancement, milano, alpha, minor

#4529 [PLAY-2034] Draggable Kit: Add Dropzones and Colors - Rails
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_colors.html.erb
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_colors_rails.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_colors_react.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_drop_zones_react.md
  playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml
  playbook/app/pb_kits/playbook/pb_draggable/draggable.rb
  playbook/app/pb_kits/playbook/pb_draggable/index.js
Labels: milano, alpha, Product Approved, Code Approved, minor, Inactive RC

#4562 [PLAY-1736] Line Graph: Add Ability to Use Line Graph Styles w/o Line Graph
  playbook/app/javascript/theme.js
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_pb_styles.jsx
  playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_pb_styles.md
  playbook/app/pb_kits/playbook/pb_line_graph/docs/example.yml
  playbook/app/pb_kits/playbook/pb_line_graph/docs/index.js
  playbook/app/pb_kits/playbook/pb_line_graph/lineGraphTheme.ts
Labels: enhancement, milano, alpha, minor, Inactive RC

#4553 [PLAY-2056] Advanced Table kit: Add Support for Different Column Border Colors for Column Groups - Rails & React
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: milano, improvement, minor, Inactive RC

#4551 [PLAY-2042] Popover Kit: Add Turbo Support - Rails
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_within_turbo_frames.html.erb
  playbook/app/pb_kits/playbook/pb_filter/docs/_filter_within_turbo_frames.md
  playbook/app/pb_kits/playbook/pb_filter/docs/example.yml
  playbook/app/pb_kits/playbook/pb_popover/docs/_popover_append_to.html.erb
  playbook/app/pb_kits/playbook/pb_popover/docs/_popover_append_to.md
  playbook/app/pb_kits/playbook/pb_popover/docs/example.yml
  playbook/app/pb_kits/playbook/pb_popover/index.ts
  playbook/app/pb_kits/playbook/pb_popover/popover.rb
  playbook/spec/pb_kits/playbook/kits/popover_spec.rb
Labels: enhancement, milano, alpha, minor

#4567 Revert "[PLAY-2056] Advanced Table kit: Add Support for Different Column Border Colors for Column Groups - Rails & React"
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
  playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
  playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color.jsx
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color_rails.html.erb
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color_rails.md
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
  playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
Labels: minor, Inactive RC

#4560 [PLAY-2048] Phone Number Input kit: Add Country Search
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
  playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_country_search.html.erb
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_country_search.jsx
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_country_search.md
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
  playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
  playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.test.js
  playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
Labels: enhancement, milano, alpha, minor, Inactive RC

#4561 [PLAY-2107] Phone Number Input kit: Error causes label to move
  playbook/app/pb_kits/playbook/pb_form_group/_error_state_mixin.scss
Labels: bug, milano, patch
